// ORIGINAL: 0x00456010 FILE
// name      ??1FactionArt@@QAE@XZ
// size      397 bytes
// spans     0x00456010-0x004560FC;0x00654F80-0x00655021
// prototype void (__thiscall ??1FactionArt@@QAE@XZ)(faction_art* this)
// callers   0   call targets   2
// kind      game
// flags     frame;sp_ready;purged_ok
// calls     0x005E3820 0x006456E4
// PRESERVED UNIT - measured MISMATCH.
//
// Kept for COVERAGE. This directory IS on the ratchet: every file here
// carries an ORIGINAL marker, `decomp_status.py` compiles and measures
// it, and 336 of the 1,108 now carry a BYTE_EXACT claim - better than a
// quarter of the project's total. It is still in no build; the earlier
// header said "on no ratchet", which stopped being true when the map
// moved into src/ and was still being written into new files.
//
// address        0x00456010
// measured tier  MISMATCH
// divergence     1
//
// The WHOLE unit as measured, scaffolding included: for the units
// that are byte-exact yet refuse extraction, the agent tuned the
// emitted scaffolding and the body alone will not reproduce the
// verdict. To resume, copy everything below back over
//   build/byte-match/00456010/unit.cpp
// and score it with tools/agent_brief.py.
// GENERATED SKELETON - tools/emit_translation_unit.py
// subject: ??1FactionArt@@QAE@XZ  at 0x00456010  (397 bytes)
//
// A VERIFICATION ARTIFACT, not product source: classes are opaque and
// globals are bound to fixed addresses, because both are byte-visible
// and both differ from the style src/ is written in.
//
// The VC6 dialect limits and the source-form rules used to live here.
// They are knowledge, not scaffolding, so they now live in the agent
// system prompt (mizuchi.yaml, plugins.claude-runner.systemPrompt),
// where they can be edited without regenerating anything and are in
// context from the first token rather than behind a file read. This
// emitter computes declarations; it does not carry lessons.

typedef int int32_t;
typedef unsigned int uint32_t;
typedef short int16_t;
typedef unsigned short uint16_t;
typedef signed char int8_t;
typedef unsigned char uint8_t;
typedef int int32;
typedef unsigned int uint32;
typedef short int16;
typedef unsigned short uint16;
// `char`, NOT `signed char`. They are distinct MSVC types and mangle
// differently - D against C - and the catalogue's `int8` means the first:
// counted over every catalogued mangled name, `PAD` appears 508 times and
// `PAC` once. Spelling it `signed char` made 150 derived prototypes emit a
// symbol no target object holds. `int8_t` keeps its C meaning below; neither
// catalogue ever uses it.
typedef char int8;
typedef unsigned char uint8;

class FactionArt;
class Sprite;

// ---- callees, declared and never defined (a definition would be inlined) ----
class Sprite { public:
    int ppszFileName_;
    int pcBits_;
    char cTransparentIndex_;
    char pad1_;
    char pad2_;
    char pad3_;
    int iSpriteWidth2_;
    int iSpriteWidth_;
    int iSpriteHeight_;
    int iWidth_;
    int iHeight_;
    int iLeftOffset_;
    int iTopOffset_;
    int fObj1Exists_;
    void close();
};
void __stdcall fn_006456e4(void*, unsigned int, int, void (*)(void*));

// ---- fixed globals this body references ----
// The const-pointer spelling reproduces the original's
// encoding including the address; `extern T *g` does not.
static int *const g_00406850 = (int *)0x00406850;
static int *const g_00655017 = (int *)0x00655017;
static int *const g_00675238 = (int *)0x00675238;

class FactionArt { public:
    ~FactionArt();
};

// EH UNWIND FUNCLETS: the original carries a full SEH frame (`push -1;
// push 0x655017; mov eax,fs:[0]; push eax; mov fs:[0],esp`) and six
// out-of-line funclets at 0x654F80-0x655016 that partially unwind this
// object if a member destructor throws mid-teardown. That scaffolding is
// generated by the compiler only when a REAL array-of-non-trivial-member
// destructor forces it; FactionArt is opaque here (no real Sprite value
// members to hang it off), so this body reproduces the linear call
// sequence only - the SEH prologue/funclets are the documented
// EH-funclet wall (0x0065xxxx range) and are not attempted.
FactionArt::~FactionArt() {
    char *self = reinterpret_cast<char *>(this);

    // Layout recovered from the vector-destructor-iterator sizes/counts
    // and the close()-call spacing: 24 Sprites at +0, 2 at +0x420, six
    // single Sprites +0x478.._+0x554 (only close()'d, not re-destructed -
    // ~Sprite() is otherwise a no-op here), 3 at +0x580, 2 at +0x604.
    fn_006456e4(self + 0x604, 0x2c, 2, reinterpret_cast<void (*)(void *)>(g_00406850));
    fn_006456e4(self + 0x580, 0x2c, 3, reinterpret_cast<void (*)(void *)>(g_00406850));
    reinterpret_cast<Sprite *>(self + 0x554)->close();
    reinterpret_cast<Sprite *>(self + 0x528)->close();
    reinterpret_cast<Sprite *>(self + 0x4fc)->close();
    reinterpret_cast<Sprite *>(self + 0x4d0)->close();
    reinterpret_cast<Sprite *>(self + 0x4a4)->close();
    reinterpret_cast<Sprite *>(self + 0x478)->close();
    fn_006456e4(self + 0x420, 0x2c, 2, reinterpret_cast<void (*)(void *)>(g_00406850));
    fn_006456e4(self, 0x2c, 0x18, reinterpret_cast<void (*)(void *)>(g_00406850));
}
