// Declarations for the fixtures that more than one family file touches.
//
// GENERATED by tools/emit_leaf_split.py - the definitions still live in the
// family file that owned them before the split; only the declaration is here.
// Entries appear in original-file order, so a fixture is always declared
// after everything it names.
#ifndef OPENSMACX_TESTS_LEAF_LEAF_SHARED_H
#define OPENSMACX_TESTS_LEAF_LEAF_SHARED_H

#include "leaf_harness.h"

// Several of these fixtures are __thiscall free functions, which GCC warns
// about on every translation unit that reads this header.  The original file
// silenced the same warning around the same declarations.

extern LPSTR filefind_get_result;

extern LPCSTR filefind_get_request;

extern int filefind_get_calls;

int __cdecl range(int input, int min, int max);

extern bool mem_get_scripted;

extern int mem_get_calls;

extern size_t mem_get_sizes[2];

extern LPVOID mem_get_results[2];

extern int atexit_calls;

extern void (__cdecl *atexit_callback)();

extern int heap_shutdown_calls;

extern int font_close_calls;

extern int font_init_calls;

extern Font *font_init_this;

extern LPCSTR font_init_name;

extern int font_init_height;

extern uint32_t font_init_style;

extern int time_close_calls;

extern Time *time_close_targets[8];

extern int text_shutdown_calls;

extern Text *text_shutdown_this;

extern int text_open_calls;

extern Text *text_open_this;

extern LPCSTR text_open_source_arg;

extern LPCSTR text_open_section_arg;

extern BOOL text_open_result;

extern int text_index_make_calls;

extern TextIndex *text_index_make_this;

extern LPCSTR text_index_make_source;

extern int text_index_search_calls;

extern TextIndex *text_index_search_this[MaxTextIndexNum];

extern LPCSTR text_index_search_source[MaxTextIndexNum];

extern LPCSTR text_index_search_section[MaxTextIndexNum];

extern int text_index_search_results[MaxTextIndexNum];

extern int env_open_calls;

#if defined(__MINGW32__)
extern int env_close_calls;
#endif

extern LPCSTR env_open_source;

extern LPCSTR env_open_mode;

extern bool env_open_fails;

extern bool capture_closed_file;

extern char closed_file_output[256];

extern void *tracked_free_pointer;

extern int tracked_free_calls;

extern func2 *_free;

extern Text *Txt;

extern TextIndex *TxtIndex;

extern Strings *StringTable;

BOOL __cdecl in_box(int x, int y, const RECT *rect);

extern int failures;

void expect_tracked_free_calls(int expected);

void expect_storage_bytes(
        const uint8_t *storage, const uint8_t *expected, size_t size);

void report_storage_mismatch(
        const char *fixture, const uint8_t *storage, const uint8_t *expected, size_t size);

void seed_storage(uint8_t *storage, uint8_t *expected, size_t size);

template <typename T>
void write_at(uint8_t *storage, size_t offset, const T &value) {
    // An array argument deduces T as the array type, so this would copy every
    // element and leave the first one at the offset where the caller meant to
    // put a pointer. That produced two Wine crashes before it was rejected
    // here; bind an explicit pointer variable instead.
    static_assert(!std::is_array<T>::value,
                  "write_at takes a pointer, not an array");
    std::memcpy(storage + offset, &value, sizeof(value));
}

template <typename T>
void write_at_volatile(uint8_t *storage, size_t offset, const T &value) {
    auto *target = reinterpret_cast<volatile uint8_t *>(storage + offset);
    const auto *source = reinterpret_cast<const uint8_t *>(&value);
    for (size_t index = 0; index < sizeof(value); ++index) {
        target[index] = source[index];
    }
}

void write_buffer_construct_expected(
        uint8_t *expected, size_t base, uint32_t reset_520,
        uint32_t default_font, const uint8_t *palette, int palette_state);

int int_from_bits(uint32_t bits);

struct ScrollCloseProbeState {
    uint8_t *base;
    const uint32_t *static_defaults;
    const uint32_t *dynamic_defaults;
    int order;
};

extern ScrollCloseProbeState scroll_close_probe_state;

uint32_t __fastcall scroll_close_left_probe(void *self, void *);

uint32_t __fastcall scroll_close_right_probe(void *self, void *);

void __thiscall scroll_close_win_probe(void *self);

void __thiscall scroll_close_buffer_probe(void *self);

// Everything Scroll::close needs in order to run: its two default tables, the
// three seams it reaches through, and the two vtables it dispatches on. The
// Scroll suite below builds this inline for a standalone Scroll; wrappers that
// contain a Scroll need the same thing at their member's offset, so it lives
// here rather than being rebuilt per test.
struct ScrollCloseFixture {
    uint32_t fixed[11] = {};
    uint32_t dynamic[17] = {};
    uint32_t base_result = 0x7B3D19E5U;
    uintptr_t left_vtable[0x16C / sizeof(uintptr_t)] = {};
    uintptr_t right_vtable[0x16C / sizeof(uintptr_t)] = {};

    uint32_t *saved_fixed = nullptr;
    uint32_t *saved_dynamic = nullptr;
    func_subobject_close *saved_win = nullptr;
    func_subobject_close *saved_buffer = nullptr;
    uint32_t *saved_base_default = nullptr;

    void install() {
        for (size_t index = 0; index < ARRAYSIZE(fixed); ++index) {
            fixed[index] = 0x51000000U + static_cast<uint32_t>(index) * 0x010203U;
        }
        for (size_t index = 0; index < ARRAYSIZE(dynamic); ++index) {
            dynamic[index] = 0xA1000000U + static_cast<uint32_t>(index) * 0x010101U;
        }
        left_vtable[0x168 / sizeof(uintptr_t)] =
            reinterpret_cast<uintptr_t>(&scroll_close_left_probe);
        right_vtable[0x168 / sizeof(uintptr_t)] =
            reinterpret_cast<uintptr_t>(&scroll_close_right_probe);
        saved_fixed = ScrollCloseStaticDefaults;
        saved_dynamic = ScrollCloseDynamicDefaults;
        saved_win = WinOriginalClose;
        saved_buffer = BufferSubobjectClose;
        saved_base_default = GraphicWinFieldA0CDefault;
        ScrollCloseStaticDefaults = fixed;
        ScrollCloseDynamicDefaults = dynamic;
        WinOriginalClose = scroll_close_win_probe;
        BufferSubobjectClose = scroll_close_buffer_probe;
        GraphicWinFieldA0CDefault = &base_result;
    }

    // Point the object at this fixture's vtables and set the two fields the
    // close path reads: 0xA08 is followed as a pointer when non-null, so it
    // has to be cleared, and 0xA10 is what the probes check they can see.
    void prepare(uint8_t *scroll) {
        uintptr_t *left = left_vtable;
        uintptr_t *right = right_vtable;
        std::memcpy(scroll + 0xAAC, &left, sizeof(left));
        std::memcpy(scroll + 0x15F8, &right, sizeof(right));
        const uint32_t zero = 0;
        const uint32_t marker = 0x13579BDFU;
        std::memcpy(scroll + 0xA08, &zero, sizeof(zero));
        std::memcpy(scroll + 0xA10, &marker, sizeof(marker));
        scroll_close_probe_state = {scroll, fixed, dynamic, 0};
    }

    void restore() {
        ScrollCloseStaticDefaults = saved_fixed;
        ScrollCloseDynamicDefaults = saved_dynamic;
        WinOriginalClose = saved_win;
        BufferSubobjectClose = saved_buffer;
        GraphicWinFieldA0CDefault = saved_base_default;
    }
};

extern int scroll_redraw_calls;

extern Scroll *scroll_redraw_self;

extern uint32_t scroll_redraw_result;

extern uint32_t scroll_redraw_minimum;

extern uint32_t scroll_redraw_maximum;

extern uint32_t scroll_redraw_reverse;

extern uint32_t scroll_redraw_position;

extern Win *scroll_redraw_parent;

extern bool scroll_redraw_check_range;

extern bool scroll_redraw_check_current;

void reset_scroll_redraw_probe();

void install_scroll_redraw_probe(uint8_t *storage, uintptr_t vtable[63]);

extern int scroll_style_redraw_calls;

extern uint8_t *scroll_style_base;

extern size_t scroll_style_offsets[3];

extern uint32_t scroll_style_value;

extern uint32_t scroll_style_results[2];

void install_scroll_style_redraw_probes(
        uint8_t *storage, uintptr_t left_vtable[63],
        uintptr_t right_vtable[63]);

struct PlayerLockProbe {
    int lock_calls;
    void *lock_entry;
    int lock_faction, lock_flags, lock_x, lock_y;
    int unlock_calls;
    void *unlock_entries[4];
    int unlock_faction;
    int active_during_last_unlock;
};

extern PlayerLockProbe g_player_lock_probe;

extern uint8_t *g_player_lock_object;

int __thiscall probe_player_lock_lock(void *entry, int a1, int a2, int a3, int a4);

void __thiscall probe_player_lock_unlock(void *entry, int slot);

extern Dialog *g_base_pop_item_dialog;

extern char *g_base_pop_item_text;

extern int g_base_pop_item_index;

extern int g_base_pop_item_calls;

int __thiscall probe_base_pop_item(Dialog *dialog, char *text, int index);

void expect_heap_clear(uint8_t *expected, size_t heap_offset);

// Recording stand-ins installed into the subobject-destructor seams. The
// destructor's own Probe bookkeeping records its *intent* inline before each
// delegation, so a suite that asserts only on the probe cannot tell whether
// the delegation call itself happened - dropping either call left every probe
// value intact. These stubs are the record of the calls actually being made.
struct GraphicWinStubRecord {
    int buffer_calls;
    void *buffer_target;
    int win_calls;
    void *win_target;
    int sequence;
};

extern GraphicWinStubRecord graphic_win_stub_record;

void __thiscall graphic_win_stub_buffer_destructor(void *target);

void __thiscall graphic_win_stub_win_destructor(void *target);

// Scroll destructor events. Every stage the destructor composes is recovered
// code with exact tests of its own, so the oracle here is compositional: the
// reference image is produced by running the documented component chain on a
// byte-identical object, and the destructor must match it exactly while the
// event log pins the stage order, the object each stage receives, and the two
// staged Scroll vtables that only the close-phase events can observe before
// the final GraphicWin stage overwrites them.
struct ScrollDtorEvent {
    int kind;  // 1 left vclose, 2 right vclose, 3 win close, 4 buffer close,
               // 5 buffer dtor, 6 win dtor, 7 free, 8 operator delete
    const void *target;
    uint32_t scroll_vtable0;
    uint32_t scroll_vtable444;
    int time_count;
};

extern ScrollDtorEvent scroll_dtor_events[24];

extern int scroll_dtor_event_count;

extern uint8_t *scroll_dtor_base;

extern int g_load_undo_arg;

extern int g_load_undo_calls;

extern void *g_tex_freed;

extern int g_tex_free_calls;

void *observe_texture_free(void *p);


#endif  // OPENSMACX_TESTS_LEAF_LEAF_SHARED_H
