set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

find_program(OPENSMACX_MINGW_CXX NAMES i686-w64-mingw32-g++ REQUIRED)
find_program(OPENSMACX_MINGW_RC NAMES i686-w64-mingw32-windres REQUIRED)

set(CMAKE_CXX_COMPILER "${OPENSMACX_MINGW_CXX}" CACHE FILEPATH "i686 MinGW C++ compiler")
set(CMAKE_RC_COMPILER "${OPENSMACX_MINGW_RC}" CACHE FILEPATH "i686 MinGW resource compiler")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
