#!/usr/bin/env python3
"""Give the compiled tree the `VCall` shim the verification units already have.

`emit_translation_unit.vtable_shim` generates one of these INSIDE every
verification unit, sized to the slots that body dispatches through. That works
until a recovered body moves into `src/`: the splice carries the definition and
leaves the shim behind, so the body references a `VCall` the compiled tree has
never heard of.

That is not hypothetical and it is not rare. Eight files - `diplowin.cpp`,
`fx.cpp`, `worldwin.cpp`, `multidebug.cpp`, `pulldown.cpp`, `radiobutton.cpp`,
`stringbox.cpp`, `tutwin.cpp` - were broken exactly this way by the first
integration pass, and the byte-match verification CANNOT catch it: it compiles
each body against the very scaffolding that supplies the missing declaration.
A green ratchet and a broken build are perfectly compatible here.

So the declaration is emitted once, into a header the compiled tree includes,
FROM THE SAME FUNCTION the scaffolding uses. Writing it by hand would let the
two drift, and a shim whose slot offsets disagree with the scaffolding's would
produce bodies that verify and then call the wrong virtual.

Only DECLARATION ORDER decides a slot's offset, so declaring more slots than
any caller uses costs nothing: slot N sits at N*4 whatever follows it. The
count is therefore generous rather than tracking the highest current use, which
would churn this file every time a recovery reached one slot further.

    tools/emit_vtable_shim_header.py
    tools/emit_vtable_shim_header.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import emit_translation_unit as emit  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "src" / "vtable_shim.h"

# The highest slot any recovered body reaches today is 79. This is comfortably
# past it so that landing one more recovery does not rewrite the header.
HIGHEST_SLOT = 95

PREAMBLE = """\
/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once

/*
 * GENERATED by tools/emit_vtable_shim_header.py, from the same
 * `emit_translation_unit.vtable_shim` the verification scaffolding uses, so
 * the two cannot disagree about where a slot sits. Do not edit.
 *
 * VC6 rejects a free `__thiscall` function pointer outright - `error C4234:
 * '__thiscall' keyword reserved for future use` - so an indirect virtual call
 * cannot be spelled directly. Calling the Nth virtual of a class that is never
 * defined and never instantiated makes the COMPILER emit
 * `mov eax, [ptr]; call [eax + N*4]`, which is the original's encoding.
 *
 * WHY A HEADER, when the emitter already writes one per unit: a recovered body
 * moved into `src/` leaves the unit's copy behind. Eight compiled files
 * referenced a `VCall` that did not exist after the first integration pass,
 * and the byte-match verification could not see it - it compiles each body
 * against the scaffolding that supplies the declaration. A green ratchet and a
 * broken build are perfectly compatible.
 *
 * Only DECLARATION ORDER decides a slot's offset, so the generous count costs
 * nothing: slot N sits at N*4 whatever follows it.
 */

"""


def render() -> str:
    body = emit.vtable_shim([HIGHEST_SLOT]).splitlines()
    kept = [line.replace("  // <-- used", "") for line in body
            if line.startswith("class ") or line.startswith("    virtual")
            or line == "};"]
    return PREAMBLE + "\n".join(kept) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed header is stale")
    arguments = parser.parse_args(argv)

    text = render()
    if arguments.check:
        current = OUTPUT.read_text() if OUTPUT.is_file() else ""
        if current != text:
            print(f"error: {OUTPUT} is stale; regenerate it", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"slots 000..{HIGHEST_SLOT:03d} -> {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
