#!/usr/bin/env -S uv run python
"""Files that tell the reader to run something which does not exist.

Nine files carried "GENERATED by tools/<x>.py. Do not edit by hand; edit the
generator and regenerate." Commit 271114cf had retired all eleven bulk
generators as "9,262 lines that nobody could run" - so for months those files
told every reader NOT to edit them in the only way they could be edited. An
instruction that cannot be followed is worse than no instruction: it reads as
authoritative.

This checks every `tools/...` path mentioned in `src/`, `docs/` and
`.claude/agents/` and fails if it is not there. Wire it into whatever runs
before a batch.

`.claude/agents/` WAS THE HOLE, and it hid the worst instance of exactly this
defect. The roots were a hand-written list of two, so a subagent's system
prompt - read by every agent on every dispatch - went months naming FOUR tools
that had been deleted (`verify_recovered_function.py`, `decomp_status.py`,
`agent_brief.py`, `disasm.py`) and describing a scaffold workflow the tree has
zero markers left of. Found by hand on 2026-08-22; a check that scanned prose
for humans but not prose for agents could never have found it.

`.sh` counts too: `tools/agent_setup.sh` is the first command a dispatched
agent runs, and matching only `.py` would not have noticed it going missing.

    uv run tools/stale_references.py

Exit 0 clean, 1 if any referenced tool is missing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MENTION = re.compile(r"\btools/[a-z0-9_]+\.(?:py|sh)\b")
# A mention is IMPERATIVE when its line tells the reader to do something with
# the tool. That distinction is the whole point: `docs/RETIRED_ROUTES.md`
# naming a retired tool is correct and must not fail this check, while
# "Do not edit by hand; edit the generator" pointing at a deleted file is the
# defect. Only imperative mentions set the exit code.
IMPERATIVE = re.compile(
    r"uv run|\brun\b|Do not edit|edit the generator|regenerate", re.I)
# A file that already says the tool is gone is CORRECT, even though it quotes
# the instruction it is retracting. Without this the check flags its own fixes -
# "the old instruction, edit the generator, outlived the generator" contains
# the very phrase it is warning about.
#
# SCOPED TO A WINDOW AROUND THE MENTION, not the whole file. Matching file-wide
# made the check unable to fail: a positive control - one fake
# `uv run tools/definitely_not_a_real_tool.py` added to docs/TOOLS.md - was
# waved through, because a retraction somewhere else in that file excused every
# mention in it.
RETRACTED = re.compile(
    r"NO LONGER EXISTS|was retired|retired the bulk generators|is gone", re.I)


if __name__ == "__main__":
    # `src/recovered/` and `src/unrecovered/` are ARCHIVES: their headers record
    # which tool produced them, which is history and stays true even after the
    # tool is retired. 3,500 of those buried the nine hand-written INSTRUCTIONS
    # that were the real defect. Only live source and docs are checked.
    roots = [REPO_ROOT / "src", REPO_ROOT / "docs",
             REPO_ROOT / ".claude" / "agents"]
    archived = (REPO_ROOT / "src" / "recovered", REPO_ROOT / "src" / "unrecovered")
    missing: dict[str, set] = {}
    mentioned: dict[str, set] = {}
    scanned = 0
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob("*")):
            if not path.is_file() or path.suffix not in (".cpp", ".h", ".md", ".csv"):
                continue
            if any(str(path).startswith(str(a)) for a in archived):
                continue
            scanned += 1
            try:
                text = path.read_text(errors="replace")
            except OSError:
                continue
            lines = text.splitlines()
            for number, line in enumerate(lines):
                for tool in set(MENTION.findall(line)):
                    if (REPO_ROOT / tool).exists():
                        continue
                    where = str(path.relative_to(REPO_ROOT))
                    window = "\n".join(
                        lines[max(0, number - 6):number + 7])
                    imperative = (IMPERATIVE.search(line)
                                  and not RETRACTED.search(window))
                    bucket = missing if imperative else mentioned
                    bucket.setdefault(tool, set()).add(where)

    # A COUNT AND THREE EXAMPLES, not every file. The first draft listed every
    # reference and produced 186KB, because `src/recovered/units/` carries a
    # few thousand copies of the same provenance header - which buries the nine
    # hand-written references that were the actual defect.
    for tool, wheres in sorted(missing.items(), key=lambda kv: -len(kv[1])):
        wheres = sorted(wheres)
        print(f"  MISSING {tool}  ({len(wheres):,} reference(s))")
        for where in wheres[:3]:
            print(f"      e.g. {where}")
        if len(wheres) > 3:
            print(f"      ... and {len(wheres) - 3:,} more")
    if not missing:
        print("  no instruction names a tool that is not there")
    print(f"\n{scanned:,} file(s) scanned; {len(missing)} missing tool(s) named by an "
          f"INSTRUCTION, {len(mentioned)} more merely mentioned")
    if mentioned and "--all" in sys.argv:
        print("\nMentioned but not instructed - history, and fine:")
        for tool in sorted(mentioned):
            print(f"  {tool}")
    sys.exit(1 if missing else 0)
