#!/usr/bin/env -S uv run python
"""Files that tell the reader to run something which does not exist.

Nine files carried "GENERATED by tools/<x>.py. Do not edit by hand; edit the
generator and regenerate." Commit 271114cf had retired all eleven bulk
generators as "9,262 lines that nobody could run" - so for months those files
told every reader NOT to edit them in the only way they could be edited. An
instruction that cannot be followed is worse than no instruction: it reads as
authoritative.

This checks every `tools/...` path mentioned in `src/`, `docs/` and
`.claude/agents/` and fails if it is not there. Wire it into whatever runs
before a batch.

`.claude/agents/` WAS THE HOLE, and it hid the worst instance of exactly this
defect. The roots were a hand-written list of two, so a subagent's system
prompt - read by every agent on every dispatch - went months naming FOUR tools
that had been deleted (`verify_recovered_function.py`, `decomp_status.py`,
`agent_brief.py`, `disasm.py`) and describing a scaffold workflow the tree has
zero markers left of. Found by hand on 2026-08-22; a check that scanned prose
for humans but not prose for agents could never have found it.

`.sh` counts too: `tools/agent_setup.sh` is the first command a dispatched
agent runs, and matching only `.py` would not have noticed it going missing.

    uv run tools/stale_references.py

Exit 0 clean, 1 if any referenced tool or source file is missing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MENTION = re.compile(r"\btools/[a-z0-9_]+\.(?:py|sh)\b")
# SOURCE PATHS TOO, and they need the opposite default. A retired tool named in
# `docs/RETIRED_ROUTES.md` is a catalogue entry and must not fail; a source file
# named in a marker's prose is a CLAIM about code the reader can go and read, so
# a path that is not there is a defect unless the prose says it went away.
#
# The distinction is worth the second pattern. `src/main.cpp` argued for fifty
# lines that a call site could only be spelled as a literal address, and cited
# "it is BYTE_EXACT in src/unrecovered/00604e40.cpp" as the evidence - a file
# that had been deleted when the body was promoted into `src/basepop.cpp`. Both
# halves were stale and the gate could not see either, because this check
# scanned tool names only.
SOURCE = re.compile(r"\bsrc/[A-Za-z0-9_/]+\.(?:cpp|h)\b")
# Measured against the tree: 83 references name a source path that is gone, and
# 58 of them already say so. Prose that records where a body CAME FROM is
# history and stays true - what is left is the live claims.
# `homed from` BELONGS HERE BY CONSTRUCTION, for the same reason
# `was deleted` belongs in RETRACTED below: it is the tree's own word for
# "moved here from", which is already in this list. Homing a body deletes
# its artifact file, and the comment recording where the body CAME FROM is
# history that stays true. Without the word, the check refuses a true
# statement - and the tempting fix is to reword the comment into something
# vaguer that passes, trading a fact for a phrasing. Add the vocabulary.
GONE = re.compile(
    r"deleted|retired|promoted|merged from|moved here from|homed from|"
    r"went into|no longer|used to|was replaced|scratch artifact|earlier",
    re.I)
# A mention is IMPERATIVE when its line tells the reader to do something with
# the tool. That distinction is the whole point: `docs/RETIRED_ROUTES.md`
# naming a retired tool is correct and must not fail this check, while
# "Do not edit by hand; edit the generator" pointing at a deleted file is the
# defect. Only imperative mentions set the exit code.
IMPERATIVE = re.compile(
    r"uv run|\brun\b|Do not edit|edit the generator|regenerate", re.I)
# A file that already says the tool is gone is CORRECT, even though it quotes
# the instruction it is retracting. Without this the check flags its own fixes -
# "the old instruction, edit the generator, outlived the generator" contains
# the very phrase it is warning about.
#
# SCOPED TO A WINDOW AROUND THE MENTION, not the whole file. Matching file-wide
# made the check unable to fail: a positive control - one fake
# `uv run tools/definitely_not_a_real_tool.py` added to a doc - was
# waved through, because a retraction somewhere else in that file excused every
# mention in it.
# `(?:was|were|both) deleted` BELONGS HERE BY CONSTRUCTION. It was missing, and
# the omission bit the moment this check was pointed at `AGENTS.md`: a line
# reading "Run `uv run tools/osmx.py status`. (`tools/recovery_metrics.py` was
# deleted...)" is a LIVE instruction naming a dead tool as history - exactly
# what this file is for - and it failed, because IMPERATIVE is per-line and
# "uv run" and the dead name share the line. The tempting fix is to reword the
# sentence until the check likes it, which trades a true statement for a
# vaguer one that passes. The vocabulary was incomplete: `was retired` and
# `is gone` were already here, and `was deleted` is the same act.
RETRACTED = re.compile(
    r"NO LONGER EXISTS|was retired|retired the bulk generators|is gone|"
    r"(?:was|were|both) deleted", re.I)


if __name__ == "__main__":
    # `src/recovered/` and `src/unrecovered/` are ARCHIVES: their headers record
    # which tool produced them, which is history and stays true even after the
    # tool is retired. 3,500 of those buried the nine hand-written INSTRUCTIONS
    # that were the real defect. Only live source and docs are checked.
    # `.claude/` ENTIRE, not just `agents/`. `.claude/commands/recover-batch.md`
    # is a slash command a human types, and every one of its seven `uv run`
    # lines named a tool that had been deleted - `recovery_frontier.py`,
    # `decomp_status.py`, `agent_brief.py`, `refresh_file_units.py`,
    # `verify_member_offsets.py`, `member_map.py`, `verify_void_returns.py`.
    # Typing it failed at step 1. The roots were widened to `agents/` once, for
    # exactly this defect, and stopped one directory short of the other file
    # where it had already happened.
    #
    # REPO-ROOT `*.md` too. `AGENTS.md` is 820 lines of handoff and named two
    # more imperatively; it sits under no directory root at all, so no amount
    # of widening `docs/` would ever have reached it.
    roots = [REPO_ROOT / "src", REPO_ROOT / "docs", REPO_ROOT / ".claude"]
    # `.claude/worktrees/` holds AGENT CHECKOUTS - whole copies of this repo,
    # archives and all. Scanning them re-scans `src/recovered/` under a
    # different prefix and reports the same reference once per live worktree.
    archived = (REPO_ROOT / "src" / "recovered", REPO_ROOT / "src" / "unrecovered",
                REPO_ROOT / ".claude" / "worktrees")
    missing: dict[str, set] = {}
    mentioned: dict[str, set] = {}
    scanned = 0
    groups = [sorted(root.rglob("*")) for root in roots if root.exists()]
    groups.append(sorted(REPO_ROOT.glob("*.md")))
    for group in groups:
        for path in group:
            if not path.is_file() or path.suffix not in (".cpp", ".h", ".md", ".csv"):
                continue
            if any(str(path).startswith(str(a)) for a in archived):
                continue
            scanned += 1
            try:
                text = path.read_text(errors="replace")
            except OSError:
                continue
            lines = text.splitlines()
            for number, line in enumerate(lines):
                window = "\n".join(lines[max(0, number - 6):number + 7])
                where = str(path.relative_to(REPO_ROOT))
                for tool in set(MENTION.findall(line)):
                    if (REPO_ROOT / tool).exists():
                        continue
                    imperative = (IMPERATIVE.search(line)
                                  and not RETRACTED.search(window))
                    bucket = missing if imperative else mentioned
                    bucket.setdefault(tool, set()).add(where)
                for ref in set(SOURCE.findall(line)):
                    if (REPO_ROOT / ref).exists():
                        continue
                    bucket = mentioned if GONE.search(window) else missing
                    bucket.setdefault(ref, set()).add(where)

    # A COUNT AND THREE EXAMPLES, not every file. The first draft listed every
    # reference and produced 186KB, because `src/recovered/units/` carries a
    # few thousand copies of the same provenance header - which buries the nine
    # hand-written references that were the actual defect.
    for tool, wheres in sorted(missing.items(), key=lambda kv: -len(kv[1])):
        wheres = sorted(wheres)
        print(f"  MISSING {tool}  ({len(wheres):,} reference(s))")
        for where in wheres[:3]:
            print(f"      e.g. {where}")
        if len(wheres) > 3:
            print(f"      ... and {len(wheres) - 3:,} more")
    if not missing:
        print("  no instruction names a tool, and no live claim names a source "
              "file, that is not there")
    print(f"\n{scanned:,} file(s) scanned; {len(missing)} missing path(s) named by a "
          f"LIVE reference, {len(mentioned)} more merely mentioned as history")
    if mentioned and "--all" in sys.argv:
        print("\nMentioned but not instructed - history, and fine:")
        for tool in sorted(mentioned):
            print(f"  {tool}")
    sys.exit(1 if missing else 0)
