/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

/*
 * Virtual-base adjustor thunks
 *
 * One compiler-emitted thunk per virtual a class overrides through a virtual
 * base. Each subtracts the vtordisp stored at a fixed negative displacement
 * from `this`, optionally subtracts a further fixed subobject offset, and tail
 * calls the real method with the arguments untouched. The receiver arithmetic
 * is the whole of the behaviour, so it is what the suite pins.
 *
 * The forward goes through one rebindable seam per distinct target rather
 * than one per thunk: several of these thunks share a target, and a single
 * seam per target is what lets the suite prove that two thunks onto the same
 * method adjust `this` differently. Each seam defaults to the original
 * address; the hybrid redirects those to recovered bodies at run time.
 *
 * Generated by tools/generate_adjustor_thunks.py - do not edit by hand.
 */

typedef int (OriginalObject::*func_adjustor_i_i)(int);
typedef int (OriginalObject::*func_adjustor_i_ii)(int, int);
typedef int (OriginalObject::*func_adjustor_i_p)(void *);
typedef int (OriginalObject::*func_adjustor_i_piii)(void *, int, int, int);
typedef void * (OriginalObject::*func_adjustor_p_u)(unsigned int);
typedef void (OriginalObject::*func_adjustor_v)();
typedef void (OriginalObject::*func_adjustor_v_i)(int);
typedef void (OriginalObject::*func_adjustor_v_ii)(int, int);
typedef void (OriginalObject::*func_adjustor_v_pi)(void *, int);

extern func_adjustor_i_piii CheckBoxAttachTarget;   // 0x0060E800
extern func_adjustor_v_i CheckBoxOnDialogFocusTarget;   // 0x0060FB90
extern func_adjustor_i_i CheckBoxOnKeyDownTarget;   // 0x0060F8B0
extern func_adjustor_v_ii CheckBoxOnLeftDoubleClickTarget;   // 0x0060FA80
extern func_adjustor_v_ii CheckBoxOnLeftDownTarget;   // 0x0060F700
extern func_adjustor_v_ii CheckBoxOnMouseLeaveTarget;   // 0x0060FC30
extern func_adjustor_v_ii CheckBoxOnMouseMoveTarget;   // 0x0060FBB0
extern func_adjustor_v CheckBoxOnRedrawTarget;   // 0x0060FAB0
extern func_adjustor_i_ii ConsoleOnKeyClickTarget;   // 0x005178C0
extern func_adjustor_v_ii ConsoleOnNcHittestTarget;   // 0x0050F680
extern func_adjustor_v_ii ConsoleOnNcLeftDownTarget;   // 0x0050FB10
extern func_adjustor_v_ii ConsoleOnNcLeftUpTarget;   // 0x0050FE70
extern func_adjustor_v_ii ConsoleOnNcMouseMoveTarget;   // 0x00510110
extern func_adjustor_v_pi ConsoleOnPostRedrawNcBufferTarget;   // 0x0050F960
extern func_adjustor_v ConsoleOnSysCloseTarget;   // 0x0051D7C0
extern func_adjustor_p_u ConsoleScalarDeleteTarget;   // 0x0051DDF0
extern func_adjustor_i_piii DialogsAttachTarget;   // 0x00612FE0
extern func_adjustor_v_i DialogsOnDialogFocusTarget;   // 0x006130E0
extern func_adjustor_i_i DialogsOnKeyDownTarget;   // 0x00612CC0
extern func_adjustor_v_ii DialogsOnLeftClickTarget;   // 0x00612E80
extern func_adjustor_v_ii DialogsOnLeftDoubleClickTarget;   // 0x00612D60
extern func_adjustor_v_ii DialogsOnLeftDownTarget;   // 0x00612C20
extern func_adjustor_v_ii DialogsOnLeftUpTarget;   // 0x00612F10
extern func_adjustor_v_ii DialogsOnMouseLeaveTarget;   // 0x00612AE0
extern func_adjustor_v_ii DialogsOnMouseMoveTarget;   // 0x00612B80
extern func_adjustor_v_i DialogsOnMousewheelTarget;   // 0x00612FC0
extern func_adjustor_v DialogsOnRedrawTarget;   // 0x00612E00
extern func_adjustor_v_ii DialogsOnRightClickTarget;   // 0x00612F60
extern func_adjustor_v_ii DialogsOnRightDoubleClickTarget;   // 0x00612EF0
extern func_adjustor_v_ii DialogsOnRightDownTarget;   // 0x00612ED0
extern func_adjustor_v_ii DialogsOnRightUpTarget;   // 0x00612F40
extern func_adjustor_v DialogsOnScrollCreateTarget;   // 0x00613220
extern func_adjustor_i_p DialogsOnScrollDeleteTarget;   // 0x00613260
extern func_adjustor_v_ii DialogsOnScrolledTarget;   // 0x00612F80
extern func_adjustor_v_ii DialogsOnScrollingTarget;   // 0x00612FA0
extern func_adjustor_v DialogsPassDialogFocusTarget;   // 0x00613180
extern func_adjustor_p_u DialogsScalarDeleteTarget;   // 0x00407100
extern func_adjustor_i_piii EditGroupAttachTarget;   // 0x00611AF0
extern func_adjustor_v_i EditGroupOnDialogFocusTarget;   // 0x00612670
extern func_adjustor_v EditGroupOnRedrawTarget;   // 0x00612450
extern func_adjustor_v EditGroupPassDialogFocusTarget;   // 0x006126C0
extern func_adjustor_i_piii ListBoxAttachTarget;   // 0x0060A670
extern func_adjustor_v_i ListBoxOnDialogFocusTarget;   // 0x0060C7C0
extern func_adjustor_v_i ListBoxOnKeyDownTarget;   // 0x0060AF90
extern func_adjustor_v_ii ListBoxOnLeftDoubleClickTarget;   // 0x0060C710
extern func_adjustor_v_ii ListBoxOnLeftDownTarget;   // 0x0060AA60
extern func_adjustor_v_ii ListBoxOnMouseLeaveTarget;   // 0x0060CE10
extern func_adjustor_v_ii ListBoxOnMouseMoveTarget;   // 0x0060CBC0
extern func_adjustor_v_i ListBoxOnMousewheelTarget;   // 0x0060CB70
extern func_adjustor_v ListBoxOnRedrawTarget;   // 0x0060C350
extern func_adjustor_v_ii ListBoxOnRightDoubleClickTarget;   // 0x0060C6D0
extern func_adjustor_v_ii ListBoxOnRightDownTarget;   // 0x0060AA20
extern func_adjustor_v_ii ListBoxOnScrolledTarget;   // 0x0060C6A0
extern func_adjustor_v_ii ListBoxOnScrollingTarget;   // 0x0060C5D0
extern func_adjustor_v_i MapWinOnButtonClickedTarget;   // 0x0046F8C0
extern func_adjustor_v_ii MapWinOnLeftClickTarget;   // 0x0046EBA0
extern func_adjustor_v_ii MapWinOnLeftDoubleClickTarget;   // 0x0046EBD0
extern func_adjustor_v_ii MapWinOnLeftDownTarget;   // 0x0046ED30
extern func_adjustor_v_ii MapWinOnLeftUpTarget;   // 0x0046EFF0
extern func_adjustor_v MapWinOnLoseMouseCaptureTarget;   // 0x0046EB90
extern func_adjustor_v_ii MapWinOnMouseMoveTarget;   // 0x0046F000
extern func_adjustor_v_ii MapWinOnNcHittestTarget;   // 0x0046F660
extern func_adjustor_v_ii MapWinOnNcLeftDownTarget;   // 0x0046F700
extern func_adjustor_v MapWinOnRedrawTarget;   // 0x0046B1D0
extern func_adjustor_v_ii MapWinOnResizeTarget;   // 0x0046FA00
extern func_adjustor_v_ii MapWinOnRightClickTarget;   // 0x0046EBE0
extern func_adjustor_v_ii MapWinOnRightDownTarget;   // 0x0046EC10
extern func_adjustor_v MapWinOnSysCloseTarget;   // 0x0046F880
extern func_adjustor_p_u MapWinScalarDeleteTarget;   // 0x00421830
extern func_adjustor_v PlanWinOnRedrawTarget;   // 0x0048AF30
extern func_adjustor_p_u PlanWinScalarDeleteTarget;   // 0x0048BF20
extern func_adjustor_i_piii RadioButtonAttachTarget;   // 0x0060D1F0
extern func_adjustor_v_i RadioButtonDtorTarget;   // 0x00406F60
extern func_adjustor_v_i RadioButtonOnDialogFocusTarget;   // 0x0060E300
extern func_adjustor_i_i RadioButtonOnKeyDownTarget;   // 0x0060E020
extern func_adjustor_v_ii RadioButtonOnLeftDoubleClickTarget;   // 0x0060E1E0
extern func_adjustor_v_ii RadioButtonOnLeftDownTarget;   // 0x0060DE10
extern func_adjustor_v_ii RadioButtonOnMouseLeaveTarget;   // 0x0060E4A0
extern func_adjustor_v_ii RadioButtonOnMouseMoveTarget;   // 0x0060E320
extern func_adjustor_v RadioButtonOnRedrawTarget;   // 0x0060E220
extern func_adjustor_i_piii SpriteBoxAttachTarget;   // 0x00610540
extern func_adjustor_v_i SpriteBoxOnDialogFocusTarget;   // 0x006115E0
extern func_adjustor_i_i SpriteBoxOnKeyDownTarget;   // 0x00611400
extern func_adjustor_v_ii SpriteBoxOnLeftClickTarget;   // 0x00611060
extern func_adjustor_v_ii SpriteBoxOnLeftDoubleClickTarget;   // 0x006112E0
extern func_adjustor_v_ii SpriteBoxOnLeftDownTarget;   // 0x00611150
extern func_adjustor_v_ii SpriteBoxOnLeftUpTarget;   // 0x006111A0
extern func_adjustor_v_ii SpriteBoxOnMouseLeaveTarget;   // 0x00611050
extern func_adjustor_v_ii SpriteBoxOnMouseMoveTarget;   // 0x00611040
extern func_adjustor_v SpriteBoxOnRedrawTarget;   // 0x00611380
extern func_adjustor_v_ii SpriteBoxOnRightClickTarget;   // 0x006111F0
extern func_adjustor_v_ii SpriteBoxOnRightDoubleClickTarget;   // 0x00611330
extern func_adjustor_v_ii SpriteBoxOnRightDownTarget;   // 0x00611240
extern func_adjustor_v_ii SpriteBoxOnRightUpTarget;   // 0x00611290

void __fastcall adjust_radio_button1_dtor(void *self, void *, int arg0);
void __fastcall adjust_radio_button1_on_redraw(void *self, void *);
void __fastcall adjust_radio_button1_on_mouse_move(void *self, void *,
                                                   int arg0, int arg1);
void __fastcall adjust_radio_button1_on_mouse_leave(void *self, void *,
                                                    int arg0, int arg1);
void __fastcall adjust_radio_button1_on_left_down(void *self, void *,
                                                  int arg0, int arg1);
int __fastcall adjust_radio_button1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_radio_button1_on_left_double_click(void *self, void *,
                                                          int arg0, int arg1);
void __fastcall adjust_radio_button1_on_dialog_focus(void *self, void *,
                                                     int arg0);
void __fastcall adjust_radio_button2_dtor(void *self, void *, int arg0);
void __fastcall adjust_radio_button3_dtor(void *self, void *, int arg0);
int __fastcall adjust_radio_button1_attach(void *self, void *, void *arg0,
                                           int arg1, int arg2, int arg3);
void __fastcall adjust_radio_button3_on_redraw(void *self, void *);
void * __fastcall adjust_dialogs1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_dialogs1_on_scroll_create(void *self, void *);
int __fastcall adjust_dialogs1_on_scroll_delete(void *self, void *,
                                                void *arg0);
void __fastcall adjust_dialogs1_on_redraw(void *self, void *);
void __fastcall adjust_dialogs1_on_mousewheel(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_mouse_leave(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_dialogs1_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_dialogs1_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_dialogs1_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_dialogs1_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_right_up(void *self, void *, int arg0,
                                            int arg1);
int __fastcall adjust_dialogs1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_dialogs1_on_right_double_click(void *self, void *,
                                                      int arg0, int arg1);
void __fastcall adjust_dialogs1_on_scrolled(void *self, void *, int arg0,
                                            int arg1);
void __fastcall adjust_dialogs1_on_scrolling(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_dialogs1_on_dialog_focus(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_pass_dialog_focus(void *self, void *);
void * __fastcall adjust_dialogs2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void * __fastcall adjust_dialogs3_scalar_delete(void *self, void *,
                                                unsigned int arg0);
int __fastcall adjust_dialogs1_attach(void *self, void *, void *arg0,
                                      int arg1, int arg2, int arg3);
void __fastcall adjust_dialogs3_on_redraw(void *self, void *);
void * __fastcall adjust_map_win1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win1_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_map_win1_on_redraw(void *self, void *);
void __fastcall adjust_map_win1_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_map_win1_on_sys_close(void *self, void *);
void __fastcall adjust_map_win1_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win1_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win1_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win1_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_map_win1_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_map_win1_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_map_win1_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_map_win2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win5_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_plan_win1_on_redraw(void *self, void *);
void __fastcall adjust_map_win5_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_map_win5_on_sys_close(void *self, void *);
void __fastcall adjust_map_win5_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win5_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win5_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win5_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_map_win5_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_map_win5_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_map_win5_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_plan_win2_scalar_delete(void *self, void *,
                                                 unsigned int arg0);
void * __fastcall adjust_console1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win4_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_map_win4_on_redraw(void *self, void *);
void __fastcall adjust_map_win4_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_console1_on_sys_close(void *self, void *);
void __fastcall adjust_map_win4_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win4_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win4_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win4_on_right_down(void *self, void *, int arg0,
                                              int arg1);
int __fastcall adjust_console1_on_key_click(void *self, void *, int arg0,
                                            int arg1);
void __fastcall adjust_map_win4_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_console1_on_nc_mouse_move(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_console1_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_console1_on_nc_left_up(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_console1_on_post_redraw_nc_buffer(void *self, void *,
                                                         void *arg0, int arg1);
void __fastcall adjust_console1_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_console2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_list_box1_on_redraw(void *self, void *);
void __fastcall adjust_list_box1_on_mousewheel(void *self, void *, int arg0);
void __fastcall adjust_list_box1_on_mouse_move(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_list_box1_on_mouse_leave(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_list_box1_on_left_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_list_box1_on_right_down(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_list_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_list_box1_on_left_double_click(void *self, void *,
                                                      int arg0, int arg1);
void __fastcall adjust_list_box1_on_right_double_click(void *self, void *,
                                                       int arg0, int arg1);
void __fastcall adjust_list_box1_on_scrolled(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_list_box1_on_scrolling(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_list_box1_on_dialog_focus(void *self, void *, int arg0);
int __fastcall adjust_list_box1_attach(void *self, void *, void *arg0,
                                       int arg1, int arg2, int arg3);
void __fastcall adjust_list_box3_on_redraw(void *self, void *);
void __fastcall adjust_check_box1_on_redraw(void *self, void *);
void __fastcall adjust_check_box1_on_mouse_move(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_check_box1_on_mouse_leave(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_check_box1_on_left_down(void *self, void *, int arg0,
                                               int arg1);
int __fastcall adjust_check_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_check_box1_on_left_double_click(void *self, void *,
                                                       int arg0, int arg1);
void __fastcall adjust_check_box1_on_dialog_focus(void *self, void *,
                                                  int arg0);
int __fastcall adjust_check_box1_attach(void *self, void *, void *arg0,
                                        int arg1, int arg2, int arg3);
void __fastcall adjust_check_box3_on_redraw(void *self, void *);
void __fastcall adjust_sprite_box1_on_redraw(void *self, void *);
void __fastcall adjust_sprite_box1_on_mouse_move(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_mouse_leave(void *self, void *,
                                                  int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_left_click(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_sprite_box1_on_left_up(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_sprite_box1_on_right_click(void *self, void *,
                                                  int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_right_down(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_right_up(void *self, void *, int arg0,
                                               int arg1);
int __fastcall adjust_sprite_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_sprite_box1_on_left_double_click(void *self, void *,
                                                        int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_right_double_click(void *self, void *,
                                                         int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_dialog_focus(void *self, void *,
                                                   int arg0);
int __fastcall adjust_sprite_box1_attach(void *self, void *, void *arg0,
                                         int arg1, int arg2, int arg3);
void __fastcall adjust_sprite_box3_on_redraw(void *self, void *);
void __fastcall adjust_edit_group1_on_redraw(void *self, void *);
void __fastcall adjust_edit_group1_on_dialog_focus(void *self, void *,
                                                   int arg0);
void __fastcall adjust_edit_group1_pass_dialog_focus(void *self, void *);
int __fastcall adjust_edit_group1_attach(void *self, void *, void *arg0,
                                         int arg1, int arg2, int arg3);
void __fastcall adjust_edit_group3_on_redraw(void *self, void *);
