/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

/*
 * Virtual-base adjustor thunks
 *
 * One compiler-emitted thunk per virtual a class overrides through a virtual
 * base. Each subtracts the vtordisp stored at a fixed negative displacement
 * from `this`, optionally subtracts a further fixed subobject offset, and tail
 * calls the real method with the arguments untouched. The receiver arithmetic
 * is the whole of the behaviour, so it is what the suite pins.
 *
 * The forward goes through one rebindable seam per distinct target rather
 * than one per thunk: several of these thunks share a target, and a single
 * seam per target is what lets the suite prove that two thunks onto the same
 * method adjust `this` differently. Each seam defaults to the original
 * address; the hybrid redirects those to recovered bodies at run time.
 *
 * Was generated by tools/generate_adjustor_thunks.py, WHICH NO LONGER EXISTS:
 * commit 271114cf retired the bulk generators as "9,262 lines that nobody
 * could run". EDIT THIS FILE DIRECTLY. The old instruction - edit the
 * generator, not the file - outlived the generator by months and told every
 * reader not to touch this file in the only way it can now be touched.
 */

typedef void * (OriginalObject::*func_adjustor_p_u)(unsigned int);
typedef void (OriginalObject::*func_adjustor_v_i)(int);

extern func_adjustor_p_u ConsoleScalarDeleteTarget;   // 0x0051DDF0
extern func_adjustor_p_u DialogsScalarDeleteTarget;   // 0x00407100
extern func_adjustor_p_u MapWinScalarDeleteTarget;   // 0x00421830
extern func_adjustor_p_u PlanWinScalarDeleteTarget;   // 0x0048BF20
extern func_adjustor_v_i RadioButtonDtorTarget;   // 0x00406F60

void __fastcall adjust_radio_button1_dtor(void *self, void *, int arg0);
void __fastcall adjust_radio_button1_on_redraw(void *self, void *);
void __fastcall adjust_radio_button1_on_mouse_move(void *self, void *,
                                                   int arg0, int arg1);
void __fastcall adjust_radio_button1_on_mouse_leave(void *self, void *,
                                                    int arg0, int arg1);
void __fastcall adjust_radio_button1_on_left_down(void *self, void *,
                                                  int arg0, int arg1);
int __fastcall adjust_radio_button1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_radio_button1_on_left_double_click(void *self, void *,
                                                          int arg0, int arg1);
void __fastcall adjust_radio_button1_on_dialog_focus(void *self, void *,
                                                     int arg0);
void __fastcall adjust_radio_button2_dtor(void *self, void *, int arg0);
void __fastcall adjust_radio_button3_dtor(void *self, void *, int arg0);
int __fastcall adjust_radio_button1_attach(void *self, void *, void *arg0,
                                           int arg1, int arg2, int arg3);
void __fastcall adjust_radio_button3_on_redraw(void *self, void *);
void * __fastcall adjust_dialogs1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_dialogs1_on_scroll_create(void *self, void *);
int __fastcall adjust_dialogs1_on_scroll_delete(void *self, void *,
                                                void *arg0);
void __fastcall adjust_dialogs1_on_redraw(void *self, void *);
void __fastcall adjust_dialogs1_on_mousewheel(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_mouse_leave(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_dialogs1_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_dialogs1_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_dialogs1_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_dialogs1_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_dialogs1_on_right_up(void *self, void *, int arg0,
                                            int arg1);
int __fastcall adjust_dialogs1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_dialogs1_on_right_double_click(void *self, void *,
                                                      int arg0, int arg1);
void __fastcall adjust_dialogs1_on_scrolled(void *self, void *, int arg0,
                                            int arg1);
void __fastcall adjust_dialogs1_on_scrolling(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_dialogs1_on_dialog_focus(void *self, void *, int arg0);
void __fastcall adjust_dialogs1_pass_dialog_focus(void *self, void *);
void * __fastcall adjust_dialogs2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void * __fastcall adjust_dialogs3_scalar_delete(void *self, void *,
                                                unsigned int arg0);
int __fastcall adjust_dialogs1_attach(void *self, void *, void *arg0,
                                      int arg1, int arg2, int arg3);
void __fastcall adjust_dialogs3_on_redraw(void *self, void *);
void * __fastcall adjust_map_win1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win1_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_map_win1_on_redraw(void *self, void *);
void __fastcall adjust_map_win1_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_map_win1_on_sys_close(void *self, void *);
void __fastcall adjust_map_win1_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win1_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win1_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win1_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win1_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_map_win1_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_map_win1_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_map_win1_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_map_win2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win5_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_plan_win1_on_redraw(void *self, void *);
void __fastcall adjust_map_win5_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_map_win5_on_sys_close(void *self, void *);
void __fastcall adjust_map_win5_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win5_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win5_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win5_on_right_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win5_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_map_win5_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_map_win5_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_map_win5_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_plan_win2_scalar_delete(void *self, void *,
                                                 unsigned int arg0);
void * __fastcall adjust_console1_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_map_win4_on_lose_mouse_capture(void *self, void *);
void __fastcall adjust_map_win4_on_redraw(void *self, void *);
void __fastcall adjust_map_win4_on_resize(void *self, void *, int arg0,
                                          int arg1);
void __fastcall adjust_console1_on_sys_close(void *self, void *);
void __fastcall adjust_map_win4_on_mouse_move(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_left_click(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_left_down(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_map_win4_on_left_up(void *self, void *, int arg0,
                                           int arg1);
void __fastcall adjust_map_win4_on_right_click(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_map_win4_on_right_down(void *self, void *, int arg0,
                                              int arg1);
int __fastcall adjust_console1_on_key_click(void *self, void *, int arg0,
                                            int arg1);
void __fastcall adjust_map_win4_on_left_double_click(void *self, void *,
                                                     int arg0, int arg1);
void __fastcall adjust_console1_on_nc_mouse_move(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_console1_on_nc_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_console1_on_nc_left_up(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_map_win4_on_button_clicked(void *self, void *,
                                                  int arg0);
void __fastcall adjust_console1_on_post_redraw_nc_buffer(void *self, void *,
                                                         void *arg0, int arg1);
void __fastcall adjust_console1_on_nc_hittest(void *self, void *, int arg0,
                                              int arg1);
void * __fastcall adjust_console2_scalar_delete(void *self, void *,
                                                unsigned int arg0);
void __fastcall adjust_list_box1_on_redraw(void *self, void *);
void __fastcall adjust_list_box1_on_mousewheel(void *self, void *, int arg0);
void __fastcall adjust_list_box1_on_mouse_move(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_list_box1_on_mouse_leave(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_list_box1_on_left_down(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_list_box1_on_right_down(void *self, void *, int arg0,
                                               int arg1);
void __fastcall adjust_list_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_list_box1_on_left_double_click(void *self, void *,
                                                      int arg0, int arg1);
void __fastcall adjust_list_box1_on_right_double_click(void *self, void *,
                                                       int arg0, int arg1);
void __fastcall adjust_list_box1_on_scrolled(void *self, void *, int arg0,
                                             int arg1);
void __fastcall adjust_list_box1_on_scrolling(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_list_box1_on_dialog_focus(void *self, void *, int arg0);
int __fastcall adjust_list_box1_attach(void *self, void *, void *arg0,
                                       int arg1, int arg2, int arg3);
void __fastcall adjust_list_box3_on_redraw(void *self, void *);
void __fastcall adjust_check_box1_on_redraw(void *self, void *);
void __fastcall adjust_check_box1_on_mouse_move(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_check_box1_on_mouse_leave(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_check_box1_on_left_down(void *self, void *, int arg0,
                                               int arg1);
int __fastcall adjust_check_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_check_box1_on_left_double_click(void *self, void *,
                                                       int arg0, int arg1);
void __fastcall adjust_check_box1_on_dialog_focus(void *self, void *,
                                                  int arg0);
int __fastcall adjust_check_box1_attach(void *self, void *, void *arg0,
                                        int arg1, int arg2, int arg3);
void __fastcall adjust_check_box3_on_redraw(void *self, void *);
void __fastcall adjust_sprite_box1_on_redraw(void *self, void *);
void __fastcall adjust_sprite_box1_on_mouse_move(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_mouse_leave(void *self, void *,
                                                  int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_left_click(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_left_down(void *self, void *, int arg0,
                                                int arg1);
void __fastcall adjust_sprite_box1_on_left_up(void *self, void *, int arg0,
                                              int arg1);
void __fastcall adjust_sprite_box1_on_right_click(void *self, void *,
                                                  int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_right_down(void *self, void *, int arg0,
                                                 int arg1);
void __fastcall adjust_sprite_box1_on_right_up(void *self, void *, int arg0,
                                               int arg1);
int __fastcall adjust_sprite_box1_on_key_down(void *self, void *, int arg0);
void __fastcall adjust_sprite_box1_on_left_double_click(void *self, void *,
                                                        int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_right_double_click(void *self, void *,
                                                         int arg0, int arg1);
void __fastcall adjust_sprite_box1_on_dialog_focus(void *self, void *,
                                                   int arg0);
int __fastcall adjust_sprite_box1_attach(void *self, void *, void *arg0,
                                         int arg1, int arg2, int arg3);
void __fastcall adjust_sprite_box3_on_redraw(void *self, void *);
void __fastcall adjust_edit_group1_on_redraw(void *self, void *);
void __fastcall adjust_edit_group1_on_dialog_focus(void *self, void *,
                                                   int arg0);
void __fastcall adjust_edit_group1_pass_dialog_focus(void *self, void *);
int __fastcall adjust_edit_group1_attach(void *self, void *, void *arg0,
                                         int arg1, int arg2, int arg3);
void __fastcall adjust_edit_group3_on_redraw(void *self, void *);
