/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "caviar.h"
#include "sprite.h"
#include "texture.h"
#include "wave.h"

/*
 * Atexit teardown thunks
 *
 * One ??__F thunk per dynamically-initialized global: MSVC registers each with
 * atexit from the matching ??__E initializer, and its whole body is "tear down
 * the object at this fixed address". The pointers below are those objects,
 * carrying the original global names out of the thunks' mangled names; they
 * are rebindable data seams and stay unclassified. The Wave teardown is the
 * one target not yet source-owned, so it is reached through a classified
 * dependency instead of a direct call.
 */

#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"
#endif
typedef void(__thiscall func_wave_destructor)(Wave *wave);
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
extern func_wave_destructor *WaveOriginalDestructor;

extern Wave *g_ALPHAMENU_WAVE;
extern Sprite *g_UNUSED_SPRITE_VAR02;
extern Sprite *g_UNUSED_SPRITE_VAR11;
extern Sprite *g_UNUSED_SPRITE_VAR06;
extern Sprite *g_UNUSED_SPRITE_VAR09;
extern Sprite *g_UNUSED_SPRITE_VAR21;
extern Sprite *g_UNUSED_SPRITE_VAR05;
extern Sprite *g_UNUSED_SPRITE_VAR08;
extern Sprite *g_UNUSED_SPRITE_VAR04;
extern Sprite *g_UNUSED_SPRITE_VAR01;
extern Sprite *g_UNUSED_SPRITE_VAR18;
extern Sprite *g_UNUSED_SPRITE_VAR03;
extern Sprite *g_UNUSED_SPRITE_VAR20;
extern Sprite *g_UNUSED_SPRITE_VAR16;
extern Sprite *g_UNUSED_SPRITE_VAR14;
extern Sprite *g_UNUSED_SPRITE_VAR22;
extern Sprite *g_UNUSED_SPRITE_VAR10;
extern Sprite *g_UNUSED_SPRITE_VAR15;
extern Sprite *g_UNUSED_SPRITE_VAR13;
extern Sprite *g_UNUSED_SPRITE_VAR17;
extern Sprite *g_UNUSED_SPRITE_VAR19;
extern Sprite *g_UNUSED_SPRITE_VAR12;
extern Sprite *g_UNUSED_SPRITE_VAR07;
extern Wave *g_BASEWIN_WAVE;
extern Wave *g_CREDITS_WAVE;
extern Wave *g_DESIGNWIN_WAVE;
extern Wave *g_MENU_UP_WAVE;
extern Wave *g_MENU_DOWN_WAVE;
extern Wave *g_SCOOT_WAVE;
extern Wave *g_OK_WAVE;
extern Wave *g_PASSOVER_WAVE;
extern Sprite *g_IFACE_STD_POPUPS_TOP_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_TOP_RIGHT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_RIGHT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_TOP_MID_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_MID_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_MID_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_MID_RIGHT_SPRITE;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR1;
extern CaviarData *g_SSF_CAVIARDATA;
extern CaviarData *g_SDP_CAVIARDATA;
extern CaviarData *g_SAS_CAVIARDATA;
extern CaviarData *g_SCD_CAVIARDATA;
extern CaviarData *g_SCJ_CAVIARDATA;
extern CaviarData *g_SAGS_CAVIARDATA;
extern CaviarData *g_SFT_CAVIARDATA;
extern CaviarData *g_VHR_CAVIARDATA1;
extern CaviarData *g_SHT_CAVIARDATA;
extern CaviarData *g_SRB_CAVIARDATA;
extern CaviarData *g_ASAS_CAVIARDATA;
extern CaviarData *g_RESLASER_CAVIARDATA;
extern CaviarData *g_RESBOLT_CAVIARDATA;
extern CaviarData *g_FUNLOAD_CAVIARDATA;
extern CaviarData *g_TECLOAD_CAVIARDATA;
extern CaviarData *g_SP_DISSWAVE_CAVIARDATA;
extern CaviarData *g_SP_MARINED_CAVIARDATA;
extern CaviarData *g_SP_NANOO_CAVIARDATA;
extern CaviarData *g_SP_SOPORIFIC_CAVIARDATA;
extern CaviarData *g_AA01_CAVIARDATA;
extern CaviarData *g_AA_ROVER_CAVIARDATA;
extern CaviarData *g_AX_CAVIARDATA;
extern CaviarData *g_AA_CAVIARDATA;
extern CaviarData *g_ACOLPOD_CAVIARDATA;
extern CaviarData *g_AT_CAVIARDATA;
extern CaviarData *g_VTA_CAVIARDATA;
extern CaviarData *g_ATP_CAVIARDATA;
extern CaviarData *g_SSFA_CAVIARDATA;
extern CaviarData *g_SFTA_CAVIARDATA;
extern CaviarData *g_VW00_CAVIARDATA;
extern CaviarData *g_VIPTAWL_CAVIARDATA;
extern CaviarData *g_VIPTASGN_CAVIARDATA;
extern CaviarData *g_VIPTAPSI_CAVIARDATA;
extern CaviarData *g_PTMOD_CAVIARDATA;
extern CaviarData *g_VB_CAVIARDATA;
extern CaviarData *g_VBP_CAVIARDATA;
extern CaviarData *g_VGMC_CAVIARDATA;
extern CaviarData *g_VGMCP_CAVIARDATA;
extern CaviarData *g_VLIGHTS_CAVIARDATA;
extern CaviarData *g_VPT_CAVIARDATA;
extern CaviarData *g_A_CAVIARDATA;
extern CaviarData *g_APWALL_CAVIARDATA;
extern CaviarData *g_ASGEN_CAVIARDATA;
extern CaviarData *g_APSID_CAVIARDATA;
extern CaviarData *g_VA01_CAVIARDATA;
extern CaviarData *g_VHR_CAVIARDATA2;
extern CaviarData *g_VI_CAVIARDATA;
extern CaviarData *g_VGMT_CAVIARDATA;
extern CaviarData *g_VGMTP_CAVIARDATA;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR2;
extern CaviarData *g_VWNTU_CAVIARDATA;
extern CaviarData *g_VT_CAVIARDATA;
extern CaviarData *g_DROP_CAVIARDATA;
extern CaviarData *g_DROPLET_CAVIARDATA;
extern CaviarData *g_VCL_CAVIARDATA;
extern CaviarData *g_VCLT00_CAVIARDATA;
extern CaviarData *g_VHT_VBP_CAVIARDATA;
extern CaviarData *g_VHTP_CAVIARDATA;
extern CaviarData *g_VHTTP_CAVIARDATA;
extern CaviarData *g_VSP_CAVIARDATA;
extern CaviarData *g_VSPTF_CAVIARDATA;
extern CaviarData *g_VSPTB_CAVIARDATA;
extern CaviarData *g_VFL_CAVIARDATA;
extern CaviarData *g_VGS_CAVIARDATA;
extern CaviarData *g_VGSP_CAVIARDATA;
extern CaviarData *g_VJTP_CAVIARDATA;
extern CaviarData *g_VCU_CAVIARDATA;
extern CaviarData *g_VCUP_CAVIARDATA;
extern CaviarData *g_VCUW_CAVIARDATA;
extern CaviarData *g_VCT_CAVIARDATA;
extern CaviarData *g_VCTP_CAVIARDATA;
extern CaviarData *g_VCTB_CAVIARDATA;
extern CaviarData *g_VWNTT_CAVIARDATA;
extern CaviarData *g_VWNST_CAVIARDATA;
extern CaviarData *g_VWNAA_CAVIARDATA;
extern CaviarData *g_VM_CAVIARDATA;
extern CaviarData *g_VM13_CAVIARDATA;
extern CaviarData *g_NW_CAVIARDATA;
extern CaviarData *g_NI_CAVIARDATA;
extern CaviarData *g_NLC_CAVIARDATA;
extern Texture *g_RADIUS1_TEXTURE;
extern Texture *g_RADIUS2_TEXTURE;
extern Texture *g_FLAT_ARID_LAND_TEXTURE;
extern Texture *g_DUNE_LAND_TEXTURE;
extern Texture *g_RAINFALL_SINGLE_TILE_TEXTURE;
extern Sprite *g_TER1_MINE_SPRITE;
extern Sprite *g_TER1_SOLAR_COLLECTOR_SPRITE;
extern Sprite *g_TER1_TIDAL_HARNESS_SPRITE;
extern Sprite *g_TER1_MINING_PLATFORM_SPRITE;
extern Sprite *g_TER1_TUT_BLANK_SPRITE;
extern Sprite *g_TER1_KELP_FARM_SPRITE;
extern Sprite *g_TER1_CONDENSER_SPRITE;
extern Sprite *g_TER1_ECHELON_MIRROR_SPRITE;
extern Sprite *g_TER1_BOREHOLE_SPRITE;
extern Sprite *g_TER1_BOREHOLE_CLUSTER_SPRITE;
extern Sprite *g_TER1_MONOLITH_SPRITE;
extern Sprite *g_TER1_BUNKER_SPRITE;
extern Sprite *g_TER1_AIRBASE_SPRITE;
extern Sprite *g_TER1_SENSOR_ARRAY_SPRITE;
extern Sprite *g_RED_ALIEN_HEAD_ICON_SPRITE;
extern Sprite *g_RED_MALE_HEAD_ICON_SPRITE;
extern Sprite *g_NULL_RESOURCE_ICON_SPRITE;
extern Sprite *g_ICON_TILE_SQUARE_SPRITE;
extern Sprite *g_BATTLE_MIND_WORM_SPRITE;
extern Sprite *g_BATTLE_ISLE_DEEP_SPRITE;
extern Sprite *g_BATTLE_LOCUSTS_CHIRON_SPRITE;
extern Sprite *g_BATTLE_FUNGAL_TOWER_SPRITE;
extern Sprite *g_BATTLE_SPORE_LAUNCHER_SPRITE;
extern Sprite *g_BATTLE_SEALURK_SPRITE;
extern Sprite *g_SCROLL_BAR_FILLER_ICON_SPRITES;
extern Sprite *g_SCROLL_BAR_SMALL_FILLER_ICON_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_MID_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_MID_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_RIGHT_SPRITE;
extern Sprite *g_UNUSED_SPRITE_VAR23;
extern Sprite *g_UNUSED_SPRITE_VAR24;
extern Sprite *g_UNUSED_SPRITE_VAR25;
extern Sprite *g_UNUSED_SPRITE_VAR26;
extern Sprite *g_UNUSED_SPRITE_VAR27;
extern Sprite *g_UNUSED_SPRITE_VAR28;
extern Sprite *g_UNUSED_SPRITE_VAR29;
extern Sprite *g_UNUSED_SPRITE_VAR30;
extern Sprite *g_UNUSED_SPRITE_VAR31;
extern Sprite *g_UNUSED_SPRITE_VAR32;
extern Sprite *g_UNUSED_SPRITE_VAR33;
extern Sprite *g_UNUSED_SPRITE_VAR34;
extern Sprite *g_UNUSED_SPRITE_VAR35;
extern Sprite *g_UNUSED_SPRITE_VAR36;
extern Sprite *g_UNUSED_SPRITE_VAR37;
extern Sprite *g_UNUSED_SPRITE_VAR38;
extern Sprite *g_UNUSED_SPRITE_VAR39;
extern Sprite *g_UNUSED_SPRITE_VAR40;
extern Sprite *g_UNUSED_SPRITE_VAR41;
extern Sprite *g_UNUSED_SPRITE_VAR42;
extern Sprite *g_UNUSED_SPRITE_VAR43;
extern Sprite *g_UNUSED_SPRITE_VAR44;
extern Sprite *g_UNUSED_SPRITE_VAR45;
extern Sprite *g_UNUSED_SPRITE_VAR46;
extern Sprite *g_UNUSED_SPRITE_VAR47;
extern Sprite *g_UNUSED_SPRITE_VAR48;
extern Sprite *g_UNUSED_SPRITE_VAR49;
extern Sprite *g_UNUSED_SPRITE_VAR50;
extern Sprite *g_UNUSED_SPRITE_VAR51;
extern Sprite *g_UNUSED_SPRITE_VAR52;
extern Sprite *g_UNUSED_SPRITE_VAR53;
extern Sprite *g_UNUSED_SPRITE_VAR54;
extern Sprite *g_UNUSED_SPRITE_VAR55;
extern Sprite *g_UNUSED_SPRITE_VAR56;
extern Sprite *g_UNUSED_SPRITE_VAR57;
extern Sprite *g_UNUSED_SPRITE_VAR58;
extern Sprite *g_UNUSED_SPRITE_VAR59;
extern Sprite *g_UNUSED_SPRITE_VAR60;
extern Sprite *g_UNUSED_SPRITE_VAR61;
extern Sprite *g_UNUSED_SPRITE_VAR62;
extern Sprite *g_UNUSED_SPRITE_VAR63;
extern Sprite *g_UNUSED_SPRITE_VAR64;
extern Sprite *g_UNUSED_SPRITE_VAR65;
extern Sprite *g_UNUSED_SPRITE_VAR66;
extern Sprite *g_UNUSED_SPRITE_VAR67;
extern Sprite *g_UNUSED_SPRITE_VAR68;
extern Sprite *g_UNUSED_SPRITE_VAR69;
extern Sprite *g_UNUSED_SPRITE_VAR70;
extern Sprite *g_UNUSED_SPRITE_VAR71;
extern Sprite *g_UNUSED_SPRITE_VAR72;
extern Sprite *g_UNUSED_SPRITE_VAR73;
extern Sprite *g_UNUSED_SPRITE_VAR74;
extern Sprite *g_UNUSED_SPRITE_VAR75;
extern Sprite *g_UNUSED_SPRITE_VAR76;
extern Sprite *g_UNUSED_SPRITE_VAR77;
extern Sprite *g_UNUSED_SPRITE_VAR78;
extern Sprite *g_UNUSED_SPRITE_VAR79;
extern Sprite *g_UNUSED_SPRITE_VAR80;
extern Sprite *g_UNUSED_SPRITE_VAR81;
extern Sprite *g_UNUSED_SPRITE_VAR82;
extern Sprite *g_UNUSED_SPRITE_VAR83;
extern Wave *g_MAININTERFACE_WAVE;
extern Wave *g_MULTIWIN_WAVE;
extern Wave *g_TOP_MENU_WAVE;
extern Wave *g_CRASH_LANDING_WAVE;
extern Wave *g_WAVE_GENERAL;

DLLEXPORT void __cdecl destroy_alphamenu_wave();
DLLEXPORT void __cdecl destroy_unused_sprite_var02();
DLLEXPORT void __cdecl destroy_unused_sprite_var11();
DLLEXPORT void __cdecl destroy_unused_sprite_var06();
DLLEXPORT void __cdecl destroy_unused_sprite_var09();
DLLEXPORT void __cdecl destroy_unused_sprite_var21();
DLLEXPORT void __cdecl destroy_unused_sprite_var05();
DLLEXPORT void __cdecl destroy_unused_sprite_var08();
DLLEXPORT void __cdecl destroy_unused_sprite_var04();
DLLEXPORT void __cdecl destroy_unused_sprite_var01();
DLLEXPORT void __cdecl destroy_unused_sprite_var18();
DLLEXPORT void __cdecl destroy_unused_sprite_var03();
DLLEXPORT void __cdecl destroy_unused_sprite_var20();
DLLEXPORT void __cdecl destroy_unused_sprite_var16();
DLLEXPORT void __cdecl destroy_unused_sprite_var14();
DLLEXPORT void __cdecl destroy_unused_sprite_var22();
DLLEXPORT void __cdecl destroy_unused_sprite_var10();
DLLEXPORT void __cdecl destroy_unused_sprite_var15();
DLLEXPORT void __cdecl destroy_unused_sprite_var13();
DLLEXPORT void __cdecl destroy_unused_sprite_var17();
DLLEXPORT void __cdecl destroy_unused_sprite_var19();
DLLEXPORT void __cdecl destroy_unused_sprite_var12();
DLLEXPORT void __cdecl destroy_unused_sprite_var07();
DLLEXPORT void __cdecl destroy_basewin_wave();
DLLEXPORT void __cdecl destroy_credits_wave();
DLLEXPORT void __cdecl destroy_designwin_wave();
DLLEXPORT void __cdecl destroy_menu_up_wave();
DLLEXPORT void __cdecl destroy_menu_down_wave();
DLLEXPORT void __cdecl destroy_scoot_wave();
DLLEXPORT void __cdecl destroy_ok_wave();
DLLEXPORT void __cdecl destroy_passover_wave();
DLLEXPORT void __cdecl destroy_iface_std_popups_top_left_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_top_right_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_bot_left_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_bot_right_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_top_mid_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_bot_mid_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_mid_left_sprite();
DLLEXPORT void __cdecl destroy_iface_std_popups_mid_right_sprite();
DLLEXPORT void __cdecl destroy_unused_caviardata_var1();
DLLEXPORT void __cdecl destroy_ssf_caviardata();
DLLEXPORT void __cdecl destroy_sdp_caviardata();
DLLEXPORT void __cdecl destroy_sas_caviardata();
DLLEXPORT void __cdecl destroy_scd_caviardata();
DLLEXPORT void __cdecl destroy_scj_caviardata();
DLLEXPORT void __cdecl destroy_sags_caviardata();
DLLEXPORT void __cdecl destroy_sft_caviardata();
DLLEXPORT void __cdecl destroy_vhr_caviardata1();
DLLEXPORT void __cdecl destroy_sht_caviardata();
DLLEXPORT void __cdecl destroy_srb_caviardata();
DLLEXPORT void __cdecl destroy_asas_caviardata();
DLLEXPORT void __cdecl destroy_reslaser_caviardata();
DLLEXPORT void __cdecl destroy_resbolt_caviardata();
DLLEXPORT void __cdecl destroy_funload_caviardata();
DLLEXPORT void __cdecl destroy_tecload_caviardata();
DLLEXPORT void __cdecl destroy_sp_disswave_caviardata();
DLLEXPORT void __cdecl destroy_sp_marined_caviardata();
DLLEXPORT void __cdecl destroy_sp_nanoo_caviardata();
DLLEXPORT void __cdecl destroy_sp_soporific_caviardata();
DLLEXPORT void __cdecl destroy_aa01_caviardata();
DLLEXPORT void __cdecl destroy_aa_rover_caviardata();
DLLEXPORT void __cdecl destroy_ax_caviardata();
DLLEXPORT void __cdecl destroy_aa_caviardata();
DLLEXPORT void __cdecl destroy_acolpod_caviardata();
DLLEXPORT void __cdecl destroy_at_caviardata();
DLLEXPORT void __cdecl destroy_vta_caviardata();
DLLEXPORT void __cdecl destroy_atp_caviardata();
DLLEXPORT void __cdecl destroy_ssfa_caviardata();
DLLEXPORT void __cdecl destroy_sfta_caviardata();
DLLEXPORT void __cdecl destroy_vw00_caviardata();
DLLEXPORT void __cdecl destroy_viptawl_caviardata();
DLLEXPORT void __cdecl destroy_viptasgn_caviardata();
DLLEXPORT void __cdecl destroy_viptapsi_caviardata();
DLLEXPORT void __cdecl destroy_ptmod_caviardata();
DLLEXPORT void __cdecl destroy_vb_caviardata();
DLLEXPORT void __cdecl destroy_vbp_caviardata();
DLLEXPORT void __cdecl destroy_vgmc_caviardata();
DLLEXPORT void __cdecl destroy_vgmcp_caviardata();
DLLEXPORT void __cdecl destroy_vlights_caviardata();
DLLEXPORT void __cdecl destroy_vpt_caviardata();
DLLEXPORT void __cdecl destroy_a_caviardata();
DLLEXPORT void __cdecl destroy_apwall_caviardata();
DLLEXPORT void __cdecl destroy_asgen_caviardata();
DLLEXPORT void __cdecl destroy_apsid_caviardata();
DLLEXPORT void __cdecl destroy_va01_caviardata();
DLLEXPORT void __cdecl destroy_vhr_caviardata2();
DLLEXPORT void __cdecl destroy_vi_caviardata();
DLLEXPORT void __cdecl destroy_vgmt_caviardata();
DLLEXPORT void __cdecl destroy_vgmtp_caviardata();
DLLEXPORT void __cdecl destroy_unused_caviardata_var2();
DLLEXPORT void __cdecl destroy_vwntu_caviardata();
DLLEXPORT void __cdecl destroy_vt_caviardata();
DLLEXPORT void __cdecl destroy_drop_caviardata();
DLLEXPORT void __cdecl destroy_droplet_caviardata();
DLLEXPORT void __cdecl destroy_vcl_caviardata();
DLLEXPORT void __cdecl destroy_vclt00_caviardata();
DLLEXPORT void __cdecl destroy_vht_vbp_caviardata();
DLLEXPORT void __cdecl destroy_vhtp_caviardata();
DLLEXPORT void __cdecl destroy_vhttp_caviardata();
DLLEXPORT void __cdecl destroy_vsp_caviardata();
DLLEXPORT void __cdecl destroy_vsptf_caviardata();
DLLEXPORT void __cdecl destroy_vsptb_caviardata();
DLLEXPORT void __cdecl destroy_vfl_caviardata();
DLLEXPORT void __cdecl destroy_vgs_caviardata();
DLLEXPORT void __cdecl destroy_vgsp_caviardata();
DLLEXPORT void __cdecl destroy_vjtp_caviardata();
DLLEXPORT void __cdecl destroy_vcu_caviardata();
DLLEXPORT void __cdecl destroy_vcup_caviardata();
DLLEXPORT void __cdecl destroy_vcuw_caviardata();
DLLEXPORT void __cdecl destroy_vct_caviardata();
DLLEXPORT void __cdecl destroy_vctp_caviardata();
DLLEXPORT void __cdecl destroy_vctb_caviardata();
DLLEXPORT void __cdecl destroy_vwntt_caviardata();
DLLEXPORT void __cdecl destroy_vwnst_caviardata();
DLLEXPORT void __cdecl destroy_vwnaa_caviardata();
DLLEXPORT void __cdecl destroy_vm_caviardata();
DLLEXPORT void __cdecl destroy_vm13_caviardata();
DLLEXPORT void __cdecl destroy_nw_caviardata();
DLLEXPORT void __cdecl destroy_ni_caviardata();
DLLEXPORT void __cdecl destroy_nlc_caviardata();
DLLEXPORT void __cdecl destroy_radius1_texture();
DLLEXPORT void __cdecl destroy_radius2_texture();
DLLEXPORT void __cdecl destroy_flat_arid_land_texture();
DLLEXPORT void __cdecl destroy_dune_land_texture();
DLLEXPORT void __cdecl destroy_rainfall_single_tile_texture();
DLLEXPORT void __cdecl destroy_ter1_mine_sprite();
DLLEXPORT void __cdecl destroy_ter1_solar_collector_sprite();
DLLEXPORT void __cdecl destroy_ter1_tidal_harness_sprite();
DLLEXPORT void __cdecl destroy_ter1_mining_platform_sprite();
DLLEXPORT void __cdecl destroy_ter1_tut_blank_sprite();
DLLEXPORT void __cdecl destroy_ter1_kelp_farm_sprite();
DLLEXPORT void __cdecl destroy_ter1_condenser_sprite();
DLLEXPORT void __cdecl destroy_ter1_echelon_mirror_sprite();
DLLEXPORT void __cdecl destroy_ter1_borehole_sprite();
DLLEXPORT void __cdecl destroy_ter1_borehole_cluster_sprite();
DLLEXPORT void __cdecl destroy_ter1_monolith_sprite();
DLLEXPORT void __cdecl destroy_ter1_bunker_sprite();
DLLEXPORT void __cdecl destroy_ter1_airbase_sprite();
DLLEXPORT void __cdecl destroy_ter1_sensor_array_sprite();
DLLEXPORT void __cdecl destroy_red_alien_head_icon_sprite();
DLLEXPORT void __cdecl destroy_red_male_head_icon_sprite();
DLLEXPORT void __cdecl destroy_null_resource_icon_sprite();
DLLEXPORT void __cdecl destroy_icon_tile_square_sprite();
DLLEXPORT void __cdecl destroy_battle_mind_worm_sprite();
DLLEXPORT void __cdecl destroy_battle_isle_deep_sprite();
DLLEXPORT void __cdecl destroy_battle_locusts_chiron_sprite();
DLLEXPORT void __cdecl destroy_battle_fungal_tower_sprite();
DLLEXPORT void __cdecl destroy_battle_spore_launcher_sprite();
DLLEXPORT void __cdecl destroy_battle_sealurk_sprite();
DLLEXPORT void __cdecl destroy_scroll_bar_filler_icon_sprites();
DLLEXPORT void __cdecl destroy_scroll_bar_small_filler_icon_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_top_left_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_top_right_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_bot_left_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_bot_right_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_mid_left_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_mid_right_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_top_mid_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_bot_mid_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_noncap_mid_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_noncap_left_sprite();
DLLEXPORT void __cdecl destroy_iface_general_windows_noncap_right_sprite();
DLLEXPORT void __cdecl destroy_unused_sprite_var23();
DLLEXPORT void __cdecl destroy_unused_sprite_var24();
DLLEXPORT void __cdecl destroy_unused_sprite_var25();
DLLEXPORT void __cdecl destroy_unused_sprite_var26();
DLLEXPORT void __cdecl destroy_unused_sprite_var27();
DLLEXPORT void __cdecl destroy_unused_sprite_var28();
DLLEXPORT void __cdecl destroy_unused_sprite_var29();
DLLEXPORT void __cdecl destroy_unused_sprite_var30();
DLLEXPORT void __cdecl destroy_unused_sprite_var31();
DLLEXPORT void __cdecl destroy_unused_sprite_var32();
DLLEXPORT void __cdecl destroy_unused_sprite_var33();
DLLEXPORT void __cdecl destroy_unused_sprite_var34();
DLLEXPORT void __cdecl destroy_unused_sprite_var35();
DLLEXPORT void __cdecl destroy_unused_sprite_var36();
DLLEXPORT void __cdecl destroy_unused_sprite_var37();
DLLEXPORT void __cdecl destroy_unused_sprite_var38();
DLLEXPORT void __cdecl destroy_unused_sprite_var39();
DLLEXPORT void __cdecl destroy_unused_sprite_var40();
DLLEXPORT void __cdecl destroy_unused_sprite_var41();
DLLEXPORT void __cdecl destroy_unused_sprite_var42();
DLLEXPORT void __cdecl destroy_unused_sprite_var43();
DLLEXPORT void __cdecl destroy_unused_sprite_var44();
DLLEXPORT void __cdecl destroy_unused_sprite_var45();
DLLEXPORT void __cdecl destroy_unused_sprite_var46();
DLLEXPORT void __cdecl destroy_unused_sprite_var47();
DLLEXPORT void __cdecl destroy_unused_sprite_var48();
DLLEXPORT void __cdecl destroy_unused_sprite_var49();
DLLEXPORT void __cdecl destroy_unused_sprite_var50();
DLLEXPORT void __cdecl destroy_unused_sprite_var51();
DLLEXPORT void __cdecl destroy_unused_sprite_var52();
DLLEXPORT void __cdecl destroy_unused_sprite_var53();
DLLEXPORT void __cdecl destroy_unused_sprite_var54();
DLLEXPORT void __cdecl destroy_unused_sprite_var55();
DLLEXPORT void __cdecl destroy_unused_sprite_var56();
DLLEXPORT void __cdecl destroy_unused_sprite_var57();
DLLEXPORT void __cdecl destroy_unused_sprite_var58();
DLLEXPORT void __cdecl destroy_unused_sprite_var59();
DLLEXPORT void __cdecl destroy_unused_sprite_var60();
DLLEXPORT void __cdecl destroy_unused_sprite_var61();
DLLEXPORT void __cdecl destroy_unused_sprite_var62();
DLLEXPORT void __cdecl destroy_unused_sprite_var63();
DLLEXPORT void __cdecl destroy_unused_sprite_var64();
DLLEXPORT void __cdecl destroy_unused_sprite_var65();
DLLEXPORT void __cdecl destroy_unused_sprite_var66();
DLLEXPORT void __cdecl destroy_unused_sprite_var67();
DLLEXPORT void __cdecl destroy_unused_sprite_var68();
DLLEXPORT void __cdecl destroy_unused_sprite_var69();
DLLEXPORT void __cdecl destroy_unused_sprite_var70();
DLLEXPORT void __cdecl destroy_unused_sprite_var71();
DLLEXPORT void __cdecl destroy_unused_sprite_var72();
DLLEXPORT void __cdecl destroy_unused_sprite_var73();
DLLEXPORT void __cdecl destroy_unused_sprite_var74();
DLLEXPORT void __cdecl destroy_unused_sprite_var75();
DLLEXPORT void __cdecl destroy_unused_sprite_var76();
DLLEXPORT void __cdecl destroy_unused_sprite_var77();
DLLEXPORT void __cdecl destroy_unused_sprite_var78();
DLLEXPORT void __cdecl destroy_unused_sprite_var79();
DLLEXPORT void __cdecl destroy_unused_sprite_var80();
DLLEXPORT void __cdecl destroy_unused_sprite_var81();
DLLEXPORT void __cdecl destroy_unused_sprite_var82();
DLLEXPORT void __cdecl destroy_unused_sprite_var83();
DLLEXPORT void __cdecl destroy_maininterface_wave();
DLLEXPORT void __cdecl destroy_multiwin_wave();
DLLEXPORT void __cdecl destroy_top_menu_wave();
DLLEXPORT void __cdecl destroy_crash_landing_wave();
DLLEXPORT void __cdecl destroy_wave_general();
