/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

class Ambience;
class BattleWin;
class Buffer;
class ButtonGroup;
class CaviarData;
class FX;
struct FactionArt;
class Font;
class FontQueue;
class Sprite;
class TextIndex;
class Texture;
class Wave;

/*
 * Atexit teardown thunks
 *
 * One ??__F thunk per dynamically-initialized global: MSVC registers each with
 * atexit from the matching ??__E initializer, and its whole body is "tear down
 * the object at this fixed address". The pointers below are those objects,
 * carrying the original global names out of the thunks' mangled names; they
 * are rebindable data seams and stay unclassified. The Wave teardown is the
 * one target not yet source-owned, so it is reached through a classified
 * dependency instead of a direct call.
 */

typedef void (OriginalObject::*func_wave_destructor)();
extern func_wave_destructor WaveOriginalDestructor;

#include "vector_teardown.h"
extern func_thiscall_teardown BufferElementTeardown;
extern func_thiscall_teardown CaviarDataElementTeardown;
extern func_thiscall_teardown FactionArtElementTeardown;
extern func_thiscall_teardown FontElementTeardown;
extern func_thiscall_teardown SpriteElementTeardown;
extern func_thiscall_teardown TextIndexElementTeardown;
extern func_thiscall_teardown TextureElementTeardown;
extern func_thiscall_teardown WaveElementTeardown;

#include "deleting_thunks.h"

// Opaque-storage teardown seams. These globals' classes are not
// modelled in source, so the thunk hands the storage address
// straight to the original teardown through a seam rather than
// naming a type. Seams are deduped on the ADDRESS they default
// to: one already bound at the same address elsewhere is reused
// from the header above, never redefined here.
extern func_thiscall_teardown InfoWinDtorTarget;   // 0x004594A0
extern func_thiscall_teardown MessageWinDtorTarget;   // 0x00472020
extern func_thiscall_teardown ReportIfDtorTarget;   // 0x004ACDA0
extern func_thiscall_teardown StatusWinDtorTarget;   // 0x004BA120
extern func_thiscall_teardown Wave_DeviceDtorTarget;   // 0x004C4E60
extern func_thiscall_teardown Midi_DeviceDtorTarget;   // 0x004C5780
extern func_thiscall_teardown Wave_In_DeviceDtorTarget;   // 0x004C5980
extern func_thiscall_teardown NetDaemonDtorTarget;   // 0x00538D10
extern func_thiscall_teardown PaletteDtorTarget;   // 0x005FE2E0
extern func_thiscall_teardown TimeDtorTarget;   // 0x00616200
extern func_thiscall_teardown StringsDtorTarget;   // 0x006169C0
extern func_thiscall_teardown CaviarCloseTarget;   // 0x00617020

extern Wave *g_ALPHAMENU_WAVE;
extern Sprite *g_UNUSED_SPRITE_VAR02;
extern Sprite *g_UNUSED_SPRITE_VAR11;
extern Sprite *g_UNUSED_SPRITE_VAR06;
extern Sprite *g_UNUSED_SPRITE_VAR09;
extern Sprite *g_UNUSED_SPRITE_VAR21;
extern Sprite *g_UNUSED_SPRITE_VAR05;
extern Sprite *g_UNUSED_SPRITE_VAR08;
extern Sprite *g_UNUSED_SPRITE_VAR04;
extern Sprite *g_UNUSED_SPRITE_VAR01;
extern Sprite *g_UNUSED_SPRITE_VAR18;
extern Sprite *g_UNUSED_SPRITE_VAR03;
extern Sprite *g_UNUSED_SPRITE_VAR20;
extern Sprite *g_UNUSED_SPRITE_VAR16;
extern Sprite *g_UNUSED_SPRITE_VAR14;
extern Sprite *g_UNUSED_SPRITE_VAR22;
extern Sprite *g_UNUSED_SPRITE_VAR10;
extern Sprite *g_UNUSED_SPRITE_VAR15;
extern Sprite *g_UNUSED_SPRITE_VAR13;
extern Sprite *g_UNUSED_SPRITE_VAR17;
extern Sprite *g_UNUSED_SPRITE_VAR19;
extern Sprite *g_UNUSED_SPRITE_VAR12;
extern Sprite *g_UNUSED_SPRITE_VAR07;
extern Wave *g_BASEWIN_WAVE;
extern BattleWin *g_BattleWin;
extern Wave *g_CREDITS_WAVE;
extern Wave *g_DESIGNWIN_WAVE;
extern Wave *g_CPU_WAVES;
extern Wave *g_MENU_UP_WAVE;
extern Wave *g_MENU_DOWN_WAVE;
extern Wave *g_SCOOT_WAVE;
extern Wave *g_OK_WAVE;
extern Wave *g_PASSOVER_WAVE;
extern FX *g_FX;
extern Ambience *g_AMBIENCE;
extern Buffer *g_PCX_PARSE_TEMP_BUFFER1;
extern FactionArt *FactionArtGlobal;
extern Sprite *g_IFACE_CLOSE_X_SPRITES;
extern Sprite *g_IFACE_BOX_SPRITES1;
extern Sprite *g_IFACE_BOX_SPRITES2;
extern Sprite *g_IFACE_BOX_SPRITES3;
extern Sprite *g_IFACE_BOX_SPRITES4;
extern Sprite *g_IFACE_BOX_SPRITES5;
extern Sprite *g_IFACE_BOX_SPRITES6;
extern Sprite *g_IFACE_BOX_SPRITES7;
extern Sprite *g_IFACE_BOX_SPRITES8;
extern Buffer *g_IFACE_BOX_SPRITE_BUFFERS;
extern Sprite *g_IFACE_STD_POPUPS_TOP_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_TOP_RIGHT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_RIGHT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_TOP_MID_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_BOT_MID_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_MID_LEFT_SPRITE;
extern Sprite *g_IFACE_STD_POPUPS_MID_RIGHT_SPRITE;
extern Buffer *g_IFACE_STD_POPUPS_MIDDLE_BUFFER;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR1;
extern CaviarData *g_SSF_CAVIARDATA;
extern CaviarData *g_SDP_CAVIARDATA;
extern CaviarData *g_SAS_CAVIARDATA;
extern CaviarData *g_SCD_CAVIARDATA;
extern CaviarData *g_SCJ_CAVIARDATA;
extern CaviarData *g_SAGS_CAVIARDATA;
extern CaviarData *g_SFT_CAVIARDATA;
extern CaviarData *g_VHR_CAVIARDATA1;
extern CaviarData *g_SHT_CAVIARDATA;
extern CaviarData *g_SRB_CAVIARDATA;
extern CaviarData *g_ASAS_CAVIARDATA;
extern CaviarData *g_RESLASER_CAVIARDATA;
extern CaviarData *g_RESBOLT_CAVIARDATA;
extern CaviarData *g_FUNLOAD_CAVIARDATA;
extern CaviarData *g_TECLOAD_CAVIARDATA;
extern CaviarData *g_SP_DISSWAVE_CAVIARDATA;
extern CaviarData *g_SP_MARINED_CAVIARDATA;
extern CaviarData *g_SP_NANOO_CAVIARDATA;
extern CaviarData *g_SP_SOPORIFIC_CAVIARDATA;
extern CaviarData *g_AA01_CAVIARDATA;
extern CaviarData *g_AA_ROVER_CAVIARDATA;
extern CaviarData *g_AA_WING_CAVIARDATA;
extern CaviarData *g_ACP_CAVIARDATA;
extern CaviarData *g_AX_CAVIARDATA;
extern CaviarData *g_AA_CAVIARDATA;
extern CaviarData *g_ACOLPOD_CAVIARDATA;
extern CaviarData *g_AT_CAVIARDATA;
extern CaviarData *g_VTA_CAVIARDATA;
extern CaviarData *g_ATP_CAVIARDATA;
extern CaviarData *g_SSFA_CAVIARDATA;
extern CaviarData *g_SFTA_CAVIARDATA;
extern CaviarData *g_VW00_CAVIARDATA;
extern CaviarData *g_VIPTAWL_CAVIARDATA;
extern CaviarData *g_VIPTASGN_CAVIARDATA;
extern CaviarData *g_VIPTAPSI_CAVIARDATA;
extern CaviarData *g_VIPTR_CAVIARDATA;
extern CaviarData *g_VIPTA_CAVIARDATA;
extern CaviarData *g_PTMOD_CAVIARDATA;
extern CaviarData *g_VB_CAVIARDATA;
extern CaviarData *g_VBP_CAVIARDATA;
extern CaviarData *g_VGMC_CAVIARDATA;
extern CaviarData *g_VGMCP_CAVIARDATA;
extern CaviarData *g_VLIGHTS_CAVIARDATA;
extern CaviarData *g_VPT_CAVIARDATA;
extern CaviarData *g_A_CAVIARDATA;
extern CaviarData *g_APWALL_CAVIARDATA;
extern CaviarData *g_ASGEN_CAVIARDATA;
extern CaviarData *g_APSID_CAVIARDATA;
extern CaviarData *g_VA01_CAVIARDATA;
extern CaviarData *g_VR_CAVIARDATA;
extern CaviarData *g_VHR_CAVIARDATA2;
extern CaviarData *g_VRC_CAVIARDATA;
extern CaviarData *g_VI_CAVIARDATA;
extern CaviarData *g_VGMT_CAVIARDATA;
extern CaviarData *g_VGMTP_CAVIARDATA;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR2;
extern CaviarData *g_VWNTU_CAVIARDATA;
extern CaviarData *g_VT_CAVIARDATA;
extern CaviarData *g_DROP_CAVIARDATA;
extern CaviarData *g_DROPLET_CAVIARDATA;
extern CaviarData *g_VCL_CAVIARDATA;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR3;
extern CaviarData *g_VCLT00_CAVIARDATA;
extern CaviarData *g_VHT_VBP_CAVIARDATA;
extern CaviarData *g_VHTP_CAVIARDATA;
extern CaviarData *g_VHTA0_CAVIARDATA;
extern CaviarData *g_VHTTP_CAVIARDATA;
extern CaviarData *g_VHTTPA0_CAVIARDATA;
extern CaviarData *g_VSP_CAVIARDATA;
extern CaviarData *g_VSPA0_CAVIARDATA;
extern CaviarData *g_VSPTF_CAVIARDATA;
extern CaviarData *g_VSPTB_CAVIARDATA;
extern CaviarData *g_VFL_CAVIARDATA;
extern CaviarData *g_VGS_CAVIARDATA;
extern CaviarData *g_VGSP_CAVIARDATA;
extern CaviarData *g_VJTP_CAVIARDATA;
extern CaviarData *g_VJT0_CAVIARDATA;
extern CaviarData *g_VCU_CAVIARDATA;
extern CaviarData *g_VCUP_CAVIARDATA;
extern CaviarData *g_VCUA0_CAVIARDATA;
extern CaviarData *g_VCUW_CAVIARDATA;
extern CaviarData *g_VCT_CAVIARDATA;
extern CaviarData *g_VCTP_CAVIARDATA;
extern CaviarData *g_VCTB_CAVIARDATA;
extern CaviarData *g_VCT0_CAVIARDATA;
extern CaviarData *g_VWNTT_CAVIARDATA;
extern CaviarData *g_VWNST_CAVIARDATA;
extern CaviarData *g_VWNAA_CAVIARDATA;
extern CaviarData *g_VW_CAVIARDATA;
extern CaviarData *g_VM_CAVIARDATA;
extern CaviarData *g_VM13_CAVIARDATA;
extern CaviarData *g_VPBR0_CAVIARDATA;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR4;
extern CaviarData *g_NW_CAVIARDATA;
extern CaviarData *g_NI_CAVIARDATA;
extern CaviarData *g_NLC_CAVIARDATA;
extern CaviarData *g_UNUSED_CAVIARDATA_VAR5;
extern Texture *g_RADIUS1_TEXTURE;
extern Texture *g_RADIUS2_TEXTURE;
extern Texture *g_ROCKY_TEXTURES;
extern Texture *g_OCEAN_TEXTURES;
extern Texture *g_FLAT_ARID_LAND_TEXTURE;
extern Texture *g_MOIST_LAND_TEXTURES;
extern Texture *g_RAINY_LAND_TEXTURES;
extern Texture *g_JUNGLE_LAND_TEXTURES;
extern Texture *g_DUNE_LAND_TEXTURE;
extern Texture *g_SUNNY_MESA_TEXTURES;
extern Texture *g_RAINFALL_SINGLE_TILE_TEXTURES;
extern Texture *g_ROAD_TEXTURES;
extern Texture *g_MAGTUBE_TEXTURES;
extern Texture *g_RIVER_TEXTURES;
extern Texture *g_MOUNT_PLANET_TEXTURES;
extern Texture *g_GARLAND_CRATER_TEXTURES;
extern Texture *g_FUNGUS_TEXTURES;
extern Texture *g_FARM_TEXTURES;
extern Texture *g_FOREST_TEXTURES;
extern Texture *g_RAINFALL_SINGLE_TILE_TEXTURE;
extern Sprite *g_TER1_WHITE_ORG_YEL_TILE_SPRITES;
extern Sprite *g_TER1_BOTTOM_LEFT_TILE_SPRITES;
extern Sprite *g_TER1_UNUSED_SPRITES2;
extern Sprite *g_TER1_MINE_SPRITE;
extern Sprite *g_TER1_SOLAR_COLLECTOR_SPRITE;
extern Sprite *g_TER1_TIDAL_HARNESS_SPRITE;
extern Sprite *g_TER1_MINING_PLATFORM_SPRITE;
extern Sprite *g_TER1_TUT_BLANK_SPRITE;
extern Sprite *g_TER1_KELP_FARM_SPRITE;
extern Sprite *g_TER1_CONDENSER_SPRITE;
extern Sprite *g_TER1_ECHELON_MIRROR_SPRITE;
extern Sprite *g_TER1_BOREHOLE_SPRITE;
extern Sprite *g_TER1_BOREHOLE_CLUSTER_SPRITE;
extern Sprite *g_TER1_MANIFOLD_NEXUS_SPRITES;
extern Sprite *g_TER1WRECK_UNITY_WRECKAGE_SPRITES;
extern Sprite *g_TER1WRECK_UNITY_WRECKAGE_ALT_SPRITES;
extern Sprite *g_FOSSIL_FIELD_RIDGE_SPRITES;
extern Sprite *g_TER1_UNUSED_SPRITES1;
extern Sprite *g_TER1_FARM_SPRITES;
extern Sprite *g_TER1_SOIL_ENRICHER_SPRITES;
extern Sprite *g_TER1_SEA_LAND_RESOURCE_SPRITES;
extern Sprite *g_TER1_LANDMARK_RESOURCE_SPRITES;
extern Sprite *g_GLOW_SPRITES;
extern Sprite *g_TER1_UNITY_POD_SPRITES;
extern Sprite *g_TER1_MONOLITH_SPRITE;
extern Sprite *g_TER1_BUNKER_SPRITE;
extern Sprite *g_TER1_AIRBASE_SPRITE;
extern Sprite *g_TER1_SENSOR_ARRAY_SPRITE;
extern Sprite *g_RAINFALL_DOUBLE_TILE_SPRITES;
extern Sprite *g_VEH_SPRITES;
extern Sprite *g_FLAGS_VEH_SPRITES;
extern Sprite *g_ICONS_GENERAL_SPRITES;
extern Sprite *g_RESOURCE_ICON_SPRITES;
extern Sprite *g_CITIZEN_LG_CURSOR_SPRITES;
extern Sprite *g_SPECIALIST_LG_CURSOR_SPRITES;
extern Sprite *g_CITIZEN_SM_CURSOR_SPRITES;
extern Sprite *g_SPECIALIST_SM_CURSOR_SPRITES;
extern Sprite *g_AL_CITIZEN_LG_CURSOR_SPRITES;
extern Sprite *g_AL_SPECIALIST_LG_CURSOR_SPRITES;
extern Sprite *g_AL_CITIZEN_SM_CURSOR_SPRITES;
extern Sprite *g_AL_SPECIALIST_SM_CURSOR_SPRITES;
extern Sprite *g_RED_ALIEN_HEAD_ICON_SPRITE;
extern Sprite *g_SILVER_MENU_ICON_SPRITES;
extern Sprite *g_SILVER_CHECKBOX_ICON_SPRITES;
extern Sprite *g_RED_MALE_HEAD_ICON_SPRITE;
extern Sprite *g_NULL_RESOURCE_ICON_SPRITE;
extern Sprite *g_PEACE_SIGN_SPRITES;
extern Sprite *g_ICON_TILE_SQUARE_SPRITE;
extern Sprite *g_XI_BOOM_VEH_SPRITES;
extern Sprite *g_XF_BOOM_VEH_SPRITES;
extern Sprite *g_BATTLE_MIND_WORM_SPRITE;
extern Sprite *g_BATTLE_ISLE_DEEP_SPRITE;
extern Sprite *g_BATTLE_LOCUSTS_CHIRON_SPRITE;
extern Sprite *g_BATTLE_FUNGAL_TOWER_SPRITE;
extern Sprite *g_BATTLE_SPORE_LAUNCHER_SPRITE;
extern Sprite *g_BATTLE_SEALURK_SPRITE;
extern Sprite *g_TECH_ICON_SPRITES;
extern Sprite *g_FACILITY_ICON_SPRITES;
extern Sprite *g_SECRET_PROJECT_ICON_SPRITES;
extern Sprite *g_IFACE_MP_COMBO_ARROW_SPRITES;
extern Sprite *g_SCROLL_BAR_ARROW_ICON_SPRITES;
extern Sprite *g_SCROLL_BAR_SMALL_ARROW_ICON_SPRITES;
extern Sprite *g_SCROLL_BAR_FILLER_ICON_SPRITES;
extern Sprite *g_SCROLL_BAR_SMALL_FILLER_ICON_SPRITE;
extern Sprite *g_IFACE_LOCK_SPRITES;
extern Sprite *g_UNUSED_SPRITES_VAR01;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_MID_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_MID_RIGHT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_TOP_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_BOT_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_MID_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_LEFT_SPRITE;
extern Sprite *g_IFACE_GENERAL_WINDOWS_NONCAP_RIGHT_SPRITE;
extern Sprite *g_UNUSED_SPRITE_VAR23;
extern Sprite *g_UNUSED_SPRITE_VAR24;
extern Sprite *g_UNUSED_SPRITE_VAR25;
extern Sprite *g_UNUSED_SPRITE_VAR26;
extern Sprite *g_UNUSED_SPRITE_VAR27;
extern Sprite *g_UNUSED_SPRITE_VAR28;
extern Sprite *g_UNUSED_SPRITE_VAR29;
extern Sprite *g_UNUSED_SPRITE_VAR30;
extern Sprite *g_UNUSED_SPRITE_VAR31;
extern Sprite *g_UNUSED_SPRITE_VAR32;
extern Sprite *g_UNUSED_SPRITE_VAR33;
extern Sprite *g_UNUSED_SPRITE_VAR34;
extern Sprite *g_UNUSED_SPRITE_VAR35;
extern Sprite *g_UNUSED_SPRITE_VAR36;
extern Sprite *g_UNUSED_SPRITE_VAR37;
extern Sprite *g_UNUSED_SPRITE_VAR38;
extern Sprite *g_UNUSED_SPRITE_VAR39;
extern Sprite *g_UNUSED_SPRITE_VAR40;
extern Sprite *g_UNUSED_SPRITE_VAR41;
extern Sprite *g_UNUSED_SPRITE_VAR42;
extern Sprite *g_UNUSED_SPRITE_VAR43;
extern Sprite *g_UNUSED_SPRITE_VAR44;
extern Sprite *g_UNUSED_SPRITE_VAR45;
extern Sprite *g_UNUSED_SPRITE_VAR46;
extern Sprite *g_IFACE_TECH_TREE_ARROW_SPRITES;
extern Sprite *g_UNUSED_SPRITE_VAR47;
extern Sprite *g_UNUSED_SPRITE_VAR48;
extern Sprite *g_UNUSED_SPRITE_VAR49;
extern Sprite *g_UNUSED_SPRITE_VAR50;
extern Sprite *g_UNUSED_SPRITE_VAR51;
extern Sprite *g_UNUSED_SPRITE_VAR52;
extern Sprite *g_UNUSED_SPRITE_VAR53;
extern Sprite *g_UNUSED_SPRITE_VAR54;
extern Sprite *g_UNUSED_SPRITE_VAR55;
extern Sprite *g_UNUSED_SPRITE_VAR56;
extern Sprite *g_UNUSED_SPRITE_VAR57;
extern Sprite *g_UNUSED_SPRITE_VAR58;
extern Sprite *g_UNUSED_SPRITE_VAR59;
extern Sprite *g_UNUSED_SPRITE_VAR60;
extern Sprite *g_UNUSED_SPRITE_VAR61;
extern Sprite *g_UNUSED_SPRITE_VAR62;
extern Sprite *g_UNUSED_SPRITE_VAR63;
extern Sprite *g_UNUSED_SPRITE_VAR64;
extern Sprite *g_UNUSED_SPRITE_VAR65;
extern Sprite *g_UNUSED_SPRITE_VAR66;
extern Sprite *g_UNUSED_SPRITE_VAR67;
extern Sprite *g_UNUSED_SPRITE_VAR68;
extern Sprite *g_UNUSED_SPRITE_VAR69;
extern Sprite *g_UNUSED_SPRITE_VAR70;
extern Sprite *g_UNUSED_SPRITE_VAR71;
extern Sprite *g_UNUSED_SPRITE_VAR72;
extern Sprite *g_UNUSED_SPRITE_VAR73;
extern Sprite *g_UNUSED_SPRITE_VAR74;
extern Sprite *g_UNUSED_SPRITES_VAR02;
extern Sprite *g_UNUSED_SPRITES_VAR03;
extern Sprite *g_UNUSED_SPRITES_VAR04;
extern Sprite *g_UNUSED_SPRITES_VAR05;
extern Sprite *g_UNUSED_SPRITES_VAR06;
extern Sprite *g_UNUSED_SPRITES_VAR07;
extern Sprite *g_UNUSED_SPRITES_VAR08;
extern Sprite *g_UNUSED_SPRITES_VAR09;
extern Sprite *g_UNUSED_SPRITES_VAR10;
extern Sprite *g_UNUSED_SPRITE_VAR75;
extern Sprite *g_UNUSED_SPRITE_VAR76;
extern Sprite *g_UNUSED_SPRITE_VAR77;
extern Sprite *g_UNUSED_SPRITE_VAR78;
extern Sprite *g_UNUSED_SPRITE_VAR79;
extern Sprite *g_UNUSED_SPRITE_VAR80;
extern Sprite *g_UNUSED_SPRITE_VAR81;
extern Sprite *g_UNUSED_SPRITE_VAR82;
extern Sprite *g_UNUSED_SPRITE_VAR83;
extern Sprite *g_BASEWIN_SPRITES;
extern Wave *g_MAININTERFACE_WAVE;
/*
 * AN OBJECT, WHERE EVERY OTHER LINE HERE HOLDS A POINTER. Both forms name the
 * same storage while this tree is injected into the shipped image, and while
 * that was the only way to run it the pointer form cost nothing. It is not
 * free any more: the artifact is now an executable of its own with the
 * recovered `WinMain` as its entry point (src/main.cpp), and `(Font *)
 * 0x007D3948` in a program that is not the shipped image is a pointer into
 * nothing. The first call WinMain makes through this global would fault.
 *
 * It also compiles differently, which is the half a byte match can see.
 * `g_JACKAL_FONT.init(...)` on an object is `mov ecx, OFFSET g_JACKAL_FONT` -
 * the `mov ecx, 0x7d3948` at 0x0045FAF6. Through a pointer variable the same
 * source is `mov ecx, dword ptr [g_JACKAL_FONT]`, a load the image never
 * performs.
 *
 * The other ~400 globals below have the same latent fault and are left as
 * they are until the entry point reaches them; this one is on WinMain's path
 * today. `g_PALETTE1` in palette.h is the same conversion.
 */
extern Font g_JACKAL_FONT;
extern Sprite *g_IFACE_GREEN_RIGHT_ARROW_SPRITE;
extern Wave *g_MULTIWIN_WAVE;
extern ButtonGroup *g_PREFWIN_BUTTONGROUP;
extern Buffer *g_VEHDRAW_BUFFER;
extern Sprite *g_CURSOR_SPRITES;
extern FontQueue *g_FONTQUEUE_VAL2;
extern FontQueue *g_FONTQUEUE_VAL1;
extern Wave *g_TOP_MENU_WAVE;
extern Font *g_FONTS;
extern Wave *g_CRASH_LANDING_WAVE;
extern Wave *g_WAVE_GENERAL;
extern Buffer *g_BUFFER;
extern TextIndex *TxtIndexGlobal;

void __cdecl destroy_alphamenu_wave();
void __cdecl destroy_unused_sprite_var02();
void __cdecl destroy_unused_sprite_var11();
void __cdecl destroy_unused_sprite_var06();
void __cdecl destroy_unused_sprite_var09();
void __cdecl destroy_unused_sprite_var21();
void __cdecl destroy_unused_sprite_var05();
void __cdecl destroy_unused_sprite_var08();
void __cdecl destroy_unused_sprite_var04();
void __cdecl destroy_unused_sprite_var01();
void __cdecl destroy_unused_sprite_var18();
void __cdecl destroy_unused_sprite_var03();
void __cdecl destroy_unused_sprite_var20();
void __cdecl destroy_unused_sprite_var16();
void __cdecl destroy_unused_sprite_var14();
void __cdecl destroy_unused_sprite_var22();
void __cdecl destroy_unused_sprite_var10();
void __cdecl destroy_unused_sprite_var15();
void __cdecl destroy_unused_sprite_var13();
void __cdecl destroy_unused_sprite_var17();
void __cdecl destroy_unused_sprite_var19();
void __cdecl destroy_unused_sprite_var12();
void __cdecl destroy_unused_sprite_var07();
void __cdecl destroy_basewin();
void __cdecl destroy_basewin_wave();
void __cdecl destroy_battlewin();
void __cdecl destroy_councwin();
void __cdecl destroy_credits_wave();
void __cdecl destroy_datalink();
void __cdecl destroy_designwin();
void __cdecl destroy_designwin_wave();
void __cdecl destroy_diplopop();
void __cdecl destroy_diplowin();
void __cdecl destroy_cpu_waves();
void __cdecl destroy_menu_up_wave();
void __cdecl destroy_menu_down_wave();
void __cdecl destroy_scoot_wave();
void __cdecl destroy_ok_wave();
void __cdecl destroy_passover_wave();
void __cdecl destroy_fx();
void __cdecl destroy_ambience();
void __cdecl destroy_famewin();
void __cdecl destroy_pcx_parse_temp_buffer1();
void __cdecl destroy_factionart();
void __cdecl destroy_iface_close_x_sprites();
void __cdecl destroy_iface_box_sprites1();
void __cdecl destroy_iface_box_sprites2();
void __cdecl destroy_iface_box_sprites3();
void __cdecl destroy_iface_box_sprites4();
void __cdecl destroy_iface_box_sprites5();
void __cdecl destroy_iface_box_sprites6();
void __cdecl destroy_iface_box_sprites7();
void __cdecl destroy_iface_box_sprites8();
void __cdecl destroy_iface_box_sprite_buffers();
void __cdecl destroy_iface_std_popups_top_left_sprite();
void __cdecl destroy_iface_std_popups_top_right_sprite();
void __cdecl destroy_iface_std_popups_bot_left_sprite();
void __cdecl destroy_iface_std_popups_bot_right_sprite();
void __cdecl destroy_iface_std_popups_top_mid_sprite();
void __cdecl destroy_iface_std_popups_bot_mid_sprite();
void __cdecl destroy_iface_std_popups_mid_left_sprite();
void __cdecl destroy_iface_std_popups_mid_right_sprite();
void __cdecl destroy_iface_std_popups_middle_buffer();
void __cdecl destroy_unused_caviardata_var1();
void __cdecl destroy_ssf_caviardata();
void __cdecl destroy_sdp_caviardata();
void __cdecl destroy_sas_caviardata();
void __cdecl destroy_scd_caviardata();
void __cdecl destroy_scj_caviardata();
void __cdecl destroy_sags_caviardata();
void __cdecl destroy_sft_caviardata();
void __cdecl destroy_vhr_caviardata1();
void __cdecl destroy_sht_caviardata();
void __cdecl destroy_srb_caviardata();
void __cdecl destroy_asas_caviardata();
void __cdecl destroy_reslaser_caviardata();
void __cdecl destroy_resbolt_caviardata();
void __cdecl destroy_funload_caviardata();
void __cdecl destroy_tecload_caviardata();
void __cdecl destroy_sp_disswave_caviardata();
void __cdecl destroy_sp_marined_caviardata();
void __cdecl destroy_sp_nanoo_caviardata();
void __cdecl destroy_sp_soporific_caviardata();
void __cdecl destroy_aa01_caviardata();
void __cdecl destroy_aa_rover_caviardata();
void __cdecl destroy_aa_wing_caviardata();
void __cdecl destroy_acp_caviardata();
void __cdecl destroy_ax_caviardata();
void __cdecl destroy_aa_caviardata();
void __cdecl destroy_acolpod_caviardata();
void __cdecl destroy_at_caviardata();
void __cdecl destroy_vta_caviardata();
void __cdecl destroy_atp_caviardata();
void __cdecl destroy_ssfa_caviardata();
void __cdecl destroy_sfta_caviardata();
void __cdecl destroy_vw00_caviardata();
void __cdecl destroy_viptawl_caviardata();
void __cdecl destroy_viptasgn_caviardata();
void __cdecl destroy_viptapsi_caviardata();
void __cdecl destroy_viptr_caviardata();
void __cdecl destroy_vipta_caviardata();
void __cdecl destroy_ptmod_caviardata();
void __cdecl destroy_vb_caviardata();
void __cdecl destroy_vbp_caviardata();
void __cdecl destroy_vgmc_caviardata();
void __cdecl destroy_vgmcp_caviardata();
void __cdecl destroy_vlights_caviardata();
void __cdecl destroy_vpt_caviardata();
void __cdecl destroy_a_caviardata();
void __cdecl destroy_apwall_caviardata();
void __cdecl destroy_asgen_caviardata();
void __cdecl destroy_apsid_caviardata();
void __cdecl destroy_va01_caviardata();
void __cdecl destroy_vr_caviardata();
void __cdecl destroy_vhr_caviardata2();
void __cdecl destroy_vrc_caviardata();
void __cdecl destroy_vi_caviardata();
void __cdecl destroy_vgmt_caviardata();
void __cdecl destroy_vgmtp_caviardata();
void __cdecl destroy_unused_caviardata_var2();
void __cdecl destroy_vwntu_caviardata();
void __cdecl destroy_vt_caviardata();
void __cdecl destroy_drop_caviardata();
void __cdecl destroy_droplet_caviardata();
void __cdecl destroy_vcl_caviardata();
void __cdecl destroy_unused_caviardata_var3();
void __cdecl destroy_vclt00_caviardata();
void __cdecl destroy_vht_vbp_caviardata();
void __cdecl destroy_vhtp_caviardata();
void __cdecl destroy_vhta0_caviardata();
void __cdecl destroy_vhttp_caviardata();
void __cdecl destroy_vhttpa0_caviardata();
void __cdecl destroy_vsp_caviardata();
void __cdecl destroy_vspa0_caviardata();
void __cdecl destroy_vsptf_caviardata();
void __cdecl destroy_vsptb_caviardata();
void __cdecl destroy_vfl_caviardata();
void __cdecl destroy_vgs_caviardata();
void __cdecl destroy_vgsp_caviardata();
void __cdecl destroy_vjtp_caviardata();
void __cdecl destroy_vjt0_caviardata();
void __cdecl destroy_vcu_caviardata();
void __cdecl destroy_vcup_caviardata();
void __cdecl destroy_vcua0_caviardata();
void __cdecl destroy_vcuw_caviardata();
void __cdecl destroy_vct_caviardata();
void __cdecl destroy_vctp_caviardata();
void __cdecl destroy_vctb_caviardata();
void __cdecl destroy_vct0_caviardata();
void __cdecl destroy_vwntt_caviardata();
void __cdecl destroy_vwnst_caviardata();
void __cdecl destroy_vwnaa_caviardata();
void __cdecl destroy_vw_caviardata();
void __cdecl destroy_vm_caviardata();
void __cdecl destroy_vm13_caviardata();
void __cdecl destroy_vpbr0_caviardata();
void __cdecl destroy_unused_caviardata_var4();
void __cdecl destroy_nw_caviardata();
void __cdecl destroy_ni_caviardata();
void __cdecl destroy_nlc_caviardata();
void __cdecl destroy_unused_caviardata_var5();
void __cdecl destroy_radius1_texture();
void __cdecl destroy_radius2_texture();
void __cdecl destroy_rocky_textures();
void __cdecl destroy_ocean_textures();
void __cdecl destroy_flat_arid_land_texture();
void __cdecl destroy_moist_land_textures();
void __cdecl destroy_rainy_land_textures();
void __cdecl destroy_jungle_land_textures();
void __cdecl destroy_dune_land_texture();
void __cdecl destroy_sunny_mesa_textures();
void __cdecl destroy_rainfall_single_tile_textures();
void __cdecl destroy_road_textures();
void __cdecl destroy_magtube_textures();
void __cdecl destroy_river_textures();
void __cdecl destroy_mount_planet_textures();
void __cdecl destroy_garland_crater_textures();
void __cdecl destroy_fungus_textures();
void __cdecl destroy_farm_textures();
void __cdecl destroy_forest_textures();
void __cdecl destroy_rainfall_single_tile_texture();
void __cdecl destroy_ter1_white_org_yel_tile_sprites();
void __cdecl destroy_ter1_bottom_left_tile_sprites();
void __cdecl destroy_ter1_unused_sprites2();
void __cdecl destroy_ter1_mine_sprite();
void __cdecl destroy_ter1_solar_collector_sprite();
void __cdecl destroy_ter1_tidal_harness_sprite();
void __cdecl destroy_ter1_mining_platform_sprite();
void __cdecl destroy_ter1_tut_blank_sprite();
void __cdecl destroy_ter1_kelp_farm_sprite();
void __cdecl destroy_ter1_condenser_sprite();
void __cdecl destroy_ter1_echelon_mirror_sprite();
void __cdecl destroy_ter1_borehole_sprite();
void __cdecl destroy_ter1_borehole_cluster_sprite();
void __cdecl destroy_ter1_manifold_nexus_sprites();
void __cdecl destroy_ter1wreck_unity_wreckage_sprites();
void __cdecl destroy_ter1wreck_unity_wreckage_alt_sprites();
void __cdecl destroy_fossil_field_ridge_sprites();
void __cdecl destroy_ter1_unused_sprites1();
void __cdecl destroy_ter1_farm_sprites();
void __cdecl destroy_ter1_soil_enricher_sprites();
void __cdecl destroy_ter1_sea_land_resource_sprites();
void __cdecl destroy_ter1_landmark_resource_sprites();
void __cdecl destroy_glow_sprites();
void __cdecl destroy_ter1_unity_pod_sprites();
void __cdecl destroy_ter1_monolith_sprite();
void __cdecl destroy_ter1_bunker_sprite();
void __cdecl destroy_ter1_airbase_sprite();
void __cdecl destroy_ter1_sensor_array_sprite();
void __cdecl destroy_rainfall_double_tile_sprites();
void __cdecl destroy_veh_sprites();
void __cdecl destroy_flags_veh_sprites();
void __cdecl destroy_icons_general_sprites();
void __cdecl destroy_resource_icon_sprites();
void __cdecl destroy_citizen_lg_cursor_sprites();
void __cdecl destroy_specialist_lg_cursor_sprites();
void __cdecl destroy_citizen_sm_cursor_sprites();
void __cdecl destroy_specialist_sm_cursor_sprites();
void __cdecl destroy_al_citizen_lg_cursor_sprites();
void __cdecl destroy_al_specialist_lg_cursor_sprites();
void __cdecl destroy_al_citizen_sm_cursor_sprites();
void __cdecl destroy_al_specialist_sm_cursor_sprites();
void __cdecl destroy_red_alien_head_icon_sprite();
void __cdecl destroy_silver_menu_icon_sprites();
void __cdecl destroy_silver_checkbox_icon_sprites();
void __cdecl destroy_red_male_head_icon_sprite();
void __cdecl destroy_null_resource_icon_sprite();
void __cdecl destroy_peace_sign_sprites();
void __cdecl destroy_icon_tile_square_sprite();
void __cdecl destroy_xi_boom_veh_sprites();
void __cdecl destroy_xf_boom_veh_sprites();
void __cdecl destroy_battle_mind_worm_sprite();
void __cdecl destroy_battle_isle_deep_sprite();
void __cdecl destroy_battle_locusts_chiron_sprite();
void __cdecl destroy_battle_fungal_tower_sprite();
void __cdecl destroy_battle_spore_launcher_sprite();
void __cdecl destroy_battle_sealurk_sprite();
void __cdecl destroy_tech_icon_sprites();
void __cdecl destroy_facility_icon_sprites();
void __cdecl destroy_secret_project_icon_sprites();
void __cdecl destroy_iface_mp_combo_arrow_sprites();
void __cdecl destroy_scroll_bar_arrow_icon_sprites();
void __cdecl destroy_scroll_bar_small_arrow_icon_sprites();
void __cdecl destroy_scroll_bar_filler_icon_sprites();
void __cdecl destroy_scroll_bar_small_filler_icon_sprite();
void __cdecl destroy_iface_lock_sprites();
void __cdecl destroy_unused_sprites_var01();
void __cdecl destroy_iface_general_windows_top_left_sprite();
void __cdecl destroy_iface_general_windows_top_right_sprite();
void __cdecl destroy_iface_general_windows_bot_left_sprite();
void __cdecl destroy_iface_general_windows_bot_right_sprite();
void __cdecl destroy_iface_general_windows_mid_left_sprite();
void __cdecl destroy_iface_general_windows_mid_right_sprite();
void __cdecl destroy_iface_general_windows_top_mid_sprite();
void __cdecl destroy_iface_general_windows_bot_mid_sprite();
void __cdecl destroy_iface_general_windows_noncap_mid_sprite();
void __cdecl destroy_iface_general_windows_noncap_left_sprite();
void __cdecl destroy_iface_general_windows_noncap_right_sprite();
void __cdecl destroy_unused_sprite_var23();
void __cdecl destroy_unused_sprite_var24();
void __cdecl destroy_unused_sprite_var25();
void __cdecl destroy_unused_sprite_var26();
void __cdecl destroy_unused_sprite_var27();
void __cdecl destroy_unused_sprite_var28();
void __cdecl destroy_unused_sprite_var29();
void __cdecl destroy_unused_sprite_var30();
void __cdecl destroy_unused_sprite_var31();
void __cdecl destroy_unused_sprite_var32();
void __cdecl destroy_unused_sprite_var33();
void __cdecl destroy_unused_sprite_var34();
void __cdecl destroy_unused_sprite_var35();
void __cdecl destroy_unused_sprite_var36();
void __cdecl destroy_unused_sprite_var37();
void __cdecl destroy_unused_sprite_var38();
void __cdecl destroy_unused_sprite_var39();
void __cdecl destroy_unused_sprite_var40();
void __cdecl destroy_unused_sprite_var41();
void __cdecl destroy_unused_sprite_var42();
void __cdecl destroy_unused_sprite_var43();
void __cdecl destroy_unused_sprite_var44();
void __cdecl destroy_unused_sprite_var45();
void __cdecl destroy_unused_sprite_var46();
void __cdecl destroy_iface_tech_tree_arrow_sprites();
void __cdecl destroy_unused_sprite_var47();
void __cdecl destroy_unused_sprite_var48();
void __cdecl destroy_unused_sprite_var49();
void __cdecl destroy_unused_sprite_var50();
void __cdecl destroy_unused_sprite_var51();
void __cdecl destroy_unused_sprite_var52();
void __cdecl destroy_unused_sprite_var53();
void __cdecl destroy_unused_sprite_var54();
void __cdecl destroy_unused_sprite_var55();
void __cdecl destroy_unused_sprite_var56();
void __cdecl destroy_unused_sprite_var57();
void __cdecl destroy_unused_sprite_var58();
void __cdecl destroy_unused_sprite_var59();
void __cdecl destroy_unused_sprite_var60();
void __cdecl destroy_unused_sprite_var61();
void __cdecl destroy_unused_sprite_var62();
void __cdecl destroy_unused_sprite_var63();
void __cdecl destroy_unused_sprite_var64();
void __cdecl destroy_unused_sprite_var65();
void __cdecl destroy_unused_sprite_var66();
void __cdecl destroy_unused_sprite_var67();
void __cdecl destroy_unused_sprite_var68();
void __cdecl destroy_unused_sprite_var69();
void __cdecl destroy_unused_sprite_var70();
void __cdecl destroy_unused_sprite_var71();
void __cdecl destroy_unused_sprite_var72();
void __cdecl destroy_unused_sprite_var73();
void __cdecl destroy_unused_sprite_var74();
void __cdecl destroy_unused_sprites_var02();
void __cdecl destroy_unused_sprites_var03();
void __cdecl destroy_unused_sprites_var04();
void __cdecl destroy_unused_sprites_var05();
void __cdecl destroy_unused_sprites_var06();
void __cdecl destroy_unused_sprites_var07();
void __cdecl destroy_unused_sprites_var08();
void __cdecl destroy_unused_sprites_var09();
void __cdecl destroy_unused_sprites_var10();
void __cdecl destroy_unused_sprite_var75();
void __cdecl destroy_unused_sprite_var76();
void __cdecl destroy_unused_sprite_var77();
void __cdecl destroy_unused_sprite_var78();
void __cdecl destroy_unused_sprite_var79();
void __cdecl destroy_unused_sprite_var80();
void __cdecl destroy_unused_sprite_var81();
void __cdecl destroy_unused_sprite_var82();
void __cdecl destroy_unused_sprite_var83();
void __cdecl destroy_basewin_sprites();
void __cdecl destroy_infowin();
void __cdecl destroy_maininterface();
void __cdecl destroy_maininterface_wave();
void __cdecl destroy_jackal_font();
void __cdecl destroy_messagewin();
void __cdecl destroy_iface_green_right_arrow_sprite();
void __cdecl destroy_monuwin();
void __cdecl destroy_multiwin();
void __cdecl destroy_multiwin_wave();
void __cdecl destroy_netmsg1();
void __cdecl destroy_netmsg2();
void __cdecl destroy_netwin();
void __cdecl destroy_newtechwin();
void __cdecl destroy_pickwin();
void __cdecl destroy_prefwin();
void __cdecl destroy_prefwin_buttongroup();
void __cdecl destroy_quaylewin();
void __cdecl destroy_reportif();
void __cdecl destroy_reportwin();
void __cdecl destroy_socialwinparent();
void __cdecl destroy_statuswin();
void __cdecl destroy_tutwin();
void __cdecl destroy_vehdraw_caviar();
void __cdecl destroy_vehdraw_buffer();
void __cdecl destroy_worldwin();
void __cdecl destroy_wave_device();
void __cdecl destroy_midi_device();
void __cdecl destroy_wave_in_device();
void __cdecl destroy_console_timer();
void __cdecl destroy_cursor_sprites();
void __cdecl destroy_netdaemon();
void __cdecl destroy_fontqueue_val2();
void __cdecl destroy_fontqueue_val1();
void __cdecl destroy_top_menu_wave();
void __cdecl destroy_fonts();
void __cdecl destroy_crash_landing_wave();
void __cdecl destroy_wave_general();
void __cdecl destroy_palette1();
void __cdecl destroy_palette2();
void __cdecl destroy_multidebug();
void __cdecl destroy_buffer();
void __cdecl destroy_txtindex();
void __cdecl destroy_stringtable();
