/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

class Ambience;
class BattleWin;
class Buffer;
class ButtonGroup;
class CaviarData;
class FX;
struct FactionArt;
class Font;
class FontQueue;
class Sprite;
class TextIndex;
class Texture;
class Wave;

/*
 * Atexit teardown thunks
 *
 * One ??__F thunk per dynamically-initialized global: MSVC registers each with
 * atexit from the matching ??__E initializer, and its whole body is "tear down
 * the object at this fixed address". The pointers below are those objects,
 * carrying the original global names out of the thunks' mangled names; they
 * are rebindable data seams and stay unclassified. The Wave teardown is the
 * one target not yet source-owned, so it is reached through a classified
 * dependency instead of a direct call.
 */

typedef void (OriginalObject::*func_wave_destructor)();
extern func_wave_destructor WaveOriginalDestructor;

#include "vector_teardown.h"
extern func_thiscall_teardown BufferElementTeardown;
extern func_thiscall_teardown CaviarDataElementTeardown;
extern func_thiscall_teardown FactionArtElementTeardown;
extern func_thiscall_teardown FontElementTeardown;
extern func_thiscall_teardown SpriteElementTeardown;
extern func_thiscall_teardown TextIndexElementTeardown;
extern func_thiscall_teardown TextureElementTeardown;
extern func_thiscall_teardown WaveElementTeardown;

#include "deleting_thunks.h"

// Opaque-storage teardown seams. These globals' classes are not
// modelled in source, so the thunk hands the storage address
// straight to the original teardown through a seam rather than
// naming a type. Seams are deduped on the ADDRESS they default
// to: one already bound at the same address elsewhere is reused
// from the header above, never redefined here.
extern func_thiscall_teardown InfoWinDtorTarget;   // 0x004594A0
extern func_thiscall_teardown MessageWinDtorTarget;   // 0x00472020
extern func_thiscall_teardown ReportIfDtorTarget;   // 0x004ACDA0
extern func_thiscall_teardown StatusWinDtorTarget;   // 0x004BA120
extern func_thiscall_teardown Wave_DeviceDtorTarget;   // 0x004C4E60
extern func_thiscall_teardown Midi_DeviceDtorTarget;   // 0x004C5780
extern func_thiscall_teardown Wave_In_DeviceDtorTarget;   // 0x004C5980
extern func_thiscall_teardown NetDaemonDtorTarget;   // 0x00538D10
extern func_thiscall_teardown PaletteDtorTarget;   // 0x005FE2E0
extern func_thiscall_teardown TimeDtorTarget;   // 0x00616200
extern func_thiscall_teardown StringsDtorTarget;   // 0x006169C0
extern func_thiscall_teardown CaviarCloseTarget;   // 0x00617020

Wave *const g_ALPHAMENU_WAVE = (Wave *)0x006A7090;
Sprite *const g_UNUSED_SPRITE_VAR02 = (Sprite *)0x006A7130;
Sprite *const g_UNUSED_SPRITE_VAR11 = (Sprite *)0x006A72E0;
Sprite *const g_UNUSED_SPRITE_VAR06 = (Sprite *)0x006A71F0;
Sprite *const g_UNUSED_SPRITE_VAR09 = (Sprite *)0x006A7280;
Sprite *const g_UNUSED_SPRITE_VAR21 = (Sprite *)0x006A74C0;
Sprite *const g_UNUSED_SPRITE_VAR05 = (Sprite *)0x006A71C0;
Sprite *const g_UNUSED_SPRITE_VAR08 = (Sprite *)0x006A7250;
Sprite *const g_UNUSED_SPRITE_VAR04 = (Sprite *)0x006A7190;
Sprite *const g_UNUSED_SPRITE_VAR01 = (Sprite *)0x006A7100;
Sprite *const g_UNUSED_SPRITE_VAR18 = (Sprite *)0x006A7430;
Sprite *const g_UNUSED_SPRITE_VAR03 = (Sprite *)0x006A7160;
Sprite *const g_UNUSED_SPRITE_VAR20 = (Sprite *)0x006A7490;
Sprite *const g_UNUSED_SPRITE_VAR16 = (Sprite *)0x006A73D0;
Sprite *const g_UNUSED_SPRITE_VAR14 = (Sprite *)0x006A7370;
Sprite *const g_UNUSED_SPRITE_VAR22 = (Sprite *)0x006A74F0;
Sprite *const g_UNUSED_SPRITE_VAR10 = (Sprite *)0x006A72B0;
Sprite *const g_UNUSED_SPRITE_VAR15 = (Sprite *)0x006A73A0;
Sprite *const g_UNUSED_SPRITE_VAR13 = (Sprite *)0x006A7340;
Sprite *const g_UNUSED_SPRITE_VAR17 = (Sprite *)0x006A7400;
Sprite *const g_UNUSED_SPRITE_VAR19 = (Sprite *)0x006A7460;
Sprite *const g_UNUSED_SPRITE_VAR12 = (Sprite *)0x006A7310;
Sprite *const g_UNUSED_SPRITE_VAR07 = (Sprite *)0x006A7220;
Wave *const g_BASEWIN_WAVE = (Wave *)0x006EEE68;
BattleWin *const g_BattleWin = (BattleWin *)0x006EEED8;
Wave *const g_CREDITS_WAVE = (Wave *)0x00703E30;
Wave *const g_DESIGNWIN_WAVE = (Wave *)0x0071F240;
Wave *const g_CPU_WAVES = (Wave *)0x0074C5F0;
Wave *const g_MENU_UP_WAVE = (Wave *)0x00749C88;
Wave *const g_MENU_DOWN_WAVE = (Wave *)0x0074D960;
Wave *const g_SCOOT_WAVE = (Wave *)0x00749C18;
Wave *const g_OK_WAVE = (Wave *)0x0074D8F0;
Wave *const g_PASSOVER_WAVE = (Wave *)0x0074D9D0;
FX *const g_FX = (FX *)0x00749CF8;
Ambience *const g_AMBIENCE = (Ambience *)0x0074DA40;
Buffer *const g_PCX_PARSE_TEMP_BUFFER1 = (Buffer *)0x00798668;
FactionArt *const FactionArtGlobal = (FactionArt *)0x0078E978;
Sprite *const g_IFACE_CLOSE_X_SPRITES = (Sprite *)0x007794D8;
Sprite *const g_IFACE_BOX_SPRITES1 = (Sprite *)0x007AC290;
Sprite *const g_IFACE_BOX_SPRITES2 = (Sprite *)0x0076DC98;
Sprite *const g_IFACE_BOX_SPRITES3 = (Sprite *)0x0078AE58;
Sprite *const g_IFACE_BOX_SPRITES4 = (Sprite *)0x0078CC60;
Sprite *const g_IFACE_BOX_SPRITES5 = (Sprite *)0x00779CB0;
Sprite *const g_IFACE_BOX_SPRITES6 = (Sprite *)0x007A6978;
Sprite *const g_IFACE_BOX_SPRITES7 = (Sprite *)0x0078E0A0;
Sprite *const g_IFACE_BOX_SPRITES8 = (Sprite *)0x0075B950;
Buffer *const g_IFACE_BOX_SPRITE_BUFFERS = (Buffer *)0x0075C218;
Sprite *const g_IFACE_STD_POPUPS_TOP_LEFT_SPRITE = (Sprite *)0x007921E8;
Sprite *const g_IFACE_STD_POPUPS_TOP_RIGHT_SPRITE = (Sprite *)0x00779478;
Sprite *const g_IFACE_STD_POPUPS_BOT_LEFT_SPRITE = (Sprite *)0x007AC1C0;
Sprite *const g_IFACE_STD_POPUPS_BOT_RIGHT_SPRITE = (Sprite *)0x007AB400;
Sprite *const g_IFACE_STD_POPUPS_TOP_MID_SPRITE = (Sprite *)0x007793F0;
Sprite *const g_IFACE_STD_POPUPS_BOT_MID_SPRITE = (Sprite *)0x007871D0;
Sprite *const g_IFACE_STD_POPUPS_MID_LEFT_SPRITE = (Sprite *)0x007ACFB0;
Sprite *const g_IFACE_STD_POPUPS_MID_RIGHT_SPRITE = (Sprite *)0x0075B058;
Buffer *const g_IFACE_STD_POPUPS_MIDDLE_BUFFER = (Buffer *)0x0077AA70;
CaviarData *const g_UNUSED_CAVIARDATA_VAR1 = (CaviarData *)0x00791D68;
CaviarData *const g_SSF_CAVIARDATA = (CaviarData *)0x007ACCA0;
CaviarData *const g_SDP_CAVIARDATA = (CaviarData *)0x0079A6A0;
CaviarData *const g_SAS_CAVIARDATA = (CaviarData *)0x00787E48;
CaviarData *const g_SCD_CAVIARDATA = (CaviarData *)0x00799228;
CaviarData *const g_SCJ_CAVIARDATA = (CaviarData *)0x007ACC90;
CaviarData *const g_SAGS_CAVIARDATA = (CaviarData *)0x0077A578;
CaviarData *const g_SFT_CAVIARDATA = (CaviarData *)0x0079A6B0;
CaviarData *const g_VHR_CAVIARDATA1 = (CaviarData *)0x007765B0;
CaviarData *const g_SHT_CAVIARDATA = (CaviarData *)0x0078A5E0;
CaviarData *const g_SRB_CAVIARDATA = (CaviarData *)0x0078A300;
CaviarData *const g_ASAS_CAVIARDATA = (CaviarData *)0x007AC030;
CaviarData *const g_RESLASER_CAVIARDATA = (CaviarData *)0x007ACCC0;
CaviarData *const g_RESBOLT_CAVIARDATA = (CaviarData *)0x007A7900;
CaviarData *const g_FUNLOAD_CAVIARDATA = (CaviarData *)0x007ACC10;
CaviarData *const g_TECLOAD_CAVIARDATA = (CaviarData *)0x00788028;
CaviarData *const g_SP_DISSWAVE_CAVIARDATA = (CaviarData *)0x00799E38;
CaviarData *const g_SP_MARINED_CAVIARDATA = (CaviarData *)0x007792A0;
CaviarData *const g_SP_NANOO_CAVIARDATA = (CaviarData *)0x0075AEF0;
CaviarData *const g_SP_SOPORIFIC_CAVIARDATA = (CaviarData *)0x007AD130;
CaviarData *const g_AA01_CAVIARDATA = (CaviarData *)0x007AD040;
CaviarData *const g_AA_ROVER_CAVIARDATA = (CaviarData *)0x0075AFC0;
CaviarData *const g_AA_WING_CAVIARDATA = (CaviarData *)0x00779288;
CaviarData *const g_ACP_CAVIARDATA = (CaviarData *)0x0078A610;
CaviarData *const g_AX_CAVIARDATA = (CaviarData *)0x0079A6F0;
CaviarData *const g_AA_CAVIARDATA = (CaviarData *)0x00789A50;
CaviarData *const g_ACOLPOD_CAVIARDATA = (CaviarData *)0x0078A600;
CaviarData *const g_AT_CAVIARDATA = (CaviarData *)0x00787E60;
CaviarData *const g_VTA_CAVIARDATA = (CaviarData *)0x007880C0;
CaviarData *const g_ATP_CAVIARDATA = (CaviarData *)0x007ABFC0;
CaviarData *const g_SSFA_CAVIARDATA = (CaviarData *)0x0078A510;
CaviarData *const g_SFTA_CAVIARDATA = (CaviarData *)0x0079A640;
CaviarData *const g_VW00_CAVIARDATA = (CaviarData *)0x007871C0;
CaviarData *const g_VIPTAWL_CAVIARDATA = (CaviarData *)0x0079A700;
CaviarData *const g_VIPTASGN_CAVIARDATA = (CaviarData *)0x007AB3F0;
CaviarData *const g_VIPTAPSI_CAVIARDATA = (CaviarData *)0x007795A0;
CaviarData *const g_VIPTR_CAVIARDATA = (CaviarData *)0x00799628;
CaviarData *const g_VIPTA_CAVIARDATA = (CaviarData *)0x007791D0;
CaviarData *const g_PTMOD_CAVIARDATA = (CaviarData *)0x0078A500;
CaviarData *const g_VB_CAVIARDATA = (CaviarData *)0x00779230;
CaviarData *const g_VBP_CAVIARDATA = (CaviarData *)0x0078E968;
CaviarData *const g_VGMC_CAVIARDATA = (CaviarData *)0x0075AED0;
CaviarData *const g_VGMCP_CAVIARDATA = (CaviarData *)0x0076EBE0;
CaviarData *const g_VLIGHTS_CAVIARDATA = (CaviarData *)0x0075B848;
CaviarData *const g_VPT_CAVIARDATA = (CaviarData *)0x007592D0;
CaviarData *const g_A_CAVIARDATA = (CaviarData *)0x0075AF00;
CaviarData *const g_APWALL_CAVIARDATA = (CaviarData *)0x0078A490;
CaviarData *const g_ASGEN_CAVIARDATA = (CaviarData *)0x007AD120;
CaviarData *const g_APSID_CAVIARDATA = (CaviarData *)0x007ACCB0;
CaviarData *const g_VA01_CAVIARDATA = (CaviarData *)0x007AD0E0;
CaviarData *const g_VR_CAVIARDATA = (CaviarData *)0x0076E560;
CaviarData *const g_VHR_CAVIARDATA2 = (CaviarData *)0x00779560;
CaviarData *const g_VRC_CAVIARDATA = (CaviarData *)0x0075ADB8;
CaviarData *const g_VI_CAVIARDATA = (CaviarData *)0x0078B740;
CaviarData *const g_VGMT_CAVIARDATA = (CaviarData *)0x0077A5B8;
CaviarData *const g_VGMTP_CAVIARDATA = (CaviarData *)0x0078B720;
CaviarData *const g_UNUSED_CAVIARDATA_VAR2 = (CaviarData *)0x007ACF90;
CaviarData *const g_VWNTU_CAVIARDATA = (CaviarData *)0x007796A0;
CaviarData *const g_VT_CAVIARDATA = (CaviarData *)0x0075AD78;
CaviarData *const g_DROP_CAVIARDATA = (CaviarData *)0x007ACD60;
CaviarData *const g_DROPLET_CAVIARDATA = (CaviarData *)0x0076EBD0;
CaviarData *const g_VCL_CAVIARDATA = (CaviarData *)0x007AD170;
CaviarData *const g_UNUSED_CAVIARDATA_VAR3 = (CaviarData *)0x007795F0;
CaviarData *const g_VCLT00_CAVIARDATA = (CaviarData *)0x00789B58;
CaviarData *const g_VHT_VBP_CAVIARDATA = (CaviarData *)0x00779608;
CaviarData *const g_VHTP_CAVIARDATA = (CaviarData *)0x0078A640;
CaviarData *const g_VHTA0_CAVIARDATA = (CaviarData *)0x00779648;
CaviarData *const g_VHTTP_CAVIARDATA = (CaviarData *)0x00759310;
CaviarData *const g_VHTTPA0_CAVIARDATA = (CaviarData *)0x0078B750;
CaviarData *const g_VSP_CAVIARDATA = (CaviarData *)0x007A6820;
CaviarData *const g_VSPA0_CAVIARDATA = (CaviarData *)0x00779270;
CaviarData *const g_VSPTF_CAVIARDATA = (CaviarData *)0x007A7290;
CaviarData *const g_VSPTB_CAVIARDATA = (CaviarData *)0x007A7280;
CaviarData *const g_VFL_CAVIARDATA = (CaviarData *)0x007ACC50;
CaviarData *const g_VGS_CAVIARDATA = (CaviarData *)0x007A7240;
CaviarData *const g_VGSP_CAVIARDATA = (CaviarData *)0x00798BF0;
CaviarData *const g_VJTP_CAVIARDATA = (CaviarData *)0x007795B0;
CaviarData *const g_VJT0_CAVIARDATA = (CaviarData *)0x0078A2B8;
CaviarData *const g_VCU_CAVIARDATA = (CaviarData *)0x0075AEE0;
CaviarData *const g_VCUP_CAVIARDATA = (CaviarData *)0x0075B440;
CaviarData *const g_VCUA0_CAVIARDATA = (CaviarData *)0x0078CAB8;
CaviarData *const g_VCUW_CAVIARDATA = (CaviarData *)0x0075B088;
CaviarData *const g_VCT_CAVIARDATA = (CaviarData *)0x0079A680;
CaviarData *const g_VCTP_CAVIARDATA = (CaviarData *)0x007ACFA0;
CaviarData *const g_VCTB_CAVIARDATA = (CaviarData *)0x0076E890;
CaviarData *const g_VCT0_CAVIARDATA = (CaviarData *)0x0079A628;
CaviarData *const g_VWNTT_CAVIARDATA = (CaviarData *)0x0078B730;
CaviarData *const g_VWNST_CAVIARDATA = (CaviarData *)0x0078DE20;
CaviarData *const g_VWNAA_CAVIARDATA = (CaviarData *)0x007AC1A0;
CaviarData *const g_VW_CAVIARDATA = (CaviarData *)0x00787100;
CaviarData *const g_VM_CAVIARDATA = (CaviarData *)0x00791D78;
CaviarData *const g_VM13_CAVIARDATA = (CaviarData *)0x0078A5F0;
CaviarData *const g_VPBR0_CAVIARDATA = (CaviarData *)0x0076E9B0;
CaviarData *const g_UNUSED_CAVIARDATA_VAR4 = (CaviarData *)0x007791E8;
CaviarData *const g_NW_CAVIARDATA = (CaviarData *)0x0079A690;
CaviarData *const g_NI_CAVIARDATA = (CaviarData *)0x007791C0;
CaviarData *const g_NLC_CAVIARDATA = (CaviarData *)0x00779660;
CaviarData *const g_UNUSED_CAVIARDATA_VAR5 = (CaviarData *)0x00787E08;
Texture *const g_RADIUS1_TEXTURE = (Texture *)0x00787FB8;
Texture *const g_RADIUS2_TEXTURE = (Texture *)0x0075B858;
Texture *const g_ROCKY_TEXTURES = (Texture *)0x0076E9E0;
Texture *const g_OCEAN_TEXTURES = (Texture *)0x007A7820;
Texture *const g_FLAT_ARID_LAND_TEXTURE = (Texture *)0x00799E48;
Texture *const g_MOIST_LAND_TEXTURES = (Texture *)0x00799EB8;
Texture *const g_RAINY_LAND_TEXTURES = (Texture *)0x00799738;
Texture *const g_JUNGLE_LAND_TEXTURES = (Texture *)0x00789C28;
Texture *const g_DUNE_LAND_TEXTURE = (Texture *)0x007AC220;
Texture *const g_SUNNY_MESA_TEXTURES = (Texture *)0x007797F8;
Texture *const g_RAINFALL_SINGLE_TILE_TEXTURES = (Texture *)0x0076E8A0;
Texture *const g_ROAD_TEXTURES = (Texture *)0x00792218;
Texture *const g_MAGTUBE_TEXTURES = (Texture *)0x00798E08;
Texture *const g_RIVER_TEXTURES = (Texture *)0x007A7AA0;
Texture *const g_MOUNT_PLANET_TEXTURES = (Texture *)0x0078A340;
Texture *const g_GARLAND_CRATER_TEXTURES = (Texture *)0x00788100;
Texture *const g_FUNGUS_TEXTURES = (Texture *)0x00776A80;
Texture *const g_FARM_TEXTURES = (Texture *)0x00799238;
Texture *const g_FOREST_TEXTURES = (Texture *)0x0078A758;
Texture *const g_RAINFALL_SINGLE_TILE_TEXTURE = (Texture *)0x0078DD80;
Sprite *const g_TER1_WHITE_ORG_YEL_TILE_SPRITES = (Sprite *)0x00791C58;
Sprite *const g_TER1_BOTTOM_LEFT_TILE_SPRITES = (Sprite *)0x007A99A0;
Sprite *const g_TER1_UNUSED_SPRITES2 = (Sprite *)0x00779420;
Sprite *const g_TER1_MINE_SPRITE = (Sprite *)0x00776A50;
Sprite *const g_TER1_SOLAR_COLLECTOR_SPRITE = (Sprite *)0x007991F8;
Sprite *const g_TER1_TIDAL_HARNESS_SPRITE = (Sprite *)0x0078A5B0;
Sprite *const g_TER1_MINING_PLATFORM_SPRITE = (Sprite *)0x00789B68;
Sprite *const g_TER1_TUT_BLANK_SPRITE = (Sprite *)0x00798C40;
Sprite *const g_TER1_KELP_FARM_SPRITE = (Sprite *)0x007A6860;
Sprite *const g_TER1_CONDENSER_SPRITE = (Sprite *)0x00779390;
Sprite *const g_TER1_ECHELON_MIRROR_SPRITE = (Sprite *)0x007ABF60;
Sprite *const g_TER1_BOREHOLE_SPRITE = (Sprite *)0x0078DD20;
Sprite *const g_TER1_BOREHOLE_CLUSTER_SPRITE = (Sprite *)0x007ACB88;
Sprite *const g_TER1_MANIFOLD_NEXUS_SPRITES = (Sprite *)0x007AC098;
Sprite *const g_TER1WRECK_UNITY_WRECKAGE_SPRITES = (Sprite *)0x00776758;
Sprite *const g_TER1WRECK_UNITY_WRECKAGE_ALT_SPRITES = (Sprite *)0x00799658;
Sprite *const g_FOSSIL_FIELD_RIDGE_SPRITES = (Sprite *)0x007ACD70;
Sprite *const g_TER1_UNUSED_SPRITES1 = (Sprite *)0x007792B0;
Sprite *const g_TER1_FARM_SPRITES = (Sprite *)0x00791FC8;
Sprite *const g_TER1_SOIL_ENRICHER_SPRITES = (Sprite *)0x0079A710;
Sprite *const g_TER1_SEA_LAND_RESOURCE_SPRITES = (Sprite *)0x0075B230;
Sprite *const g_TER1_LANDMARK_RESOURCE_SPRITES = (Sprite *)0x0078A650;
Sprite *const g_GLOW_SPRITES = (Sprite *)0x00779770;
Sprite *const g_TER1_UNITY_POD_SPRITES = (Sprite *)0x0077AFF8;
Sprite *const g_TER1_MONOLITH_SPRITE = (Sprite *)0x0075B098;
Sprite *const g_TER1_BUNKER_SPRITE = (Sprite *)0x007AD010;
Sprite *const g_TER1_AIRBASE_SPRITE = (Sprite *)0x007ACC60;
Sprite *const g_TER1_SENSOR_ARRAY_SPRITE = (Sprite *)0x007A6830;
Sprite *const g_RAINFALL_DOUBLE_TILE_SPRITES = (Sprite *)0x007ACBB8;
Sprite *const g_VEH_SPRITES = (Sprite *)0x007777A0;
Sprite *const g_FLAGS_VEH_SPRITES = (Sprite *)0x0078B778;
Sprite *const g_ICONS_GENERAL_SPRITES = (Sprite *)0x0075B450;
Sprite *const g_RESOURCE_ICON_SPRITES = (Sprite *)0x007A72A0;
Sprite *const g_CITIZEN_LG_CURSOR_SPRITES = (Sprite *)0x0078CAD0;
Sprite *const g_SPECIALIST_LG_CURSOR_SPRITES = (Sprite *)0x007765C0;
Sprite *const g_CITIZEN_SM_CURSOR_SPRITES = (Sprite *)0x00776420;
Sprite *const g_SPECIALIST_SM_CURSOR_SPRITES = (Sprite *)0x00779B78;
Sprite *const g_AL_CITIZEN_LG_CURSOR_SPRITES = (Sprite *)0x007AD1B0;
Sprite *const g_AL_SPECIALIST_LG_CURSOR_SPRITES = (Sprite *)0x00798CD0;
Sprite *const g_AL_CITIZEN_SM_CURSOR_SPRITES = (Sprite *)0x0075B180;
Sprite *const g_AL_SPECIALIST_SM_CURSOR_SPRITES = (Sprite *)0x0075B710;
Sprite *const g_RED_ALIEN_HEAD_ICON_SPRITE = (Sprite *)0x00791F98;
Sprite *const g_SILVER_MENU_ICON_SPRITES = (Sprite *)0x0075AE20;
Sprite *const g_SILVER_CHECKBOX_ICON_SPRITES = (Sprite *)0x0075AF68;
Sprite *const g_RED_MALE_HEAD_ICON_SPRITE = (Sprite *)0x0075AD88;
Sprite *const g_NULL_RESOURCE_ICON_SPRITE = (Sprite *)0x0078A520;
Sprite *const g_PEACE_SIGN_SPRITES = (Sprite *)0x0075AF10;
Sprite *const g_ICON_TILE_SQUARE_SPRITE = (Sprite *)0x00776728;
Sprite *const g_XI_BOOM_VEH_SPRITES = (Sprite *)0x007A9B30;
Sprite *const g_XF_BOOM_VEH_SPRITES = (Sprite *)0x007AB460;
Sprite *const g_BATTLE_MIND_WORM_SPRITE = (Sprite *)0x00779200;
Sprite *const g_BATTLE_ISLE_DEEP_SPRITE = (Sprite *)0x0076DC30;
Sprite *const g_BATTLE_LOCUSTS_CHIRON_SPRITE = (Sprite *)0x0078A4A0;
Sprite *const g_BATTLE_FUNGAL_TOWER_SPRITE = (Sprite *)0x00787E70;
Sprite *const g_BATTLE_SPORE_LAUNCHER_SPRITE = (Sprite *)0x007AC000;
Sprite *const g_BATTLE_SEALURK_SPRITE = (Sprite *)0x00779570;
Sprite *const g_TECH_ICON_SPRITES = (Sprite *)0x00759E28;
Sprite *const g_FACILITY_ICON_SPRITES = (Sprite *)0x00787200;
Sprite *const g_SECRET_PROJECT_ICON_SPRITES = (Sprite *)0x00759320;
Sprite *const g_IFACE_MP_COMBO_ARROW_SPRITES = (Sprite *)0x00788038;
Sprite *const g_SCROLL_BAR_ARROW_ICON_SPRITES = (Sprite *)0x00791D88;
Sprite *const g_SCROLL_BAR_SMALL_ARROW_ICON_SPRITES = (Sprite *)0x0078DE30;
Sprite *const g_SCROLL_BAR_FILLER_ICON_SPRITES = (Sprite *)0x0079A5E8;
Sprite *const g_SCROLL_BAR_SMALL_FILLER_ICON_SPRITE = (Sprite *)0x007796B0;
Sprite *const g_IFACE_LOCK_SPRITES = (Sprite *)0x007AC040;
Sprite *const g_UNUSED_SPRITES_VAR01 = (Sprite *)0x007A7940;
Sprite *const g_IFACE_GENERAL_WINDOWS_TOP_LEFT_SPRITE = (Sprite *)0x0078DD50;
Sprite *const g_IFACE_GENERAL_WINDOWS_TOP_RIGHT_SPRITE = (Sprite *)0x00789BC8;
Sprite *const g_IFACE_GENERAL_WINDOWS_BOT_LEFT_SPRITE = (Sprite *)0x00776580;
Sprite *const g_IFACE_GENERAL_WINDOWS_BOT_RIGHT_SPRITE = (Sprite *)0x007ABFD0;
Sprite *const g_IFACE_GENERAL_WINDOWS_MID_LEFT_SPRITE = (Sprite *)0x00787F88;
Sprite *const g_IFACE_GENERAL_WINDOWS_MID_RIGHT_SPRITE = (Sprite *)0x0078A2D0;
Sprite *const g_IFACE_GENERAL_WINDOWS_TOP_MID_SPRITE = (Sprite *)0x0078E070;
Sprite *const g_IFACE_GENERAL_WINDOWS_BOT_MID_SPRITE = (Sprite *)0x0078A550;
Sprite *const g_IFACE_GENERAL_WINDOWS_NONCAP_MID_SPRITE = (Sprite *)0x00789BF8;
Sprite *const g_IFACE_GENERAL_WINDOWS_NONCAP_LEFT_SPRITE = (Sprite *)0x0075B150;
Sprite *const g_IFACE_GENERAL_WINDOWS_NONCAP_RIGHT_SPRITE = (Sprite *)0x007AD180;
Sprite *const g_UNUSED_SPRITE_VAR23 = (Sprite *)0x007880D0;
Sprite *const g_UNUSED_SPRITE_VAR24 = (Sprite *)0x0079A5B8;
Sprite *const g_UNUSED_SPRITE_VAR25 = (Sprite *)0x007797C8;
Sprite *const g_UNUSED_SPRITE_VAR26 = (Sprite *)0x00792638;
Sprite *const g_UNUSED_SPRITE_VAR27 = (Sprite *)0x0079A650;
Sprite *const g_UNUSED_SPRITE_VAR28 = (Sprite *)0x00799708;
Sprite *const g_UNUSED_SPRITE_VAR29 = (Sprite *)0x007ACFE0;
Sprite *const g_UNUSED_SPRITE_VAR30 = (Sprite *)0x007A7910;
Sprite *const g_UNUSED_SPRITE_VAR31 = (Sprite *)0x00779240;
Sprite *const g_UNUSED_SPRITE_VAR32 = (Sprite *)0x007ACD00;
Sprite *const g_UNUSED_SPRITE_VAR33 = (Sprite *)0x00776A20;
Sprite *const g_UNUSED_SPRITE_VAR34 = (Sprite *)0x007769F0;
Sprite *const g_UNUSED_SPRITE_VAR35 = (Sprite *)0x007796E0;
Sprite *const g_UNUSED_SPRITE_VAR36 = (Sprite *)0x007AC1F0;
Sprite *const g_UNUSED_SPRITE_VAR37 = (Sprite *)0x00789A60;
Sprite *const g_UNUSED_SPRITE_VAR38 = (Sprite *)0x0078CC30;
Sprite *const g_UNUSED_SPRITE_VAR39 = (Sprite *)0x00787F58;
Sprite *const g_UNUSED_SPRITE_VAR40 = (Sprite *)0x00798C00;
Sprite *const g_UNUSED_SPRITE_VAR41 = (Sprite *)0x0078A580;
Sprite *const g_UNUSED_SPRITE_VAR42 = (Sprite *)0x007AD0F0;
Sprite *const g_UNUSED_SPRITE_VAR43 = (Sprite *)0x007AD080;
Sprite *const g_UNUSED_SPRITE_VAR44 = (Sprite *)0x00792608;
Sprite *const g_UNUSED_SPRITE_VAR45 = (Sprite *)0x00787EA0;
Sprite *const g_UNUSED_SPRITE_VAR46 = (Sprite *)0x007ACCD0;
Sprite *const g_IFACE_TECH_TREE_ARROW_SPRITES = (Sprite *)0x0075AFD0;
Sprite *const g_UNUSED_SPRITE_VAR47 = (Sprite *)0x00779740;
Sprite *const g_UNUSED_SPRITE_VAR48 = (Sprite *)0x0078A4D0;
Sprite *const g_UNUSED_SPRITE_VAR49 = (Sprite *)0x007AD140;
Sprite *const g_UNUSED_SPRITE_VAR50 = (Sprite *)0x007793C0;
Sprite *const g_UNUSED_SPRITE_VAR51 = (Sprite *)0x00789B98;
Sprite *const g_UNUSED_SPRITE_VAR52 = (Sprite *)0x007766F8;
Sprite *const g_UNUSED_SPRITE_VAR53 = (Sprite *)0x00798C70;
Sprite *const g_UNUSED_SPRITE_VAR54 = (Sprite *)0x0076EBA0;
Sprite *const g_UNUSED_SPRITE_VAR55 = (Sprite *)0x007592E0;
Sprite *const g_UNUSED_SPRITE_VAR56 = (Sprite *)0x007795C0;
Sprite *const g_UNUSED_SPRITE_VAR57 = (Sprite *)0x00792130;
Sprite *const g_UNUSED_SPRITE_VAR58 = (Sprite *)0x0075ADF0;
Sprite *const g_UNUSED_SPRITE_VAR59 = (Sprite *)0x0076E980;
Sprite *const g_UNUSED_SPRITE_VAR60 = (Sprite *)0x0078A310;
Sprite *const g_UNUSED_SPRITE_VAR61 = (Sprite *)0x0076DC60;
Sprite *const g_UNUSED_SPRITE_VAR62 = (Sprite *)0x00789B18;
Sprite *const g_UNUSED_SPRITE_VAR63 = (Sprite *)0x007A68C0;
Sprite *const g_UNUSED_SPRITE_VAR64 = (Sprite *)0x0077A588;
Sprite *const g_UNUSED_SPRITE_VAR65 = (Sprite *)0x00779710;
Sprite *const g_UNUSED_SPRITE_VAR66 = (Sprite *)0x0079A6C0;
Sprite *const g_UNUSED_SPRITE_VAR67 = (Sprite *)0x0078DDF0;
Sprite *const g_UNUSED_SPRITE_VAR68 = (Sprite *)0x007A7250;
Sprite *const g_UNUSED_SPRITE_VAR69 = (Sprite *)0x007AD0B0;
Sprite *const g_UNUSED_SPRITE_VAR70 = (Sprite *)0x007AD050;
Sprite *const g_UNUSED_SPRITE_VAR71 = (Sprite *)0x007A6890;
Sprite *const g_UNUSED_SPRITE_VAR72 = (Sprite *)0x007763F0;
Sprite *const g_UNUSED_SPRITE_VAR73 = (Sprite *)0x007ACD30;
Sprite *const g_UNUSED_SPRITE_VAR74 = (Sprite *)0x007ABF90;
Sprite *const g_UNUSED_SPRITES_VAR02 = (Sprite *)0x007A68F0;
Sprite *const g_UNUSED_SPRITES_VAR03 = (Sprite *)0x00789A90;
Sprite *const g_UNUSED_SPRITES_VAR04 = (Sprite *)0x00792160;
Sprite *const g_UNUSED_SPRITES_VAR05 = (Sprite *)0x0075B0C8;
Sprite *const g_UNUSED_SPRITES_VAR06 = (Sprite *)0x0075B8C8;
Sprite *const g_UNUSED_SPRITES_VAR07 = (Sprite *)0x00787ED0;
Sprite *const g_UNUSED_SPRITES_VAR08 = (Sprite *)0x007ACE80;
Sprite *const g_UNUSED_SPRITES_VAR09 = (Sprite *)0x007920A8;
Sprite *const g_UNUSED_SPRITES_VAR10 = (Sprite *)0x007ACF08;
Sprite *const g_UNUSED_SPRITE_VAR75 = (Sprite *)0x007794A8;
Sprite *const g_UNUSED_SPRITE_VAR76 = (Sprite *)0x00779670;
Sprite *const g_UNUSED_SPRITE_VAR77 = (Sprite *)0x007AB430;
Sprite *const g_UNUSED_SPRITE_VAR78 = (Sprite *)0x00798CA0;
Sprite *const g_UNUSED_SPRITE_VAR79 = (Sprite *)0x0078E040;
Sprite *const g_UNUSED_SPRITE_VAR80 = (Sprite *)0x007A67F0;
Sprite *const g_UNUSED_SPRITE_VAR81 = (Sprite *)0x00779618;
Sprite *const g_UNUSED_SPRITE_VAR82 = (Sprite *)0x007ACB58;
Sprite *const g_UNUSED_SPRITE_VAR83 = (Sprite *)0x007ACC20;
Sprite *const g_BASEWIN_SPRITES = (Sprite *)0x0077A5C8;
Wave *const g_MAININTERFACE_WAVE = (Wave *)0x007D38B8;
/*
 * AN OBJECT, WHERE EVERY OTHER LINE HERE HOLDS A POINTER. Both forms name the
 * same storage while this tree is injected into the shipped image, and while
 * that was the only way to run it the pointer form cost nothing. It is not
 * free any more: the artifact is now an executable of its own with the
 * recovered `WinMain` as its entry point (src/main.cpp), and `(Font *)
 * 0x007D3948` in a program that is not the shipped image is a pointer into
 * nothing. The first call WinMain makes through this global would fault.
 *
 * It also compiles differently, which is the half a byte match can see.
 * `g_JACKAL_FONT.init(...)` on an object is `mov ecx, OFFSET g_JACKAL_FONT` -
 * the `mov ecx, 0x7d3948` at 0x0045FAF6. Through a pointer variable the same
 * source is `mov ecx, dword ptr [g_JACKAL_FONT]`, a load the image never
 * performs.
 *
 * The other ~400 globals below have the same latent fault and are left as
 * they are until the entry point reaches them; this one is on WinMain's path
 * today. `g_PALETTE1` in palette.h is the same conversion.
 */
extern Font g_JACKAL_FONT;
Sprite *const g_IFACE_GREEN_RIGHT_ARROW_SPRITE = (Sprite *)0x007F67C8;
Wave *const g_MULTIWIN_WAVE = (Wave *)0x007FFF00;
ButtonGroup *const g_PREFWIN_BUTTONGROUP = (ButtonGroup *)0x008577F0;
Buffer *const g_VEHDRAW_BUFFER = (Buffer *)0x008CC298;
Sprite *const g_CURSOR_SPRITES = (Sprite *)0x0093AA70;
FontQueue *const g_FONTQUEUE_VAL2 = (FontQueue *)0x0093FB88;
FontQueue *const g_FONTQUEUE_VAL1 = (FontQueue *)0x0093FAE8;
Wave *const g_TOP_MENU_WAVE = (Wave *)0x00945780;
Font *const g_FONTS = (Font *)0x0093FC58;
Wave *const g_CRASH_LANDING_WAVE = (Wave *)0x00945E08;
Wave *const g_WAVE_GENERAL = (Wave *)0x00945ED0;
Buffer *const g_BUFFER = (Buffer *)0x009B6080;
TextIndex *const TxtIndexGlobal = (TextIndex *)0x009B7D08;

void __cdecl destroy_alphamenu_wave();
void __cdecl destroy_unused_sprite_var02();
void __cdecl destroy_unused_sprite_var11();
void __cdecl destroy_unused_sprite_var06();
void __cdecl destroy_unused_sprite_var09();
void __cdecl destroy_unused_sprite_var21();
void __cdecl destroy_unused_sprite_var05();
void __cdecl destroy_unused_sprite_var08();
void __cdecl destroy_unused_sprite_var04();
void __cdecl destroy_unused_sprite_var01();
void __cdecl destroy_unused_sprite_var18();
void __cdecl destroy_unused_sprite_var03();
void __cdecl destroy_unused_sprite_var20();
void __cdecl destroy_unused_sprite_var16();
void __cdecl destroy_unused_sprite_var14();
void __cdecl destroy_unused_sprite_var22();
void __cdecl destroy_unused_sprite_var10();
void __cdecl destroy_unused_sprite_var15();
void __cdecl destroy_unused_sprite_var13();
void __cdecl destroy_unused_sprite_var17();
void __cdecl destroy_unused_sprite_var19();
void __cdecl destroy_unused_sprite_var12();
void __cdecl destroy_unused_sprite_var07();
void __cdecl destroy_basewin();
void __cdecl destroy_basewin_wave();
void __cdecl destroy_battlewin();
void __cdecl destroy_councwin();
void __cdecl destroy_credits_wave();
void __cdecl destroy_datalink();
void __cdecl destroy_designwin();
void __cdecl destroy_designwin_wave();
void __cdecl destroy_diplopop();
void __cdecl destroy_diplowin();
void __cdecl destroy_cpu_waves();
void __cdecl destroy_menu_up_wave();
void __cdecl destroy_menu_down_wave();
void __cdecl destroy_scoot_wave();
void __cdecl destroy_ok_wave();
void __cdecl destroy_passover_wave();
void __cdecl destroy_fx();
void __cdecl destroy_ambience();
void __cdecl destroy_famewin();
void __cdecl destroy_pcx_parse_temp_buffer1();
void __cdecl destroy_factionart();
void __cdecl destroy_iface_close_x_sprites();
void __cdecl destroy_iface_box_sprites1();
void __cdecl destroy_iface_box_sprites2();
void __cdecl destroy_iface_box_sprites3();
void __cdecl destroy_iface_box_sprites4();
void __cdecl destroy_iface_box_sprites5();
void __cdecl destroy_iface_box_sprites6();
void __cdecl destroy_iface_box_sprites7();
void __cdecl destroy_iface_box_sprites8();
void __cdecl destroy_iface_box_sprite_buffers();
void __cdecl destroy_iface_std_popups_top_left_sprite();
void __cdecl destroy_iface_std_popups_top_right_sprite();
void __cdecl destroy_iface_std_popups_bot_left_sprite();
void __cdecl destroy_iface_std_popups_bot_right_sprite();
void __cdecl destroy_iface_std_popups_top_mid_sprite();
void __cdecl destroy_iface_std_popups_bot_mid_sprite();
void __cdecl destroy_iface_std_popups_mid_left_sprite();
void __cdecl destroy_iface_std_popups_mid_right_sprite();
void __cdecl destroy_iface_std_popups_middle_buffer();
void __cdecl destroy_unused_caviardata_var1();
void __cdecl destroy_ssf_caviardata();
void __cdecl destroy_sdp_caviardata();
void __cdecl destroy_sas_caviardata();
void __cdecl destroy_scd_caviardata();
void __cdecl destroy_scj_caviardata();
void __cdecl destroy_sags_caviardata();
void __cdecl destroy_sft_caviardata();
void __cdecl destroy_vhr_caviardata1();
void __cdecl destroy_sht_caviardata();
void __cdecl destroy_srb_caviardata();
void __cdecl destroy_asas_caviardata();
void __cdecl destroy_reslaser_caviardata();
void __cdecl destroy_resbolt_caviardata();
void __cdecl destroy_funload_caviardata();
void __cdecl destroy_tecload_caviardata();
void __cdecl destroy_sp_disswave_caviardata();
void __cdecl destroy_sp_marined_caviardata();
void __cdecl destroy_sp_nanoo_caviardata();
void __cdecl destroy_sp_soporific_caviardata();
void __cdecl destroy_aa01_caviardata();
void __cdecl destroy_aa_rover_caviardata();
void __cdecl destroy_aa_wing_caviardata();
void __cdecl destroy_acp_caviardata();
void __cdecl destroy_ax_caviardata();
void __cdecl destroy_aa_caviardata();
void __cdecl destroy_acolpod_caviardata();
void __cdecl destroy_at_caviardata();
void __cdecl destroy_vta_caviardata();
void __cdecl destroy_atp_caviardata();
void __cdecl destroy_ssfa_caviardata();
void __cdecl destroy_sfta_caviardata();
void __cdecl destroy_vw00_caviardata();
void __cdecl destroy_viptawl_caviardata();
void __cdecl destroy_viptasgn_caviardata();
void __cdecl destroy_viptapsi_caviardata();
void __cdecl destroy_viptr_caviardata();
void __cdecl destroy_vipta_caviardata();
void __cdecl destroy_ptmod_caviardata();
void __cdecl destroy_vb_caviardata();
void __cdecl destroy_vbp_caviardata();
void __cdecl destroy_vgmc_caviardata();
void __cdecl destroy_vgmcp_caviardata();
void __cdecl destroy_vlights_caviardata();
void __cdecl destroy_vpt_caviardata();
void __cdecl destroy_a_caviardata();
void __cdecl destroy_apwall_caviardata();
void __cdecl destroy_asgen_caviardata();
void __cdecl destroy_apsid_caviardata();
void __cdecl destroy_va01_caviardata();
void __cdecl destroy_vr_caviardata();
void __cdecl destroy_vhr_caviardata2();
void __cdecl destroy_vrc_caviardata();
void __cdecl destroy_vi_caviardata();
void __cdecl destroy_vgmt_caviardata();
void __cdecl destroy_vgmtp_caviardata();
void __cdecl destroy_unused_caviardata_var2();
void __cdecl destroy_vwntu_caviardata();
void __cdecl destroy_vt_caviardata();
void __cdecl destroy_drop_caviardata();
void __cdecl destroy_droplet_caviardata();
void __cdecl destroy_vcl_caviardata();
void __cdecl destroy_unused_caviardata_var3();
void __cdecl destroy_vclt00_caviardata();
void __cdecl destroy_vht_vbp_caviardata();
void __cdecl destroy_vhtp_caviardata();
void __cdecl destroy_vhta0_caviardata();
void __cdecl destroy_vhttp_caviardata();
void __cdecl destroy_vhttpa0_caviardata();
void __cdecl destroy_vsp_caviardata();
void __cdecl destroy_vspa0_caviardata();
void __cdecl destroy_vsptf_caviardata();
void __cdecl destroy_vsptb_caviardata();
void __cdecl destroy_vfl_caviardata();
void __cdecl destroy_vgs_caviardata();
void __cdecl destroy_vgsp_caviardata();
void __cdecl destroy_vjtp_caviardata();
void __cdecl destroy_vjt0_caviardata();
void __cdecl destroy_vcu_caviardata();
void __cdecl destroy_vcup_caviardata();
void __cdecl destroy_vcua0_caviardata();
void __cdecl destroy_vcuw_caviardata();
void __cdecl destroy_vct_caviardata();
void __cdecl destroy_vctp_caviardata();
void __cdecl destroy_vctb_caviardata();
void __cdecl destroy_vct0_caviardata();
void __cdecl destroy_vwntt_caviardata();
void __cdecl destroy_vwnst_caviardata();
void __cdecl destroy_vwnaa_caviardata();
void __cdecl destroy_vw_caviardata();
void __cdecl destroy_vm_caviardata();
void __cdecl destroy_vm13_caviardata();
void __cdecl destroy_vpbr0_caviardata();
void __cdecl destroy_unused_caviardata_var4();
void __cdecl destroy_nw_caviardata();
void __cdecl destroy_ni_caviardata();
void __cdecl destroy_nlc_caviardata();
void __cdecl destroy_unused_caviardata_var5();
void __cdecl destroy_radius1_texture();
void __cdecl destroy_radius2_texture();
void __cdecl destroy_rocky_textures();
void __cdecl destroy_ocean_textures();
void __cdecl destroy_flat_arid_land_texture();
void __cdecl destroy_moist_land_textures();
void __cdecl destroy_rainy_land_textures();
void __cdecl destroy_jungle_land_textures();
void __cdecl destroy_dune_land_texture();
void __cdecl destroy_sunny_mesa_textures();
void __cdecl destroy_rainfall_single_tile_textures();
void __cdecl destroy_road_textures();
void __cdecl destroy_magtube_textures();
void __cdecl destroy_river_textures();
void __cdecl destroy_mount_planet_textures();
void __cdecl destroy_garland_crater_textures();
void __cdecl destroy_fungus_textures();
void __cdecl destroy_farm_textures();
void __cdecl destroy_forest_textures();
void __cdecl destroy_rainfall_single_tile_texture();
void __cdecl destroy_ter1_white_org_yel_tile_sprites();
void __cdecl destroy_ter1_bottom_left_tile_sprites();
void __cdecl destroy_ter1_unused_sprites2();
void __cdecl destroy_ter1_mine_sprite();
void __cdecl destroy_ter1_solar_collector_sprite();
void __cdecl destroy_ter1_tidal_harness_sprite();
void __cdecl destroy_ter1_mining_platform_sprite();
void __cdecl destroy_ter1_tut_blank_sprite();
void __cdecl destroy_ter1_kelp_farm_sprite();
void __cdecl destroy_ter1_condenser_sprite();
void __cdecl destroy_ter1_echelon_mirror_sprite();
void __cdecl destroy_ter1_borehole_sprite();
void __cdecl destroy_ter1_borehole_cluster_sprite();
void __cdecl destroy_ter1_manifold_nexus_sprites();
void __cdecl destroy_ter1wreck_unity_wreckage_sprites();
void __cdecl destroy_ter1wreck_unity_wreckage_alt_sprites();
void __cdecl destroy_fossil_field_ridge_sprites();
void __cdecl destroy_ter1_unused_sprites1();
void __cdecl destroy_ter1_farm_sprites();
void __cdecl destroy_ter1_soil_enricher_sprites();
void __cdecl destroy_ter1_sea_land_resource_sprites();
void __cdecl destroy_ter1_landmark_resource_sprites();
void __cdecl destroy_glow_sprites();
void __cdecl destroy_ter1_unity_pod_sprites();
void __cdecl destroy_ter1_monolith_sprite();
void __cdecl destroy_ter1_bunker_sprite();
void __cdecl destroy_ter1_airbase_sprite();
void __cdecl destroy_ter1_sensor_array_sprite();
void __cdecl destroy_rainfall_double_tile_sprites();
void __cdecl destroy_veh_sprites();
void __cdecl destroy_flags_veh_sprites();
void __cdecl destroy_icons_general_sprites();
void __cdecl destroy_resource_icon_sprites();
void __cdecl destroy_citizen_lg_cursor_sprites();
void __cdecl destroy_specialist_lg_cursor_sprites();
void __cdecl destroy_citizen_sm_cursor_sprites();
void __cdecl destroy_specialist_sm_cursor_sprites();
void __cdecl destroy_al_citizen_lg_cursor_sprites();
void __cdecl destroy_al_specialist_lg_cursor_sprites();
void __cdecl destroy_al_citizen_sm_cursor_sprites();
void __cdecl destroy_al_specialist_sm_cursor_sprites();
void __cdecl destroy_red_alien_head_icon_sprite();
void __cdecl destroy_silver_menu_icon_sprites();
void __cdecl destroy_silver_checkbox_icon_sprites();
void __cdecl destroy_red_male_head_icon_sprite();
void __cdecl destroy_null_resource_icon_sprite();
void __cdecl destroy_peace_sign_sprites();
void __cdecl destroy_icon_tile_square_sprite();
void __cdecl destroy_xi_boom_veh_sprites();
void __cdecl destroy_xf_boom_veh_sprites();
void __cdecl destroy_battle_mind_worm_sprite();
void __cdecl destroy_battle_isle_deep_sprite();
void __cdecl destroy_battle_locusts_chiron_sprite();
void __cdecl destroy_battle_fungal_tower_sprite();
void __cdecl destroy_battle_spore_launcher_sprite();
void __cdecl destroy_battle_sealurk_sprite();
void __cdecl destroy_tech_icon_sprites();
void __cdecl destroy_facility_icon_sprites();
void __cdecl destroy_secret_project_icon_sprites();
void __cdecl destroy_iface_mp_combo_arrow_sprites();
void __cdecl destroy_scroll_bar_arrow_icon_sprites();
void __cdecl destroy_scroll_bar_small_arrow_icon_sprites();
void __cdecl destroy_scroll_bar_filler_icon_sprites();
void __cdecl destroy_scroll_bar_small_filler_icon_sprite();
void __cdecl destroy_iface_lock_sprites();
void __cdecl destroy_unused_sprites_var01();
void __cdecl destroy_iface_general_windows_top_left_sprite();
void __cdecl destroy_iface_general_windows_top_right_sprite();
void __cdecl destroy_iface_general_windows_bot_left_sprite();
void __cdecl destroy_iface_general_windows_bot_right_sprite();
void __cdecl destroy_iface_general_windows_mid_left_sprite();
void __cdecl destroy_iface_general_windows_mid_right_sprite();
void __cdecl destroy_iface_general_windows_top_mid_sprite();
void __cdecl destroy_iface_general_windows_bot_mid_sprite();
void __cdecl destroy_iface_general_windows_noncap_mid_sprite();
void __cdecl destroy_iface_general_windows_noncap_left_sprite();
void __cdecl destroy_iface_general_windows_noncap_right_sprite();
void __cdecl destroy_unused_sprite_var23();
void __cdecl destroy_unused_sprite_var24();
void __cdecl destroy_unused_sprite_var25();
void __cdecl destroy_unused_sprite_var26();
void __cdecl destroy_unused_sprite_var27();
void __cdecl destroy_unused_sprite_var28();
void __cdecl destroy_unused_sprite_var29();
void __cdecl destroy_unused_sprite_var30();
void __cdecl destroy_unused_sprite_var31();
void __cdecl destroy_unused_sprite_var32();
void __cdecl destroy_unused_sprite_var33();
void __cdecl destroy_unused_sprite_var34();
void __cdecl destroy_unused_sprite_var35();
void __cdecl destroy_unused_sprite_var36();
void __cdecl destroy_unused_sprite_var37();
void __cdecl destroy_unused_sprite_var38();
void __cdecl destroy_unused_sprite_var39();
void __cdecl destroy_unused_sprite_var40();
void __cdecl destroy_unused_sprite_var41();
void __cdecl destroy_unused_sprite_var42();
void __cdecl destroy_unused_sprite_var43();
void __cdecl destroy_unused_sprite_var44();
void __cdecl destroy_unused_sprite_var45();
void __cdecl destroy_unused_sprite_var46();
void __cdecl destroy_iface_tech_tree_arrow_sprites();
void __cdecl destroy_unused_sprite_var47();
void __cdecl destroy_unused_sprite_var48();
void __cdecl destroy_unused_sprite_var49();
void __cdecl destroy_unused_sprite_var50();
void __cdecl destroy_unused_sprite_var51();
void __cdecl destroy_unused_sprite_var52();
void __cdecl destroy_unused_sprite_var53();
void __cdecl destroy_unused_sprite_var54();
void __cdecl destroy_unused_sprite_var55();
void __cdecl destroy_unused_sprite_var56();
void __cdecl destroy_unused_sprite_var57();
void __cdecl destroy_unused_sprite_var58();
void __cdecl destroy_unused_sprite_var59();
void __cdecl destroy_unused_sprite_var60();
void __cdecl destroy_unused_sprite_var61();
void __cdecl destroy_unused_sprite_var62();
void __cdecl destroy_unused_sprite_var63();
void __cdecl destroy_unused_sprite_var64();
void __cdecl destroy_unused_sprite_var65();
void __cdecl destroy_unused_sprite_var66();
void __cdecl destroy_unused_sprite_var67();
void __cdecl destroy_unused_sprite_var68();
void __cdecl destroy_unused_sprite_var69();
void __cdecl destroy_unused_sprite_var70();
void __cdecl destroy_unused_sprite_var71();
void __cdecl destroy_unused_sprite_var72();
void __cdecl destroy_unused_sprite_var73();
void __cdecl destroy_unused_sprite_var74();
void __cdecl destroy_unused_sprites_var02();
void __cdecl destroy_unused_sprites_var03();
void __cdecl destroy_unused_sprites_var04();
void __cdecl destroy_unused_sprites_var05();
void __cdecl destroy_unused_sprites_var06();
void __cdecl destroy_unused_sprites_var07();
void __cdecl destroy_unused_sprites_var08();
void __cdecl destroy_unused_sprites_var09();
void __cdecl destroy_unused_sprites_var10();
void __cdecl destroy_unused_sprite_var75();
void __cdecl destroy_unused_sprite_var76();
void __cdecl destroy_unused_sprite_var77();
void __cdecl destroy_unused_sprite_var78();
void __cdecl destroy_unused_sprite_var79();
void __cdecl destroy_unused_sprite_var80();
void __cdecl destroy_unused_sprite_var81();
void __cdecl destroy_unused_sprite_var82();
void __cdecl destroy_unused_sprite_var83();
void __cdecl destroy_basewin_sprites();
void __cdecl destroy_infowin();
void __cdecl destroy_maininterface();
void __cdecl destroy_maininterface_wave();
void __cdecl destroy_jackal_font();
void __cdecl destroy_messagewin();
void __cdecl destroy_iface_green_right_arrow_sprite();
void __cdecl destroy_monuwin();
void __cdecl destroy_multiwin();
void __cdecl destroy_multiwin_wave();
void __cdecl destroy_netmsg1();
void __cdecl destroy_netmsg2();
void __cdecl destroy_netwin();
void __cdecl destroy_newtechwin();
void __cdecl destroy_pickwin();
void __cdecl destroy_prefwin();
void __cdecl destroy_prefwin_buttongroup();
void __cdecl destroy_quaylewin();
void __cdecl destroy_reportif();
void __cdecl destroy_reportwin();
void __cdecl destroy_socialwinparent();
void __cdecl destroy_statuswin();
void __cdecl destroy_tutwin();
void __cdecl destroy_vehdraw_caviar();
void __cdecl destroy_vehdraw_buffer();
void __cdecl destroy_worldwin();
void __cdecl destroy_wave_device();
void __cdecl destroy_midi_device();
void __cdecl destroy_wave_in_device();
void __cdecl destroy_console_timer();
void __cdecl destroy_cursor_sprites();
void __cdecl destroy_netdaemon();
void __cdecl destroy_fontqueue_val2();
void __cdecl destroy_fontqueue_val1();
void __cdecl destroy_top_menu_wave();
void __cdecl destroy_fonts();
void __cdecl destroy_crash_landing_wave();
void __cdecl destroy_wave_general();
void __cdecl destroy_palette1();
void __cdecl destroy_palette2();
void __cdecl destroy_multidebug();
void __cdecl destroy_buffer();
void __cdecl destroy_txtindex();
void __cdecl destroy_stringtable();
