/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

/*
 * Object-deletion thunks
 *
 * Two compiler-emitted families that only make sense together.
 *
 * `adjust_this_*` steps the receiver back from the subobject the caller
 * holds - by a fixed amount, or by the vtordisp stored immediately ahead of
 * it - and forwards to the real body with the arguments untouched. The
 * receiver arithmetic is the whole of the behaviour.
 *
 * `scalar_delete_*` is the compiler-generated scalar deleting destructor:
 * run the complete destructor, release the storage through the executable's
 * operator delete only when bit 0 of the flags asks, and always return the
 * object.
 *
 * Both take their receiver in ecx and pop their own stack argument. The
 * mangled names claim otherwise for most of the first family - do not
 * reintroduce them here.
 *
 * A forward that this file recovers is an ordinary call; a forward that is
 * source-owned elsewhere goes through the binding that already exists. Only
 * what neither covers gets a seam below, each defaulting to the original
 * address for the hybrid to redirect at run time.
 *
 * Generated by tools/generate_deleting_thunks.py - do not edit by hand.
 */

typedef void (OriginalObject::*func_deleting_dtor)();
typedef void * (OriginalObject::*func_deleting_forward)(unsigned int arg0);
typedef void * (OriginalObject::*func_deleting_forward_nullary)();

extern func_deleting_dtor AlphaMenuDtorTarget;   // 0x0051DC10
extern func_deleting_dtor AlphaMovieDtorTarget;   // 0x00404310
extern func_deleting_dtor AlphaSaveDtorTarget;   // 0x00408170
extern func_deleting_dtor BasePopDtorTarget;   // 0x004064D0
extern func_deleting_dtor BaseWinDtorTarget;   // 0x00420A70
extern func_deleting_dtor CheckButtonDtorTarget;   // 0x004B3EC0
extern func_deleting_dtor CouncWinDtorTarget;   // 0x00428550
extern func_deleting_dtor CreditsDtorTarget;   // 0x00428E90
extern func_deleting_dtor DatalinkDtorTarget;   // 0x00432290
extern func_deleting_dtor DesignWinDtorTarget;   // 0x0043ECB0
extern func_deleting_dtor DipEditDtorTarget;   // 0x004E2240
extern func_deleting_dtor DiploPopDtorTarget;   // 0x00440D50
extern func_deleting_dtor DiploWinDtorTarget;   // 0x00444DB0
extern func_deleting_dtor EditBoxDtorTarget;   // 0x00408010
extern func_deleting_dtor FameWinDtorTarget;   // 0x0044B100
extern func_deleting_dtor GammaDtorTarget;   // 0x00456110
extern func_deleting_dtor ImageButtonDtorTarget;   // 0x00625310
extern func_deleting_dtor InterludeDtorTarget;   // 0x0045F740
extern func_deleting_dtor MainInterfaceDtorTarget;   // 0x0045EB80
extern func_deleting_dtor MenuDtorTarget;   // 0x005FAD00
extern func_deleting_dtor MonuWinDtorTarget;   // 0x00477B10
extern func_deleting_dtor MultiDebugDtorTarget;   // 0x005C9E00
extern func_deleting_dtor MultiWinDtorTarget;   // 0x0047A430
extern func_deleting_dtor NetMsgDtorTarget;   // 0x0047ADA0
extern func_deleting_dtor NetWinDtorTarget;   // 0x004834E0
extern func_deleting_dtor NewTechWinDtorTarget;   // 0x00484810
extern func_deleting_dtor PickTechDtorTarget;   // 0x00488690
extern func_deleting_dtor PickWinDtorTarget;   // 0x0048A8E0
extern func_deleting_dtor PopMenuDtorTarget;   // 0x00421400
extern func_deleting_dtor PopupDtorTarget;   // 0x00406C00
extern func_deleting_dtor PrefWinDtorTarget;   // 0x00491DF0
extern func_deleting_dtor ProdPickerDtorTarget;   // 0x00421100
extern func_deleting_dtor PushButtonDtorTarget;   // 0x0062C010
extern func_deleting_dtor QuayleWinDtorTarget;   // 0x00496710
extern func_deleting_dtor ReplayWinDtorTarget;   // 0x005ADF10
extern func_deleting_dtor ReportWinDtorTarget;   // 0x004AD3B0
extern func_deleting_dtor SelectPartWinDtorTarget;   // 0x0043EE10
extern func_deleting_dtor SetupWinDtorTarget;   // 0x004AE790
extern func_deleting_dtor SocialWinDtorTarget;   // 0x004B3C80
extern func_deleting_dtor StringBoxDtorTarget;   // 0x004325C0
extern func_deleting_forward_nullary Sub004042B0Target;   // 0x004042B0
extern func_deleting_dtor Sub004C86D0Target;   // 0x004C86D0
extern func_deleting_forward Sub00612710Target;   // 0x00612710
extern func_deleting_dtor Sub00633010Target;   // 0x00633010
extern func_deleting_forward Sub006336D0Target;   // 0x006336D0
extern func_deleting_dtor TutWinDtorTarget;   // 0x004BE7D0
extern func_deleting_dtor VoiceRxDtorTarget;   // 0x004C8A50
extern func_deleting_dtor VoiceTxDtorTarget;   // 0x004C8DB0
extern func_deleting_dtor WorldWinDtorTarget;   // 0x004C4A70

void *__fastcall scalar_delete_alpha_movie(void *self, void *,
                                           unsigned int arg0);
void *__fastcall adjust_this_sub_404420(void *self, void *);
void *__fastcall adjust_this_alpha_movie(void *self, void *,
                                         unsigned int arg0);
void *__fastcall scalar_delete_flat_button(void *self, void *,
                                           unsigned int arg0);
void *__fastcall scalar_delete_base_pop(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_popup(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_base_pop(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_scroll(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_popup(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_flat_button(void *self, void *,
                                         unsigned int arg0);
void *__fastcall scalar_delete_edit_box(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_alpha_save(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_alpha_save(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_edit_box(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_prod_picker(void *self, void *,
                                           unsigned int arg0);
void *__fastcall scalar_delete_base_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_pop_menu(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_base_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_prod_picker(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_pop_menu_delete1(void *self, void *,
                                              unsigned int arg0);
void *__fastcall adjust_this_pop_menu_delete2(void *self, void *,
                                              unsigned int arg0);
void *__fastcall adjust_this_pop_menu_delete3(void *self, void *,
                                              unsigned int arg0);
void *__fastcall scalar_delete_counc_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_counc_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_credits(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_credits(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_string_box(void *self, void *,
                                          unsigned int arg0);
void *__fastcall scalar_delete_datalink(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_string_box(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_datalink(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_design_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall scalar_delete_select_part_win(void *self, void *,
                                               unsigned int arg0);
void *__fastcall adjust_this_design_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_select_part_win(void *self, void *,
                                             unsigned int arg0);
void *__fastcall scalar_delete_diplo_pop(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_diplo_pop(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_diplo_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_diplo_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_effect(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_sub_448390(void *self, void *,
                                          unsigned int arg0);
void *__fastcall scalar_delete_fame_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_fame_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_gamma(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_gamma(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_main_interface(void *self, void *,
                                              unsigned int arg0);
void *__fastcall adjust_this_main_interface(void *self, void *,
                                            unsigned int arg0);
void *__fastcall scalar_delete_interlude(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_interlude(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_monu_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_monu_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_multi_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_multi_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_net_msg(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_net_msg(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_net_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_net_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_new_tech_win(void *self, void *,
                                            unsigned int arg0);
void *__fastcall adjust_this_new_tech_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall scalar_delete_pick_tech(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_pick_tech(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_pick_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_pick_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_plan_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_pref_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_pref_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_quayle_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_quayle_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_report_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_report_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_setup_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_setup_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_check_button(void *self, void *,
                                            unsigned int arg0);
void *__fastcall scalar_delete_social_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_check_button(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_social_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_tut_win(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_tut_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_world_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_world_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_ambience(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_video(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_voice_rx(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_voice_tx(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_dip_edit(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_dip_edit(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_alpha_menu(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_alpha_menu(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_replay_win(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_replay_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_multi_debug(void *self, void *,
                                           unsigned int arg0);
void *__fastcall adjust_this_multi_debug(void *self, void *,
                                         unsigned int arg0);
void *__fastcall scalar_delete_graphic_win(void *self, void *,
                                           unsigned int arg0);
void *__fastcall adjust_this_graphic_win(void *self, void *,
                                         unsigned int arg0);
void *__fastcall scalar_delete_buffer(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_win(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_pull_down(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_pull_down(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_menu(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_menu(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_base_button(void *self, void *,
                                           unsigned int arg0);
void *__fastcall adjust_this_base_button(void *self, void *,
                                         unsigned int arg0);
void *__fastcall adjust_this_sub_612700(void *self, void *, unsigned int arg0);
void *__fastcall scalar_delete_image_button(void *self, void *,
                                            unsigned int arg0);
void *__fastcall adjust_this_image_button(void *self, void *,
                                          unsigned int arg0);
void *__fastcall scalar_delete_push_button(void *self, void *,
                                           unsigned int arg0);
void *__fastcall adjust_this_push_button(void *self, void *,
                                         unsigned int arg0);
void *__fastcall scalar_delete_sub_633160(void *self, void *,
                                          unsigned int arg0);
void *__fastcall adjust_this_sub_633730(void *self, void *, unsigned int arg0);
void *__fastcall adjust_this_sub_633740(void *self, void *, unsigned int arg0);
