/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "original_seam.h"
#include "delegation_thunks.h"

/*
 * Guarded delegation thunks - GENERATED by
 * tools/generate_delegation_thunks.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * One shape, 59 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * These are free redirects over opaque storage rather than methods. The
 * classes involved are largely unmodelled, the redirect is what gets
 * installed at the original address either way, and nothing here touches a
 * class header.
 */

/*
Purpose: ?on_key_click@AlphaMovie@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00404210 BYTE_EXACT
// name      ?on_key_click@AlphaMovie@@QAEHHH@Z
// size      16 bytes
// spans     0x00404210-0x00404220
// prototype int (__thiscall ?on_key_click@AlphaMovie@@QAEHHH@Z)(AlphaMovie* this, int, int)
// callers   0   call targets   0
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall alpha_movie_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x0041B4C0 BYTE_EXACT
// name      ?on_scrolling@BaseWin@@QAEXHH@Z
// size      23 bytes
// spans     0x0041B4C0-0x0041B4D7
// prototype void (__thiscall ?on_scrolling@BaseWin@@QAEXHH@Z)(BaseWin* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_iface_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0x4 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x0041DCB0 BYTE_EXACT
// name      ?on_iface_scrolling@BaseWin@@QAEXHH@Z
// size      20 bytes
// spans     0x0041DCB0-0x0041DCC4
// prototype void (__thiscall ?on_iface_scrolling@BaseWin@@QAEXHH@Z)(BaseWin* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_iface_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00428D60 BYTE_EXACT
// name      ?on_key_click@Credits@@QAEXHH@Z
// size      16 bytes
// spans     0x00428D60-0x00428D70
// prototype void (__thiscall ?on_key_click@Credits@@QAEXHH@Z)(Credits* this, int, int)
// callers   0   call targets   0
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall credits_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00428D70 BYTE_EXACT
// name      ?on_left_click@Credits@@QAEXHH@Z
// size      11 bytes
// spans     0x00428D70-0x00428D7B
// prototype void (__thiscall ?on_left_click@Credits@@QAEXHH@Z)(Credits* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall credits_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@SelectPartWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x00433F50 BYTE_EXACT
// name      ?on_scrolling@SelectPartWin@@QAEXHH@Z
// size      23 bytes
// spans     0x00433F50-0x00433F67
// prototype void (__thiscall ?on_scrolling@SelectPartWin@@QAEXHH@Z)(SelectPartWin* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall select_part_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_down@Interlude@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x0045F6F0 BYTE_EXACT
// name      ?on_key_down@Interlude@@QAEXH@Z
// size      16 bytes
// spans     0x0045F6F0-0x0045F700
// prototype void (__thiscall ?on_key_down@Interlude@@QAEXH@Z)(Interlude* this, int)
// callers   0   call targets   0
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall interlude_on_key_down_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_down@Interlude@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x0045F700 BYTE_EXACT
// name      ?on_left_down@Interlude@@QAEXHH@Z
// size      11 bytes
// spans     0x0045F700-0x0045F70B
// prototype void (__thiscall ?on_left_down@Interlude@@QAEXHH@Z)(Interlude* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall interlude_on_left_down_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@NewTechWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00483E80 BYTE_EXACT
// name      ?on_button_clicked@NewTechWin@@QAEXH@Z
// size      11 bytes
// spans     0x00483E80-0x00483E8B
// prototype void (__thiscall ?on_button_clicked@NewTechWin@@QAEXH@Z)(NewTechWin* this, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall new_tech_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@ProdPicker@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x00493E70 BYTE_EXACT
// name      ?on_scrolling@ProdPicker@@QAEXHH@Z
// size      23 bytes
// spans     0x00493E70-0x00493E87
// prototype void (__thiscall ?on_scrolling@ProdPicker@@QAEXHH@Z)(ProdPicker* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall prod_picker_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_codec@Wave_In_Device@@QAEHK@Z - forward 1 argument(s) to slot 0x60 of the
         object at +0x14, answering 0x13 when that object is absent.
ORIGINAL: 0x004C5A80
// name      ?set_codec@Wave_In_Device@@QAEHK@Z
// size      32 bytes
// spans     0x004C5A80-0x004C5AA0
// prototype int (__thiscall ?set_codec@Wave_In_Device@@QAEHK@Z)(Wave_In_Device* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_codec_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x60 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z - forward 1 argument(s) to slot 0x64 of the
         object at +0x14, answering 0x13 when that object is absent.
ORIGINAL: 0x004C5AA0
// name      ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z
// size      32 bytes
// spans     0x004C5AA0-0x004C5AC0
// prototype int (__thiscall ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z)(Wave_In_Device* this, int8*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x64 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play@Midi@@QAEHXZ - forward 0 argument(s) to slot 0x1c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7760
// name      ?play@Midi@@QAEHXZ
// size      18 bytes
// spans     0x004C7760-0x004C7772
// prototype int (__thiscall ?play@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x1c / sizeof(void *)])))();
}

/*
Purpose: ?set_switch_type@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x100 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C77D0
// name      ?set_switch_type@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C77D0-0x004C77F3
// prototype int (__thiscall ?set_switch_type@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_switch_type_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x100 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_switch_range@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x108 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C7800
// name      ?add_switch_range@Midi@@QAEHKK@Z
// size      39 bytes
// spans     0x004C7800-0x004C7827
// prototype int (__thiscall ?add_switch_range@Midi@@QAEHKK@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_add_switch_range_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x108 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_nswitch_threads@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x104 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C7830
// name      ?set_nswitch_threads@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C7830-0x004C7853
// prototype int (__thiscall ?set_nswitch_threads@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_nswitch_threads_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x104 / sizeof(void *)])))(a1);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADKK@Z - forward 3 argument(s) to slot 0xdc of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7860
// name      ?map_patch@Midi@@QAEHPADKK@Z
// size      43 bytes
// spans     0x004C7860-0x004C788B
// prototype int (__thiscall ?map_patch@Midi@@QAEHPADKK@Z)(Midi* this, int8*, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_3_redirect(void *self, void *, int a1, uint32_t a2, uint32_t a3) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_3>(reinterpret_cast<unsigned long>(vtable[0xdc / sizeof(void *)])))(a1, a2, a3);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADK@Z - forward 2 argument(s) to slot 0xd8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7890
// name      ?map_patch@Midi@@QAEHPADK@Z
// size      39 bytes
// spans     0x004C7890-0x004C78B7
// prototype int (__thiscall ?map_patch@Midi@@QAEHPADK@Z)(Midi* this, int8*, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_2_redirect(void *self, void *, int a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xd8 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?clear_patch@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xe0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C78E0
// name      ?clear_patch@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C78E0-0x004C7903
// prototype int (__thiscall ?clear_patch@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_clear_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?reset@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7910
// name      ?reset@Midi@@QAEHXZ
// size      21 bytes
// spans     0x004C7910-0x004C7925
// prototype int (__thiscall ?reset@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_reset_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc8 / sizeof(void *)])))();
}

/*
Purpose: ?set_track@Midi@@QAEHPAEK@Z - forward 2 argument(s) to slot 0x84 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7930
// name      ?set_track@Midi@@QAEHPAEK@Z
// size      39 bytes
// spans     0x004C7930-0x004C7957
// prototype int (__thiscall ?set_track@Midi@@QAEHPAEK@Z)(Midi* this, unsigned int8*, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x84 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?mute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7960
// name      ?mute_track@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C7960-0x004C7983
// prototype int (__thiscall ?mute_track@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_mute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?unmute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xac of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7990
// name      ?unmute_track@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C7990-0x004C79B3
// prototype int (__thiscall ?unmute_track@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unmute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xac / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C79C0
// name      ?set_active_tracks@Midi@@QAEHKK@Z
// size      39 bytes
// spans     0x004C79C0-0x004C79E7
// prototype int (__thiscall ?set_active_tracks@Midi@@QAEHKK@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_2_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C79F0
// name      ?set_active_tracks@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C79F0-0x004C7A13
// prototype int (__thiscall ?set_active_tracks@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_1_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x10c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A20
// name      ?play_trackset@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C7A20-0x004C7A43
// prototype int (__thiscall ?play_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x10c / sizeof(void *)])))(a1);
}

/*
Purpose: ?xpose_trackset@Midi@@QAEHIH@Z - forward 2 argument(s) to slot 0x114 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A50
// name      ?xpose_trackset@Midi@@QAEHIH@Z
// size      39 bytes
// spans     0x004C7A50-0x004C7A77
// prototype int (__thiscall ?xpose_trackset@Midi@@QAEHIH@Z)(Midi* this, unsigned int, int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_xpose_trackset_redirect(void *self, void *, uint32_t a1, int a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x114 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?stop_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x110 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A80
// name      ?stop_trackset@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C7A80-0x004C7AA3
// prototype int (__thiscall ?stop_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_stop_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x110 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z - forward 1 argument(s) to slot 0x98 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7AD0
// name      ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z
// size      35 bytes
// spans     0x004C7AD0-0x004C7AF3
// prototype int (__thiscall ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z)(Midi* this, TrackSet*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_add_active_trackset_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x98 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_range_lo@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B00
// name      ?set_active_range_lo@Midi@@QAEHII@Z
// size      39 bytes
// spans     0x004C7B00-0x004C7B27
// prototype int (__thiscall ?set_active_range_lo@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_lo_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_range_hi@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa4 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B30
// name      ?set_active_range_hi@Midi@@QAEHII@Z
// size      39 bytes
// spans     0x004C7B30-0x004C7B57
// prototype int (__thiscall ?set_active_range_hi@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_hi_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?remove_active_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0xa8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B60
// name      ?remove_active_trackset@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C7B60-0x004C7B83
// prototype int (__thiscall ?remove_active_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_remove_active_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xa8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x9c of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7B90
// name      ?get_trackset@Midi@@QAEHI@Z
// size      32 bytes
// spans     0x004C7B90-0x004C7BB0
// prototype int (__thiscall ?get_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x9c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_ntracks@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7BB0
// name      ?get_ntracks@Midi@@QAEHXZ
// size      18 bytes
// spans     0x004C7BB0-0x004C7BC2
// prototype int (__thiscall ?get_ntracks@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_ntracks_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc4 / sizeof(void *)])))();
}

/*
Purpose: ?load_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x120 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7BD0
// name      ?load_patch@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C7BD0-0x004C7BF3
// prototype int (__thiscall ?load_patch@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_load_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x120 / sizeof(void *)])))(a1);
}

/*
Purpose: ?unload_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x124 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7C00
// name      ?unload_patch@Midi@@QAEHI@Z
// size      35 bytes
// spans     0x004C7C00-0x004C7C23
// prototype int (__thiscall ?unload_patch@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unload_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x124 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_patch@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0x128 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7C30
// name      ?set_patch@Midi@@QAEHII@Z
// size      39 bytes
// spans     0x004C7C30-0x004C7C57
// prototype int (__thiscall ?set_patch@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_patch_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x128 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_tempo@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7D50
// name      ?set_tempo@Midi@@QAEHK@Z
// size      35 bytes
// spans     0x004C7D50-0x004C7D73
// prototype int (__thiscall ?set_tempo@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_tempo_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_time@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xd4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7E80
// name      ?get_time@Midi@@QAEHK@Z
// size      32 bytes
// spans     0x004C7E80-0x004C7EA0
// prototype int (__thiscall ?get_time@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_time_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xd4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_control_track@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xf4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7EA0
// name      ?get_control_track@Midi@@QAEHXZ
// size      18 bytes
// spans     0x004C7EA0-0x004C7EB2
// prototype int (__thiscall ?get_control_track@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_control_track_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf4 / sizeof(void *)])))();
}

/*
Purpose: ?get_total_track_ticks@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xf8 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7EC0
// name      ?get_total_track_ticks@Midi@@QAEHK@Z
// size      32 bytes
// spans     0x004C7EC0-0x004C7EE0
// prototype int (__thiscall ?get_total_track_ticks@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_total_track_ticks_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z - forward 1 argument(s) to slot 0xe4 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7EE0
// name      ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z
// size      35 bytes
// spans     0x004C7EE0-0x004C7F03
// prototype int (__thiscall ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z)(Midi* this, ChannelCtrl*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_channel_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z - forward 1 argument(s) to slot 0xe8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7F10
// name      ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z
// size      35 bytes
// spans     0x004C7F10-0x004C7F33
// prototype int (__thiscall ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z)(Midi* this, ProgramCtrl*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_program_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z - forward 1 argument(s) to slot 0xc0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7F40
// name      ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z
// size      35 bytes
// spans     0x004C7F40-0x004C7F63
// prototype int (__thiscall ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z)(Midi* this, TrackCtrl*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?start@VoiceRx@@QAEHXZ - dispatch to slot 0x88 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8C20 BYTE_EXACT
// name      ?start@VoiceRx@@QAEHXZ
// size      18 bytes
// spans     0x004C8C20-0x004C8C32
// prototype int (__thiscall ?start@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_start_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?stop@VoiceRx@@QAEHXZ - dispatch to slot 0x20 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8C40 BYTE_EXACT
// name      ?stop@VoiceRx@@QAEHXZ
// size      15 bytes
// spans     0x004C8C40-0x004C8C4F
// prototype int (__thiscall ?stop@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_stop_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x20 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?unload@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x14 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C8C50
// name      ?unload@VoiceRx@@QAEHXZ
// size      18 bytes
// spans     0x004C8C50-0x004C8C62
// prototype int (__thiscall ?unload@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_unload_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x14 / sizeof(void *)])))();
}

/*
Purpose: ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C8C70
// name      ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z
// size      35 bytes
// spans     0x004C8C70-0x004C8C93
// prototype int (__thiscall ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z)(VoiceRx* this, _MMIOINFO*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_add_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_buffer_size@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C8CA0
// name      ?get_buffer_size@VoiceRx@@QAEHXZ
// size      18 bytes
// spans     0x004C8CA0-0x004C8CB2
// prototype int (__thiscall ?get_buffer_size@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))();
}

/*
Purpose: ?release@VoiceTx@@QAEXXZ - dispatch to slot 0x38 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8EA0 BYTE_EXACT
// name      ?release@VoiceTx@@QAEXXZ
// size      15 bytes
// spans     0x004C8EA0-0x004C8EAF
// prototype void (__thiscall ?release@VoiceTx@@QAEXXZ)(VoiceTx* this)
// callers   0   call targets   0
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_tx_release_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x38 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?get_nbuffers@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C9010
// name      ?get_nbuffers@VoiceTx@@QAEHXZ
// size      18 bytes
// spans     0x004C9010-0x004C9022
// prototype int (__thiscall ?get_nbuffers@VoiceTx@@QAEHXZ)(VoiceTx* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))();
}

/*
Purpose: ?get_next_buffer@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C9030
// name      ?get_next_buffer@VoiceTx@@QAEHXZ
// size      18 bytes
// spans     0x004C9030-0x004C9042
// prototype int (__thiscall ?get_next_buffer@VoiceTx@@QAEHXZ)(VoiceTx* this)
// callers   0   call targets   0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
}

/*
Purpose: ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C9050
// name      ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z
// size      35 bytes
// spans     0x004C9050-0x004C9073
// prototype int (__thiscall ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z)(VoiceTx* this, _MMIOINFO*)
// callers   0   call targets   0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_tx_return_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?on_left_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD3B0 BYTE_EXACT
// name      ?on_left_click@ReplayWin@@QAEXHH@Z
// size      11 bytes
// spans     0x005AD3B0-0x005AD3BB
// prototype void (__thiscall ?on_left_click@ReplayWin@@QAEXHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_right_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD3C0 BYTE_EXACT
// name      ?on_right_click@ReplayWin@@QAEXHH@Z
// size      11 bytes
// spans     0x005AD3C0-0x005AD3CB
// prototype void (__thiscall ?on_right_click@ReplayWin@@QAEXHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_right_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@ReplayWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD430 BYTE_EXACT
// name      ?on_button_clicked@ReplayWin@@QAEXH@Z
// size      11 bytes
// spans     0x005AD430-0x005AD43B
// prototype void (__thiscall ?on_button_clicked@ReplayWin@@QAEXH@Z)(ReplayWin* this, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_key_click@ReplayWin@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD440 BYTE_EXACT
// name      ?on_key_click@ReplayWin@@QAEHHH@Z
// size      16 bytes
// spans     0x005AD440-0x005AD450
// prototype int (__thiscall ?on_key_click@ReplayWin@@QAEHHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall replay_win_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@Gamma@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x005C93A0 BYTE_EXACT
// name      ?on_scrolling@Gamma@@QAEXHH@Z
// size      23 bytes
// spans     0x005C93A0-0x005C93B7
// prototype void (__thiscall ?on_scrolling@Gamma@@QAEXHH@Z)(Gamma* this, int, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall gamma_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_dialog_focus@BaseButton@@QAEXH@Z - dispatch to slot 0xf8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00607B00 BYTE_EXACT
// name      ?on_dialog_focus@BaseButton@@QAEXH@Z
// size      11 bytes
// spans     0x00607B00-0x00607B0B
// prototype void (__thiscall ?on_dialog_focus@BaseButton@@QAEXH@Z)(BaseButton* this, int)
// callers   0   call targets   0
Return Value: n/a
Status: Complete
*/
void __fastcall base_button_on_dialog_focus_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))();
}
