/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/*
 * Guarded delegation thunks - GENERATED by
 * tools/generate_delegation_thunks.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * One shape, 34 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * These are free redirects over opaque storage rather than methods. The
 * classes involved are largely unmodelled, the redirect is what gets
 * installed at the original address either way, and nothing here touches a
 * class header.
 */

#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"
#endif
// The delegate is entered on the MEMBER, not on the thunk's
// own object, so every one of these is __thiscall with the
// member as its receiver.
typedef int(__thiscall func_delegation_0)(void *);
typedef int(__thiscall func_delegation_1)(void *, int);
typedef int(__thiscall func_delegation_2)(void *, int, int);
typedef int(__thiscall func_delegation_3)(void *, int, int, int);
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif

int __fastcall wave_in_device_set_codec_redirect(void *self, void *, int a1);
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1);
int __fastcall midi_play_redirect(void *self, void *);
int __fastcall midi_set_switch_type_redirect(void *self, void *, int a1);
int __fastcall midi_add_switch_range_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_set_nswitch_threads_redirect(void *self, void *, int a1);
int __fastcall midi_map_patch_3_redirect(void *self, void *, int a1, int a2, int a3);
int __fastcall midi_map_patch_2_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_clear_patch_redirect(void *self, void *, int a1);
int __fastcall midi_reset_redirect(void *self, void *);
int __fastcall midi_set_track_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_mute_track_redirect(void *self, void *, int a1);
int __fastcall midi_unmute_track_redirect(void *self, void *, int a1);
int __fastcall midi_set_active_tracks_2_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_set_active_tracks_1_redirect(void *self, void *, int a1);
int __fastcall midi_play_trackset_redirect(void *self, void *, int a1);
int __fastcall midi_xpose_trackset_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_stop_trackset_redirect(void *self, void *, int a1);
int __fastcall midi_set_active_range_lo_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_set_active_range_hi_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_remove_active_trackset_redirect(void *self, void *, int a1);
int __fastcall midi_get_trackset_redirect(void *self, void *, int a1);
int __fastcall midi_get_ntracks_redirect(void *self, void *);
int __fastcall midi_load_patch_redirect(void *self, void *, int a1);
int __fastcall midi_unload_patch_redirect(void *self, void *, int a1);
int __fastcall midi_set_patch_redirect(void *self, void *, int a1, int a2);
int __fastcall midi_set_tempo_redirect(void *self, void *, int a1);
int __fastcall midi_get_time_redirect(void *self, void *, int a1);
int __fastcall midi_get_control_track_redirect(void *self, void *);
int __fastcall midi_get_total_track_ticks_redirect(void *self, void *, int a1);
int __fastcall voice_rx_unload_redirect(void *self, void *);
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *);
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *);
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *);
