/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "original_seam.h"
#include "delegation_thunks.h"

/*
 * Guarded delegation thunks - GENERATED by
 * tools/generate_delegation_thunks.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * One shape, 59 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * These are free redirects over opaque storage rather than methods. The
 * classes involved are largely unmodelled, the redirect is what gets
 * installed at the original address either way, and nothing here touches a
 * class header.
 */

/*
Purpose: ?on_key_click@AlphaMovie@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00404210
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall alpha_movie_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x0041B4C0
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_iface_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0x4 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x0041DCB0
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_iface_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00428D60
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall credits_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00428D70
Return Value: n/a
Status: Complete
*/
void __fastcall credits_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@SelectPartWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x00433F50
Return Value: n/a
Status: Complete
*/
void __fastcall select_part_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_down@Interlude@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x0045F6F0
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall interlude_on_key_down_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_down@Interlude@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x0045F700
Return Value: n/a
Status: Complete
*/
void __fastcall interlude_on_left_down_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@NewTechWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00483E80
Return Value: n/a
Status: Complete
*/
void __fastcall new_tech_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@ProdPicker@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x00493E70
Return Value: n/a
Status: Complete
*/
void __fastcall prod_picker_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_codec@Wave_In_Device@@QAEHK@Z - forward 1 argument(s) to slot 0x60 of the
         object at +0x14, answering 0x13 when that object is absent.
ORIGINAL: 0x004C5A80
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_codec_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x60 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z - forward 1 argument(s) to slot 0x64 of the
         object at +0x14, answering 0x13 when that object is absent.
ORIGINAL: 0x004C5AA0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x64 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play@Midi@@QAEHXZ - forward 0 argument(s) to slot 0x1c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7760
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x1c / sizeof(void *)])))();
}

/*
Purpose: ?set_switch_type@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x100 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C77D0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_switch_type_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x100 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_switch_range@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x108 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C7800
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_add_switch_range_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x108 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_nswitch_threads@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x104 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C7830
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_nswitch_threads_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x104 / sizeof(void *)])))(a1);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADKK@Z - forward 3 argument(s) to slot 0xdc of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7860
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_3_redirect(void *self, void *, int a1, uint32_t a2, uint32_t a3) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_3>(reinterpret_cast<unsigned long>(vtable[0xdc / sizeof(void *)])))(a1, a2, a3);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADK@Z - forward 2 argument(s) to slot 0xd8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7890
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_2_redirect(void *self, void *, int a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xd8 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?clear_patch@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xe0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C78E0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_clear_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?reset@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7910
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_reset_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc8 / sizeof(void *)])))();
}

/*
Purpose: ?set_track@Midi@@QAEHPAEK@Z - forward 2 argument(s) to slot 0x84 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7930
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x84 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?mute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7960
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_mute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?unmute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xac of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7990
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unmute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xac / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C79C0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_2_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C79F0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_1_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x10c of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A20
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x10c / sizeof(void *)])))(a1);
}

/*
Purpose: ?xpose_trackset@Midi@@QAEHIH@Z - forward 2 argument(s) to slot 0x114 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A50
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_xpose_trackset_redirect(void *self, void *, uint32_t a1, int a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x114 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?stop_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x110 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7A80
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_stop_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x110 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z - forward 1 argument(s) to slot 0x98 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7AD0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_add_active_trackset_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x98 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_range_lo@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B00
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_lo_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_range_hi@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa4 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B30
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_hi_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?remove_active_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0xa8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7B60
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_remove_active_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xa8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x9c of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7B90
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x9c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_ntracks@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7BB0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_ntracks_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc4 / sizeof(void *)])))();
}

/*
Purpose: ?load_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x120 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7BD0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_load_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x120 / sizeof(void *)])))(a1);
}

/*
Purpose: ?unload_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x124 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7C00
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unload_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x124 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_patch@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0x128 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7C30
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_patch_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x128 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_tempo@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7D50
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_tempo_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_time@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xd4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7E80
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_time_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xd4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_control_track@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xf4 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7EA0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_control_track_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf4 / sizeof(void *)])))();
}

/*
Purpose: ?get_total_track_ticks@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xf8 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C7EC0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_total_track_ticks_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z - forward 1 argument(s) to slot 0xe4 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7EE0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_channel_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z - forward 1 argument(s) to slot 0xe8 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7F10
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_program_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z - forward 1 argument(s) to slot 0xc0 of the
         object at +0x3c, answering 0x14 when that object is absent.
ORIGINAL: 0x004C7F40
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?start@VoiceRx@@QAEHXZ - dispatch to slot 0x88 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8C20
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_start_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?stop@VoiceRx@@QAEHXZ - dispatch to slot 0x20 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8C40
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_stop_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x20 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?unload@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x14 of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C8C50
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_unload_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x14 / sizeof(void *)])))();
}

/*
Purpose: ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C8C70
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_add_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_buffer_size@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C8CA0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))();
}

/*
Purpose: ?release@VoiceTx@@QAEXXZ - dispatch to slot 0x38 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
ORIGINAL: 0x004C8EA0
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_tx_release_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x38 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?get_nbuffers@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C9010
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))();
}

/*
Purpose: ?get_next_buffer@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x0 when that object is absent.
ORIGINAL: 0x004C9030
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
}

/*
Purpose: ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
ORIGINAL: 0x004C9050
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_tx_return_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?on_left_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD3B0
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_right_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD3C0
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_right_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@ReplayWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD430
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_key_click@ReplayWin@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x005AD440
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall replay_win_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@Gamma@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
ORIGINAL: 0x005C93A0
Return Value: n/a
Status: Complete
*/
void __fastcall gamma_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_dialog_focus@BaseButton@@QAEXH@Z - dispatch to slot 0xf8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
ORIGINAL: 0x00607B00
Return Value: n/a
Status: Complete
*/
void __fastcall base_button_on_dialog_focus_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))();
}
