/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

/*
 * Guarded delegation thunks - was generated by
 * tools/generate_delegation_thunks.py, WHICH NO LONGER EXISTS: commit 271114cf retired
 * eleven bulk generators as "9,262 lines that nobody could run". EDIT THIS
 * FILE DIRECTLY. The old instruction to edit the generator instead survived
 * the generator by months and told every reader not to touch this file in the
 * only way it can now be touched.
 *
 * One shape, 59 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * Most rows are free redirects over opaque storage rather than methods;
 * the classes involved there are still unmodelled. The 32 Midi rows became
 * real `Midi::` methods on 2026-08-23 - their delegate is modelled as
 * `MidiDelegate` in midi.h with virtuals at the image's own
 * slot order - so this header declares none of them any more.
 */

// The delegate is entered on the MEMBER, not on the thunk's
// own object, so every one of these is __thiscall with the
// member as its receiver.
typedef int (OriginalObject::*func_delegation_0)();
typedef int (OriginalObject::*func_delegation_1)(int);
typedef int (OriginalObject::*func_delegation_2)(int, int);
typedef int (OriginalObject::*func_delegation_3)(int, int, int);

int __fastcall alpha_movie_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall base_win_on_scrolling_redirect(void *self, void *, int a1, int a2);
void __fastcall base_win_on_iface_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall credits_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall credits_on_left_click_redirect(void *self, void *, int a1, int a2);
void __fastcall select_part_win_on_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall interlude_on_key_down_redirect(void *self, void *, int a1);
void __fastcall interlude_on_left_down_redirect(void *self, void *, int a1, int a2);
void __fastcall new_tech_win_on_button_clicked_redirect(void *self, void *, int a1);
void __fastcall prod_picker_on_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall wave_in_device_set_codec_redirect(void *self, void *, uint32_t a1);
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1);
int __fastcall voice_rx_start_redirect(void *self, void *);
int __fastcall voice_rx_stop_redirect(void *self, void *);
int __fastcall voice_rx_unload_redirect(void *self, void *);
int __fastcall voice_rx_add_buffer_redirect(void *self, void *, int a1);
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *);
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *);
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *);
int __fastcall voice_tx_return_buffer_redirect(void *self, void *, int a1);
void __fastcall replay_win_on_left_click_redirect(void *self, void *, int a1, int a2);
void __fastcall replay_win_on_right_click_redirect(void *self, void *, int a1, int a2);
void __fastcall replay_win_on_button_clicked_redirect(void *self, void *, int a1);
int __fastcall replay_win_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall gamma_on_scrolling_redirect(void *self, void *, int a1, int a2);
void __fastcall base_button_on_dialog_focus_redirect(void *self, void *, int a1);
