/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "original_seam.h"

/*
 * Guarded delegation thunks - GENERATED by
 * tools/generate_delegation_thunks.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * One shape, 59 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * These are free redirects over opaque storage rather than methods. The
 * classes involved are largely unmodelled, the redirect is what gets
 * installed at the original address either way, and nothing here touches a
 * class header.
 */

// The delegate is entered on the MEMBER, not on the thunk's
// own object, so every one of these is __thiscall with the
// member as its receiver.
typedef int (OriginalObject::*func_delegation_0)();
typedef int (OriginalObject::*func_delegation_1)(int);
typedef int (OriginalObject::*func_delegation_2)(int, int);
typedef int (OriginalObject::*func_delegation_3)(int, int, int);

int __fastcall alpha_movie_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall base_win_on_scrolling_redirect(void *self, void *, int a1, int a2);
void __fastcall base_win_on_iface_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall credits_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall credits_on_left_click_redirect(void *self, void *, int a1, int a2);
void __fastcall select_part_win_on_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall interlude_on_key_down_redirect(void *self, void *, int a1);
void __fastcall interlude_on_left_down_redirect(void *self, void *, int a1, int a2);
void __fastcall new_tech_win_on_button_clicked_redirect(void *self, void *, int a1);
void __fastcall prod_picker_on_scrolling_redirect(void *self, void *, int a1, int a2);
int __fastcall wave_in_device_set_codec_redirect(void *self, void *, uint32_t a1);
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1);
int __fastcall midi_play_redirect(void *self, void *);
int __fastcall midi_set_switch_type_redirect(void *self, void *, uint32_t a1);
// The seven midi_* declarations below take uint32_t where this file's
// generator would emit a generic `int`. The definitions in
// delegation_thunks.cpp already use uint32_t and are right to: the
// originals they stand in for mangle as ...@@QAEHII@Z, two UNSIGNED
// arguments. The header was the half that had not been corrected, so
// caller and definition emitted different symbols and the DLL did not
// link. tools/generate_delegation_thunks.py still emits `int` for both,
// so regenerating this file reintroduces the mismatch.
int __fastcall midi_add_switch_range_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_set_nswitch_threads_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_map_patch_3_redirect(void *self, void *, int a1, uint32_t a2, uint32_t a3);
int __fastcall midi_map_patch_2_redirect(void *self, void *, int a1, uint32_t a2);
int __fastcall midi_clear_patch_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_reset_redirect(void *self, void *);
int __fastcall midi_set_track_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_mute_track_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_unmute_track_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_set_active_tracks_2_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_set_active_tracks_1_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_play_trackset_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_xpose_trackset_redirect(void *self, void *, uint32_t a1, int a2);
int __fastcall midi_stop_trackset_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_add_active_trackset_redirect(void *self, void *, int a1);
int __fastcall midi_set_active_range_lo_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_set_active_range_hi_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_remove_active_trackset_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_get_trackset_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_get_ntracks_redirect(void *self, void *);
int __fastcall midi_load_patch_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_unload_patch_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_set_patch_redirect(void *self, void *, uint32_t a1, uint32_t a2);
int __fastcall midi_set_tempo_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_get_time_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_get_control_track_redirect(void *self, void *);
int __fastcall midi_get_total_track_ticks_redirect(void *self, void *, uint32_t a1);
int __fastcall midi_set_channel_ctrl_redirect(void *self, void *, int a1);
int __fastcall midi_set_program_ctrl_redirect(void *self, void *, int a1);
int __fastcall midi_set_track_ctrl_redirect(void *self, void *, int a1);
int __fastcall voice_rx_start_redirect(void *self, void *);
int __fastcall voice_rx_stop_redirect(void *self, void *);
int __fastcall voice_rx_unload_redirect(void *self, void *);
int __fastcall voice_rx_add_buffer_redirect(void *self, void *, int a1);
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *);
int __fastcall voice_tx_release_redirect(void *self, void *);
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *);
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *);
int __fastcall voice_tx_return_buffer_redirect(void *self, void *, int a1);
void __fastcall replay_win_on_left_click_redirect(void *self, void *, int a1, int a2);
void __fastcall replay_win_on_right_click_redirect(void *self, void *, int a1, int a2);
void __fastcall replay_win_on_button_clicked_redirect(void *self, void *, int a1);
int __fastcall replay_win_on_key_click_redirect(void *self, void *, int a1, int a2);
void __fastcall gamma_on_scrolling_redirect(void *self, void *, int a1, int a2);
void __fastcall base_button_on_dialog_focus_redirect(void *self, void *, int a1);
