/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "original_seam.h"
#include "delegation_thunks.h"

/*
 * Guarded delegation thunks - was generated by
 * tools/generate_delegation_thunks.py, WHICH NO LONGER EXISTS: commit 271114cf retired
 * eleven bulk generators as "9,262 lines that nobody could run". EDIT THIS
 * FILE DIRECTLY. The old instruction to edit the generator instead survived
 * the generator by months and told every reader not to touch this file in the
 * only way it can now be touched.
 *
 * One shape, 59 times over: read a member object pointer, answer a constant
 * when it is absent, otherwise forward the arguments through a slot of that
 * member's OWN vtable. The four numbers that differ per function - the member
 * offset, the slot, the forwarded argument count and the absent-member
 * constant - are read from the bytes of each function and are kept as inline
 * literals here so a mutation sweep has something to perturb.
 *
 * These are free redirects over opaque storage rather than methods. The
 * classes involved are largely unmodelled, the redirect is what gets
 * installed at the original address either way, and nothing here touches a
 * class header.
 */

/*
Purpose: ?on_key_click@AlphaMovie@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x00404210 ?on_key_click@AlphaMovie@@QAEHHH@Z 0x00404210-0x00404220 BYTE_EXACT
// symbol    ?alpha_movie_on_key_click_redirect@@YIHPAX0HH@Z
// size      16 bytes
// prototype int (__thiscall ?on_key_click@AlphaMovie@@QAEHHH@Z)(AlphaMovie* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00404212
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall alpha_movie_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
// ORIGINAL: 0x0041B4C0 ?on_scrolling@BaseWin@@QAEXHH@Z 0x0041B4C0-0x0041B4D7 BYTE_EXACT
// symbol    ?base_win_on_scrolling_redirect@@YIXPAX0HH@Z
// size      23 bytes
// prototype void (__thiscall ?on_scrolling@BaseWin@@QAEXHH@Z)(BaseWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;sp_ready;purged_ok
// calls     (none)
// indirect  0x0041B4CD
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_iface_scrolling@BaseWin@@QAEXHH@Z - dispatch to slot 0x4 of this object's OWN
         vtable, forwarding 2 argument(s).
// ORIGINAL: 0x0041DCB0 ?on_iface_scrolling@BaseWin@@QAEXHH@Z 0x0041DCB0-0x0041DCC4 BYTE_EXACT
// symbol    ?base_win_on_iface_scrolling_redirect@@YIXPAX0HH@Z
// size      20 bytes
// prototype void (__thiscall ?on_iface_scrolling@BaseWin@@QAEXHH@Z)(BaseWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x0041DCBD
Return Value: n/a
Status: Complete
*/
void __fastcall base_win_on_iface_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x00428D60 ?on_key_click@Credits@@QAEXHH@Z 0x00428D60-0x00428D70 BYTE_EXACT
// symbol    ?credits_on_key_click_redirect@@YIHPAX0HH@Z
// size      16 bytes
// prototype void (__thiscall ?on_key_click@Credits@@QAEXHH@Z)(Credits* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00428D62
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall credits_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_click@Credits@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x00428D70 ?on_left_click@Credits@@QAEXHH@Z 0x00428D70-0x00428D7B BYTE_EXACT
// symbol    ?credits_on_left_click_redirect@@YIXPAX0HH@Z
// size      11 bytes
// prototype void (__thiscall ?on_left_click@Credits@@QAEXHH@Z)(Credits* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00428D72
Return Value: n/a
Status: Complete
*/
void __fastcall credits_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@SelectPartWin@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
// ORIGINAL: 0x00433F50 ?on_scrolling@SelectPartWin@@QAEXHH@Z 0x00433F50-0x00433F67 BYTE_EXACT
// symbol    ?select_part_win_on_scrolling_redirect@@YIXPAX0HH@Z
// size      23 bytes
// prototype void (__thiscall ?on_scrolling@SelectPartWin@@QAEXHH@Z)(SelectPartWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00433F5D
Return Value: n/a
Status: Complete
*/
void __fastcall select_part_win_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_key_down@Interlude@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x0045F6F0 ?on_key_down@Interlude@@QAEXH@Z 0x0045F6F0-0x0045F700 BYTE_EXACT
// symbol    ?interlude_on_key_down_redirect@@YIHPAX0H@Z
// size      16 bytes
// prototype void (__thiscall ?on_key_down@Interlude@@QAEXH@Z)(Interlude* this, int)
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
// indirect  0x0045F6F2
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall interlude_on_key_down_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_left_down@Interlude@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x0045F700 ?on_left_down@Interlude@@QAEXHH@Z 0x0045F700-0x0045F70B BYTE_EXACT
// symbol    ?interlude_on_left_down_redirect@@YIXPAX0HH@Z
// size      11 bytes
// prototype void (__thiscall ?on_left_down@Interlude@@QAEXHH@Z)(Interlude* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x0045F702
Return Value: n/a
Status: Complete
*/
void __fastcall interlude_on_left_down_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@NewTechWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x00483E80 ?on_button_clicked@NewTechWin@@QAEXH@Z 0x00483E80-0x00483E8B BYTE_EXACT
// symbol    ?new_tech_win_on_button_clicked_redirect@@YIXPAX0H@Z
// size      11 bytes
// prototype void (__thiscall ?on_button_clicked@NewTechWin@@QAEXH@Z)(NewTechWin* this, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00483E82
Return Value: n/a
Status: Complete
*/
void __fastcall new_tech_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_scrolling@ProdPicker@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
// ORIGINAL: 0x00493E70 ?on_scrolling@ProdPicker@@QAEXHH@Z 0x00493E70-0x00493E87 BYTE_EXACT
// symbol    ?prod_picker_on_scrolling_redirect@@YIXPAX0HH@Z
// size      23 bytes
// prototype void (__thiscall ?on_scrolling@ProdPicker@@QAEXHH@Z)(ProdPicker* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;sp_ready;purged_ok
// calls     (none)
// indirect  0x00493E7D
Return Value: n/a
Status: Complete
*/
void __fastcall prod_picker_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_codec@Wave_In_Device@@QAEHK@Z - forward 1 argument(s) to slot 0x60 of the
         object at +0x14, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C5A80 ?set_codec@Wave_In_Device@@QAEHK@Z 0x004C5A80-0x004C5AA0
// symbol    ?wave_in_device_set_codec_redirect@@YIHPAX0I@Z
// size      32 bytes
// prototype int (__thiscall ?set_codec@Wave_In_Device@@QAEHK@Z)(Wave_In_Device* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C5A90
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_codec_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x60 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z - forward 1 argument(s) to slot 0x64 of the
         object at +0x14, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C5AA0 ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z 0x004C5AA0-0x004C5AC0
// symbol    ?wave_in_device_set_vxw_key_redirect@@YIHPAX0H@Z
// size      32 bytes
// prototype int (__thiscall ?set_vxw_key@Wave_In_Device@@QAEHPAC@Z)(Wave_In_Device* this, int8*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C5AB0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall wave_in_device_set_vxw_key_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x14);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x64 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play@Midi@@QAEHXZ - forward 0 argument(s) to slot 0x1c of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7760 ?play@Midi@@QAEHXZ 0x004C7760-0x004C7772
// symbol    ?midi_play_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?play@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x1c / sizeof(void *)])))();
}

/*
Purpose: ?set_switch_type@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x100 of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C77D0 ?set_switch_type@Midi@@QAEHK@Z 0x004C77D0-0x004C77F3
// symbol    ?midi_set_switch_type_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?set_switch_type@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C77E0
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_switch_type_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x100 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_switch_range@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x108 of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C7800 ?add_switch_range@Midi@@QAEHKK@Z 0x004C7800-0x004C7827
// symbol    ?midi_add_switch_range_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?add_switch_range@Midi@@QAEHKK@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7814
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_add_switch_range_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x108 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_nswitch_threads@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x104 of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C7830 ?set_nswitch_threads@Midi@@QAEHK@Z 0x004C7830-0x004C7853
// symbol    ?midi_set_nswitch_threads_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?set_nswitch_threads@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7840
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall midi_set_nswitch_threads_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x104 / sizeof(void *)])))(a1);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADKK@Z - forward 3 argument(s) to slot 0xdc of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7860 ?map_patch@Midi@@QAEHPADKK@Z 0x004C7860-0x004C788B
// symbol    ?midi_map_patch_3_redirect@@YIHPAX0HII@Z
// size      43 bytes
// prototype int (__thiscall ?map_patch@Midi@@QAEHPADKK@Z)(Midi* this, int8*, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7878
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_3_redirect(void *self, void *, int a1, uint32_t a2, uint32_t a3) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_3>(reinterpret_cast<unsigned long>(vtable[0xdc / sizeof(void *)])))(a1, a2, a3);
}

/*
Purpose: ?map_patch@Midi@@QAEHPADK@Z - forward 2 argument(s) to slot 0xd8 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7890 ?map_patch@Midi@@QAEHPADK@Z 0x004C7890-0x004C78B7
// symbol    ?midi_map_patch_2_redirect@@YIHPAX0HI@Z
// size      39 bytes
// prototype int (__thiscall ?map_patch@Midi@@QAEHPADK@Z)(Midi* this, int8*, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C78A4
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_map_patch_2_redirect(void *self, void *, int a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xd8 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?clear_patch@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xe0 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C78E0 ?clear_patch@Midi@@QAEHK@Z 0x004C78E0-0x004C7903
// symbol    ?midi_clear_patch_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?clear_patch@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C78F0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_clear_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?reset@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc8 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7910 ?reset@Midi@@QAEHXZ 0x004C7910-0x004C7925
// symbol    ?midi_reset_redirect@@YIHPAX0@Z
// size      21 bytes
// prototype int (__thiscall ?reset@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_reset_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc8 / sizeof(void *)])))();
}

/*
Purpose: ?set_track@Midi@@QAEHPAEK@Z - forward 2 argument(s) to slot 0x84 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7930 ?set_track@Midi@@QAEHPAEK@Z 0x004C7930-0x004C7957
// symbol    ?midi_set_track_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?set_track@Midi@@QAEHPAEK@Z)(Midi* this, unsigned int8*, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7944
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x84 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?mute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7960 ?mute_track@Midi@@QAEHK@Z 0x004C7960-0x004C7983
// symbol    ?midi_mute_track_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?mute_track@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7970
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_mute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?unmute_track@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xac of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7990 ?unmute_track@Midi@@QAEHK@Z 0x004C7990-0x004C79B3
// symbol    ?midi_unmute_track_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?unmute_track@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C79A0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unmute_track_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xac / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHKK@Z - forward 2 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C79C0 ?set_active_tracks@Midi@@QAEHKK@Z 0x004C79C0-0x004C79E7
// symbol    ?midi_set_active_tracks_2_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?set_active_tracks@Midi@@QAEHKK@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C79D4
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_2_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_tracks@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C79F0 ?set_active_tracks@Midi@@QAEHI@Z 0x004C79F0-0x004C7A13
// symbol    ?midi_set_active_tracks_1_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?set_active_tracks@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7A00
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_tracks_1_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))(a1);
}

/*
Purpose: ?play_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x10c of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7A20 ?play_trackset@Midi@@QAEHI@Z 0x004C7A20-0x004C7A43
// symbol    ?midi_play_trackset_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?play_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7A30
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_play_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x10c / sizeof(void *)])))(a1);
}

/*
Purpose: ?xpose_trackset@Midi@@QAEHIH@Z - forward 2 argument(s) to slot 0x114 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7A50 ?xpose_trackset@Midi@@QAEHIH@Z 0x004C7A50-0x004C7A77
// symbol    ?midi_xpose_trackset_redirect@@YIHPAX0IH@Z
// size      39 bytes
// prototype int (__thiscall ?xpose_trackset@Midi@@QAEHIH@Z)(Midi* this, unsigned int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7A64
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_xpose_trackset_redirect(void *self, void *, uint32_t a1, int a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x114 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?stop_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x110 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7A80 ?stop_trackset@Midi@@QAEHI@Z 0x004C7A80-0x004C7AA3
// symbol    ?midi_stop_trackset_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?stop_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7A90
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_stop_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x110 / sizeof(void *)])))(a1);
}

/*
Purpose: ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z - forward 1 argument(s) to slot 0x98 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7AD0 ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z 0x004C7AD0-0x004C7AF3
// symbol    ?midi_add_active_trackset_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?add_active_trackset@Midi@@QAEHPAUTrackSet@@@Z)(Midi* this, TrackSet*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7AE0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_add_active_trackset_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x98 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_active_range_lo@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa0 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7B00 ?set_active_range_lo@Midi@@QAEHII@Z 0x004C7B00-0x004C7B27
// symbol    ?midi_set_active_range_lo_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?set_active_range_lo@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7B14
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_lo_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_active_range_hi@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0xa4 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7B30 ?set_active_range_hi@Midi@@QAEHII@Z 0x004C7B30-0x004C7B57
// symbol    ?midi_set_active_range_hi_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?set_active_range_hi@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7B44
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_active_range_hi_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xa4 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?remove_active_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0xa8 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7B60 ?remove_active_trackset@Midi@@QAEHI@Z 0x004C7B60-0x004C7B83
// symbol    ?midi_remove_active_trackset_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?remove_active_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7B70
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_remove_active_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xa8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_trackset@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x9c of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C7B90 ?get_trackset@Midi@@QAEHI@Z 0x004C7B90-0x004C7BB0
// symbol    ?midi_get_trackset_redirect@@YIHPAX0I@Z
// size      32 bytes
// prototype int (__thiscall ?get_trackset@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7BA0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_trackset_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x9c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_ntracks@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xc4 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C7BB0 ?get_ntracks@Midi@@QAEHXZ 0x004C7BB0-0x004C7BC2
// symbol    ?midi_get_ntracks_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?get_ntracks@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_ntracks_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xc4 / sizeof(void *)])))();
}

/*
Purpose: ?load_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x120 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7BD0 ?load_patch@Midi@@QAEHI@Z 0x004C7BD0-0x004C7BF3
// symbol    ?midi_load_patch_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?load_patch@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7BE0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_load_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x120 / sizeof(void *)])))(a1);
}

/*
Purpose: ?unload_patch@Midi@@QAEHI@Z - forward 1 argument(s) to slot 0x124 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7C00 ?unload_patch@Midi@@QAEHI@Z 0x004C7C00-0x004C7C23
// symbol    ?midi_unload_patch_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?unload_patch@Midi@@QAEHI@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7C10
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_unload_patch_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x124 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_patch@Midi@@QAEHII@Z - forward 2 argument(s) to slot 0x128 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7C30 ?set_patch@Midi@@QAEHII@Z 0x004C7C30-0x004C7C57
// symbol    ?midi_set_patch_redirect@@YIHPAX0II@Z
// size      39 bytes
// prototype int (__thiscall ?set_patch@Midi@@QAEHII@Z)(Midi* this, unsigned int, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7C44
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_patch_redirect(void *self, void *, uint32_t a1, uint32_t a2) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0x128 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?set_tempo@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7D50 ?set_tempo@Midi@@QAEHK@Z 0x004C7D50-0x004C7D73
// symbol    ?midi_set_tempo_redirect@@YIHPAX0I@Z
// size      35 bytes
// prototype int (__thiscall ?set_tempo@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7D60
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_tempo_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_time@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xd4 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C7E80 ?get_time@Midi@@QAEHK@Z 0x004C7E80-0x004C7EA0
// symbol    ?midi_get_time_redirect@@YIHPAX0I@Z
// size      32 bytes
// prototype int (__thiscall ?get_time@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7E90
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_time_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xd4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_control_track@Midi@@QAEHXZ - forward 0 argument(s) to slot 0xf4 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C7EA0 ?get_control_track@Midi@@QAEHXZ 0x004C7EA0-0x004C7EB2
// symbol    ?midi_get_control_track_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?get_control_track@Midi@@QAEHXZ)(Midi* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_control_track_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf4 / sizeof(void *)])))();
}

/*
Purpose: ?get_total_track_ticks@Midi@@QAEHK@Z - forward 1 argument(s) to slot 0xf8 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C7EC0 ?get_total_track_ticks@Midi@@QAEHK@Z 0x004C7EC0-0x004C7EE0
// symbol    ?midi_get_total_track_ticks_redirect@@YIHPAX0I@Z
// size      32 bytes
// prototype int (__thiscall ?get_total_track_ticks@Midi@@QAEHK@Z)(Midi* this, unsigned int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7ED0
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall midi_get_total_track_ticks_redirect(void *self, void *, uint32_t a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z - forward 1 argument(s) to slot 0xe4 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7EE0 ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z 0x004C7EE0-0x004C7F03
// symbol    ?midi_set_channel_ctrl_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?set_channel_ctrl@Midi@@QAEHPAUChannelCtrl@@@Z)(Midi* this, ChannelCtrl*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7EF0
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_channel_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe4 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z - forward 1 argument(s) to slot 0xe8 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7F10 ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z 0x004C7F10-0x004C7F33
// symbol    ?midi_set_program_ctrl_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?set_program_ctrl@Midi@@QAEHPAUProgramCtrl@@@Z)(Midi* this, ProgramCtrl*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7F20
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_program_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))(a1);
}

/*
Purpose: ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z - forward 1 argument(s) to slot 0xc0 of the
         object at +0x3c, answering 0x14 when that object is absent.
// ORIGINAL: 0x004C7F40 ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z 0x004C7F40-0x004C7F63
// symbol    ?midi_set_track_ctrl_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?set_track_ctrl@Midi@@QAEHPAUTrackCtrl@@@Z)(Midi* this, TrackCtrl*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C7F50
Return Value: the delegate's, or 0x14 when the member is null
Status: Complete
*/
int __fastcall midi_set_track_ctrl_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x14;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1);
}

/*
Purpose: ?start@VoiceRx@@QAEHXZ - dispatch to slot 0x88 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
// ORIGINAL: 0x004C8C20 ?start@VoiceRx@@QAEHXZ 0x004C8C20-0x004C8C32 BYTE_EXACT
// symbol    ?voice_rx_start_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?start@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C8C29
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_start_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?stop@VoiceRx@@QAEHXZ - dispatch to slot 0x20 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
// ORIGINAL: 0x004C8C40 ?stop@VoiceRx@@QAEHXZ 0x004C8C40-0x004C8C4F BYTE_EXACT
// symbol    ?voice_rx_stop_redirect@@YIHPAX0@Z
// size      15 bytes
// prototype int (__thiscall ?stop@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C8C49
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_rx_stop_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x20 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?unload@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x14 of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C8C50 ?unload@VoiceRx@@QAEHXZ 0x004C8C50-0x004C8C62
// symbol    ?voice_rx_unload_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?unload@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_unload_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x14 / sizeof(void *)])))();
}

/*
Purpose: ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C8C70 ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z 0x004C8C70-0x004C8C93
// symbol    ?voice_rx_add_buffer_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?add_buffer@VoiceRx@@QAEHPAU_MMIOINFO@@@Z)(VoiceRx* this, _MMIOINFO*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C8C80
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_rx_add_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?get_buffer_size@VoiceRx@@QAEHXZ - forward 0 argument(s) to slot 0x90 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C8CA0 ?get_buffer_size@VoiceRx@@QAEHXZ 0x004C8CA0-0x004C8CB2
// symbol    ?voice_rx_get_buffer_size_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?get_buffer_size@VoiceRx@@QAEHXZ)(VoiceRx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_rx_get_buffer_size_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x90 / sizeof(void *)])))();
}

/*
Purpose: ?release@VoiceTx@@QAEXXZ - dispatch to slot 0x38 of the object at
         0x3c when it is present, and answer 0x0 either way: both
         paths land on the same zeroing, so the delegate's own result
         never reaches the caller.
// ORIGINAL: 0x004C8EA0 ?release@VoiceTx@@QAEXXZ 0x004C8EA0-0x004C8EAF BYTE_EXACT
// symbol    ?voice_tx_release_redirect@@YIHPAX0@Z
// size      15 bytes
// prototype void (__thiscall ?release@VoiceTx@@QAEXXZ)(VoiceTx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C8EA9
Return Value: 0x0, whether the delegate ran or not
Status: Complete
*/
int __fastcall voice_tx_release_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    (void)(ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x38 / sizeof(void *)])))();
    return 0x0;
}

/*
Purpose: ?get_nbuffers@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x94 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C9010 ?get_nbuffers@VoiceTx@@QAEHXZ 0x004C9010-0x004C9022
// symbol    ?voice_tx_get_nbuffers_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?get_nbuffers@VoiceTx@@QAEHXZ)(VoiceTx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_nbuffers_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x94 / sizeof(void *)])))();
}

/*
Purpose: ?get_next_buffer@VoiceTx@@QAEHXZ - forward 0 argument(s) to slot 0x88 of the
         object at +0x3c, answering 0x0 when that object is absent.
// ORIGINAL: 0x004C9030 ?get_next_buffer@VoiceTx@@QAEHXZ 0x004C9030-0x004C9042
// symbol    ?voice_tx_get_next_buffer_redirect@@YIHPAX0@Z
// size      18 bytes
// prototype int (__thiscall ?get_next_buffer@VoiceTx@@QAEHXZ)(VoiceTx* this)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: the delegate's, or 0x0 when the member is null
Status: Complete
*/
int __fastcall voice_tx_get_next_buffer_redirect(void *self, void *) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x0;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0x88 / sizeof(void *)])))();
}

/*
Purpose: ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z - forward 1 argument(s) to slot 0x8c of the
         object at +0x3c, answering 0x13 when that object is absent.
// ORIGINAL: 0x004C9050 ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z 0x004C9050-0x004C9073
// symbol    ?voice_tx_return_buffer_redirect@@YIHPAX0H@Z
// size      35 bytes
// prototype int (__thiscall ?return_buffer@VoiceTx@@QAEHPAU_MMIOINFO@@@Z)(VoiceTx* this, _MMIOINFO*)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x004C9060
Return Value: the delegate's, or 0x13 when the member is null
Status: Complete
*/
int __fastcall voice_tx_return_buffer_redirect(void *self, void *, int a1) {
    void *const member = *reinterpret_cast<void **>(
        static_cast<uint8_t *>(self) + 0x3c);
    if (member == nullptr) {
        return 0x13;
    }
    void **const vtable = *reinterpret_cast<void ***>(member);
    return (ORIGINAL(member)->*original_method<func_delegation_1>(reinterpret_cast<unsigned long>(vtable[0x8c / sizeof(void *)])))(a1);
}

/*
Purpose: ?on_left_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x005AD3B0 ?on_left_click@ReplayWin@@QAEXHH@Z 0x005AD3B0-0x005AD3BB BYTE_EXACT
// symbol    ?replay_win_on_left_click_redirect@@YIXPAX0HH@Z
// size      11 bytes
// prototype void (__thiscall ?on_left_click@ReplayWin@@QAEXHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x005AD3B2
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_left_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_right_click@ReplayWin@@QAEXHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x005AD3C0 ?on_right_click@ReplayWin@@QAEXHH@Z 0x005AD3C0-0x005AD3CB BYTE_EXACT
// symbol    ?replay_win_on_right_click_redirect@@YIXPAX0HH@Z
// size      11 bytes
// prototype void (__thiscall ?on_right_click@ReplayWin@@QAEXHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x005AD3C2
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_right_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_button_clicked@ReplayWin@@QAEXH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x005AD430 ?on_button_clicked@ReplayWin@@QAEXH@Z 0x005AD430-0x005AD43B BYTE_EXACT
// symbol    ?replay_win_on_button_clicked_redirect@@YIXPAX0H@Z
// size      11 bytes
// prototype void (__thiscall ?on_button_clicked@ReplayWin@@QAEXH@Z)(ReplayWin* this, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x005AD432
Return Value: n/a
Status: Complete
*/
void __fastcall replay_win_on_button_clicked_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
}

/*
Purpose: ?on_key_click@ReplayWin@@QAEHHH@Z - dispatch to slot 0xe8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x005AD440 ?on_key_click@ReplayWin@@QAEHHH@Z 0x005AD440-0x005AD450 BYTE_EXACT
// symbol    ?replay_win_on_key_click_redirect@@YIHPAX0HH@Z
// size      16 bytes
// prototype int (__thiscall ?on_key_click@ReplayWin@@QAEHHH@Z)(ReplayWin* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x005AD442
Return Value: 0x1, a constant
Status: Complete
*/
int __fastcall replay_win_on_key_click_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xe8 / sizeof(void *)])))();
    return 0x1;
}

/*
Purpose: ?on_scrolling@Gamma@@QAEXHH@Z - dispatch to slot 0xc0 of this object's OWN
         vtable, forwarding 2 argument(s).
// ORIGINAL: 0x005C93A0 ?on_scrolling@Gamma@@QAEXHH@Z 0x005C93A0-0x005C93B7 BYTE_EXACT
// symbol    ?gamma_on_scrolling_redirect@@YIXPAX0HH@Z
// size      23 bytes
// prototype void (__thiscall ?on_scrolling@Gamma@@QAEXHH@Z)(Gamma* this, int, int)
// callers   0   call targets   0
// kind      game
// flags     frame;hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x005C93AD
Return Value: n/a
Status: Complete
*/
void __fastcall gamma_on_scrolling_redirect(void *self, void *, int a1, int a2) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_2>(reinterpret_cast<unsigned long>(vtable[0xc0 / sizeof(void *)])))(a1, a2);
}

/*
Purpose: ?on_dialog_focus@BaseButton@@QAEXH@Z - dispatch to slot 0xf8 of this object's OWN
         vtable with NO arguments: the original pushes nothing between the
         vtable load and the call, so the parameters this function declares are
         discarded and only the `ret` cleans them up.
// ORIGINAL: 0x00607B00 ?on_dialog_focus@BaseButton@@QAEXH@Z 0x00607B00-0x00607B0B BYTE_EXACT
// symbol    ?base_button_on_dialog_focus_redirect@@YIXPAX0H@Z
// size      11 bytes
// prototype void (__thiscall ?on_dialog_focus@BaseButton@@QAEXH@Z)(BaseButton* this, int)
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
// indirect  0x00607B02
Return Value: n/a
Status: Complete
*/
void __fastcall base_button_on_dialog_focus_redirect(void *self, void *, int a1) {
    void **const vtable = *reinterpret_cast<void ***>(self);
    (void)(ORIGINAL(self)->*original_method<func_delegation_0>(reinterpret_cast<unsigned long>(vtable[0xf8 / sizeof(void *)])))();
}
