// GENERATED by tools/generate_signature_oracles.py - do not edit.
//
// Each function below is executed in its ORIGINAL form, at its canonical
// address inside the hybrid process, and compared against the recovered
// implementation reached through the same address with the redirect
// restored. Return value AND the globals each side produces are compared;
// these functions return void as often as not and do their work in .data.
//
// The markers below are the input to `unproven_recovered` in
// docs/recovery/summary.json; tools/export_proven_functions.py decides
// what counts.
//
// PROVEN-AGAINST-ORIGINAL: 0x004456A0  ?passover_callback@@YAXXZ
// PROVEN-AGAINST-ORIGINAL: 0x00455E50  ?load_deswin_sprites@@YAXXZ
// PROVEN-AGAINST-ORIGINAL: 0x0052DC70  ?not_my_turn@@YAHXZ
// PROVEN-AGAINST-ORIGINAL: 0x0058EE50  ?desktop_update@@YAXXZ
// PROVEN-AGAINST-ORIGINAL: 0x005FD2B0  ?do_sound@@YAXXZ

#include "stdafx.h"
#include "generated_signature_oracle.h"

#include "runtime_oracle.h"

#include <cstdio>
#include <cstdint>
#include <cstring>
#include <vector>

namespace {

// .data and .bss of the original image. The recovered bodies write here
// and so do the originals; comparing it is what makes a void-returning
// function testable at all.
constexpr uintptr_t GlobalsBegin = 0x00682000U;
constexpr uintptr_t GlobalsEnd   = 0x009C21F8U;
constexpr size_t GlobalsSize = GlobalsEnd - GlobalsBegin;

void snapshot(std::vector<uint8_t> &into) {
    into.resize(GlobalsSize);
    std::memcpy(into.data(), reinterpret_cast<const void *>(GlobalsBegin),
                GlobalsSize);
}

void restore(const std::vector<uint8_t> &from) {
    std::memcpy(reinterpret_cast<void *>(GlobalsBegin), from.data(),
                GlobalsSize);
}

// Where the two images first disagree, for a message that names an address
// rather than saying only that something differed.
bool same_globals(const std::vector<uint8_t> &a,
                  const std::vector<uint8_t> &b, uintptr_t *where) {
    for (size_t index = 0; index < GlobalsSize; ++index) {
        if (a[index] != b[index]) {
            *where = GlobalsBegin + index;
            return false;
        }
    }
    return true;
}

}  // namespace

// ?passover_callback@@YAXXZ
// recovered in src/guarded_teardowns.cpp:104
static bool verify_passover_callback_004456a0() {
    typedef void (__cdecl *Callable)();
    Callable target = reinterpret_cast<Callable>(0x004456A0U);
    std::vector<uint8_t> before, after_original, after_recovered;
    bool passed = true;
    {
        snapshot(before);
        if (!suspend_redirect_at(0x004456A0U)) {
            std::printf("  ?passover_callback@@YAXXZ: cannot suspend redirect\n");
            return false;
        }
        target();
        snapshot(after_original);
        restore(before);
        if (!resume_redirect_at(0x004456A0U)) {
            std::printf("  ?passover_callback@@YAXXZ: cannot resume redirect\n");
            return false;
        }
        target();
        snapshot(after_recovered);
        restore(before);   // leave the process as it was found
        uintptr_t where = 0;
        if (!same_globals(after_original, after_recovered, &where)) {
            std::printf("  ?passover_callback@@YAXXZ: globals differ, first at %p\n",
                        reinterpret_cast<void *>(where));
            passed = false;
        }
    }
    return passed;
}

// ?load_deswin_sprites@@YAXXZ
// recovered in src/leaf_recoveries.cpp:1304
static bool verify_load_deswin_sprites_00455e50() {
    typedef void (__cdecl *Callable)();
    Callable target = reinterpret_cast<Callable>(0x00455E50U);
    std::vector<uint8_t> before, after_original, after_recovered;
    bool passed = true;
    {
        snapshot(before);
        if (!suspend_redirect_at(0x00455E50U)) {
            std::printf("  ?load_deswin_sprites@@YAXXZ: cannot suspend redirect\n");
            return false;
        }
        target();
        snapshot(after_original);
        restore(before);
        if (!resume_redirect_at(0x00455E50U)) {
            std::printf("  ?load_deswin_sprites@@YAXXZ: cannot resume redirect\n");
            return false;
        }
        target();
        snapshot(after_recovered);
        restore(before);   // leave the process as it was found
        uintptr_t where = 0;
        if (!same_globals(after_original, after_recovered, &where)) {
            std::printf("  ?load_deswin_sprites@@YAXXZ: globals differ, first at %p\n",
                        reinterpret_cast<void *>(where));
            passed = false;
        }
    }
    return passed;
}

// ?not_my_turn@@YAHXZ
// recovered in src/game.cpp:53
static bool verify_not_my_turn_0052dc70() {
    typedef int (__cdecl *Callable)();
    Callable target = reinterpret_cast<Callable>(0x0052DC70U);
    std::vector<uint8_t> before, after_original, after_recovered;
    bool passed = true;
    {
        snapshot(before);
        if (!suspend_redirect_at(0x0052DC70U)) {
            std::printf("  ?not_my_turn@@YAHXZ: cannot suspend redirect\n");
            return false;
        }
        const int original_result = target();
        snapshot(after_original);
        restore(before);
        if (!resume_redirect_at(0x0052DC70U)) {
            std::printf("  ?not_my_turn@@YAHXZ: cannot resume redirect\n");
            return false;
        }
        const int recovered_result = target();
        snapshot(after_recovered);
        restore(before);   // leave the process as it was found
        if (original_result != recovered_result) {
            std::printf("  ?not_my_turn@@YAHXZ: return value differs\n");
            passed = false;
        }
        uintptr_t where = 0;
        if (!same_globals(after_original, after_recovered, &where)) {
            std::printf("  ?not_my_turn@@YAHXZ: globals differ, first at %p\n",
                        reinterpret_cast<void *>(where));
            passed = false;
        }
    }
    return passed;
}

// ?desktop_update@@YAXXZ
// recovered in src/maininterface.cpp:42
static bool verify_desktop_update_0058ee50() {
    typedef void (__cdecl *Callable)();
    Callable target = reinterpret_cast<Callable>(0x0058EE50U);
    std::vector<uint8_t> before, after_original, after_recovered;
    bool passed = true;
    {
        snapshot(before);
        if (!suspend_redirect_at(0x0058EE50U)) {
            std::printf("  ?desktop_update@@YAXXZ: cannot suspend redirect\n");
            return false;
        }
        target();
        snapshot(after_original);
        restore(before);
        if (!resume_redirect_at(0x0058EE50U)) {
            std::printf("  ?desktop_update@@YAXXZ: cannot resume redirect\n");
            return false;
        }
        target();
        snapshot(after_recovered);
        restore(before);   // leave the process as it was found
        uintptr_t where = 0;
        if (!same_globals(after_original, after_recovered, &where)) {
            std::printf("  ?desktop_update@@YAXXZ: globals differ, first at %p\n",
                        reinterpret_cast<void *>(where));
            passed = false;
        }
    }
    return passed;
}

// ?do_sound@@YAXXZ
// recovered in src/autosound.cpp:144
static bool verify_do_sound_005fd2b0() {
    typedef void (__cdecl *Callable)();
    Callable target = reinterpret_cast<Callable>(0x005FD2B0U);
    std::vector<uint8_t> before, after_original, after_recovered;
    bool passed = true;
    {
        snapshot(before);
        if (!suspend_redirect_at(0x005FD2B0U)) {
            std::printf("  ?do_sound@@YAXXZ: cannot suspend redirect\n");
            return false;
        }
        target();
        snapshot(after_original);
        restore(before);
        if (!resume_redirect_at(0x005FD2B0U)) {
            std::printf("  ?do_sound@@YAXXZ: cannot resume redirect\n");
            return false;
        }
        target();
        snapshot(after_recovered);
        restore(before);   // leave the process as it was found
        uintptr_t where = 0;
        if (!same_globals(after_original, after_recovered, &where)) {
            std::printf("  ?do_sound@@YAXXZ: globals differ, first at %p\n",
                        reinterpret_cast<void *>(where));
            passed = false;
        }
    }
    return passed;
}

bool run_generated_signature_oracles() {
    bool passed = true;
    passed &= verify_passover_callback_004456a0();
    passed &= verify_load_deswin_sprites_00455e50();
    passed &= verify_not_my_turn_0052dc70();
    passed &= verify_desktop_update_0058ee50();
    passed &= verify_do_sound_005fd2b0();
    std::printf("generated signature oracles: %d function(s)\n", 5);
    return passed;
}
