/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/*
 * Absolute-operand arithmetic leaves.
 * Was generated by tools/generate_global_arith.py, WHICH NO LONGER EXISTS:
 * commit 271114cf retired the bulk generators as "9,262 lines that nobody
 * could run". EDIT THIS FILE DIRECTLY. The old instruction - edit the
 * generator, not the file - outlived the generator by months and told every
 * reader not to touch this file in the only way it can now be touched.
 *
 *
 * 26 functions that read fixed globals, compute, store, and return. No
 * register is live on entry and no memory operand is register-relative, so
 * one C statement per original instruction reproduces them exactly - store
 * order included, which matters wherever a load must see an earlier store.
 *
 * The 35 globals below are BOUND rather than inlined. Every one lives in the
 * original image and is unmapped in a standalone test process, so a body that
 * dereferenced its address directly would compile, pass the hybrid gate, and
 * fault the moment a leaf test called it.
 */

int32_t *const GlobalSlot00686B6C = (int32_t *)0x00686B6C;
int32_t *const GlobalSlot00686B70 = (int32_t *)0x00686B70;
int32_t *const GlobalSlot00686B74 = (int32_t *)0x00686B74;
int32_t *const GlobalSlot00686B78 = (int32_t *)0x00686B78;
int32_t *const GlobalSlot00686B7C = (int32_t *)0x00686B7C;
int32_t *const GlobalSlot00686B80 = (int32_t *)0x00686B80;
int32_t *const GlobalSlot00686B84 = (int32_t *)0x00686B84;
int32_t *const GlobalSlot00686B8C = (int32_t *)0x00686B8C;
int32_t *const GlobalSlot007591C4 = (int32_t *)0x007591C4;
int32_t *const GlobalSlot008577D8 = (int32_t *)0x008577D8;
int32_t *const GlobalSlot008577DC = (int32_t *)0x008577DC;
int32_t *const GlobalSlot008577E0 = (int32_t *)0x008577E0;
int32_t *const GlobalSlot008577E4 = (int32_t *)0x008577E4;
int32_t *const GlobalSlot008577E8 = (int32_t *)0x008577E8;
int32_t *const GlobalSlot008577EC = (int32_t *)0x008577EC;
int32_t *const GlobalSlot00857884 = (int32_t *)0x00857884;
int32_t *const GlobalSlot00857888 = (int32_t *)0x00857888;
int32_t *const GlobalSlot0085788C = (int32_t *)0x0085788C;
int32_t *const GlobalSlot00857890 = (int32_t *)0x00857890;
int32_t *const GlobalSlot00857894 = (int32_t *)0x00857894;
int32_t *const GlobalSlot00857898 = (int32_t *)0x00857898;
int32_t *const GlobalSlot0085789C = (int32_t *)0x0085789C;
int32_t *const GlobalSlot008578A0 = (int32_t *)0x008578A0;
int32_t *const GlobalSlot008578A4 = (int32_t *)0x008578A4;
int32_t *const GlobalSlot008578A8 = (int32_t *)0x008578A8;
int32_t *const GlobalSlot008578AC = (int32_t *)0x008578AC;
int32_t *const GlobalSlot008578B0 = (int32_t *)0x008578B0;
int32_t *const GlobalSlot008578B4 = (int32_t *)0x008578B4;
int32_t *const GlobalSlot008578BC = (int32_t *)0x008578BC;
int32_t *const GlobalSlot008578C0 = (int32_t *)0x008578C0;
int32_t *const GlobalSlot008578C4 = (int32_t *)0x008578C4;
int32_t *const GlobalSlot008578C8 = (int32_t *)0x008578C8;
int32_t *const GlobalSlot008578CC = (int32_t *)0x008578CC;
int32_t *const GlobalSlot008578D0 = (int32_t *)0x008578D0;
int32_t *const GlobalSlot009B3A54 = (int32_t *)0x009B3A54;

void __fastcall global_arith_0044c870_redirect(void *self, void *);
void __fastcall global_arith_0048d550_redirect(void *self, void *);
void __fastcall global_arith_0048d560_redirect(void *self, void *);
void __fastcall global_arith_0048d570_redirect(void *self, void *);
void __fastcall global_arith_0048d590_redirect(void *self, void *);
void __fastcall global_arith_0048d5b0_redirect(void *self, void *);
void __fastcall global_arith_0048d5d0_redirect(void *self, void *);
void __fastcall global_arith_0048d5f0_redirect(void *self, void *);
void __fastcall global_arith_0048d610_redirect(void *self, void *);
void __fastcall global_arith_0048d630_redirect(void *self, void *);
void __fastcall global_arith_0048d670_redirect(void *self, void *);
void __fastcall global_arith_0048d690_redirect(void *self, void *);
void __fastcall global_arith_0048d6b0_redirect(void *self, void *);
void __fastcall global_arith_0048d6d0_redirect(void *self, void *);
void __fastcall global_arith_0048d6f0_redirect(void *self, void *);
void __fastcall global_arith_0048d710_redirect(void *self, void *);
void __fastcall global_arith_0048d730_redirect(void *self, void *);
void __fastcall global_arith_0048d750_redirect(void *self, void *);
void __fastcall global_arith_0048d760_redirect(void *self, void *);
void __fastcall global_arith_0048d770_redirect(void *self, void *);
void __fastcall global_arith_0048d790_redirect(void *self, void *);
void __fastcall global_arith_0048d7b0_redirect(void *self, void *);
void __fastcall global_arith_0048d7d0_redirect(void *self, void *);
void __fastcall global_arith_0048d7f0_redirect(void *self, void *);
void __fastcall global_arith_0048d810_redirect(void *self, void *);
void __fastcall global_arith_005d8360_redirect(void *self, void *);
