/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/*
 * Absolute-operand arithmetic leaves - GENERATED by
 * tools/generate_global_arith.py. Do not edit by hand; edit the generator and
 * regenerate.
 *
 * 26 functions that read fixed globals, compute, store, and return. No
 * register is live on entry and no memory operand is register-relative, so
 * one C statement per original instruction reproduces them exactly - store
 * order included, which matters wherever a load must see an earlier store.
 *
 * The 35 globals below are BOUND rather than inlined. Every one lives in the
 * original image and is unmapped in a standalone test process, so a body that
 * dereferenced its address directly would compile, pass the hybrid gate, and
 * fault the moment a leaf test called it.
 */

int32_t *const GlobalSlot00686B6C = (int32_t *)0x00686B6C;
int32_t *const GlobalSlot00686B70 = (int32_t *)0x00686B70;
int32_t *const GlobalSlot00686B74 = (int32_t *)0x00686B74;
int32_t *const GlobalSlot00686B78 = (int32_t *)0x00686B78;
int32_t *const GlobalSlot00686B7C = (int32_t *)0x00686B7C;
int32_t *const GlobalSlot00686B80 = (int32_t *)0x00686B80;
int32_t *const GlobalSlot00686B84 = (int32_t *)0x00686B84;
int32_t *const GlobalSlot00686B8C = (int32_t *)0x00686B8C;
extern int32_t *GlobalSlot007591C4;
extern int32_t *GlobalSlot008577D8;
extern int32_t *GlobalSlot008577DC;
extern int32_t *GlobalSlot008577E0;
extern int32_t *GlobalSlot008577E4;
extern int32_t *GlobalSlot008577E8;
extern int32_t *GlobalSlot008577EC;
extern int32_t *GlobalSlot00857884;
extern int32_t *GlobalSlot00857888;
extern int32_t *GlobalSlot0085788C;
extern int32_t *GlobalSlot00857890;
extern int32_t *GlobalSlot00857894;
extern int32_t *GlobalSlot00857898;
extern int32_t *GlobalSlot0085789C;
extern int32_t *GlobalSlot008578A0;
extern int32_t *GlobalSlot008578A4;
int32_t *const GlobalSlot008578A8 = (int32_t *)0x008578A8;
extern int32_t *GlobalSlot008578AC;
extern int32_t *GlobalSlot008578B0;
extern int32_t *GlobalSlot008578B4;
extern int32_t *GlobalSlot008578BC;
extern int32_t *GlobalSlot008578C0;
extern int32_t *GlobalSlot008578C4;
extern int32_t *GlobalSlot008578C8;
extern int32_t *GlobalSlot008578CC;
extern int32_t *GlobalSlot008578D0;
extern int32_t *GlobalSlot009B3A54;

void __fastcall global_arith_0044c870_redirect(void *self, void *);
void __fastcall global_arith_0048d550_redirect(void *self, void *);
void __fastcall global_arith_0048d560_redirect(void *self, void *);
void __fastcall global_arith_0048d570_redirect(void *self, void *);
void __fastcall global_arith_0048d590_redirect(void *self, void *);
void __fastcall global_arith_0048d5b0_redirect(void *self, void *);
void __fastcall global_arith_0048d5d0_redirect(void *self, void *);
void __fastcall global_arith_0048d5f0_redirect(void *self, void *);
void __fastcall global_arith_0048d610_redirect(void *self, void *);
void __fastcall global_arith_0048d630_redirect(void *self, void *);
void __fastcall global_arith_0048d670_redirect(void *self, void *);
void __fastcall global_arith_0048d690_redirect(void *self, void *);
void __fastcall global_arith_0048d6b0_redirect(void *self, void *);
void __fastcall global_arith_0048d6d0_redirect(void *self, void *);
void __fastcall global_arith_0048d6f0_redirect(void *self, void *);
void __fastcall global_arith_0048d710_redirect(void *self, void *);
void __fastcall global_arith_0048d730_redirect(void *self, void *);
void __fastcall global_arith_0048d750_redirect(void *self, void *);
void __fastcall global_arith_0048d760_redirect(void *self, void *);
void __fastcall global_arith_0048d770_redirect(void *self, void *);
void __fastcall global_arith_0048d790_redirect(void *self, void *);
void __fastcall global_arith_0048d7b0_redirect(void *self, void *);
void __fastcall global_arith_0048d7d0_redirect(void *self, void *);
void __fastcall global_arith_0048d7f0_redirect(void *self, void *);
void __fastcall global_arith_0048d810_redirect(void *self, void *);
void __fastcall global_arith_005d8360_redirect(void *self, void *);
