/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "original_seam.h"
#include "guarded_teardowns.h"
#include "statuswin.h"
#include "sprite.h"

/*
 * Once-guarded teardown thunks - GENERATED by
 * tools/generate_guarded_teardowns.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * 25 ??__F bodies that tear a global down AT MOST ONCE, gated on a bit in a
 * shared flag byte. The teardown runs only when the bit is CLEAR, and the bit
 * is set BEFORE the call rather than after. Flag bytes are shared: three
 * FileWin sprites use bits 1, 2 and 4 of one byte, so the mask belongs to the
 * function and is never inferred from the object.
 *
 * Flags and objects are BOUND rather than inlined. Both live in the original
 * image and are unmapped in a standalone test process.
 */

func_thiscall_teardown TeardownTarget00420F90 =
    original_method<func_thiscall_teardown>(0x00420F90);
func_thiscall_teardown TeardownTarget004327A0 =
    original_method<func_thiscall_teardown>(0x004327A0);
func_thiscall_teardown TeardownTarget0048BD80 =
    original_method<func_thiscall_teardown>(0x0048BD80);
func_thiscall_teardown TeardownTarget0051D9F0 =
    original_method<func_thiscall_teardown>(0x0051D9F0);
func_thiscall_teardown TeardownTarget005D4DD0 =
    original_method<func_thiscall_teardown>(0x005D4DD0);
void __fastcall sprite_close_default(void *object) {
    static_cast<Sprite *>(object)->close();
}

/*
Purpose: ?timer_callback_daemon@BattleWin@@QAAXHH@Z - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00422EB0 ?timer_callback_daemon@BattleWin@@QAAXHH@Z 0x00422EB0-0x00422EBA BYTE_EXACT
// symbol    ?teardown_00422eb0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00422eb0() {
    sub_interface_global()->release_iface_mode();
}

/*
Purpose: ?timer_callback_daemon@BattleWin@@QAAXH@Z - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00422EC0 ?timer_callback_daemon@BattleWin@@QAAXH@Z 0x00422EC0-0x00422ECA BYTE_EXACT
// symbol    ?teardown_00422ec0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00422ec0() {
    sub_interface_global()->release_iface_mode();
}

/*
Purpose: ?passover_callback@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x004456A0 ?passover_callback@@YAXXZ 0x004456A0-0x004456AA
// symbol    ?teardown_004456a0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_004456a0() {
    (ORIGINAL(g_PASSOVER_WAVE)->*original_method<func_thiscall_teardown>(original_address(PopupWavePlay)))();
}

/*
Purpose: ??__Fg_MAPWIN@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x004620A0 ??__Fg_MAPWIN@@YAXXZ 0x004620A0-0x004620B4
// symbol    ?teardown_g_mapwin@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x00420F90
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_mapwin() {
    (ORIGINAL(TeardownObject007F5ACC)->*TeardownTarget00420F90)();
    (ORIGINAL(TeardownObject007F5ACC)->*TeardownTarget005D4DD0)();
}

/*
Purpose: ??__Fg_PLANWIN@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0048AE20 ??__Fg_PLANWIN@@YAXXZ 0x0048AE20-0x0048AE34
// symbol    ?teardown_g_planwin@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x0048BD80
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_planwin() {
    (ORIGINAL(TeardownObject00856DC0)->*TeardownTarget0048BD80)();
    (ORIGINAL(TeardownObject00856DC0)->*TeardownTarget005D4DD0)();
}

/*
Purpose: ??__Eg_BOOM_BUFFER1@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00505D20 ??__Eg_BOOM_BUFFER1@@YAXXZ 0x00505D20-0x00505D2A BYTE_EXACT
// symbol    ?teardown_00505d20@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00505d20() {
    TeardownObject00915068->Buffer::~Buffer();
}

/*
Purpose: ??__Eg_BOOM_FLIC@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00505D30 ??__Eg_BOOM_FLIC@@YAXXZ 0x00505D30-0x00505D3A
// symbol    ?teardown_00505d30@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00505d30() {
    (ORIGINAL(TeardownObject0090EA68)->*TeardownTarget004327A0)();
}

/*
Purpose: ??__Fg_CONSOLE@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0050E870 ??__Fg_CONSOLE@@YAXXZ 0x0050E870-0x0050E884
// symbol    ?teardown_g_console@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x0051D9F0
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_console() {
    (ORIGINAL(TeardownObject00939444)->*TeardownTarget0051D9F0)();
    (ORIGINAL(TeardownObject00939444)->*TeardownTarget005D4DD0)();
}

/*
Purpose: sub_589890 - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00589890 sub_589890 0x00589890-0x0058989A
// symbol    ?teardown_00589890@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00589890() {
    (ORIGINAL(TeardownObject009403E0)->*original_method<func_thiscall_teardown>(original_address(PopupDtorTarget)))();
}

/*
Purpose: ??__Fg_BUFFER_SPRITE@@YAXXZ - tear down the global at 0x9b3a50 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 2 of the flag byte
         at 0x9b37cc.
// ORIGINAL: 0x005D71F0 ??__Fg_BUFFER_SPRITE@@YAXXZ 0x005D71F0-0x005D720F
// symbol    ?teardown_g_buffer_sprite@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_buffer_sprite() {
    const uint8_t flags = *TeardownFlags009B37CC;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B37CC = static_cast<uint8_t>(flags | 2);
    g_BUFFER_SPRITE->close();
}

/*
Purpose: ??__Fg_WIN_BUFFER@@YAXXZ - tear down the global at 0x9b6f08 through
         ??1Buffer@@QAE@XZ, at most once, gated on bit 1 of the flag byte
         at 0x9b6e30.
// ORIGINAL: 0x005EB370 ??__Fg_WIN_BUFFER@@YAXXZ 0x005EB370-0x005EB38F
// symbol    ?teardown_g_win_buffer@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_win_buffer() {
    const uint8_t flags = *TeardownFlags009B6E30;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B6E30 = static_cast<uint8_t>(flags | 1);
    g_WIN_BUFFER->Buffer::~Buffer();
}

/*
Purpose: sub_5eb3b0 - tear down the global at 0x9b7490 through
         ??1Buffer@@QAE@XZ, at most once, gated on bit 2 of the flag byte
         at 0x9b6e30.
// ORIGINAL: 0x005EB3B0 sub_5eb3b0 0x005EB3B0-0x005EB3CF
// symbol    ?teardown_005eb3b0@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_005eb3b0() {
    const uint8_t flags = *TeardownFlags009B6E30;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B6E30 = static_cast<uint8_t>(flags | 2);
    TeardownObject009B7490->Buffer::~Buffer();
}

/*
Purpose: ??__Fg_RADIOBUTTON_SPRITE_1@@YAXXZ - tear down the global at 0x9b8ef8 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 1 of the flag byte
         at 0x9b8ef0.
// ORIGINAL: 0x0060D080 ??__Fg_RADIOBUTTON_SPRITE_1@@YAXXZ 0x0060D080-0x0060D09F
// symbol    ?teardown_g_radiobutton_sprite_1@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_radiobutton_sprite_1() {
    const uint8_t flags = *TeardownFlags009B8EF0;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B8EF0 = static_cast<uint8_t>(flags | 1);
    g_RADIOBUTTON_SPRITE_1->close();
}

/*
Purpose: ??__Fg_RADIOBUTTON_SPRITE_2@@YAXXZ - tear down the global at 0x9b8f28 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 2 of the flag byte
         at 0x9b8ef0.
// ORIGINAL: 0x0060D0C0 ??__Fg_RADIOBUTTON_SPRITE_2@@YAXXZ 0x0060D0C0-0x0060D0DF
// symbol    ?teardown_g_radiobutton_sprite_2@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_radiobutton_sprite_2() {
    const uint8_t flags = *TeardownFlags009B8EF0;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B8EF0 = static_cast<uint8_t>(flags | 2);
    g_RADIOBUTTON_SPRITE_2->close();
}

/*
Purpose: ?close_class@RadioButton@@QAAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0060E5D0 ?close_class@RadioButton@@QAAXXZ 0x0060E5D0-0x0060E5E4 BYTE_EXACT
// symbol    ?teardown_0060e5d0@@YAXXZ
// size      20 bytes
// prototype 
// callers   1   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x005E3820
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0060e5d0() {
    g_RADIOBUTTON_SPRITE_2->close();
    g_RADIOBUTTON_SPRITE_1->close();
}

/*
Purpose: ??__Fg_CHECKBOX_SPRITE_1@@YAXXZ - tear down the global at 0x9b8f60 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 1 of the flag byte
         at 0x9b8f58.
// ORIGINAL: 0x0060E610 ??__Fg_CHECKBOX_SPRITE_1@@YAXXZ 0x0060E610-0x0060E62F
// symbol    ?teardown_g_checkbox_sprite_1@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_checkbox_sprite_1() {
    const uint8_t flags = *TeardownFlags009B8F58;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B8F58 = static_cast<uint8_t>(flags | 1);
    g_CHECKBOX_SPRITE_1->close();
}

/*
Purpose: ??__Fg_CHECKBOX_SPRITE_2@@YAXXZ - tear down the global at 0x9b8f90 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 2 of the flag byte
         at 0x9b8f58.
// ORIGINAL: 0x0060E650 ??__Fg_CHECKBOX_SPRITE_2@@YAXXZ 0x0060E650-0x0060E66F
// symbol    ?teardown_g_checkbox_sprite_2@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_checkbox_sprite_2() {
    const uint8_t flags = *TeardownFlags009B8F58;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B8F58 = static_cast<uint8_t>(flags | 2);
    g_CHECKBOX_SPRITE_2->close();
}

/*
Purpose: ?close_class@CheckBox@@QAAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0060FD60 ?close_class@CheckBox@@QAAXXZ 0x0060FD60-0x0060FD74 BYTE_EXACT
// symbol    ?teardown_0060fd60@@YAXXZ
// size      20 bytes
// prototype 
// callers   1   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x005E3820
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0060fd60() {
    g_CHECKBOX_SPRITE_1->close();
    g_CHECKBOX_SPRITE_2->close();
}

/*
Purpose: ??__Fg_FILEWIN_SPRITE_1@@YAXXZ - tear down the global at 0x9b9048 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 1 of the flag byte
         at 0x9b9014.
// ORIGINAL: 0x006137B0 ??__Fg_FILEWIN_SPRITE_1@@YAXXZ 0x006137B0-0x006137CF
// symbol    ?teardown_g_filewin_sprite_1@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_filewin_sprite_1() {
    const uint8_t flags = *TeardownFlags009B9014;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B9014 = static_cast<uint8_t>(flags | 1);
    g_FILEWIN_SPRITE_1->close();
}

/*
Purpose: ??__Fg_FILEWIN_SPRITE_2@@YAXXZ - tear down the global at 0x9b9018 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 2 of the flag byte
         at 0x9b9014.
// ORIGINAL: 0x006137F0 ??__Fg_FILEWIN_SPRITE_2@@YAXXZ 0x006137F0-0x0061380F
// symbol    ?teardown_g_filewin_sprite_2@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_filewin_sprite_2() {
    const uint8_t flags = *TeardownFlags009B9014;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B9014 = static_cast<uint8_t>(flags | 2);
    g_FILEWIN_SPRITE_2->close();
}

/*
Purpose: ??__Fg_FILEWIN_SPRITE_3@@YAXXZ - tear down the global at 0x9b9078 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 4 of the flag byte
         at 0x9b9014.
// ORIGINAL: 0x00613830 ??__Fg_FILEWIN_SPRITE_3@@YAXXZ 0x00613830-0x0061384F
// symbol    ?teardown_g_filewin_sprite_3@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_filewin_sprite_3() {
    const uint8_t flags = *TeardownFlags009B9014;
    if ((4 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B9014 = static_cast<uint8_t>(flags | 4);
    g_FILEWIN_SPRITE_3->close();
}

/*
Purpose: ??__Fg_CAVIAR_BUFFER_1@@YAXXZ - tear down the global at 0x9b9108 through
         ??1Buffer@@QAE@XZ, at most once, gated on bit 1 of the flag byte
         at 0x9b9104.
// ORIGINAL: 0x00616AC0 ??__Fg_CAVIAR_BUFFER_1@@YAXXZ 0x00616AC0-0x00616ADF
// symbol    ?teardown_g_caviar_buffer_1@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_caviar_buffer_1() {
    const uint8_t flags = *TeardownFlags009B9104;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B9104 = static_cast<uint8_t>(flags | 1);
    g_CAVIAR_BUFFER_1->Buffer::~Buffer();
}

/*
Purpose: ??__Fg_CAVIAR_BUFFER_2@@YAXXZ - tear down the global at 0x9b96b0 through
         ??1Buffer@@QAE@XZ, at most once, gated on bit 2 of the flag byte
         at 0x9b9104.
// ORIGINAL: 0x00616B00 ??__Fg_CAVIAR_BUFFER_2@@YAXXZ 0x00616B00-0x00616B1F
// symbol    ?teardown_g_caviar_buffer_2@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_caviar_buffer_2() {
    const uint8_t flags = *TeardownFlags009B9104;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B9104 = static_cast<uint8_t>(flags | 2);
    g_CAVIAR_BUFFER_2->Buffer::~Buffer();
}

/*
Purpose: sub_63bb00 - tear down the global at 0x9beae8 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 1 of the flag byte
         at 0x9beae0.
// ORIGINAL: 0x0063BB00 sub_63bb00 0x0063BB00-0x0063BB1F
// symbol    ?teardown_0063bb00@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0063bb00() {
    const uint8_t flags = *TeardownFlags009BEAE0;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009BEAE0 = static_cast<uint8_t>(flags | 1);
    TeardownObject009BEAE8->close();
}

/*
Purpose: sub_63cef0 - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0063CEF0 sub_63cef0 0x0063CEF0-0x0063CEFA BYTE_EXACT
// symbol    ?teardown_0063cef0@@YAXXZ
// size      10 bytes
// prototype 
// callers   1   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0063cef0() {
    TeardownObject009BEAE8->close();
}
