/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "original_seam.h"
#include "guarded_teardowns.h"
#include "statuswin.h"
#include "sprite.h"
#include "planwin.h"
#include "console.h"
#include "mapwin.h"
#include "graphicwin.h"

/*
 * Once-guarded teardown thunks - was generated by
 * tools/generate_guarded_teardowns.py, WHICH NO LONGER EXISTS: commit 271114cf retired
 * eleven bulk generators as "9,262 lines that nobody could run". EDIT THIS
 * FILE DIRECTLY. The old instruction to edit the generator instead survived
 * the generator by months and told every reader not to touch this file in the
 * only way it can now be touched.
 *
 * 25 ??__F bodies that tear a global down AT MOST ONCE, gated on a bit in a
 * shared flag byte. The teardown runs only when the bit is CLEAR, and the bit
 * is set BEFORE the call rather than after. Flag bytes are shared: three
 * FileWin sprites use bits 1, 2 and 4 of one byte, so the mask belongs to the
 * function and is never inferred from the object.
 *
 * Flags and objects are BOUND rather than inlined. Both live in the original
 * image and are unmapped in a standalone test process.
 */

func_thiscall_teardown TeardownTarget00420F90 =
    original_method<func_thiscall_teardown>(0x00420F90);
func_thiscall_teardown TeardownTarget004327A0 =
    original_method<func_thiscall_teardown>(0x004327A0);
func_thiscall_teardown TeardownTarget0048BD80 =
    original_method<func_thiscall_teardown>(0x0048BD80);
func_thiscall_teardown TeardownTarget0051D9F0 =
    original_method<func_thiscall_teardown>(0x0051D9F0);
func_thiscall_teardown TeardownTarget005D4DD0 =
    original_method<func_thiscall_teardown>(0x005D4DD0);
void __fastcall sprite_close_default(void *object) {
    static_cast<Sprite *>(object)->close();
}

/*
Purpose: ?timer_callback_daemon@BattleWin@@QAAXHH@Z - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00422EB0 ?timer_callback_daemon@BattleWin@@QAAXHH@Z 0x00422EB0-0x00422EBA BYTE_EXACT
// symbol    ?teardown_00422eb0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00422eb0() {
    sub_interface_global()->release_iface_mode();
}

/*
Purpose: ?timer_callback_daemon@BattleWin@@QAAXH@Z - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00422EC0 ?timer_callback_daemon@BattleWin@@QAAXH@Z 0x00422EC0-0x00422ECA BYTE_EXACT
// symbol    ?teardown_00422ec0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00422ec0() {
    sub_interface_global()->release_iface_mode();
}

/*
Purpose: ?passover_callback@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x004456A0 ?passover_callback@@YAXXZ 0x004456A0-0x004456AA BYTE_EXACT
// symbol    ?teardown_004456a0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
// BODY IN guarded_teardowns.h, as `MEASURED inline`: the image writes it out at
// some call sites and calls it at others, and a .cpp definition is only ever
// one of those. The marker stays here because that is where the catalogue
// reads it.


/*
Purpose: ??__Fg_MAPWIN@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x004620A0 ??__Fg_MAPWIN@@YAXXZ 0x004620A0-0x004620B4 BYTE_EXACT
// symbol    ?teardown_g_mapwin@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x00420F90
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_mapwin() {
    reinterpret_cast<MapWin *>(TeardownObject007F5ACC)->MapWin::~MapWin();
    reinterpret_cast<GraphicWin *>(TeardownObject007F5ACC)->GraphicWin::~GraphicWin();
}

/*
Purpose: ??__Fg_PLANWIN@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0048AE20 ??__Fg_PLANWIN@@YAXXZ 0x0048AE20-0x0048AE34 BYTE_EXACT
// symbol    ?teardown_g_planwin@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x0048BD80
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_planwin() {
    reinterpret_cast<PlanWin *>(TeardownObject00856DC0)->PlanWin::~PlanWin();
    reinterpret_cast<GraphicWin *>(TeardownObject00856DC0)->GraphicWin::~GraphicWin();
}

/*
Purpose: ??__Eg_BOOM_BUFFER1@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00505D20 ??__Eg_BOOM_BUFFER1@@YAXXZ 0x00505D20-0x00505D2A BYTE_EXACT
// symbol    ?teardown_00505d20@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00505d20() {
    TeardownObject00915068->Buffer::~Buffer();
}

/*
Purpose: ??__Eg_BOOM_FLIC@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00505D30 ??__Eg_BOOM_FLIC@@YAXXZ 0x00505D30-0x00505D3A BYTE_EXACT
// symbol    ?teardown_00505d30@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00505d30() {
    reinterpret_cast<Flic *>(TeardownObject0090EA68)->Flic::~Flic();
}

/*
Purpose: ??__Fg_CONSOLE@@YAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0050E870 ??__Fg_CONSOLE@@YAXXZ 0x0050E870-0x0050E884 BYTE_EXACT
// symbol    ?teardown_g_console@@YAXXZ
// size      20 bytes
// prototype 
// callers   0   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x0051D9F0
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_g_console() {
    reinterpret_cast<Console *>(TeardownObject00939444)->Console::~Console();
    reinterpret_cast<GraphicWin *>(TeardownObject00939444)->GraphicWin::~GraphicWin();
}

/*
Purpose: sub_589890 - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x00589890 sub_589890 0x00589890-0x0058989A BYTE_EXACT
// symbol    ?teardown_00589890@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_00589890() {
    // THIS SITE is why `convert_seams --dtors` refused PopupDtorTarget: it read
    // the seam as a VALUE through `original_address`, so the pointer could not
    // be retired while it stood. It is a named destructor call now.
    reinterpret_cast<Popup *>(TeardownObject009403E0)->Popup::~Popup();
}





/*
Purpose: sub_5eb3b0 - tear down the global at 0x9b7490 through
         ??1Buffer@@QAE@XZ, at most once, gated on bit 2 of the flag byte
         at 0x9b6e30.
// ORIGINAL: 0x005EB3B0 sub_5eb3b0 0x005EB3B0-0x005EB3CF
// symbol    ?teardown_005eb3b0@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_005eb3b0() {
    const uint8_t flags = *TeardownFlags009B6E30;
    if ((2 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009B6E30 = static_cast<uint8_t>(flags | 2);
    TeardownObject009B7490->Buffer::~Buffer();
}





/*
Purpose: ?close_class@RadioButton@@QAAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0060E5D0 ?close_class@RadioButton@@QAAXXZ 0x0060E5D0-0x0060E5E4 BYTE_EXACT
// symbol    ?teardown_0060e5d0@@YAXXZ
// size      20 bytes
// prototype 
// callers   1   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x005E3820
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0060e5d0() {
    g_RADIOBUTTON_SPRITE_2.close();
    g_RADIOBUTTON_SPRITE_1.close();
}





/*
Purpose: ?close_class@CheckBox@@QAAXXZ - run 2 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0060FD60 ?close_class@CheckBox@@QAAXXZ 0x0060FD60-0x0060FD74 BYTE_EXACT
// symbol    ?teardown_0060fd60@@YAXXZ
// size      20 bytes
// prototype 
// callers   1   call targets   1
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     0x005E3820
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0060fd60() {
    g_CHECKBOX_SPRITE_1.close();
    g_CHECKBOX_SPRITE_2.close();
}











/*
Purpose: sub_63bb00 - tear down the global at 0x9beae8 through
         ?close@Sprite@@QAEXXZ, at most once, gated on bit 1 of the flag byte
         at 0x9beae0.
// ORIGINAL: 0x0063BB00 sub_63bb00 0x0063BB00-0x0063BB1F
// symbol    ?teardown_0063bb00@@YAXXZ
// size      31 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0063bb00() {
    const uint8_t flags = *TeardownFlags009BEAE0;
    if ((1 & flags) != 0) {
        return;
    }
    // Set BEFORE the teardown, not after: the original stores at the
    // instruction preceding its tail jump.
    *TeardownFlags009BEAE0 = static_cast<uint8_t>(flags | 1);
    TeardownObject009BEAE8->close();
}

/*
Purpose: sub_63cef0 - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x0063CEF0 sub_63cef0 0x0063CEF0-0x0063CEFA BYTE_EXACT
// symbol    ?teardown_0063cef0@@YAXXZ
// size      10 bytes
// prototype 
// callers   1   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __cdecl teardown_0063cef0() {
    TeardownObject009BEAE8->close();
}
