/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once
#include "vector_teardown.h"
#include "statuswin.h"
#include "popup.h"
#include "init_thunks.h"
#include "deleting_thunks.h"
#include "sprite.h"
#include "atexit_thunks.h"
#include "buffer.h"

/*
 * Once-guarded teardown thunks - GENERATED by
 * tools/generate_guarded_teardowns.py. Do not edit by hand; edit the
 * generator and regenerate.
 *
 * 25 ??__F bodies that tear a global down AT MOST ONCE, gated on a bit in a
 * shared flag byte. The teardown runs only when the bit is CLEAR, and the bit
 * is set BEFORE the call rather than after. Flag bytes are shared: three
 * FileWin sprites use bits 1, 2 and 4 of one byte, so the mask belongs to the
 * function and is never inferred from the object.
 *
 * Flags and objects are BOUND rather than inlined. Both live in the original
 * image and are unmapped in a standalone test process.
 */

uint8_t *const TeardownFlags009B37CC = (uint8_t *)0x009B37CC;
uint8_t *const TeardownFlags009B6E30 = (uint8_t *)0x009B6E30;
uint8_t *const TeardownFlags009B8EF0 = (uint8_t *)0x009B8EF0;
uint8_t *const TeardownFlags009B8F58 = (uint8_t *)0x009B8F58;
uint8_t *const TeardownFlags009B9014 = (uint8_t *)0x009B9014;
uint8_t *const TeardownFlags009B9104 = (uint8_t *)0x009B9104;
uint8_t *const TeardownFlags009BEAE0 = (uint8_t *)0x009BEAE0;
void *const TeardownObject007F5ACC = (void *)0x007F5ACC;
void *const TeardownObject00856DC0 = (void *)0x00856DC0;
void *const TeardownObject0090EA68 = (void *)0x0090EA68;
Buffer *const TeardownObject00915068 = (Buffer *)0x00915068;
void *const TeardownObject00939444 = (void *)0x00939444;
void *const TeardownObject009403E0 = (void *)0x009403E0;
Buffer *const TeardownObject009B7490 = (Buffer *)0x009B7490;
Sprite *const TeardownObject009BEAE8 = (Sprite *)0x009BEAE8;
extern func_thiscall_teardown TeardownTarget00420F90;
extern func_thiscall_teardown TeardownTarget004327A0;
extern func_thiscall_teardown TeardownTarget0048BD80;
extern func_thiscall_teardown TeardownTarget0051D9F0;
extern func_thiscall_teardown TeardownTarget005D4DD0;
extern func_thiscall_teardown TeardownTarget005E3820;

void __cdecl teardown_00422eb0();
void __cdecl teardown_00422ec0();
void __cdecl teardown_g_mapwin();
void __cdecl teardown_g_planwin();
void __cdecl teardown_00505d20();
void __cdecl teardown_00505d30();
void __cdecl teardown_g_console();
void __cdecl teardown_00589890();
void __cdecl teardown_g_buffer_sprite();
void __cdecl teardown_g_win_buffer();
void __cdecl teardown_005eb3b0();
void __cdecl teardown_g_radiobutton_sprite_1();
void __cdecl teardown_g_radiobutton_sprite_2();
void __cdecl teardown_0060e5d0();
void __cdecl teardown_g_checkbox_sprite_1();
void __cdecl teardown_g_checkbox_sprite_2();
void __cdecl teardown_0060fd60();
void __cdecl teardown_g_filewin_sprite_1();
void __cdecl teardown_g_filewin_sprite_2();
void __cdecl teardown_g_filewin_sprite_3();
void __cdecl teardown_g_caviar_buffer_1();
void __cdecl teardown_g_caviar_buffer_2();
void __cdecl teardown_0063bb00();
void __cdecl teardown_0063cef0();

/*
Purpose: ?passover_callback@@YAXXZ - run 1 (ORIGINAL(s)->*teardown)() on fixed globals,
         unguarded. The last is a tail jump in the original, so its
         return goes straight to this function's caller.
// ORIGINAL: 0x004456A0 ?passover_callback@@YAXXZ 0x004456A0-0x004456AA
// symbol    ?teardown_004456a0@@YAXXZ
// size      10 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
MEASURED inline void __cdecl teardown_004456a0() {
    (ORIGINAL(g_PASSOVER_WAVE)->*original_method<func_thiscall_teardown>(original_address(PopupWavePlay)))();
}
