/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once

/*
 * GENERATED by tools/emit_hypothesis_layouts.py. Do not edit; edit the
 * generator, or promote a class out of this file into one of its own.
 *
 * Classes the binary has and the rest of src/ does not declare. Their
 * offsets come from the IDA database and the Thinker mod, and they are
 * HYPOTHESES: no member here is proved against the image.
 *
 * There is deliberately no static_assert. A compile-time size assertion
 * is believed by everything downstream and checked by nothing, so it
 * needs derive_class_layout.py --score-csv at zero wrong first - and
 * these sizes cannot pass it. The IDB's offsets ACCUMULATE from member
 * sizes, so one member nobody entered shifts every member after it:
 * PullDown records a single member of 0xa14 against a true 0xf40.
 *
 * Because there is no assertion, class_layouts.pinned_layouts() does not
 * read these, so none of them can reach an agent as a proved layout or
 * enter verified-layouts.txt by verifying against itself.
 *
 * Every member is raw storage rather than another class by value.
 * BaseButton's first member is 0xa14 bytes and is a GraphicWin, but
 * declaring it as one would make these classes depend on each other and
 * on emission order - by-value layout members once broke 675 units and
 * alphabetical order 77 more. A byte array holds the same offsets and
 * depends on nothing.
 */

#include "stdafx.h"

/* 0x72 bytes, 9 member(s), 1 named. From the IDB. 3 function(s) in the image. */
class AAmbience {
 public:
  uint8_t ambience_[0x58];  // 0x0
  uint32_t field_58_;  // 0x58
  uint32_t field_5C_;  // 0x5C
  uint32_t field_60_;  // 0x60
  uint32_t field_64_;  // 0x64
  uint32_t field_68_;  // 0x68
  uint8_t field_6C_;  // 0x6C
  uint8_t field_6D_;  // 0x6D
  uint32_t field_6E_;  // 0x6E
};

/* 0x6058 bytes, 8 member(s), 8 named. From the IDB. 15 function(s) in the image. */
class AlphaSave {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint8_t fileWin_[0x33C4];  // 0xA14
  uint8_t scroll_[0x214C];  // 0x3DD8
  uint8_t sprite1_[0x2C];  // 0x5F24
  uint8_t sprites2_[0x84];  // 0x5F50
  uint8_t sprite3_[0x2C];  // 0x5FD4
  uint8_t sprite4_[0x2C];  // 0x6000
  uint8_t sprite5_[0x2C];  // 0x602C
};

/* 0x134 bytes, 71 member(s), 60 named. From Thinker. */
struct BASE {
  uint16_t x_;  // 0x0
  uint16_t y_;  // 0x2
  uint8_t faction_id_;  // 0x4
  uint8_t faction_id_former_;  // 0x5
  uint8_t pop_size_;  // 0x6
  uint8_t assimilation_turns_left_;  // 0x7
  uint8_t nerve_staple_turns_left_;  // 0x8
  uint8_t ai_plan_status_;  // 0x9
  uint8_t visibility_;  // 0xA
  uint8_t factions_pop_size_intel_[0x8];  // 0xB
  uint8_t name_[0x19];  // 0x13
  uint16_t field_2C_;  // 0x2C
  uint16_t field_2E_;  // 0x2E
  uint32_t state_flags_;  // 0x30
  uint32_t event_flags_;  // 0x34
  uint32_t governor_flags_;  // 0x38
  uint32_t nutrients_accumulated_;  // 0x3C
  uint32_t minerals_accumulated_;  // 0x40
  uint32_t production_id_last_;  // 0x44
  uint32_t eco_damage_;  // 0x48
  uint32_t queue_size_;  // 0x4C
  uint8_t queue_items_[0x28];  // 0x50
  uint32_t worked_tiles_;  // 0x78
  uint32_t specialist_total_;  // 0x7C
  uint32_t specialist_adjust_;  // 0x80
  uint8_t specialist_types_[0x8];  // 0x84
  uint8_t facilities_built_[0xC];  // 0x8C
  uint32_t mineral_surplus_final_;  // 0x98
  uint32_t minerals_accumulated_2_;  // 0x9C
  uint32_t field_A0_;  // 0xA0
  uint32_t field_A4_;  // 0xA4
  uint32_t field_A8_;  // 0xA8
  uint32_t field_AC_;  // 0xAC
  uint32_t nutrient_intake_;  // 0xB0
  uint32_t mineral_intake_;  // 0xB4
  uint32_t energy_intake_;  // 0xB8
  uint32_t unused_intake_;  // 0xBC
  uint32_t nutrient_intake_2_;  // 0xC0
  uint32_t mineral_intake_2_;  // 0xC4
  uint32_t energy_intake_2_;  // 0xC8
  uint32_t unused_intake_2_;  // 0xCC
  uint32_t nutrient_surplus_;  // 0xD0
  uint32_t mineral_surplus_;  // 0xD4
  uint32_t energy_surplus_;  // 0xD8
  uint32_t unused_surplus_;  // 0xDC
  uint32_t nutrient_inefficiency_;  // 0xE0
  uint32_t mineral_inefficiency_;  // 0xE4
  uint32_t energy_inefficiency_;  // 0xE8
  uint32_t unused_inefficiency_;  // 0xEC
  uint32_t nutrient_consumption_;  // 0xF0
  uint32_t mineral_consumption_;  // 0xF4
  uint32_t energy_consumption_;  // 0xF8
  uint32_t unused_consumption_;  // 0xFC
  uint32_t economy_total_;  // 0x100
  uint32_t psych_total_;  // 0x104
  uint32_t labs_total_;  // 0x108
  uint32_t field_10C_;  // 0x10C
  uint16_t autoforward_land_base_id_;  // 0x110
  uint16_t autoforward_sea_base_id_;  // 0x112
  uint16_t autoforward_air_base_id_;  // 0x114
  uint16_t field_116_;  // 0x116
  uint32_t talent_total_;  // 0x118
  uint32_t drone_total_;  // 0x11C
  uint32_t superdrone_total_;  // 0x120
  uint32_t random_event_turns_;  // 0x124
  uint32_t nerve_staple_count_;  // 0x128
  uint8_t defend_goal_;  // 0x12C
  uint8_t defend_range_;  // 0x12D
  uint8_t field_12E_;  // 0x12E
  uint8_t field_12F_;  // 0x12F
  uint32_t field_130_;  // 0x130
};

/* 0x7E bytes, 12 member(s), 1 named. From the IDB. 7 function(s) in the image. */
class BAmbience {
 public:
  uint8_t ambience_[0x58];  // 0x0
  uint32_t field_58_;  // 0x58
  uint32_t field_5C_;  // 0x5C
  uint32_t field_60_;  // 0x60
  uint32_t field_64_;  // 0x64
  uint32_t field_68_;  // 0x68
  uint8_t field_6C_;  // 0x6C
  uint8_t field_6D_;  // 0x6D
  uint32_t field_6E_;  // 0x6E
  uint32_t field_72_;  // 0x72
  uint32_t field_76_;  // 0x76
  uint32_t field_7A_;  // 0x7A
};

/* 0x18 bytes, 6 member(s), 6 named. From Thinker. */
struct BItem {
  uint32_t item_id_;  // 0x0
  uint32_t explore_;  // 0x4
  uint32_t discover_;  // 0x8
  uint32_t build_;  // 0xC
  uint32_t conquer_;  // 0x10
  uint32_t energy_;  // 0x14
};

/* 0x1C bytes, 8 member(s), 6 named. From Thinker. */
struct CAbility {
  uint32_t name_;  // 0x0
  uint32_t description_;  // 0x4
  uint32_t abbreviation_;  // 0x8
  uint32_t cost_;  // 0xC
  uint32_t field_10_;  // 0x10
  uint32_t flags_;  // 0x14
  uint16_t preq_tech_;  // 0x18
  uint16_t field_1A_;  // 0x1A
};

/* 0x10 bytes, 8 member(s), 6 named. From Thinker. */
struct CArmor {
  uint32_t name_;  // 0x0
  uint32_t name_short_;  // 0x4
  uint8_t defense_value_;  // 0x8
  uint8_t mode_;  // 0x9
  uint8_t cost_;  // 0xA
  uint8_t field_B_;  // 0xB
  uint16_t preq_tech_;  // 0xC
  uint16_t field_E_;  // 0xE
};

/* 0x18 bytes, 1 member(s), 1 named. From Thinker. */
struct CBonusName {
  uint8_t key_[0x18];  // 0x0
};

/* 0x90 bytes, 33 member(s), 33 named. From Thinker. */
struct CChassis {
  uint32_t offsv1_name_;  // 0x0
  uint32_t offsv2_name_;  // 0x4
  uint32_t offsv_name_lrg_;  // 0x8
  uint32_t defsv1_name_;  // 0xC
  uint32_t defsv2_name_;  // 0x10
  uint32_t defsv_name_lrg_;  // 0x14
  uint32_t offsv1_gender_;  // 0x18
  uint32_t offsv2_gender_;  // 0x1C
  uint32_t offsv_gender_lrg_;  // 0x20
  uint32_t defsv1_gender_;  // 0x24
  uint32_t defsv2_gender_;  // 0x28
  uint32_t defsv_gender_lrg_;  // 0x2C
  uint32_t offsv1_is_plural_;  // 0x30
  uint32_t offsv2_is_plural_;  // 0x34
  uint32_t offsv_is_plural_lrg_;  // 0x38
  uint32_t defsv1_is_plural_;  // 0x3C
  uint32_t defsv2_is_plural_;  // 0x40
  uint32_t defsv_is_plural_lrg_;  // 0x44
  uint8_t speed_;  // 0x48
  uint8_t triad_;  // 0x49
  uint8_t range_;  // 0x4A
  uint8_t cargo_;  // 0x4B
  uint8_t cost_;  // 0x4C
  uint8_t missile_;  // 0x4D
  uint8_t sprite_flag_x_coord_[0x8];  // 0x4E
  uint8_t sprite_flag_y_coord_[0x8];  // 0x56
  uint8_t sprite_unk1_x_coord_[0x8];  // 0x5E
  uint8_t sprite_unk1_y_coord_[0x8];  // 0x66
  uint8_t sprite_unk2_x_coord_[0x8];  // 0x6E
  uint8_t sprite_unk2_y_coord_[0x8];  // 0x76
  uint8_t sprite_unk3_x_coord_[0x8];  // 0x7E
  uint8_t sprite_unk3_y_coord_[0x8];  // 0x86
  uint16_t preq_tech_;  // 0x8E
};

/* 0x1C bytes, 7 member(s), 7 named. From Thinker. */
struct CCitizen {
  uint32_t singular_name_;  // 0x0
  uint32_t plural_name_;  // 0x4
  uint32_t preq_tech_;  // 0x8
  uint32_t obsol_tech_;  // 0xC
  uint32_t econ_bonus_;  // 0x10
  uint32_t psych_bonus_;  // 0x14
  uint32_t labs_bonus_;  // 0x18
};

/* 0x10 bytes, 4 member(s), 4 named. From Thinker. */
struct CCombatMode {
  uint32_t name_;  // 0x0
  uint32_t hyphened_;  // 0x4
  uint32_t abbrev_;  // 0x8
  uint32_t letter_;  // 0xC
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CEnergy {
  uint32_t abbrev_;  // 0x0
  uint32_t name_;  // 0x4
};

/* 0x30 bytes, 12 member(s), 11 named. From Thinker. */
struct CFacility {
  uint32_t name_;  // 0x0
  uint32_t effect_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t cost_;  // 0xC
  uint32_t maint_;  // 0x10
  uint32_t preq_tech_;  // 0x14
  uint32_t free_tech_;  // 0x18
  uint32_t AI_fight_;  // 0x1C
  uint32_t AI_growth_;  // 0x20
  uint32_t AI_tech_;  // 0x24
  uint32_t AI_wealth_;  // 0x28
  uint32_t AI_power_;  // 0x2C
};

/* 0x18 bytes, 6 member(s), 6 named. From Thinker. */
struct CList {
  uint32_t vtable_;  // 0x0
  uint32_t pFirst_;  // 0x4
  uint32_t pCurrent_;  // 0x8
  uint32_t iCount_;  // 0xC
  uint32_t iCurrent_;  // 0x10
  uint32_t poMemAllocator_;  // 0x14
};

/* 0x1C bytes, 7 member(s), 4 named. From Thinker. */
struct CListItem {
  uint32_t field_0_;  // 0x0
  uint32_t pItem_;  // 0x4
  uint32_t p4Alloced_;  // 0x8
  uint32_t pPrev_;  // 0xC
  uint32_t pNext_;  // 0x10
  uint32_t field_14_;  // 0x14
  uint32_t field_18_;  // 0x18
};

/* 0x14 bytes, 5 member(s), 5 named. From Thinker. */
struct CMainMenuItem {
  uint32_t iMenuItemID_;  // 0x0
  uint32_t pszCaption_;  // 0x4
  uint32_t iFlags_;  // 0x8
  uint32_t pszHotKey_;  // 0xC
  uint32_t poSubMenu_;  // 0x10
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CMandate {
  uint32_t name_;  // 0x0
  uint32_t name_caps_;  // 0x4
};

/* 0x14 bytes, 5 member(s), 4 named. From Thinker. */
struct CMenuItem {
  uint32_t pszCaption_;  // 0x0
  uint32_t pszHotKey_;  // 0x4
  uint32_t iMenuID_;  // 0x8
  uint32_t iFlag_;  // 0xC
  uint32_t field_10_;  // 0x10
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CMight {
  uint32_t adj_start_;  // 0x0
  uint32_t adj_;  // 0x4
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CMorale {
  uint32_t name_;  // 0x0
  uint32_t name_lifecycle_;  // 0x4
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CNatural {
  uint32_t name_;  // 0x0
  uint32_t name_short_;  // 0x4
};

/* 0xC bytes, 3 member(s), 3 named. From Thinker. */
struct COrder {
  uint32_t order_;  // 0x0
  uint32_t order_sea_;  // 0x4
  uint32_t letter_;  // 0x8
};

/* 0xC bytes, 3 member(s), 3 named. From Thinker. */
struct CProposal {
  uint32_t name_;  // 0x0
  uint32_t description_;  // 0x4
  uint32_t preq_tech_;  // 0x8
};

/* 0xC bytes, 4 member(s), 4 named. From Thinker. */
struct CReactor {
  uint32_t name_;  // 0x0
  uint32_t name_short_;  // 0x4
  uint16_t preq_tech_;  // 0x8
  uint16_t power_;  // 0xA
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct CResourceName {
  uint32_t name_singular_;  // 0x0
  uint32_t name_plural_;  // 0x4
};

/* 0x134 bytes, 73 member(s), 73 named. From Thinker. */
struct CRules {
  uint32_t move_rate_roads_;  // 0x0
  uint32_t nutrient_intake_req_citizen_;  // 0x4
  uint32_t max_airdrop_rng_wo_orbital_insert_;  // 0x8
  uint32_t artillery_max_rng_;  // 0xC
  uint32_t artillery_dmg_numerator_;  // 0x10
  uint32_t artillery_dmg_denominator_;  // 0x14
  uint32_t nutrient_cost_multi_;  // 0x18
  uint32_t mineral_cost_multi_;  // 0x1C
  uint32_t tech_discovery_rate_;  // 0x20
  uint32_t limit_mineral_inc_for_mine_wo_road_;  // 0x24
  uint32_t nutrient_effect_mine_sq_;  // 0x28
  uint32_t min_base_size_specialists_;  // 0x2C
  uint32_t drones_induced_genejack_factory_;  // 0x30
  uint32_t pop_limit_wo_hab_complex_;  // 0x34
  uint32_t pop_limit_wo_hab_dome_;  // 0x38
  uint32_t tech_preq_improv_fungus_;  // 0x3C
  uint32_t tech_preq_ease_fungus_mov_;  // 0x40
  uint32_t tech_preq_build_road_fungus_;  // 0x44
  uint32_t tech_preq_allow_2_spec_abil_;  // 0x48
  uint32_t tech_preq_allow_3_nutrients_sq_;  // 0x4C
  uint32_t tech_preq_allow_3_minerals_sq_;  // 0x50
  uint32_t tech_preq_allow_3_energy_sq_;  // 0x54
  uint32_t extra_cost_prototype_land_;  // 0x58
  uint32_t extra_cost_prototype_sea_;  // 0x5C
  uint32_t extra_cost_prototype_air_;  // 0x60
  uint8_t psi_combat_ratio_atk_[0xC];  // 0x64
  uint8_t psi_combat_ratio_def_[0xC];  // 0x70
  uint32_t starting_energy_reserve_;  // 0x7C
  uint32_t combat_bonus_intrinsic_base_def_;  // 0x80
  uint32_t combat_bonus_atk_road_;  // 0x84
  uint32_t combat_bonus_atk_higher_elevation_;  // 0x88
  uint32_t combat_penalty_atk_lower_elevation_;  // 0x8C
  uint32_t tech_preq_orb_insert_wo_space_;  // 0x90
  uint32_t min_turns_between_councils_;  // 0x94
  uint32_t minerals_harvesting_forest_;  // 0x98
  uint32_t territory_max_dist_base_;  // 0x9C
  uint32_t turns_corner_global_energy_market_;  // 0xA0
  uint32_t tech_preq_mining_platform_bonus_;  // 0xA4
  uint32_t tech_preq_economic_victory_;  // 0xA8
  uint32_t combat_penalty_atk_airdrop_;  // 0xAC
  uint32_t combat_bonus_fanatic_;  // 0xB0
  uint32_t combat_land_vs_sea_artillery_;  // 0xB4
  uint32_t combat_artillery_bonus_altitude_;  // 0xB8
  uint32_t combat_mobile_open_ground_;  // 0xBC
  uint32_t combat_mobile_def_in_rough_;  // 0xC0
  uint32_t combat_bonus_trance_vs_psi_;  // 0xC4
  uint32_t combat_bonus_empath_song_vs_psi_;  // 0xC8
  uint32_t combat_infantry_vs_base_;  // 0xCC
  uint32_t combat_penalty_air_supr_vs_ground_;  // 0xD0
  uint32_t combat_bonus_air_supr_vs_air_;  // 0xD4
  uint32_t combat_penalty_non_combat_vs_combat_;  // 0xD8
  uint32_t combat_comm_jammer_vs_mobile_;  // 0xDC
  uint32_t combat_bonus_vs_ship_port_;  // 0xE0
  uint32_t combat_aaa_bonus_vs_air_;  // 0xE4
  uint32_t combat_defend_sensor_;  // 0xE8
  uint32_t combat_psi_bonus_per_planet_;  // 0xEC
  uint32_t retool_strictness_;  // 0xF0
  uint32_t retool_penalty_prod_change_;  // 0xF4
  uint32_t retool_exemption_;  // 0xF8
  uint32_t tgl_probe_steal_tech_;  // 0xFC
  uint32_t tgl_humans_always_contact_net_;  // 0x100
  uint32_t tgl_humans_always_contact_pbem_;  // 0x104
  uint32_t max_dmg_percent_arty_base_bunker_;  // 0x108
  uint32_t max_dmg_percent_arty_open_;  // 0x10C
  uint32_t max_dmg_percent_arty_sea_;  // 0x110
  uint32_t freq_global_warming_numerator_;  // 0x114
  uint32_t freq_global_warming_denominator_;  // 0x118
  uint32_t normal_start_year_;  // 0x11C
  uint32_t normal_end_year_low_three_diff_;  // 0x120
  uint32_t normal_end_year_high_three_diff_;  // 0x124
  uint32_t tgl_oblit_base_atrocity_;  // 0x128
  uint32_t base_size_subspace_gen_;  // 0x12C
  uint32_t subspace_gen_req_;  // 0x130
};

/* 0x10 bytes, 4 member(s), 4 named. From Thinker. */
struct CSocialCategory {
  uint32_t politics_;  // 0x0
  uint32_t economics_;  // 0x4
  uint32_t values_;  // 0x8
  uint32_t future_;  // 0xC
};

/* 0x2C bytes, 11 member(s), 11 named. From Thinker. */
struct CSocialEffect {
  uint32_t economy_;  // 0x0
  uint32_t efficiency_;  // 0x4
  uint32_t support_;  // 0x8
  uint32_t talent_;  // 0xC
  uint32_t morale_;  // 0x10
  uint32_t police_;  // 0x14
  uint32_t growth_;  // 0x18
  uint32_t planet_;  // 0x1C
  uint32_t probe_;  // 0x20
  uint32_t industry_;  // 0x24
  uint32_t research_;  // 0x28
};

/* 0x24 bytes, 3 member(s), 3 named. From Thinker. */
struct CSocialField {
  uint32_t field_name_;  // 0x0
  uint8_t soc_preq_tech_[0x10];  // 0x4
  uint8_t soc_name_[0x10];  // 0x14
};

/* 0x68 bytes, 3 member(s), 2 named. From Thinker. */
struct CSocialParam {
  uint8_t set1_[0x18];  // 0x0
  uint8_t set2_[0x18];  // 0x18
  uint8_t field_30_[0x38];  // 0x30
};

/* 0x2C bytes, 10 member(s), 9 named. From Thinker. */
struct CTech {
  uint32_t flags_;  // 0x0
  uint32_t name_;  // 0x4
  uint8_t short_name_[0x8];  // 0x8
  uint32_t field_10_;  // 0x10
  uint32_t AI_growth_;  // 0x14
  uint32_t AI_tech_;  // 0x18
  uint32_t AI_wealth_;  // 0x1C
  uint32_t AI_power_;  // 0x20
  uint32_t preq_tech1_;  // 0x24
  uint32_t preq_tech2_;  // 0x28
};

/* 0x20 bytes, 8 member(s), 8 named. From Thinker. */
struct CTerraform {
  uint32_t name_;  // 0x0
  uint32_t name_sea_;  // 0x4
  uint32_t preq_tech_;  // 0x8
  uint32_t preq_tech_sea_;  // 0xC
  uint32_t bit_;  // 0x10
  uint32_t bit_incompatible_;  // 0x14
  uint32_t rate_;  // 0x18
  uint32_t shortcuts_;  // 0x1C
};

/* 0x20 bytes, 8 member(s), 8 named. From Thinker. */
struct CTimeControl {
  uint32_t name_;  // 0x0
  uint32_t turn_;  // 0x4
  uint32_t base_;  // 0x8
  uint32_t unit_;  // 0xC
  uint32_t event_;  // 0x10
  uint32_t extra_;  // 0x14
  uint32_t refresh_;  // 0x18
  uint32_t accumulated_;  // 0x1C
};

/* 0x10 bytes, 8 member(s), 7 named. From Thinker. */
struct CWeapon {
  uint32_t name_;  // 0x0
  uint32_t name_short_;  // 0x4
  uint8_t offense_value_;  // 0x8
  uint8_t icon_;  // 0x9
  uint8_t mode_;  // 0xA
  uint8_t cost_;  // 0xB
  uint16_t preq_tech_;  // 0xC
  uint16_t field_E_;  // 0xE
};

/* 0x7C bytes, 31 member(s), 31 named. From Thinker. */
struct CWorldbuilder {
  uint32_t land_base_;  // 0x0
  uint32_t land_mod_;  // 0x4
  uint32_t continent_base_;  // 0x8
  uint32_t continent_mod_;  // 0xC
  uint32_t hills_base_;  // 0x10
  uint32_t hills_mod_;  // 0x14
  uint32_t plateau_base_;  // 0x18
  uint32_t plateau_mod_;  // 0x1C
  uint32_t rivers_base_;  // 0x20
  uint32_t rivers_rain_mod_;  // 0x24
  uint32_t solar_energy_;  // 0x28
  uint32_t thermal_band_;  // 0x2C
  uint32_t thermal_deviance_;  // 0x30
  uint32_t global_warming_;  // 0x34
  uint32_t sea_level_rises_;  // 0x38
  uint32_t cloudmass_peaks_;  // 0x3C
  uint32_t cloudmass_hills_;  // 0x40
  uint32_t rainfall_coeff_;  // 0x44
  uint32_t deep_water_;  // 0x48
  uint32_t shelf_;  // 0x4C
  uint32_t plains_;  // 0x50
  uint32_t beach_;  // 0x54
  uint32_t hills_;  // 0x58
  uint32_t peaks_;  // 0x5C
  uint32_t fungus_;  // 0x60
  uint32_t cont_size_ratio1_;  // 0x64
  uint32_t cont_size_ratio2_;  // 0x68
  uint32_t cont_size_ratio3_;  // 0x6C
  uint32_t cont_size_ratio4_;  // 0x70
  uint32_t cont_size_ratio5_;  // 0x74
  uint32_t islands_;  // 0x78
};

/* 0xB74 bytes, 80 member(s), 2 named. From the IDB. 16 function(s) in the image. */
class EditBox {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint32_t field_A54_;  // 0xA54
  uint32_t field_A58_;  // 0xA58
  uint32_t field_A5C_;  // 0xA5C
  uint32_t field_A60_;  // 0xA60
  uint32_t field_A64_;  // 0xA64
  uint32_t field_A68_;  // 0xA68
  uint32_t field_A6C_;  // 0xA6C
  uint32_t field_A70_;  // 0xA70
  uint32_t field_A74_;  // 0xA74
  uint32_t field_A78_;  // 0xA78
  uint32_t field_A7C_;  // 0xA7C
  uint32_t field_A80_;  // 0xA80
  uint32_t field_A84_;  // 0xA84
  uint32_t field_A88_;  // 0xA88
  uint32_t field_A8C_;  // 0xA8C
  uint32_t field_A90_;  // 0xA90
  uint32_t field_A94_;  // 0xA94
  uint32_t field_A98_;  // 0xA98
  uint32_t field_A9C_;  // 0xA9C
  uint32_t field_AA0_;  // 0xAA0
  uint32_t field_AA4_;  // 0xAA4
  uint32_t field_AA8_;  // 0xAA8
  uint32_t field_AAC_;  // 0xAAC
  uint32_t field_AB0_;  // 0xAB0
  uint32_t field_AB4_;  // 0xAB4
  uint32_t field_AB8_;  // 0xAB8
  uint32_t field_ABC_;  // 0xABC
  uint32_t field_AC0_;  // 0xAC0
  uint32_t field_AC4_;  // 0xAC4
  uint32_t field_AC8_;  // 0xAC8
  uint32_t field_ACC_;  // 0xACC
  uint32_t field_AD0_;  // 0xAD0
  uint32_t field_AD4_;  // 0xAD4
  uint32_t field_AD8_;  // 0xAD8
  uint32_t field_ADC_;  // 0xADC
  uint32_t field_AE0_;  // 0xAE0
  uint32_t field_AE4_;  // 0xAE4
  uint32_t field_AE8_;  // 0xAE8
  uint32_t field_AEC_;  // 0xAEC
  uint32_t field_AF0_;  // 0xAF0
  uint32_t field_AF4_;  // 0xAF4
  uint32_t field_AF8_;  // 0xAF8
  uint32_t field_AFC_;  // 0xAFC
  uint32_t field_B00_;  // 0xB00
  uint32_t field_B04_;  // 0xB04
  uint32_t field_B08_;  // 0xB08
  uint32_t field_B0C_;  // 0xB0C
  uint32_t field_B10_;  // 0xB10
  uint32_t field_B14_;  // 0xB14
  uint32_t field_B18_;  // 0xB18
  uint32_t field_B1C_;  // 0xB1C
  uint32_t field_B20_;  // 0xB20
  uint32_t field_B24_;  // 0xB24
  uint32_t field_B28_;  // 0xB28
  uint32_t field_B2C_;  // 0xB2C
  uint32_t field_B30_;  // 0xB30
  uint32_t field_B34_;  // 0xB34
  uint32_t field_B38_;  // 0xB38
  uint32_t field_B3C_;  // 0xB3C
  uint32_t field_B40_;  // 0xB40
  uint32_t field_B44_;  // 0xB44
  uint32_t field_B48_;  // 0xB48
  uint8_t time_[0x28];  // 0xB4C
};

/* 0x6C bytes, 1 member(s), 1 named. From the IDB. 1 function(s) in the image. */
class Effect {
 public:
  uint8_t wave_[0x6C];  // 0x0
};

/* 0x16DC bytes, 175 member(s), 156 named. From Thinker. */
struct Faction {
  uint32_t player_flags_;  // 0x0
  uint32_t ranking_;  // 0x4
  uint32_t diff_level_;  // 0x8
  uint32_t base_name_offset_;  // 0xC
  uint32_t base_sea_name_offset_;  // 0x10
  uint32_t last_base_turn_;  // 0x14
  uint8_t diplo_status_[0x20];  // 0x18
  uint8_t diplo_agenda_[0x20];  // 0x38
  uint8_t diplo_friction_[0x20];  // 0x58
  uint8_t diplo_spoke_[0x20];  // 0x78
  uint8_t diplo_merc_[0x20];  // 0x98
  uint8_t diplo_patience_[0x8];  // 0xB8
  uint32_t sanction_turns_;  // 0xC0
  uint8_t loan_balance_[0x20];  // 0xC4
  uint8_t loan_payment_[0x20];  // 0xE4
  uint8_t field_104_[0x20];  // 0x104
  uint32_t integrity_blemishes_;  // 0x124
  uint32_t diplo_reputation_;  // 0x128
  uint8_t diplo_gifts_[0x20];  // 0x12C
  uint8_t diplo_wrongs_[0x20];  // 0x14C
  uint8_t diplo_betrayed_[0x20];  // 0x16C
  uint8_t diplo_unk_3_[0x20];  // 0x18C
  uint8_t diplo_unk_4_[0x20];  // 0x1AC
  uint32_t traded_maps_;  // 0x1CC
  uint32_t base_governor_adv_;  // 0x1D0
  uint32_t atrocities_;  // 0x1D4
  uint32_t major_atrocities_;  // 0x1D8
  uint32_t mind_control_total_;  // 0x1DC
  uint8_t diplo_mind_control_[0x20];  // 0x1E0
  uint8_t diplo_stolen_techs_[0x20];  // 0x200
  uint32_t energy_credits_;  // 0x220
  uint32_t hurry_cost_total_;  // 0x224
  uint32_t SE_Politics_pending_;  // 0x228
  uint32_t SE_Economics_pending_;  // 0x22C
  uint32_t SE_Values_pending_;  // 0x230
  uint32_t SE_Future_pending_;  // 0x234
  uint32_t SE_Politics_;  // 0x238
  uint32_t SE_Economics_;  // 0x23C
  uint32_t SE_Values_;  // 0x240
  uint32_t SE_Future_;  // 0x244
  uint32_t SE_upheaval_cost_paid_;  // 0x248
  uint32_t SE_economy_pending_;  // 0x24C
  uint32_t SE_effic_pending_;  // 0x250
  uint32_t SE_support_pending_;  // 0x254
  uint32_t SE_talent_pending_;  // 0x258
  uint32_t SE_morale_pending_;  // 0x25C
  uint32_t SE_police_pending_;  // 0x260
  uint32_t SE_growth_pending_;  // 0x264
  uint32_t SE_planet_pending_;  // 0x268
  uint32_t SE_probe_pending_;  // 0x26C
  uint32_t SE_industry_pending_;  // 0x270
  uint32_t SE_research_pending_;  // 0x274
  uint32_t SE_economy_;  // 0x278
  uint32_t SE_effic_;  // 0x27C
  uint32_t SE_support_;  // 0x280
  uint32_t SE_talent_;  // 0x284
  uint32_t SE_morale_;  // 0x288
  uint32_t SE_police_;  // 0x28C
  uint32_t SE_growth_;  // 0x290
  uint32_t SE_planet_;  // 0x294
  uint32_t SE_probe_;  // 0x298
  uint32_t SE_industry_;  // 0x29C
  uint32_t SE_research_;  // 0x2A0
  uint32_t SE_economy_2_;  // 0x2A4
  uint32_t SE_effic_2_;  // 0x2A8
  uint32_t SE_support_2_;  // 0x2AC
  uint32_t SE_talent_2_;  // 0x2B0
  uint32_t SE_morale_2_;  // 0x2B4
  uint32_t SE_police_2_;  // 0x2B8
  uint32_t SE_growth_2_;  // 0x2BC
  uint32_t SE_planet_2_;  // 0x2C0
  uint32_t SE_probe_2_;  // 0x2C4
  uint32_t SE_industry_2_;  // 0x2C8
  uint32_t SE_research_2_;  // 0x2CC
  uint32_t SE_economy_base_;  // 0x2D0
  uint32_t SE_effic_base_;  // 0x2D4
  uint32_t SE_support_base_;  // 0x2D8
  uint32_t SE_talent_base_;  // 0x2DC
  uint32_t SE_morale_base_;  // 0x2E0
  uint32_t SE_police_base_;  // 0x2E4
  uint32_t SE_growth_base_;  // 0x2E8
  uint32_t SE_planet_base_;  // 0x2EC
  uint32_t SE_probe_base_;  // 0x2F0
  uint32_t SE_industry_base_;  // 0x2F4
  uint32_t SE_research_base_;  // 0x2F8
  uint32_t energy_surplus_total_;  // 0x2FC
  uint32_t facility_maint_total_;  // 0x300
  uint32_t tech_commerce_bonus_;  // 0x304
  uint32_t turn_commerce_income_;  // 0x308
  uint32_t field_30C_;  // 0x30C
  uint32_t field_310_;  // 0x310
  uint32_t tech_fungus_nutrient_;  // 0x314
  uint32_t tech_fungus_mineral_;  // 0x318
  uint32_t tech_fungus_energy_;  // 0x31C
  uint32_t tech_fungus_unused_;  // 0x320
  uint32_t SE_alloc_psych_;  // 0x324
  uint32_t SE_alloc_labs_;  // 0x328
  uint8_t tech_pact_shared_goals_[0x30];  // 0x32C
  uint32_t tech_ranking_;  // 0x35C
  uint32_t field_360_;  // 0x360
  uint32_t ODP_deployed_;  // 0x364
  uint32_t tech_count_transcendent_;  // 0x368
  uint8_t tech_trade_source_[0x5C];  // 0x36C
  uint32_t tech_accumulated_;  // 0x3C8
  uint32_t tech_research_id_;  // 0x3CC
  uint32_t tech_cost_;  // 0x3D0
  uint32_t earned_techs_saved_;  // 0x3D4
  uint32_t net_random_event_;  // 0x3D8
  uint32_t AI_fight_;  // 0x3DC
  uint32_t AI_growth_;  // 0x3E0
  uint32_t AI_tech_;  // 0x3E4
  uint32_t AI_wealth_;  // 0x3E8
  uint32_t AI_power_;  // 0x3EC
  uint32_t target_x_;  // 0x3F0
  uint32_t target_y_;  // 0x3F4
  uint32_t best_mineral_output_;  // 0x3F8
  uint32_t council_call_turn_;  // 0x3FC
  uint8_t field_400_[0x2C];  // 0x400
  uint8_t field_42C_[0x2C];  // 0x42C
  uint8_t facility_announced_[0xC];  // 0x458
  uint32_t clean_minerals_modifier_;  // 0x464
  uint32_t base_id_attack_target_;  // 0x468
  uint32_t field_46C_;  // 0x46C
  uint8_t saved_queue_size_[0x20];  // 0x470
  uint8_t social_support_[0x20];  // 0x490
  uint8_t social_effic_[0x24];  // 0x4B0
  uint32_t field_4D4_;  // 0x4D4
  uint32_t field_4D8_;  // 0x4D8
  uint32_t field_4DC_;  // 0x4DC
  uint32_t nutrient_surplus_total_;  // 0x4E0
  uint32_t labs_total_;  // 0x4E4
  uint32_t satellites_nutrient_;  // 0x4E8
  uint32_t satellites_mineral_;  // 0x4EC
  uint32_t satellites_energy_;  // 0x4F0
  uint32_t satellites_ODP_;  // 0x4F4
  uint32_t best_weapon_value_;  // 0x4F8
  uint32_t best_psi_land_offense_;  // 0x4FC
  uint32_t best_psi_land_defense_;  // 0x500
  uint32_t best_armor_value_;  // 0x504
  uint32_t best_land_speed_;  // 0x508
  uint32_t enemy_best_weapon_value_;  // 0x50C
  uint32_t enemy_best_armor_value_;  // 0x510
  uint32_t enemy_best_land_speed_;  // 0x514
  uint32_t enemy_best_psi_land_offense_;  // 0x518
  uint32_t enemy_best_psi_land_defense_;  // 0x51C
  uint32_t field_520_;  // 0x520
  uint32_t field_524_;  // 0x524
  uint32_t field_528_;  // 0x528
  uint32_t field_52C_;  // 0x52C
  uint32_t field_530_;  // 0x530
  uint32_t field_534_;  // 0x534
  uint8_t units_active_[0x200];  // 0x538
  uint8_t units_queue_[0x200];  // 0x738
  uint8_t units_lost_[0x400];  // 0x938
  uint32_t total_combat_units_;  // 0xD38
  uint32_t base_count_;  // 0xD3C
  uint32_t mil_strength_1_;  // 0xD40
  uint32_t mil_strength_2_;  // 0xD44
  uint32_t pop_total_;  // 0xD48
  uint32_t field_D4C_;  // 0xD4C
  uint32_t planet_busters_;  // 0xD50
  uint32_t field_D54_;  // 0xD54
  uint32_t field_D58_;  // 0xD58
  uint8_t region_total_combat_units_[0x100];  // 0xD5C
  uint8_t region_total_bases_[0x80];  // 0xE5C
  uint8_t region_total_offensive_units_[0x80];  // 0xEDC
  uint8_t region_force_rating_[0x100];  // 0xF5C
  uint8_t region_flags_[0x100];  // 0x105C
  uint8_t region_territory_tiles_[0x100];  // 0x115C
  uint8_t region_visible_tiles_[0x100];  // 0x125C
  uint8_t region_good_tiles_[0x100];  // 0x135C
  uint8_t region_unk_5_[0x100];  // 0x145C
  uint8_t region_unk_6_[0x80];  // 0x155C
  uint8_t region_territory_pods_[0x80];  // 0x15DC
  uint8_t region_base_plan_[0x80];  // 0x165C
};

/* 0xB69C bytes, 49 member(s), 10 named. From the IDB. 9 function(s) in the image. */
class FameWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t factionID_;  // 0xA4C
  uint8_t spot_[0xC];  // 0xA50
  uint8_t flatButtons1_[0x4F14];  // 0xA5C
  uint8_t buttonGroup_[0x94];  // 0x5970
  uint8_t flatButtons2_[0x43C8];  // 0x5A04
  uint8_t flatButton3_[0xB4C];  // 0x9DCC
  uint32_t field_A918_;  // 0xA918
  uint8_t buffer1_[0x588];  // 0xA91C
  uint8_t buffer2_[0x588];  // 0xAEA4
  uint32_t field_B42C_;  // 0xB42C
  uint32_t field_B430_;  // 0xB430
  uint32_t field_B434_;  // 0xB434
  uint32_t field_B438_;  // 0xB438
  uint32_t field_B43C_;  // 0xB43C
  uint32_t field_B440_;  // 0xB440
  uint32_t field_B444_;  // 0xB444
  uint32_t field_B448_;  // 0xB448
  uint32_t field_B44C_;  // 0xB44C
  uint32_t field_B450_;  // 0xB450
  uint32_t field_B454_;  // 0xB454
  uint32_t field_B458_;  // 0xB458
  uint32_t field_B45C_;  // 0xB45C
  uint32_t field_B460_;  // 0xB460
  uint32_t field_B464_;  // 0xB464
  uint32_t field_B468_;  // 0xB468
  uint32_t field_B46C_;  // 0xB46C
  uint32_t field_B470_;  // 0xB470
  uint32_t field_B474_;  // 0xB474
  uint32_t field_B478_;  // 0xB478
  uint32_t field_B47C_;  // 0xB47C
  uint32_t field_B480_;  // 0xB480
  uint32_t field_B484_;  // 0xB484
  uint32_t field_B488_;  // 0xB488
  uint8_t sprites_[0x210];  // 0xB48C
};

/* 0x41C bytes, 7 member(s), 4 named. From the IDB. 7 function(s) in the image. */
class FileBox {
 public:
  uint8_t field_0_[0x104];  // 0x0
  uint8_t def_name_[0x104];  // 0x104
  uint8_t field_208_[0x104];  // 0x208
  uint8_t filter_[0x104];  // 0x30C
  uint32_t ptrFilter_;  // 0x410
  uint32_t def_ext_;  // 0x414
  uint32_t field_418_;  // 0x418
};

/* 0x500 bytes, 5 member(s), 5 named. From Thinker. */
struct FileFindPath {
  uint8_t cd_path_[0x100];  // 0x0
  uint8_t alt_path_[0x100];  // 0x100
  uint8_t last_path_[0x100];  // 0x200
  uint8_t exe_dir_[0x100];  // 0x300
  uint8_t relative_path_[0x100];  // 0x400
};

/* 0xABC bytes, 2 member(s), 1 named. From the IDB. 3 function(s) in the image. */
class ImageButton {
 public:
  uint8_t baseButton_[0xAB8];  // 0x0
  uint32_t field_AB8_;  // 0xAB8
};

/* 0xFDC bytes, 18 member(s), 2 named. From the IDB. 5 function(s) in the image. */
class Interlude {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint8_t buffer_[0x588];  // 0xA54
};

/* 0x14 bytes, 5 member(s), 5 named. From Thinker. */
struct ListNode {
  uint32_t vtable_;  // 0x0
  uint32_t tagged_id_;  // 0x4
  uint32_t obj_;  // 0x8
  uint32_t next_;  // 0xC
  uint32_t prev_;  // 0x10
};

/* 0x18 bytes, 6 member(s), 5 named. From Thinker. */
struct ListRoot {
  uint32_t vtable_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t first_;  // 0x8
  uint32_t current_;  // 0xC
  uint32_t cur_count_;  // 0x10
  uint32_t last_index_;  // 0x14
};

/* 0x2C bytes, 11 member(s), 10 named. From Thinker. */
struct MAP {
  uint8_t climate_;  // 0x0
  uint8_t contour_;  // 0x1
  uint8_t val2_;  // 0x2
  uint8_t region_;  // 0x3
  uint8_t visibility_;  // 0x4
  uint8_t val3_;  // 0x5
  uint8_t field_6_;  // 0x6
  uint8_t owner_;  // 0x7
  uint32_t items_;  // 0x8
  uint32_t landmarks_;  // 0xC
  uint8_t visible_items_[0x1C];  // 0x10
};

/* 0x46C bytes, 7 member(s), 2 named. From the IDB. 6 function(s) in the image. */
class MCIVideo {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t mciId_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
  uint8_t palette_[0x454];  // 0x10
  uint32_t field_464_;  // 0x464
  uint32_t field_468_;  // 0x468
};

/* 0x59C bytes, 55 member(s), 53 named. From Thinker. */
struct MFaction {
  uint32_t is_leader_female_;  // 0x0
  uint8_t filename_[0x18];  // 0x4
  uint8_t search_key_[0x18];  // 0x1C
  uint8_t name_leader_[0x18];  // 0x34
  uint8_t title_leader_[0x18];  // 0x4C
  uint8_t adj_leader_[0x80];  // 0x64
  uint8_t adj_insult_leader_[0x80];  // 0xE4
  uint8_t adj_faction_[0x80];  // 0x164
  uint8_t adj_insult_faction_[0x80];  // 0x1E4
  uint8_t thinker_unused_[0xC];  // 0x264
  uint8_t thinker_probe_lost_;  // 0x270
  uint8_t thinker_probe_renew_;  // 0x271
  uint16_t thinker_last_mc_turn_;  // 0x272
  uint8_t thinker_probe_end_turn_[0x10];  // 0x274
  uint8_t field_284_[0x60];  // 0x284
  uint8_t noun_faction_[0x18];  // 0x2E4
  uint32_t noun_gender_;  // 0x2FC
  uint32_t is_noun_plural_;  // 0x300
  uint8_t adj_name_faction_[0x80];  // 0x304
  uint8_t formal_name_faction_[0x28];  // 0x384
  uint8_t insult_leader_[0x18];  // 0x3AC
  uint8_t desc_name_faction_[0x18];  // 0x3C4
  uint8_t assistant_name_[0x18];  // 0x3DC
  uint8_t scientist_name_[0x18];  // 0x3F4
  uint8_t assistant_city_[0x18];  // 0x40C
  uint8_t field_424_[0xB0];  // 0x424
  uint32_t rule_tech_selected_;  // 0x4D4
  uint32_t rule_morale_;  // 0x4D8
  uint32_t rule_research_;  // 0x4DC
  uint32_t rule_drone_;  // 0x4E0
  uint32_t rule_talent_;  // 0x4E4
  uint32_t rule_energy_;  // 0x4E8
  uint32_t rule_interest_;  // 0x4EC
  uint32_t rule_population_;  // 0x4F0
  uint32_t rule_hurry_;  // 0x4F4
  uint32_t rule_techcost_;  // 0x4F8
  uint32_t rule_psi_;  // 0x4FC
  uint32_t rule_sharetech_;  // 0x500
  uint32_t rule_commerce_;  // 0x504
  uint32_t rule_flags_;  // 0x508
  uint32_t faction_bonus_count_;  // 0x50C
  uint8_t faction_bonus_id_[0x20];  // 0x510
  uint8_t faction_bonus_val1_[0x20];  // 0x530
  uint8_t faction_bonus_val2_[0x20];  // 0x550
  uint32_t AI_fight_;  // 0x570
  uint32_t AI_growth_;  // 0x574
  uint32_t AI_tech_;  // 0x578
  uint32_t AI_wealth_;  // 0x57C
  uint32_t AI_power_;  // 0x580
  uint32_t soc_priority_category_;  // 0x584
  uint32_t soc_opposition_category_;  // 0x588
  uint32_t soc_priority_model_;  // 0x58C
  uint32_t soc_opposition_model_;  // 0x590
  uint32_t soc_priority_effect_;  // 0x594
  uint32_t soc_opposition_effect_;  // 0x598
};

/* 0xC bytes, 3 member(s), 3 named. From Thinker. */
struct MapNode {
  uint32_t x_;  // 0x0
  uint32_t y_;  // 0x4
  uint32_t type_;  // 0x8
};

/* 0x10 bytes, 4 member(s), 4 named. From Thinker. */
struct MapTile {
  uint32_t x_;  // 0x0
  uint32_t y_;  // 0x4
  uint32_t i_;  // 0x8
  uint32_t sq_;  // 0xC
};

/* 0x366C bytes, 122 member(s), 13 named. From the IDB. 7 function(s) in the image. */
class MonuWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint32_t field_A54_;  // 0xA54
  uint8_t flatButton1_[0xB4C];  // 0xA58
  uint8_t flatButton2_[0xB4C];  // 0x15A4
  uint8_t spot_[0xC];  // 0x20F0
  uint8_t buffer1_[0x588];  // 0x20FC
  uint8_t buffer2_[0x588];  // 0x2684
  uint8_t sprites1_[0x294];  // 0x2C0C
  uint8_t sprites2_[0x294];  // 0x2EA0
  uint32_t field_3134_;  // 0x3134
  uint32_t field_3138_;  // 0x3138
  uint32_t field_313C_;  // 0x313C
  uint32_t field_3140_;  // 0x3140
  uint32_t field_3144_;  // 0x3144
  uint32_t field_3148_;  // 0x3148
  uint32_t field_314C_;  // 0x314C
  uint32_t field_3150_;  // 0x3150
  uint32_t field_3154_;  // 0x3154
  uint32_t field_3158_;  // 0x3158
  uint32_t field_315C_;  // 0x315C
  uint32_t field_3160_;  // 0x3160
  uint32_t field_3164_;  // 0x3164
  uint32_t field_3168_;  // 0x3168
  uint32_t field_316C_;  // 0x316C
  uint32_t field_3170_;  // 0x3170
  uint32_t field_3174_;  // 0x3174
  uint32_t field_3178_;  // 0x3178
  uint32_t field_317C_;  // 0x317C
  uint32_t field_3180_;  // 0x3180
  uint32_t field_3184_;  // 0x3184
  uint32_t field_3188_;  // 0x3188
  uint32_t field_318C_;  // 0x318C
  uint32_t field_3190_;  // 0x3190
  uint32_t field_3194_;  // 0x3194
  uint32_t field_3198_;  // 0x3198
  uint32_t field_319C_;  // 0x319C
  uint32_t field_31A0_;  // 0x31A0
  uint32_t field_31A4_;  // 0x31A4
  uint32_t field_31A8_;  // 0x31A8
  uint32_t field_31AC_;  // 0x31AC
  uint32_t field_31B0_;  // 0x31B0
  uint32_t field_31B4_;  // 0x31B4
  uint32_t field_31B8_;  // 0x31B8
  uint32_t field_31BC_;  // 0x31BC
  uint32_t field_31C0_;  // 0x31C0
  uint32_t field_31C4_;  // 0x31C4
  uint32_t field_31C8_;  // 0x31C8
  uint32_t field_31CC_;  // 0x31CC
  uint32_t field_31D0_;  // 0x31D0
  uint32_t field_31D4_;  // 0x31D4
  uint32_t field_31D8_;  // 0x31D8
  uint32_t field_31DC_;  // 0x31DC
  uint32_t field_31E0_;  // 0x31E0
  uint32_t field_31E4_;  // 0x31E4
  uint32_t field_31E8_;  // 0x31E8
  uint32_t field_31EC_;  // 0x31EC
  uint32_t field_31F0_;  // 0x31F0
  uint32_t field_31F4_;  // 0x31F4
  uint32_t field_31F8_;  // 0x31F8
  uint32_t field_31FC_;  // 0x31FC
  uint32_t field_3200_;  // 0x3200
  uint32_t field_3204_;  // 0x3204
  uint32_t field_3208_;  // 0x3208
  uint32_t field_320C_;  // 0x320C
  uint32_t field_3210_;  // 0x3210
  uint32_t field_3214_;  // 0x3214
  uint32_t field_3218_;  // 0x3218
  uint32_t field_321C_;  // 0x321C
  uint32_t field_3220_;  // 0x3220
  uint32_t field_3224_;  // 0x3224
  uint32_t field_3228_;  // 0x3228
  uint32_t field_322C_;  // 0x322C
  uint32_t field_3230_;  // 0x3230
  uint32_t field_3234_;  // 0x3234
  uint32_t field_3238_;  // 0x3238
  uint32_t field_323C_;  // 0x323C
  uint32_t field_3240_;  // 0x3240
  uint8_t sprites3_[0x108];  // 0x3244
  uint32_t field_334C_;  // 0x334C
  uint32_t field_3350_;  // 0x3350
  uint32_t field_3354_;  // 0x3354
  uint32_t field_3358_;  // 0x3358
  uint32_t field_335C_;  // 0x335C
  uint32_t field_3360_;  // 0x3360
  uint32_t field_3364_;  // 0x3364
  uint32_t field_3368_;  // 0x3368
  uint32_t field_336C_;  // 0x336C
  uint32_t field_3370_;  // 0x3370
  uint32_t field_3374_;  // 0x3374
  uint32_t field_3378_;  // 0x3378
  uint32_t field_337C_;  // 0x337C
  uint32_t field_3380_;  // 0x3380
  uint32_t field_3384_;  // 0x3384
  uint32_t field_3388_;  // 0x3388
  uint32_t field_338C_;  // 0x338C
  uint32_t field_3390_;  // 0x3390
  uint32_t field_3394_;  // 0x3394
  uint32_t field_3398_;  // 0x3398
  uint32_t field_339C_;  // 0x339C
  uint32_t field_33A0_;  // 0x33A0
  uint32_t field_33A4_;  // 0x33A4
  uint32_t field_33A8_;  // 0x33A8
  uint8_t sprites4_[0x134];  // 0x33AC
  uint8_t sprites5_[0x134];  // 0x34E0
  uint8_t sprite8_[0x2C];  // 0x3614
  uint8_t sprite9_[0x2C];  // 0x3640
};

/* 0x334 bytes, 1 member(s), 1 named. From Thinker. */
struct Monument {
  uint8_t data1_[0x334];  // 0x0
};

/* 0x28B8 bytes, 31 member(s), 14 named. From the IDB. 16 function(s) in the image. */
class MultiWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint8_t buffer_[0x588];  // 0xA54
  uint8_t sprites1_[0x84];  // 0xFDC
  uint8_t sprites2_[0x84];  // 0x1060
  uint8_t sprite3_[0x2C];  // 0x10E4
  uint8_t sprite4_[0x2C];  // 0x1110
  uint8_t sprite5_[0x2C];  // 0x113C
  uint32_t field_1168_;  // 0x1168
  uint8_t sprite6_[0x2C];  // 0x116C
  uint8_t sprite7_[0x2C];  // 0x1198
  uint8_t flatButton1_[0xB4C];  // 0x11C4
  uint8_t flatButton2_[0xB4C];  // 0x1D10
  uint8_t font1_[0x28];  // 0x285C
  uint8_t font2_[0x28];  // 0x2884
  uint8_t spot_[0xC];  // 0x28AC
};

/* 0x260 bytes, 3 member(s), 0 named. From Thinker. */
struct NameNode {
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint8_t field_8_[0x258];  // 0x8
};

/* 0x10 bytes, 4 member(s), 0 named. From the IDB. 4 function(s) in the image. */
class NetFifo {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
};

/* 0x30 bytes, 12 member(s), 12 named. From Thinker. */
struct PInfo {
  uint32_t former_;  // 0x0
  uint32_t safety_;  // 0x4
  uint32_t target_;  // 0x8
  uint32_t roads_;  // 0xC
  uint32_t flags_;  // 0x10
  uint32_t unit_near_;  // 0x14
  uint32_t unit_path_;  // 0x18
  uint32_t enemy_;  // 0x1C
  uint32_t enemy_near_;  // 0x20
  uint32_t enemy_dist_;  // 0x24
  uint32_t enemy_rank_;  // 0x28
  uint32_t overlay_;  // 0x2C
};

/* 0x10 bytes, 7 member(s), 1 named. From the IDB. */
struct PaletteInternal {
  uint32_t field_0_;  // 0x0
  uint32_t ptrTime_;  // 0x4
  uint8_t field_8_;  // 0x8
  uint8_t field_9_;  // 0x9
  uint8_t field_A_;  // 0xA
  uint8_t field_B_;  // 0xB
  uint32_t field_C_;  // 0xC
};

/* 0xC5C bytes, 111 member(s), 5 named. From the IDB. 9 function(s) in the image. */
class PickTech {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t field_A20_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint32_t field_A54_;  // 0xA54
  uint32_t field_A58_;  // 0xA58
  uint32_t field_A5C_;  // 0xA5C
  uint32_t field_A60_;  // 0xA60
  uint32_t field_A64_;  // 0xA64
  uint32_t field_A68_;  // 0xA68
  uint32_t field_A6C_;  // 0xA6C
  uint32_t field_A70_;  // 0xA70
  uint32_t field_A74_;  // 0xA74
  uint32_t field_A78_;  // 0xA78
  uint32_t field_A7C_;  // 0xA7C
  uint32_t field_A80_;  // 0xA80
  uint32_t field_A84_;  // 0xA84
  uint32_t field_A88_;  // 0xA88
  uint32_t field_A8C_;  // 0xA8C
  uint32_t field_A90_;  // 0xA90
  uint32_t field_A94_;  // 0xA94
  uint32_t field_A98_;  // 0xA98
  uint32_t field_A9C_;  // 0xA9C
  uint32_t field_AA0_;  // 0xAA0
  uint32_t field_AA4_;  // 0xAA4
  uint32_t field_AA8_;  // 0xAA8
  uint32_t field_AAC_;  // 0xAAC
  uint32_t field_AB0_;  // 0xAB0
  uint32_t field_AB4_;  // 0xAB4
  uint32_t field_AB8_;  // 0xAB8
  uint32_t field_ABC_;  // 0xABC
  uint32_t field_AC0_;  // 0xAC0
  uint32_t field_AC4_;  // 0xAC4
  uint32_t field_AC8_;  // 0xAC8
  uint32_t field_ACC_;  // 0xACC
  uint32_t field_AD0_;  // 0xAD0
  uint32_t field_AD4_;  // 0xAD4
  uint32_t field_AD8_;  // 0xAD8
  uint32_t field_ADC_;  // 0xADC
  uint32_t field_AE0_;  // 0xAE0
  uint32_t field_AE4_;  // 0xAE4
  uint32_t field_AE8_;  // 0xAE8
  uint32_t field_AEC_;  // 0xAEC
  uint32_t field_AF0_;  // 0xAF0
  uint32_t field_AF4_;  // 0xAF4
  uint32_t field_AF8_;  // 0xAF8
  uint32_t field_AFC_;  // 0xAFC
  uint32_t field_B00_;  // 0xB00
  uint32_t field_B04_;  // 0xB04
  uint32_t field_B08_;  // 0xB08
  uint32_t field_B0C_;  // 0xB0C
  uint32_t field_B10_;  // 0xB10
  uint32_t field_B14_;  // 0xB14
  uint32_t field_B18_;  // 0xB18
  uint32_t field_B1C_;  // 0xB1C
  uint32_t field_B20_;  // 0xB20
  uint32_t field_B24_;  // 0xB24
  uint32_t field_B28_;  // 0xB28
  uint32_t field_B2C_;  // 0xB2C
  uint32_t field_B30_;  // 0xB30
  uint32_t field_B34_;  // 0xB34
  uint32_t field_B38_;  // 0xB38
  uint32_t field_B3C_;  // 0xB3C
  uint32_t field_B40_;  // 0xB40
  uint32_t field_B44_;  // 0xB44
  uint32_t field_B48_;  // 0xB48
  uint32_t field_B4C_;  // 0xB4C
  uint32_t field_B50_;  // 0xB50
  uint32_t field_B54_;  // 0xB54
  uint32_t field_B58_;  // 0xB58
  uint32_t field_B5C_;  // 0xB5C
  uint32_t field_B60_;  // 0xB60
  uint32_t field_B64_;  // 0xB64
  uint32_t field_B68_;  // 0xB68
  uint32_t field_B6C_;  // 0xB6C
  uint32_t field_B70_;  // 0xB70
  uint32_t field_B74_;  // 0xB74
  uint32_t field_B78_;  // 0xB78
  uint32_t field_B7C_;  // 0xB7C
  uint32_t field_B80_;  // 0xB80
  uint32_t field_B84_;  // 0xB84
  uint32_t field_B88_;  // 0xB88
  uint32_t field_B8C_;  // 0xB8C
  uint32_t field_B90_;  // 0xB90
  uint32_t field_B94_;  // 0xB94
  uint32_t field_B98_;  // 0xB98
  uint32_t field_B9C_;  // 0xB9C
  uint32_t field_BA0_;  // 0xBA0
  uint32_t field_BA4_;  // 0xBA4
  uint32_t field_BA8_;  // 0xBA8
  uint32_t field_BAC_;  // 0xBAC
  uint32_t field_BB0_;  // 0xBB0
  uint32_t field_BB4_;  // 0xBB4
  uint32_t field_BB8_;  // 0xBB8
  uint8_t font1_[0x28];  // 0xBBC
  uint8_t font2_[0x28];  // 0xBE4
  uint8_t font3_[0x28];  // 0xC0C
  uint8_t font4_[0x28];  // 0xC34
};

/* 0x8 bytes, 2 member(s), 2 named. From Thinker. */
struct Point {
  uint32_t x_;  // 0x0
  uint32_t y_;  // 0x4
};

/* 0x1B3D0 bytes, 55 member(s), 50 named. From the IDB. 16 function(s) in the image. */
class PrefWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t field_A1C_;  // 0xA1C
  uint32_t prefsFinal_;  // 0xA20
  uint32_t morePrefsFinal_;  // 0xA24
  uint32_t warningsFinal_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t prefsBasicPending_;  // 0xA30
  uint32_t morePrefsBasicPending_;  // 0xA34
  uint32_t prefsAdvPending_;  // 0xA38
  uint32_t morePrefsAdvPending_;  // 0xA3C
  uint32_t prefsAutoPending_;  // 0xA40
  uint32_t morePrefsAutoPending_;  // 0xA44
  uint32_t warningsPending_;  // 0xA48
  uint32_t prefsAVPending_;  // 0xA4C
  uint32_t morePrefsAVPending_;  // 0xA50
  uint32_t prefsMapPending_;  // 0xA54
  uint32_t morePrefsMapPending_;  // 0xA58
  uint32_t field_A5C_;  // 0xA5C
  uint8_t bscPrefButton_[0xB4C];  // 0xA60
  uint8_t advPrefButton_[0xB4C];  // 0x15AC
  uint8_t warnPrefButton_[0xB4C];  // 0x20F8
  uint8_t autoPrefButton_[0xB4C];  // 0x2C44
  uint8_t audioVisPrefButton_[0xB4C];  // 0x3790
  uint8_t mapPrefButton_[0xB4C];  // 0x42DC
  uint8_t gammaButton_[0xB4C];  // 0x4E28
  uint8_t bscPrefCheckBox_[0xB28];  // 0x5974
  uint8_t advPrefCheckBox_[0xB28];  // 0x649C
  uint8_t autoPrefCheckBox_[0xB28];  // 0x6FC4
  uint8_t audioVisPrefCheckBox_[0xB28];  // 0x7AEC
  uint8_t warnPrefCheckBox_[0xB28];  // 0x8614
  uint8_t warnContPrefCheckBox_[0xB28];  // 0x913C
  uint8_t mapPrefCheckBox_[0xB28];  // 0x9C64
  uint8_t volumeMainScroll_[0x214C];  // 0xA78C
  uint8_t volumeVoiceScroll_[0x214C];  // 0xC8D8
  uint8_t volumeSFXScroll_[0x214C];  // 0xEA24
  uint8_t volumeMusicScroll_[0x214C];  // 0x10B70
  uint8_t scroll5_[0x214C];  // 0x12CBC
  uint8_t volumeMainToggle_[0xB4C];  // 0x14E08
  uint8_t volumeSFXToggle_[0xB4C];  // 0x15954
  uint8_t volumeVoiceToggle_[0xB4C];  // 0x164A0
  uint8_t volumemusicToggle_[0xB4C];  // 0x16FEC
  uint8_t flatButton12_[0xB4C];  // 0x17B38
  uint8_t restoreDefaultButton_[0xB4C];  // 0x18684
  uint8_t cancelButton_[0xB4C];  // 0x191D0
  uint8_t okButton_[0xB4C];  // 0x19D1C
  uint8_t moreButton_[0xB4C];  // 0x1A868
  uint32_t ptrFont1_;  // 0x1B3B4
  uint32_t ptrFont2_;  // 0x1B3B8
  uint32_t ptrFont3_;  // 0x1B3BC
  uint32_t ptrFont4_;  // 0x1B3C0
  uint32_t ptrFont5_;  // 0x1B3C4
  uint32_t ptrFont6_;  // 0x1B3C8
  uint32_t ptrFont7_;  // 0x1B3CC
};

/* 0xB00 bytes, 19 member(s), 1 named. From the IDB. 2 function(s) in the image. */
class PushButton {
 public:
  uint8_t baseButton_[0xAB8];  // 0x0
  uint32_t field_AB8_;  // 0xAB8
  uint32_t field_ABC_;  // 0xABC
  uint32_t field_AC0_;  // 0xAC0
  uint32_t field_AC4_;  // 0xAC4
  uint32_t field_AC8_;  // 0xAC8
  uint32_t field_ACC_;  // 0xACC
  uint32_t field_AD0_;  // 0xAD0
  uint32_t field_AD4_;  // 0xAD4
  uint32_t field_AD8_;  // 0xAD8
  uint32_t field_ADC_;  // 0xADC
  uint32_t field_AE0_;  // 0xAE0
  uint32_t field_AE4_;  // 0xAE4
  uint32_t field_AE8_;  // 0xAE8
  uint32_t field_AEC_;  // 0xAEC
  uint32_t field_AF0_;  // 0xAF0
  uint32_t field_AF4_;  // 0xAF4
  uint32_t field_AF8_;  // 0xAF8
  uint32_t field_AFC_;  // 0xAFC
};

/* 0x37BC bytes, 47 member(s), 9 named. From the IDB. 7 function(s) in the image. */
class QuayleWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint32_t field_A14_;  // 0xA14
  uint32_t field_A18_;  // 0xA18
  uint32_t displayWidth_;  // 0xA1C
  uint32_t displayHeight_;  // 0xA20
  uint32_t field_A24_;  // 0xA24
  uint32_t field_A28_;  // 0xA28
  uint32_t field_A2C_;  // 0xA2C
  uint32_t field_A30_;  // 0xA30
  uint32_t field_A34_;  // 0xA34
  uint32_t field_A38_;  // 0xA38
  uint32_t field_A3C_;  // 0xA3C
  uint32_t field_A40_;  // 0xA40
  uint32_t field_A44_;  // 0xA44
  uint32_t field_A48_;  // 0xA48
  uint32_t field_A4C_;  // 0xA4C
  uint32_t field_A50_;  // 0xA50
  uint32_t field_A54_;  // 0xA54
  uint32_t field_A58_;  // 0xA58
  uint32_t field_A5C_;  // 0xA5C
  uint32_t field_A60_;  // 0xA60
  uint32_t field_A64_;  // 0xA64
  uint32_t field_A68_;  // 0xA68
  uint32_t field_A6C_;  // 0xA6C
  uint32_t field_A70_;  // 0xA70
  uint32_t field_A74_;  // 0xA74
  uint32_t field_A78_;  // 0xA78
  uint32_t field_A7C_;  // 0xA7C
  uint32_t field_A80_;  // 0xA80
  uint32_t field_A84_;  // 0xA84
  uint32_t field_A88_;  // 0xA88
  uint32_t field_A8C_;  // 0xA8C
  uint32_t field_A90_;  // 0xA90
  uint32_t field_A94_;  // 0xA94
  uint32_t field_A98_;  // 0xA98
  uint32_t field_A9C_;  // 0xA9C
  uint32_t field_AA0_;  // 0xAA0
  uint32_t field_AA4_;  // 0xAA4
  uint32_t field_AA8_;  // 0xAA8
  uint8_t flatButton1_[0xB4C];  // 0xAAC
  uint8_t flatButton2_[0xB4C];  // 0x15F8
  uint32_t field_2144_;  // 0x2144
  uint32_t field_2148_;  // 0x2148
  uint8_t spot_[0xC];  // 0x214C
  uint8_t listBox_[0xB54];  // 0x2158
  uint8_t buffer1_[0x588];  // 0x2CAC
  uint8_t buffer2_[0x588];  // 0x3234
};

/* 0x8 bytes, 5 member(s), 5 named. From Thinker. */
struct ReplayEvent {
  uint8_t event_;  // 0x0
  uint8_t faction_id_;  // 0x1
  uint16_t turn_;  // 0x2
  uint16_t x_;  // 0x4
  uint16_t y_;  // 0x6
};

/* 0x10 bytes, 4 member(s), 4 named. From Thinker. */
struct ResValue {
  uint32_t nutrient_;  // 0x0
  uint32_t mineral_;  // 0x4
  uint32_t energy_;  // 0x8
  uint32_t unused_;  // 0xC
};

/* 0x464C bytes, 87 member(s), 6 named. From the IDB. 13 function(s) in the image. */
class SelectPartWin {
 public:
  uint8_t graphicWin_[0xA14];  // 0x0
  uint8_t scroll_[0x214C];  // 0xA14
  uint32_t field_2B60_;  // 0x2B60
  uint32_t field_2B64_;  // 0x2B64
  uint32_t field_2B68_;  // 0x2B68
  uint32_t field_2B6C_;  // 0x2B6C
  uint32_t field_2B70_;  // 0x2B70
  uint32_t field_2B74_;  // 0x2B74
  uint32_t field_2B78_;  // 0x2B78
  uint32_t field_2B7C_;  // 0x2B7C
  uint32_t field_2B80_;  // 0x2B80
  uint32_t field_2B84_;  // 0x2B84
  uint32_t field_2B88_;  // 0x2B88
  uint32_t field_2B8C_;  // 0x2B8C
  uint32_t field_2B90_;  // 0x2B90
  uint32_t field_2B94_;  // 0x2B94
  uint32_t field_2B98_;  // 0x2B98
  uint8_t caviar_[0x13D0];  // 0x2B9C
  uint32_t field_3F6C_;  // 0x3F6C
  uint32_t field_3F70_;  // 0x3F70
  uint32_t field_3F74_;  // 0x3F74
  uint32_t field_3F78_;  // 0x3F78
  uint32_t field_3F7C_;  // 0x3F7C
  uint32_t field_3F80_;  // 0x3F80
  uint32_t field_3F84_;  // 0x3F84
  uint32_t field_3F88_;  // 0x3F88
  uint32_t field_3F8C_;  // 0x3F8C
  uint32_t field_3F90_;  // 0x3F90
  uint32_t field_3F94_;  // 0x3F94
  uint32_t field_3F98_;  // 0x3F98
  uint32_t field_3F9C_;  // 0x3F9C
  uint32_t field_3FA0_;  // 0x3FA0
  uint32_t field_3FA4_;  // 0x3FA4
  uint32_t field_3FA8_;  // 0x3FA8
  uint32_t field_3FAC_;  // 0x3FAC
  uint32_t field_3FB0_;  // 0x3FB0
  uint32_t field_3FB4_;  // 0x3FB4
  uint32_t field_3FB8_;  // 0x3FB8
  uint32_t field_3FBC_;  // 0x3FBC
  uint32_t field_3FC0_;  // 0x3FC0
  uint32_t field_3FC4_;  // 0x3FC4
  uint32_t field_3FC8_;  // 0x3FC8
  uint32_t field_3FCC_;  // 0x3FCC
  uint32_t field_3FD0_;  // 0x3FD0
  uint32_t field_3FD4_;  // 0x3FD4
  uint32_t field_3FD8_;  // 0x3FD8
  uint32_t field_3FDC_;  // 0x3FDC
  uint32_t field_3FE0_;  // 0x3FE0
  uint32_t field_3FE4_;  // 0x3FE4
  uint32_t field_3FE8_;  // 0x3FE8
  uint32_t field_3FEC_;  // 0x3FEC
  uint32_t field_3FF0_;  // 0x3FF0
  uint32_t field_3FF4_;  // 0x3FF4
  uint32_t field_3FF8_;  // 0x3FF8
  uint32_t field_3FFC_;  // 0x3FFC
  uint32_t field_4000_;  // 0x4000
  uint32_t field_4004_;  // 0x4004
  uint32_t field_4008_;  // 0x4008
  uint32_t field_400C_;  // 0x400C
  uint32_t field_4010_;  // 0x4010
  uint32_t field_4014_;  // 0x4014
  uint32_t field_4018_;  // 0x4018
  uint32_t field_401C_;  // 0x401C
  uint32_t field_4020_;  // 0x4020
  uint32_t field_4024_;  // 0x4024
  uint32_t field_4028_;  // 0x4028
  uint32_t field_402C_;  // 0x402C
  uint32_t field_4030_;  // 0x4030
  uint32_t field_4034_;  // 0x4034
  uint32_t field_4038_;  // 0x4038
  uint32_t field_403C_;  // 0x403C
  uint32_t field_4040_;  // 0x4040
  uint32_t field_4044_;  // 0x4044
  uint32_t field_4048_;  // 0x4048
  uint32_t field_404C_;  // 0x404C
  uint32_t field_4050_;  // 0x4050
  uint32_t field_4054_;  // 0x4054
  uint32_t field_4058_;  // 0x4058
  uint32_t field_405C_;  // 0x405C
  uint32_t field_4060_;  // 0x4060
  uint32_t field_4064_;  // 0x4064
  uint32_t field_4068_;  // 0x4068
  uint8_t buffer_[0x588];  // 0x406C
  uint8_t font1_[0x28];  // 0x45F4
  uint8_t font2_[0x28];  // 0x461C
  uint32_t field_4644_;  // 0x4644
  uint32_t field_4648_;  // 0x4648
};

/* 0x24 bytes, 9 member(s), 0 named. From the IDB. 2 function(s) in the image. */
class ServiceStruct {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
  uint32_t field_10_;  // 0x10
  uint32_t field_14_;  // 0x14
  uint32_t field_18_;  // 0x18
  uint32_t field_1C_;  // 0x1C
  uint32_t field_20_;  // 0x20
};

/* 0xC bytes, 3 member(s), 3 named. From Thinker. */
struct SpotList {
  uint32_t spots_;  // 0x0
  uint32_t max_count_;  // 0x4
  uint32_t cur_count_;  // 0x8
};

/* 0x8 bytes, 2 member(s), 1 named. From the IDB. 3 function(s) in the image. */
class SubInterface {
 public:
  uint32_t vtable_;  // 0x0
  uint32_t field_4_;  // 0x4
};

/* 0xC bytes, 12 member(s), 0 named. From Thinker. */
struct TTilePos {
  uint8_t field_0_;  // 0x0
  uint8_t field_1_;  // 0x1
  uint8_t field_2_;  // 0x2
  uint8_t field_3_;  // 0x3
  uint8_t field_4_;  // 0x4
  uint8_t field_5_;  // 0x5
  uint8_t field_6_;  // 0x6
  uint8_t field_7_;  // 0x7
  uint8_t field_8_;  // 0x8
  uint8_t field_9_;  // 0x9
  uint8_t field_A_;  // 0xA
  uint8_t field_B_;  // 0xB
};

/* 0x10 bytes, 4 member(s), 4 named. From the IDB. 5 function(s) in the image. */
class TexHeap {
 public:
  uint32_t basePtr_;  // 0x0
  uint32_t baseSize_;  // 0x4
  uint32_t currentPtr_;  // 0x8
  uint32_t count_;  // 0xC
};

/* 0xB0 bytes, 5 member(s), 4 named. From Thinker. */
struct ThinkerData {
  uint8_t reserved_[0x8];  // 0x0
  uint8_t game_time_spent_[0x8];  // 0x8
  uint8_t build_date_[0xC];  // 0x10
  uint32_t map_random_value_;  // 0x1C
  uint8_t field_20_[0x90];  // 0x20
};

/* 0x1C bytes, 7 member(s), 7 named. From Thinker. */
struct TileValue {
  uint32_t x_;  // 0x0
  uint32_t y_;  // 0x4
  uint32_t i_;  // 0x8
  uint32_t sq_;  // 0xC
  uint32_t nutrient_;  // 0x10
  uint32_t mineral_;  // 0x14
  uint32_t energy_;  // 0x18
};

/* 0x34 bytes, 16 member(s), 15 named. From Thinker. */
struct UNIT {
  uint8_t name_[0x20];  // 0x0
  uint32_t ability_flags_;  // 0x20
  uint8_t chassis_id_;  // 0x24
  uint8_t weapon_id_;  // 0x25
  uint8_t armor_id_;  // 0x26
  uint8_t reactor_id_;  // 0x27
  uint8_t carry_capacity_;  // 0x28
  uint8_t cost_;  // 0x29
  uint8_t plan_;  // 0x2A
  uint8_t group_id_;  // 0x2B
  uint8_t obsolete_factions_;  // 0x2C
  uint8_t combat_factions_;  // 0x2D
  uint8_t icon_offset_;  // 0x2E
  uint8_t field_2F_;  // 0x2F
  uint16_t unit_flags_;  // 0x30
  uint16_t preq_tech_;  // 0x32
};

/* 0x34 bytes, 27 member(s), 26 named. From Thinker. */
struct VEH {
  uint16_t x_;  // 0x0
  uint16_t y_;  // 0x2
  uint32_t state_;  // 0x4
  uint16_t flags_;  // 0x8
  uint16_t unit_id_;  // 0xA
  uint16_t field_C_;  // 0xC
  uint8_t faction_id_;  // 0xE
  uint8_t year_end_lurking_;  // 0xF
  uint8_t damage_taken_;  // 0x10
  uint8_t order_;  // 0x11
  uint8_t waypoint_count_;  // 0x12
  uint8_t patrol_current_point_;  // 0x13
  uint8_t waypoint_x_[0x8];  // 0x14
  uint8_t waypoint_y_[0x8];  // 0x1C
  uint8_t morale_;  // 0x24
  uint8_t movement_turns_;  // 0x25
  uint8_t order_auto_type_;  // 0x26
  uint8_t visibility_;  // 0x27
  uint8_t moves_spent_;  // 0x28
  uint8_t rotate_angle_;  // 0x29
  uint8_t iter_count_;  // 0x2A
  uint8_t status_icon_;  // 0x2B
  uint8_t probe_action_;  // 0x2C
  uint8_t probe_sabotage_id_;  // 0x2D
  uint16_t home_base_id_;  // 0x2E
  uint16_t next_veh_id_stack_;  // 0x30
  uint16_t prev_veh_id_stack_;  // 0x32
};

/* 0x1038 bytes, 365 member(s), 7 named. From the IDB. 8 function(s) in the image. */
class Video {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
  uint32_t field_10_;  // 0x10
  uint32_t field_14_;  // 0x14
  uint32_t field_18_;  // 0x18
  uint32_t field_1C_;  // 0x1C
  uint32_t field_20_;  // 0x20
  uint32_t field_24_;  // 0x24
  uint32_t field_28_;  // 0x28
  uint32_t field_2C_;  // 0x2C
  uint32_t field_30_;  // 0x30
  uint32_t field_34_;  // 0x34
  uint32_t field_38_;  // 0x38
  uint32_t field_3C_;  // 0x3C
  uint32_t field_40_;  // 0x40
  uint32_t field_44_;  // 0x44
  uint32_t field_48_;  // 0x48
  uint32_t field_4C_;  // 0x4C
  uint32_t field_50_;  // 0x50
  uint8_t palette_[0x454];  // 0x54
  uint32_t field_4A8_;  // 0x4A8
  uint32_t field_4AC_;  // 0x4AC
  uint32_t field_4B0_;  // 0x4B0
  uint8_t bytes_4B4_[0x14];  // 0x4B4
  uint8_t bytes_4C8_[0x14];  // 0x4C8
  uint32_t field_4DC_;  // 0x4DC
  uint32_t field_4E0_;  // 0x4E0
  uint32_t field_4E4_;  // 0x4E4
  uint32_t field_4E8_;  // 0x4E8
  uint32_t field_4EC_;  // 0x4EC
  uint32_t field_4F0_;  // 0x4F0
  uint32_t field_4F4_;  // 0x4F4
  uint32_t field_4F8_;  // 0x4F8
  uint32_t field_4FC_;  // 0x4FC
  uint32_t field_500_;  // 0x500
  uint32_t field_504_;  // 0x504
  uint32_t field_508_;  // 0x508
  uint32_t field_50C_;  // 0x50C
  uint32_t field_510_;  // 0x510
  uint32_t field_514_;  // 0x514
  uint32_t field_518_;  // 0x518
  uint32_t field_51C_;  // 0x51C
  uint32_t field_520_;  // 0x520
  uint32_t field_524_;  // 0x524
  uint32_t field_528_;  // 0x528
  uint32_t field_52C_;  // 0x52C
  uint32_t field_530_;  // 0x530
  uint32_t field_534_;  // 0x534
  uint32_t field_538_;  // 0x538
  uint32_t field_53C_;  // 0x53C
  uint32_t field_540_;  // 0x540
  uint32_t field_544_;  // 0x544
  uint32_t field_548_;  // 0x548
  uint32_t field_54C_;  // 0x54C
  uint32_t field_550_;  // 0x550
  uint32_t field_554_;  // 0x554
  uint32_t field_558_;  // 0x558
  uint32_t field_55C_;  // 0x55C
  uint32_t field_560_;  // 0x560
  uint32_t field_564_;  // 0x564
  uint32_t field_568_;  // 0x568
  uint32_t field_56C_;  // 0x56C
  uint32_t field_570_;  // 0x570
  uint32_t field_574_;  // 0x574
  uint32_t field_578_;  // 0x578
  uint32_t field_57C_;  // 0x57C
  uint32_t field_580_;  // 0x580
  uint32_t field_584_;  // 0x584
  uint32_t field_588_;  // 0x588
  uint32_t field_58C_;  // 0x58C
  uint32_t field_590_;  // 0x590
  uint32_t field_594_;  // 0x594
  uint32_t field_598_;  // 0x598
  uint32_t field_59C_;  // 0x59C
  uint32_t field_5A0_;  // 0x5A0
  uint32_t field_5A4_;  // 0x5A4
  uint32_t field_5A8_;  // 0x5A8
  uint32_t field_5AC_;  // 0x5AC
  uint32_t field_5B0_;  // 0x5B0
  uint32_t field_5B4_;  // 0x5B4
  uint32_t field_5B8_;  // 0x5B8
  uint32_t field_5BC_;  // 0x5BC
  uint32_t field_5C0_;  // 0x5C0
  uint32_t field_5C4_;  // 0x5C4
  uint32_t field_5C8_;  // 0x5C8
  uint32_t field_5CC_;  // 0x5CC
  uint32_t field_5D0_;  // 0x5D0
  uint32_t field_5D4_;  // 0x5D4
  uint32_t field_5D8_;  // 0x5D8
  uint32_t field_5DC_;  // 0x5DC
  uint32_t field_5E0_;  // 0x5E0
  uint32_t field_5E4_;  // 0x5E4
  uint32_t field_5E8_;  // 0x5E8
  uint32_t field_5EC_;  // 0x5EC
  uint32_t field_5F0_;  // 0x5F0
  uint32_t field_5F4_;  // 0x5F4
  uint32_t field_5F8_;  // 0x5F8
  uint32_t field_5FC_;  // 0x5FC
  uint32_t field_600_;  // 0x600
  uint32_t field_604_;  // 0x604
  uint32_t field_608_;  // 0x608
  uint32_t field_60C_;  // 0x60C
  uint32_t field_610_;  // 0x610
  uint32_t field_614_;  // 0x614
  uint32_t field_618_;  // 0x618
  uint32_t field_61C_;  // 0x61C
  uint32_t field_620_;  // 0x620
  uint32_t field_624_;  // 0x624
  uint32_t field_628_;  // 0x628
  uint32_t field_62C_;  // 0x62C
  uint32_t field_630_;  // 0x630
  uint32_t field_634_;  // 0x634
  uint32_t field_638_;  // 0x638
  uint32_t field_63C_;  // 0x63C
  uint32_t field_640_;  // 0x640
  uint32_t field_644_;  // 0x644
  uint32_t field_648_;  // 0x648
  uint32_t field_64C_;  // 0x64C
  uint32_t field_650_;  // 0x650
  uint32_t field_654_;  // 0x654
  uint32_t field_658_;  // 0x658
  uint32_t field_65C_;  // 0x65C
  uint32_t field_660_;  // 0x660
  uint32_t field_664_;  // 0x664
  uint32_t field_668_;  // 0x668
  uint32_t field_66C_;  // 0x66C
  uint32_t field_670_;  // 0x670
  uint32_t field_674_;  // 0x674
  uint32_t field_678_;  // 0x678
  uint32_t field_67C_;  // 0x67C
  uint32_t field_680_;  // 0x680
  uint32_t field_684_;  // 0x684
  uint32_t field_688_;  // 0x688
  uint32_t field_68C_;  // 0x68C
  uint32_t field_690_;  // 0x690
  uint32_t field_694_;  // 0x694
  uint32_t field_698_;  // 0x698
  uint32_t field_69C_;  // 0x69C
  uint32_t field_6A0_;  // 0x6A0
  uint32_t field_6A4_;  // 0x6A4
  uint32_t field_6A8_;  // 0x6A8
  uint32_t field_6AC_;  // 0x6AC
  uint32_t field_6B0_;  // 0x6B0
  uint32_t field_6B4_;  // 0x6B4
  uint32_t field_6B8_;  // 0x6B8
  uint32_t field_6BC_;  // 0x6BC
  uint32_t field_6C0_;  // 0x6C0
  uint32_t field_6C4_;  // 0x6C4
  uint32_t field_6C8_;  // 0x6C8
  uint32_t field_6CC_;  // 0x6CC
  uint32_t field_6D0_;  // 0x6D0
  uint32_t field_6D4_;  // 0x6D4
  uint32_t field_6D8_;  // 0x6D8
  uint32_t field_6DC_;  // 0x6DC
  uint32_t field_6E0_;  // 0x6E0
  uint32_t field_6E4_;  // 0x6E4
  uint32_t field_6E8_;  // 0x6E8
  uint32_t field_6EC_;  // 0x6EC
  uint32_t field_6F0_;  // 0x6F0
  uint32_t field_6F4_;  // 0x6F4
  uint32_t field_6F8_;  // 0x6F8
  uint32_t field_6FC_;  // 0x6FC
  uint32_t field_700_;  // 0x700
  uint32_t field_704_;  // 0x704
  uint32_t field_708_;  // 0x708
  uint32_t field_70C_;  // 0x70C
  uint32_t field_710_;  // 0x710
  uint32_t field_714_;  // 0x714
  uint32_t field_718_;  // 0x718
  uint32_t field_71C_;  // 0x71C
  uint32_t field_720_;  // 0x720
  uint32_t field_724_;  // 0x724
  uint32_t field_728_;  // 0x728
  uint32_t field_72C_;  // 0x72C
  uint32_t field_730_;  // 0x730
  uint32_t field_734_;  // 0x734
  uint32_t field_738_;  // 0x738
  uint32_t field_73C_;  // 0x73C
  uint32_t field_740_;  // 0x740
  uint32_t field_744_;  // 0x744
  uint32_t field_748_;  // 0x748
  uint32_t field_74C_;  // 0x74C
  uint32_t field_750_;  // 0x750
  uint32_t field_754_;  // 0x754
  uint32_t field_758_;  // 0x758
  uint32_t field_75C_;  // 0x75C
  uint32_t field_760_;  // 0x760
  uint32_t field_764_;  // 0x764
  uint32_t field_768_;  // 0x768
  uint32_t field_76C_;  // 0x76C
  uint32_t field_770_;  // 0x770
  uint32_t field_774_;  // 0x774
  uint32_t field_778_;  // 0x778
  uint32_t field_77C_;  // 0x77C
  uint32_t field_780_;  // 0x780
  uint32_t field_784_;  // 0x784
  uint32_t field_788_;  // 0x788
  uint32_t field_78C_;  // 0x78C
  uint32_t field_790_;  // 0x790
  uint32_t field_794_;  // 0x794
  uint32_t field_798_;  // 0x798
  uint32_t field_79C_;  // 0x79C
  uint32_t field_7A0_;  // 0x7A0
  uint32_t field_7A4_;  // 0x7A4
  uint32_t field_7A8_;  // 0x7A8
  uint32_t field_7AC_;  // 0x7AC
  uint32_t field_7B0_;  // 0x7B0
  uint32_t field_7B4_;  // 0x7B4
  uint32_t field_7B8_;  // 0x7B8
  uint32_t field_7BC_;  // 0x7BC
  uint32_t field_7C0_;  // 0x7C0
  uint32_t field_7C4_;  // 0x7C4
  uint32_t field_7C8_;  // 0x7C8
  uint32_t field_7CC_;  // 0x7CC
  uint32_t field_7D0_;  // 0x7D0
  uint32_t field_7D4_;  // 0x7D4
  uint32_t field_7D8_;  // 0x7D8
  uint32_t field_7DC_;  // 0x7DC
  uint32_t field_7E0_;  // 0x7E0
  uint32_t field_7E4_;  // 0x7E4
  uint32_t field_7E8_;  // 0x7E8
  uint32_t field_7EC_;  // 0x7EC
  uint32_t field_7F0_;  // 0x7F0
  uint32_t field_7F4_;  // 0x7F4
  uint32_t field_7F8_;  // 0x7F8
  uint32_t field_7FC_;  // 0x7FC
  uint32_t field_800_;  // 0x800
  uint32_t field_804_;  // 0x804
  uint32_t field_808_;  // 0x808
  uint32_t field_80C_;  // 0x80C
  uint32_t field_810_;  // 0x810
  uint32_t field_814_;  // 0x814
  uint32_t field_818_;  // 0x818
  uint32_t field_81C_;  // 0x81C
  uint32_t field_820_;  // 0x820
  uint32_t field_824_;  // 0x824
  uint32_t field_828_;  // 0x828
  uint32_t field_82C_;  // 0x82C
  uint32_t field_830_;  // 0x830
  uint32_t field_834_;  // 0x834
  uint32_t field_838_;  // 0x838
  uint32_t field_83C_;  // 0x83C
  uint32_t field_840_;  // 0x840
  uint32_t field_844_;  // 0x844
  uint32_t field_848_;  // 0x848
  uint32_t field_84C_;  // 0x84C
  uint32_t field_850_;  // 0x850
  uint32_t field_854_;  // 0x854
  uint32_t field_858_;  // 0x858
  uint32_t field_85C_;  // 0x85C
  uint32_t field_860_;  // 0x860
  uint32_t field_864_;  // 0x864
  uint32_t field_868_;  // 0x868
  uint32_t field_86C_;  // 0x86C
  uint32_t field_870_;  // 0x870
  uint32_t field_874_;  // 0x874
  uint32_t field_878_;  // 0x878
  uint32_t field_87C_;  // 0x87C
  uint32_t field_880_;  // 0x880
  uint32_t field_884_;  // 0x884
  uint32_t field_888_;  // 0x888
  uint32_t field_88C_;  // 0x88C
  uint32_t field_890_;  // 0x890
  uint32_t field_894_;  // 0x894
  uint32_t field_898_;  // 0x898
  uint32_t field_89C_;  // 0x89C
  uint32_t field_8A0_;  // 0x8A0
  uint32_t field_8A4_;  // 0x8A4
  uint32_t field_8A8_;  // 0x8A8
  uint32_t field_8AC_;  // 0x8AC
  uint32_t field_8B0_;  // 0x8B0
  uint32_t field_8B4_;  // 0x8B4
  uint32_t field_8B8_;  // 0x8B8
  uint32_t field_8BC_;  // 0x8BC
  uint32_t field_8C0_;  // 0x8C0
  uint32_t field_8C4_;  // 0x8C4
  uint32_t field_8C8_;  // 0x8C8
  uint32_t field_8CC_;  // 0x8CC
  uint32_t field_8D0_;  // 0x8D0
  uint32_t field_8D4_;  // 0x8D4
  uint32_t field_8D8_;  // 0x8D8
  uint32_t field_8DC_;  // 0x8DC
  uint32_t field_8E0_;  // 0x8E0
  uint32_t field_8E4_;  // 0x8E4
  uint32_t field_8E8_;  // 0x8E8
  uint32_t field_8EC_;  // 0x8EC
  uint32_t field_8F0_;  // 0x8F0
  uint32_t field_8F4_;  // 0x8F4
  uint32_t field_8F8_;  // 0x8F8
  uint32_t field_8FC_;  // 0x8FC
  uint32_t field_900_;  // 0x900
  uint32_t field_904_;  // 0x904
  uint32_t field_908_;  // 0x908
  uint32_t field_90C_;  // 0x90C
  uint32_t field_910_;  // 0x910
  uint32_t field_914_;  // 0x914
  uint32_t field_918_;  // 0x918
  uint32_t field_91C_;  // 0x91C
  uint32_t field_920_;  // 0x920
  uint32_t field_924_;  // 0x924
  uint32_t field_928_;  // 0x928
  uint32_t field_92C_;  // 0x92C
  uint32_t field_930_;  // 0x930
  uint32_t field_934_;  // 0x934
  uint32_t field_938_;  // 0x938
  uint32_t field_93C_;  // 0x93C
  uint32_t field_940_;  // 0x940
  uint32_t field_944_;  // 0x944
  uint32_t field_948_;  // 0x948
  uint32_t field_94C_;  // 0x94C
  uint32_t field_950_;  // 0x950
  uint32_t field_954_;  // 0x954
  uint32_t field_958_;  // 0x958
  uint32_t field_95C_;  // 0x95C
  uint32_t field_960_;  // 0x960
  uint32_t field_964_;  // 0x964
  uint32_t field_968_;  // 0x968
  uint32_t field_96C_;  // 0x96C
  uint32_t field_970_;  // 0x970
  uint32_t field_974_;  // 0x974
  uint32_t field_978_;  // 0x978
  uint32_t field_97C_;  // 0x97C
  uint32_t field_980_;  // 0x980
  uint32_t field_984_;  // 0x984
  uint32_t field_988_;  // 0x988
  uint32_t field_98C_;  // 0x98C
  uint32_t field_990_;  // 0x990
  uint32_t field_994_;  // 0x994
  uint32_t field_998_;  // 0x998
  uint32_t field_99C_;  // 0x99C
  uint32_t field_9A0_;  // 0x9A0
  uint32_t field_9A4_;  // 0x9A4
  uint32_t field_9A8_;  // 0x9A8
  uint32_t field_9AC_;  // 0x9AC
  uint32_t field_9B0_;  // 0x9B0
  uint32_t field_9B4_;  // 0x9B4
  uint32_t field_9B8_;  // 0x9B8
  uint32_t field_9BC_;  // 0x9BC
  uint32_t field_9C0_;  // 0x9C0
  uint32_t field_9C4_;  // 0x9C4
  uint32_t field_9C8_;  // 0x9C8
  uint32_t field_9CC_;  // 0x9CC
  uint32_t field_9D0_;  // 0x9D0
  uint32_t field_9D4_;  // 0x9D4
  uint32_t field_9D8_;  // 0x9D8
  uint8_t bytes_9DC_[0x54];  // 0x9DC
  uint8_t bytes_A30_[0x2C];  // 0xA30
  uint8_t field_A5C_[0x10];  // 0xA5C
  uint8_t buffer_[0x588];  // 0xA6C
  uint32_t field_FF4_;  // 0xFF4
  uint32_t field_FF8_;  // 0xFF8
  uint32_t field_FFC_;  // 0xFFC
  uint32_t field_1000_;  // 0x1000
  uint32_t field_1004_;  // 0x1004
  uint32_t field_1008_;  // 0x1008
  uint32_t field_100C_;  // 0x100C
  uint32_t field_1010_;  // 0x1010
  uint32_t field_1014_;  // 0x1014
  uint32_t field_1018_;  // 0x1018
  uint32_t field_101C_;  // 0x101C
  uint32_t field_1020_;  // 0x1020
  uint32_t field_1024_;  // 0x1024
  uint8_t fields_1028_[0x10];  // 0x1028
};

/* 0x54 bytes, 21 member(s), 0 named. From the IDB. 7 function(s) in the image. */
class VoiceRx {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
  uint32_t field_10_;  // 0x10
  uint32_t field_14_;  // 0x14
  uint32_t field_18_;  // 0x18
  uint32_t field_1C_;  // 0x1C
  uint32_t field_20_;  // 0x20
  uint32_t field_24_;  // 0x24
  uint32_t field_28_;  // 0x28
  uint32_t field_2C_;  // 0x2C
  uint32_t field_30_;  // 0x30
  uint32_t field_34_;  // 0x34
  uint32_t field_38_;  // 0x38
  uint32_t field_3C_;  // 0x3C
  uint32_t field_40_;  // 0x40
  uint32_t field_44_;  // 0x44
  uint32_t field_48_;  // 0x48
  uint32_t field_4C_;  // 0x4C
  uint32_t field_50_;  // 0x50
};

/* 0x58 bytes, 22 member(s), 0 named. From the IDB. 8 function(s) in the image. */
class VoiceTx {
 public:
  uint32_t field_0_;  // 0x0
  uint32_t field_4_;  // 0x4
  uint32_t field_8_;  // 0x8
  uint32_t field_C_;  // 0xC
  uint32_t field_10_;  // 0x10
  uint32_t field_14_;  // 0x14
  uint32_t field_18_;  // 0x18
  uint32_t field_1C_;  // 0x1C
  uint32_t field_20_;  // 0x20
  uint32_t field_24_;  // 0x24
  uint32_t field_28_;  // 0x28
  uint32_t field_2C_;  // 0x2C
  uint32_t field_30_;  // 0x30
  uint32_t field_34_;  // 0x34
  uint32_t field_38_;  // 0x38
  uint32_t field_3C_;  // 0x3C
  uint32_t field_40_;  // 0x40
  uint32_t field_44_;  // 0x44
  uint32_t field_48_;  // 0x48
  uint32_t field_4C_;  // 0x4C
  uint32_t field_50_;  // 0x50
  uint32_t field_54_;  // 0x54
};

/* 0x14 bytes, 5 member(s), 5 named. From Thinker. */
struct WItem {
  uint32_t AI_growth_;  // 0x0
  uint32_t AI_tech_;  // 0x4
  uint32_t AI_wealth_;  // 0x8
  uint32_t AI_power_;  // 0xC
  uint32_t AI_fight_;  // 0x10
};

