/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "nullsub_thunks.h"

/*
 * Do-nothing leaves - GENERATED by tools/generate_nullsub_thunks.py. Do not
 * edit by hand; edit the generator and regenerate.
 *
 * 56 functions whose entire body is a return, optionally zeroing EAX first,
 * optionally popping arguments. They read nothing and write nothing.
 *
 * These are free redirects over opaque storage. None of these functions
 * carries a mangled name, so nothing in the image declares a calling
 * convention for them - and none is needed: the only observable facts are the
 * pop count, which the `ret N` states outright, and EAX. A __fastcall
 * redirect with N trailing stack parameters is byte-identical to __thiscall
 * and to __stdcall for a body that reads neither ECX nor EDX.
 */

/*
Purpose: sub_406a80 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
ORIGINAL: 0x00406A80
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00406a80_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: sub_406b30 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x00406B30
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00406b30_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_3 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C820
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c820_redirect(void *, void *) {
}

/*
Purpose: nullsub_191 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C850
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c850_redirect(void *, void *) {
}

/*
Purpose: nullsub_226 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C8A0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8a0_redirect(void *, void *) {
}

/*
Purpose: nullsub_227 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C8B0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8b0_redirect(void *, void *) {
}

/*
Purpose: sub_44c8c0 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x0044C8C0
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0044c8c0_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_229 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C8D0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_230 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C8E0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_231 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C8F0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8f0_redirect(void *, void *) {
}

/*
Purpose: nullsub_232 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C900
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c900_redirect(void *, void *) {
}

/*
Purpose: nullsub_233 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C930
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c930_redirect(void *, void *) {
}

/*
Purpose: nullsub_234 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C960
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c960_redirect(void *, void *) {
}

/*
Purpose: sub_44c970 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x0044C970
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0044c970_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_235 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C9A0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c9a0_redirect(void *, void *) {
}

/*
Purpose: nullsub_236 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044C9D0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c9d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_237 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CA00
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca00_redirect(void *, void *) {
}

/*
Purpose: nullsub_238 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CA30
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca30_redirect(void *, void *) {
}

/*
Purpose: nullsub_239 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CA60
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca60_redirect(void *, void *) {
}

/*
Purpose: nullsub_240 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CAC0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cac0_redirect(void *, void *) {
}

/*
Purpose: nullsub_241 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CAF0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044caf0_redirect(void *, void *) {
}

/*
Purpose: nullsub_242 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CB00
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb00_redirect(void *, void *) {
}

/*
Purpose: nullsub_243 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CB10
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb10_redirect(void *, void *) {
}

/*
Purpose: nullsub_244 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0044CB20
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb20_redirect(void *, void *) {
}

/*
Purpose: mapwin_nullsub1 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x00471160
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub1_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub2 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x00471170
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub2_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub3 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x00471180
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub3_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub4 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x00471190
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub4_redirect(void *, void *, int, int) {
}

/*
Purpose: vehdraw_nullsub1 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004C1D00
Return Value: n/a
Status: Complete
*/
void __fastcall vehdraw_nullsub1_redirect(void *, void *) {
}

/*
Purpose: vehdraw_nullsub2 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004C38A0
Return Value: n/a
Status: Complete
*/
void __fastcall vehdraw_nullsub2_redirect(void *, void *) {
}

/*
Purpose: nullsub_223 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004C8140
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004c8140_redirect(void *, void *) {
}

/*
Purpose: sub_4c8950 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x004C8950
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_004c8950_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_164 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x004E32C0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32c0_redirect(void *, void *, int, int) {
}

/*
Purpose: nullsub_165 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004E32D0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_166 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004E32E0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_20 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
ORIGINAL: 0x004E32F0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32f0_redirect(void *, void *, int, int) {
}

/*
Purpose: nullsub_220 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x004E9B60
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e9b60_redirect(void *, void *) {
}

/*
Purpose: nullsub_186 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x00515760
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00515760_redirect(void *, void *) {
}

/*
Purpose: nullsub_187 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0051D9D0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0051d9d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_188 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0051D9E0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0051d9e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_224 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x005D5240
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005d5240_redirect(void *, void *) {
}

/*
Purpose: sub_5fc9e0 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x005FC9E0
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_005fc9e0_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_192 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x005FD280
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd280_redirect(void *, void *) {
}

/*
Purpose: nullsub_193 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x005FD290
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd290_redirect(void *, void *) {
}

/*
Purpose: nullsub_194 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x005FD2A0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd2a0_redirect(void *, void *) {
}

/*
Purpose: sub_616b30 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
ORIGINAL: 0x00616B30
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00616b30_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: nullsub_195 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x00616D90
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00616d90_redirect(void *, void *) {
}

/*
Purpose: sub_62d140 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
ORIGINAL: 0x0062D140
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0062d140_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_253 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0062D150
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062d150_redirect(void *, void *) {
}

/*
Purpose: nullsub_261 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0062EE80
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062ee80_redirect(void *, void *) {
}

/*
Purpose: nullsub_262 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0062EE90
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062ee90_redirect(void *, void *) {
}

/*
Purpose: nullsub_256 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x00631A10
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00631a10_redirect(void *, void *) {
}

/*
Purpose: Video_unk7 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
ORIGINAL: 0x00637190
Return Value: 0
Status: Complete
*/
int __fastcall video_unk7_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: nullsub_16 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x00639380
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00639380_redirect(void *, void *) {
}

/*
Purpose: nullsub_175 - a do-nothing leaf. The whole body is a return
         popping 4 bytes.
ORIGINAL: 0x0063C500
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0063c500_redirect(void *, void *, int) {
}

/*
Purpose: nullsub_266 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
ORIGINAL: 0x0063C9C0
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0063c9c0_redirect(void *, void *) {
}
