/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#include "stdafx.h"
#include "nullsub_thunks.h"

/*
 * Do-nothing leaves - GENERATED by tools/generate_nullsub_thunks.py. Do not
 * edit by hand; edit the generator and regenerate.
 *
 * 56 functions whose entire body is a return, optionally zeroing EAX first,
 * optionally popping arguments. They read nothing and write nothing.
 *
 * These are free redirects over opaque storage. None of these functions
 * carries a mangled name, so nothing in the image declares a calling
 * convention for them - and none is needed: the only observable facts are the
 * pop count, which the `ret N` states outright, and EAX. A __fastcall
 * redirect with N trailing stack parameters is byte-identical to __thiscall
 * and to __stdcall for a body that reads neither ECX nor EDX.
 */

/*
Purpose: sub_406a80 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
// ORIGINAL: 0x00406A80 sub_406a80 0x00406A80-0x00406A85 BYTE_EXACT
// symbol    ?nullsub_00406a80_redirect@@YIHPAX0HH@Z
// size      5 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00406a80_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: sub_406b30 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.

         AND IT IS AN EMPTY VIRTUAL, reached from 129 vtable slots across 70
         classes - `tools/derive_class_vtables.py` counts them - which is
         also why `callers 0` below is true: nothing calls it directly.
         `/Gy` gives every function its own COMDAT and the linker folded
         every identical empty override in the program onto this one copy.

         THE REDIRECT BELOW IS NOT THAT FUNCTION'S SHAPE. Those 129 slots
         have different arities - slot 1 of Buffer, slot 6 of AlphaMovie,
         slot 103 of something else - and a single
         `int __fastcall(void *, void *)` models none of them; it produces
         the right three bytes by ignoring everything it is handed. Nothing
         calls it either, here or anywhere: all 56 redirects in this file are
         annotation carriers.

         `Buffer::surface_lost` in src/buffer.cpp is the first declaration in
         this tree that is actually TRUE about one of those slots - a virtual
         returning 0 - and it emits the identical `33 c0 c3`. As more classes
         declare their real virtuals, each empty override folds here too, and
         the claim on this address should move to whichever class declares
         the base virtual. Note that `span_classes` records `shared=0`:
         `byte_match.shared_span_index` detects folding between two
         catalogued FUNCTIONS, and one function reached from 129 vtable slots
         is not that case.
// ORIGINAL: 0x00406B30 sub_406b30 0x00406B30-0x00406B33 BYTE_EXACT
// symbol    ?nullsub_00406b30_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00406b30_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_3 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C820 nullsub_3 0x0044C820-0x0044C821 BYTE_EXACT
// symbol    ?nullsub_0044c820_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c820_redirect(void *, void *) {
}

/*
Purpose: nullsub_191 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C850 nullsub_191 0x0044C850-0x0044C851 BYTE_EXACT
// symbol    ?nullsub_0044c850_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c850_redirect(void *, void *) {
}

/*
Purpose: nullsub_226 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C8A0 nullsub_226 0x0044C8A0-0x0044C8A1 BYTE_EXACT
// symbol    ?nullsub_0044c8a0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8a0_redirect(void *, void *) {
}

/*
Purpose: nullsub_227 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C8B0 nullsub_227 0x0044C8B0-0x0044C8B1 BYTE_EXACT
// symbol    ?nullsub_0044c8b0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8b0_redirect(void *, void *) {
}

/*
Purpose: sub_44c8c0 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
// ORIGINAL: 0x0044C8C0 sub_44c8c0 0x0044C8C0-0x0044C8C3 BYTE_EXACT
// symbol    ?nullsub_0044c8c0_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0044c8c0_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_229 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C8D0 nullsub_229 0x0044C8D0-0x0044C8D1 BYTE_EXACT
// symbol    ?nullsub_0044c8d0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_230 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C8E0 nullsub_230 0x0044C8E0-0x0044C8E1 BYTE_EXACT
// symbol    ?nullsub_0044c8e0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_231 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C8F0 nullsub_231 0x0044C8F0-0x0044C8F1 BYTE_EXACT
// symbol    ?nullsub_0044c8f0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c8f0_redirect(void *, void *) {
}

/*
Purpose: nullsub_232 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C900 nullsub_232 0x0044C900-0x0044C901 BYTE_EXACT
// symbol    ?nullsub_0044c900_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c900_redirect(void *, void *) {
}

/*
Purpose: nullsub_233 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C930 nullsub_233 0x0044C930-0x0044C931 BYTE_EXACT
// symbol    ?nullsub_0044c930_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c930_redirect(void *, void *) {
}

/*
Purpose: nullsub_234 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C960 nullsub_234 0x0044C960-0x0044C961 BYTE_EXACT
// symbol    ?nullsub_0044c960_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c960_redirect(void *, void *) {
}

/*
Purpose: sub_44c970 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
// ORIGINAL: 0x0044C970 sub_44c970 0x0044C970-0x0044C973 BYTE_EXACT
// symbol    ?nullsub_0044c970_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0044c970_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_235 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C9A0 nullsub_235 0x0044C9A0-0x0044C9A1 BYTE_EXACT
// symbol    ?nullsub_0044c9a0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c9a0_redirect(void *, void *) {
}

/*
Purpose: nullsub_236 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044C9D0 nullsub_236 0x0044C9D0-0x0044C9D1 BYTE_EXACT
// symbol    ?nullsub_0044c9d0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044c9d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_237 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CA00 nullsub_237 0x0044CA00-0x0044CA01 BYTE_EXACT
// symbol    ?nullsub_0044ca00_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca00_redirect(void *, void *) {
}

/*
Purpose: nullsub_238 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CA30 nullsub_238 0x0044CA30-0x0044CA31 BYTE_EXACT
// symbol    ?nullsub_0044ca30_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca30_redirect(void *, void *) {
}

/*
Purpose: nullsub_239 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CA60 nullsub_239 0x0044CA60-0x0044CA61 BYTE_EXACT
// symbol    ?nullsub_0044ca60_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044ca60_redirect(void *, void *) {
}

/*
Purpose: nullsub_240 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CAC0 nullsub_240 0x0044CAC0-0x0044CAC1 BYTE_EXACT
// symbol    ?nullsub_0044cac0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cac0_redirect(void *, void *) {
}

/*
Purpose: nullsub_241 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CAF0 nullsub_241 0x0044CAF0-0x0044CAF1 BYTE_EXACT
// symbol    ?nullsub_0044caf0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044caf0_redirect(void *, void *) {
}

/*
Purpose: nullsub_242 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CB00 nullsub_242 0x0044CB00-0x0044CB01 BYTE_EXACT
// symbol    ?nullsub_0044cb00_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb00_redirect(void *, void *) {
}

/*
Purpose: nullsub_243 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CB10 nullsub_243 0x0044CB10-0x0044CB11 BYTE_EXACT
// symbol    ?nullsub_0044cb10_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb10_redirect(void *, void *) {
}

/*
Purpose: nullsub_244 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0044CB20 nullsub_244 0x0044CB20-0x0044CB21 BYTE_EXACT
// symbol    ?nullsub_0044cb20_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0044cb20_redirect(void *, void *) {
}

/*
Purpose: mapwin_nullsub1 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x00471160 mapwin_nullsub1 0x00471160-0x00471163 BYTE_EXACT
// symbol    ?mapwin_nullsub1_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub1_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub2 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x00471170 mapwin_nullsub2 0x00471170-0x00471173 BYTE_EXACT
// symbol    ?mapwin_nullsub2_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub2_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub3 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x00471180 mapwin_nullsub3 0x00471180-0x00471183 BYTE_EXACT
// symbol    ?mapwin_nullsub3_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub3_redirect(void *, void *, int, int) {
}

/*
Purpose: mapwin_nullsub4 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x00471190 mapwin_nullsub4 0x00471190-0x00471193 BYTE_EXACT
// symbol    ?mapwin_nullsub4_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall mapwin_nullsub4_redirect(void *, void *, int, int) {
}

/*
Purpose: vehdraw_nullsub1 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004C1D00 vehdraw_nullsub1 0x004C1D00-0x004C1D01 BYTE_EXACT
// symbol    ?vehdraw_nullsub1_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall vehdraw_nullsub1_redirect(void *, void *) {
}

/*
Purpose: vehdraw_nullsub2 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004C38A0 vehdraw_nullsub2 0x004C38A0-0x004C38A1 BYTE_EXACT
// symbol    ?vehdraw_nullsub2_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall vehdraw_nullsub2_redirect(void *, void *) {
}

/*
Purpose: nullsub_223 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004C8140 nullsub_223 0x004C8140-0x004C8141 BYTE_EXACT
// symbol    ?nullsub_004c8140_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004c8140_redirect(void *, void *) {
}

/*
Purpose: sub_4c8950 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
// ORIGINAL: 0x004C8950 sub_4c8950 0x004C8950-0x004C8953 BYTE_EXACT
// symbol    ?nullsub_004c8950_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_004c8950_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_164 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x004E32C0 nullsub_164 0x004E32C0-0x004E32C3 BYTE_EXACT
// symbol    ?nullsub_004e32c0_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32c0_redirect(void *, void *, int, int) {
}

/*
Purpose: nullsub_165 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004E32D0 nullsub_165 0x004E32D0-0x004E32D1 BYTE_EXACT
// symbol    ?nullsub_004e32d0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_166 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004E32E0 nullsub_166 0x004E32E0-0x004E32E1 BYTE_EXACT
// symbol    ?nullsub_004e32e0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_20 - a do-nothing leaf. The whole body is a return
         popping 8 bytes.
// ORIGINAL: 0x004E32F0 nullsub_20 0x004E32F0-0x004E32F3 BYTE_EXACT
// symbol    ?nullsub_004e32f0_redirect@@YIXPAX0HH@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e32f0_redirect(void *, void *, int, int) {
}

/*
Purpose: nullsub_220 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x004E9B60 nullsub_220 0x004E9B60-0x004E9B61 BYTE_EXACT
// symbol    ?nullsub_004e9b60_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_004e9b60_redirect(void *, void *) {
}

/*
Purpose: nullsub_186 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x00515760 nullsub_186 0x00515760-0x00515761 BYTE_EXACT
// symbol    ?nullsub_00515760_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00515760_redirect(void *, void *) {
}

/*
Purpose: nullsub_187 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0051D9D0 nullsub_187 0x0051D9D0-0x0051D9D1 BYTE_EXACT
// symbol    ?nullsub_0051d9d0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0051d9d0_redirect(void *, void *) {
}

/*
Purpose: nullsub_188 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0051D9E0 nullsub_188 0x0051D9E0-0x0051D9E1 BYTE_EXACT
// symbol    ?nullsub_0051d9e0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0051d9e0_redirect(void *, void *) {
}

/*
Purpose: nullsub_224 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x005D5240 nullsub_224 0x005D5240-0x005D5241 BYTE_EXACT
// symbol    ?nullsub_005d5240_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005d5240_redirect(void *, void *) {
}

/*
Purpose: sub_5fc9e0 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
// ORIGINAL: 0x005FC9E0 sub_5fc9e0 0x005FC9E0-0x005FC9E3 BYTE_EXACT
// symbol    ?nullsub_005fc9e0_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_005fc9e0_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_192 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x005FD280 nullsub_192 0x005FD280-0x005FD281 BYTE_EXACT
// symbol    ?nullsub_005fd280_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd280_redirect(void *, void *) {
}

/*
Purpose: nullsub_193 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x005FD290 nullsub_193 0x005FD290-0x005FD291 BYTE_EXACT
// symbol    ?nullsub_005fd290_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd290_redirect(void *, void *) {
}

/*
Purpose: nullsub_194 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x005FD2A0 nullsub_194 0x005FD2A0-0x005FD2A1 BYTE_EXACT
// symbol    ?nullsub_005fd2a0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_005fd2a0_redirect(void *, void *) {
}

/*
Purpose: sub_616b30 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
// ORIGINAL: 0x00616B30 sub_616b30 0x00616B30-0x00616B35 BYTE_EXACT
// symbol    ?nullsub_00616b30_redirect@@YIHPAX0HH@Z
// size      5 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_00616b30_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: nullsub_195 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x00616D90 nullsub_195 0x00616D90-0x00616D91 BYTE_EXACT
// symbol    ?nullsub_00616d90_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00616d90_redirect(void *, void *) {
}

/*
Purpose: sub_62d140 - a do-nothing leaf. The whole body is a return
         popping 0 bytes after zeroing EAX.
// ORIGINAL: 0x0062D140 sub_62d140 0x0062D140-0x0062D143 BYTE_EXACT
// symbol    ?nullsub_0062d140_redirect@@YIHPAX0@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall nullsub_0062d140_redirect(void *, void *) {
    return 0;
}

/*
Purpose: nullsub_253 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0062D150 nullsub_253 0x0062D150-0x0062D151 BYTE_EXACT
// symbol    ?nullsub_0062d150_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062d150_redirect(void *, void *) {
}

/*
Purpose: nullsub_261 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0062EE80 nullsub_261 0x0062EE80-0x0062EE81 BYTE_EXACT
// symbol    ?nullsub_0062ee80_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062ee80_redirect(void *, void *) {
}

/*
Purpose: nullsub_262 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0062EE90 nullsub_262 0x0062EE90-0x0062EE91 BYTE_EXACT
// symbol    ?nullsub_0062ee90_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0062ee90_redirect(void *, void *) {
}

/*
Purpose: nullsub_256 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x00631A10 nullsub_256 0x00631A10-0x00631A11 BYTE_EXACT
// symbol    ?nullsub_00631a10_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00631a10_redirect(void *, void *) {
}

/*
Purpose: Video_unk7 - a do-nothing leaf. The whole body is a return
         popping 8 bytes after zeroing EAX.
// ORIGINAL: 0x00637190 Video_unk7 0x00637190-0x00637195 BYTE_EXACT
// symbol    ?video_unk7_redirect@@YIHPAX0HH@Z
// size      5 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: 0
Status: Complete
*/
int __fastcall video_unk7_redirect(void *, void *, int, int) {
    return 0;
}

/*
Purpose: nullsub_16 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x00639380 nullsub_16 0x00639380-0x00639381 BYTE_EXACT
// symbol    ?nullsub_00639380_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   1   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_00639380_redirect(void *, void *) {
}

/*
Purpose: nullsub_175 - a do-nothing leaf. The whole body is a return
         popping 4 bytes.
// ORIGINAL: 0x0063C500 nullsub_175 0x0063C500-0x0063C503 BYTE_EXACT
// symbol    ?nullsub_0063c500_redirect@@YIXPAX0H@Z
// size      3 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0063c500_redirect(void *, void *, int) {
}

/*
Purpose: nullsub_266 - a do-nothing leaf. The whole body is a return
         popping 0 bytes.
// ORIGINAL: 0x0063C9C0 nullsub_266 0x0063C9C0-0x0063C9C1 BYTE_EXACT
// symbol    ?nullsub_0063c9c0_redirect@@YIXPAX0@Z
// size      1 bytes
// prototype 
// callers   0   call targets   0
// kind      game
// flags     hidden;sp_ready;purged_ok
// calls     (none)
Return Value: n/a
Status: Complete
*/
void __fastcall nullsub_0063c9c0_redirect(void *, void *) {
}
