/*
 * OpenSMACX - an open source clone of Sid Meier's Alpha Centauri.
 * Copyright (C) 2013-2021 Brendan Casey
 *
 * OpenSMACX is free software: you can redistribute it and / or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * OpenSMACX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with OpenSMACX. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

/*
 * Do-nothing leaves - GENERATED by tools/generate_nullsub_thunks.py. Do not
 * edit by hand; edit the generator and regenerate.
 *
 * 56 functions whose entire body is a return, optionally zeroing EAX first,
 * optionally popping arguments. They read nothing and write nothing.
 *
 * These are free redirects over opaque storage. None of these functions
 * carries a mangled name, so nothing in the image declares a calling
 * convention for them - and none is needed: the only observable facts are the
 * pop count, which the `ret N` states outright, and EAX. A __fastcall
 * redirect with N trailing stack parameters is byte-identical to __thiscall
 * and to __stdcall for a body that reads neither ECX nor EDX.
 */

int __fastcall nullsub_00406a80_redirect(void *self, void *, int, int);
int __fastcall nullsub_00406b30_redirect(void *self, void *);
void __fastcall nullsub_0044c820_redirect(void *self, void *);
void __fastcall nullsub_0044c850_redirect(void *self, void *);
void __fastcall nullsub_0044c8a0_redirect(void *self, void *);
void __fastcall nullsub_0044c8b0_redirect(void *self, void *);
int __fastcall nullsub_0044c8c0_redirect(void *self, void *);
void __fastcall nullsub_0044c8d0_redirect(void *self, void *);
void __fastcall nullsub_0044c8e0_redirect(void *self, void *);
void __fastcall nullsub_0044c8f0_redirect(void *self, void *);
void __fastcall nullsub_0044c900_redirect(void *self, void *);
void __fastcall nullsub_0044c930_redirect(void *self, void *);
void __fastcall nullsub_0044c960_redirect(void *self, void *);
int __fastcall nullsub_0044c970_redirect(void *self, void *);
void __fastcall nullsub_0044c9a0_redirect(void *self, void *);
void __fastcall nullsub_0044c9d0_redirect(void *self, void *);
void __fastcall nullsub_0044ca00_redirect(void *self, void *);
void __fastcall nullsub_0044ca30_redirect(void *self, void *);
void __fastcall nullsub_0044ca60_redirect(void *self, void *);
void __fastcall nullsub_0044cac0_redirect(void *self, void *);
void __fastcall nullsub_0044caf0_redirect(void *self, void *);
void __fastcall nullsub_0044cb00_redirect(void *self, void *);
void __fastcall nullsub_0044cb10_redirect(void *self, void *);
void __fastcall nullsub_0044cb20_redirect(void *self, void *);
void __fastcall mapwin_nullsub1_redirect(void *self, void *, int, int);
void __fastcall mapwin_nullsub2_redirect(void *self, void *, int, int);
void __fastcall mapwin_nullsub3_redirect(void *self, void *, int, int);
void __fastcall mapwin_nullsub4_redirect(void *self, void *, int, int);
void __fastcall vehdraw_nullsub1_redirect(void *self, void *);
void __fastcall vehdraw_nullsub2_redirect(void *self, void *);
void __fastcall nullsub_004c8140_redirect(void *self, void *);
int __fastcall nullsub_004c8950_redirect(void *self, void *);
void __fastcall nullsub_004e32c0_redirect(void *self, void *, int, int);
void __fastcall nullsub_004e32d0_redirect(void *self, void *);
void __fastcall nullsub_004e32e0_redirect(void *self, void *);
void __fastcall nullsub_004e32f0_redirect(void *self, void *, int, int);
void __fastcall nullsub_004e9b60_redirect(void *self, void *);
void __fastcall nullsub_00515760_redirect(void *self, void *);
void __fastcall nullsub_0051d9d0_redirect(void *self, void *);
void __fastcall nullsub_0051d9e0_redirect(void *self, void *);
void __fastcall nullsub_005d5240_redirect(void *self, void *);
int __fastcall nullsub_005fc9e0_redirect(void *self, void *);
void __fastcall nullsub_005fd280_redirect(void *self, void *);
void __fastcall nullsub_005fd290_redirect(void *self, void *);
void __fastcall nullsub_005fd2a0_redirect(void *self, void *);
int __fastcall nullsub_00616b30_redirect(void *self, void *, int, int);
void __fastcall nullsub_00616d90_redirect(void *self, void *);
int __fastcall nullsub_0062d140_redirect(void *self, void *);
void __fastcall nullsub_0062d150_redirect(void *self, void *);
void __fastcall nullsub_0062ee80_redirect(void *self, void *);
void __fastcall nullsub_0062ee90_redirect(void *self, void *);
void __fastcall nullsub_00631a10_redirect(void *self, void *);
int __fastcall video_unk7_redirect(void *self, void *, int, int);
void __fastcall nullsub_00639380_redirect(void *self, void *);
void __fastcall nullsub_0063c500_redirect(void *self, void *, int);
void __fastcall nullsub_0063c9c0_redirect(void *self, void *);
